renegade-fi/renegade

- Cargo.toml
- circuits/Dockerfile
- circuits/integration/mpc_gadgets/arithmetic.rs
- circuits/integration/mpc_gadgets/mod.rs
- circuits/integration/mpc_gadgets/modulo.rs
- circuits/integration/mpc_gadgets/poseidon.rs
- circuits/integration/zk_circuits/valid_match_mpc.rs
- circuits/integration/zk_gadgets/arithmetic.rs
- circuits/integration/zk_gadgets/bits.rs
- circuits/integration/zk_gadgets/merkle.rs
- circuits/integration/zk_gadgets/poseidon.rs
- circuits/src/lib.rs
- circuits/src/mpc_gadgets/bits.rs
- circuits/src/mpc_gadgets/modulo.rs
- circuits/src/mpc_gadgets/poseidon.rs
- circuits/src/types/fee.rs
- circuits/src/types/handshake_tuple.rs
- circuits/src/zk_gadgets/arithmetic.rs
- circuits/src/zk_gadgets/bits.rs
- circuits/src/zk_gadgets/merkle.rs
- circuits/src/zk_gadgets/poseidon.rs
- crypto/Cargo.toml
- crypto/src/constants.rs
- crypto/src/fields.rs
- crypto/src/hash.rs
- crypto/src/lib.rs
This PR:
1. Adds the `crypto` crate to the monorepo. This crate will contain reusable cryptographic primitives that can be depended on by other crates in a symmetric way. I.e. we can be sure that the `circuits` crate and `core` are hashing values in the same Poseidon configuration.
2. Refactors the `circuits` crate to move many of the helpers into the new `crypto` crate. This includes field translation, Poseidon constants, arkworks hashing, etc.
- `cargo-integrate circuits`: all integration tests pass
- Ran two clusters locally; verified high level execution
> Add `crypto` crate to monorepo

- core/Cargo.toml
- core/src/api/cluster_management.rs
- core/src/api/handshake.rs
- core/src/handshake/jobs.rs
- core/src/handshake/manager.rs
- core/src/handshake/match.rs
- core/src/handshake/mod.rs
- core/src/handshake/state.rs
- core/src/handshake/types.rs
- core/src/state.rs
This PR includes hashes of orders, balances, fees, and wallet randomness throughout the match process; including in the state machine, the messages passed between peers, etc. These hashes form the statement that is proven (the witness of course being the inputs to the matching engine); and are used for input consistency checks across proofs.
- Workspace unit tests
- Verified basic relayer execution
> core: handshake: Add hashes to handshake messages and state

- Cargo.toml
- circuits/Cargo.toml
- crypto/Cargo.toml
We use certain unreleased versions of Arkworks primitives for the time being. Pinning these to a specific revision so that changes in their repo don't cause breaking changes to ours.
These dependencies will be updated at the next Arkworks release.
- Workspace clean and build succeeds now
> workspace, circuis, crypto: Pin arkworks deps to specific revision

- core/src/api/cluster_management.rs
- core/src/handshake/handshake_cache.rs
- core/src/handshake/jobs.rs
- core/src/handshake/manager.rs
- core/src/handshake/match.rs
- core/src/network_manager/manager.rs
Within a cluster; when one peer begins a match on two orders, its cluster peers should not schedule that match for some time -- this avoids duplicating in-progress work. However, if a peer commits to trying a match and then fails, its cluster peers should try that order pair again after some time. 
To support this, we add cache states to the `HandshakeCache`; one of which is `Invisible`. In the `Invisible` state, an order pair is considered cached until some timeout has elapsed. This allows cluster peers to avoid scheduling an order pair while one peer attempts a match.
- Tested the behavior by spinning up multiple peers in a cluster and having them match with a peer in a separate cluster.
> core: handshake: Place in-flight match order pairs in invisibility window

- core/Cargo.toml
- core/resources/cluster1.toml
- core/resources/cluster2.toml
- core/src/api/http.rs
- core/src/api/mod.rs
- core/src/api_server/error.rs
- core/src/api_server/mod.rs
- core/src/api_server/routes.rs
- core/src/api_server/server.rs
- core/src/api_server/worker.rs
- core/src/config.rs
- core/src/main.rs
- core/src/network_manager/worker.rs
This PR bootstraps the `api-server` worker run by the coordinator.
The API server will serve externally originating HTTP and websocket requests. In this PR, only an HTTP server with a dummy test endpoint is included. 
- API for `/replicas` works properly for external request
- Ad-hoc verified other relayer functionality
> core: api-server: Bootstrap the API server worker

- core/Cargo.toml
- core/src/main.rs
- core/src/system_bus.rs
The `system-bus` module exposes an embedded Pub/Sub functionality to the node. This will allow workers to push messages onto the bus to be consumed elsewhere (i.e. by a listener managing a websocket connection to a front end). In the long run, we will use these events to display status updates in the FE.
There are three abstractions of interest here:
The `TopicReader` is the lowest level of encapsulation. It holds the underlying [`bus::BusReader`](https://docs.rs/bus/latest/bus/struct.BusReader.html#) that is used to receive a multi-consumer message. As well, the `TopicReader` provides two additional functionalities:
1. Wraps the `BusReader` in an `async` interface by using [`tokio::future::poll_fn`](https://docs.rs/tokio/0.2.0-alpha.4/tokio/future/fn.poll_fn.html). 
2. Holds a reference …
> core: system-bus: Bootstrap the `system-bus` module

- core/Cargo.toml
- core/resources/cluster1.toml
- core/resources/cluster2.toml
- core/src/api/mod.rs
- core/src/api/websocket.rs
- core/src/api_server/error.rs
- core/src/api_server/server.rs
- core/src/api_server/worker.rs
- core/src/config.rs
- core/src/gossip/worker.rs
- core/src/handshake/manager.rs
- core/src/handshake/worker.rs
- core/src/main.rs
- core/src/network_manager/worker.rs
- core/src/system_bus.rs
- core/src/types.rs
This PR adds the initial external facing websocket API and connects it to the system bus. The websocket server accepts connections on the configurable port and waits for two types of messages:
1. Messages from the websocket client indicating that the client would like to subscribe or unsubscribe from a websocket topic.
2. Messages from the internal system bus indicating that some event has occurred (e.g. a handshake completes). The websocket handler will only listen on topics that the client has explicitly subscribed to.
- Produced events from a handshake between two peers, verified that the client received the message.
> core: api-server: Create websocket API and forward internal events

- README.md
- circuits/src/lib.rs
- circuits/src/zk_circuits/mod.rs
- circuits/src/zk_circuits/valid_wallet_create.rs
This PR adds an initial implementation of the `VALID WALLET CREATE` circuit definition. This circuit asserts that a commitment given to the contract is a commitment to a wallet with zero balances or open orders, but possibly with non-zero fees. 
This PR implements:
- The general code structure for this circuit; including witness and statement variables, trait implementations, etc.
- Constraint specification for the commitment check; i.e. the check that the balances and orders are _truly_ zero. 
Follow up PRs will implement the constraints for the validity of the key generation process, and the encryption of the wallet under the view key. These constraints need extra ZK gadgetry to be built before they can be added.
- Workspace unit and integration tests pass
- Tested the commitment logic …
> circuits: zk-circuits: Add initial implementation of `VALID WALLET CREATE`

- circuits/Cargo.toml
- circuits/src/zk_gadgets/bigint.rs
- circuits/src/zk_gadgets/mod.rs
- crypto/src/fields.rs
This PR adds the initial implementation of the `U256Var` type, which represents an unsigned 256-bit integer allocated within a constraint system. Two arithmetic methods are currently implemented: `add` and `multiply`, both of which are performed within the constraint system.
- Tested both constrained add and multiply circuits
> circuits: zk-gadgets: bigint: Implement initial `U256Var` gadgets

- circuits/Cargo.toml
- circuits/src/zk_gadgets/nonnative.rs
This PR implements two arithmetic methods: `subtract` (and its bigint complement) and `invert`. 
- `subtract` adds the additive inverse of the right hand operand to the left hand operand modulo the non-native field.
- `invert` computes the multiplicative inverse of the single operand modulo the non-native field
- Tested `subtract`, `subtract_bigint`, and `invert` in both circuit and direct forms
> circuits: zk-gadgets: nonnative: Implement `sub` and `invert` methods on nonnative elements

- circuits/Cargo.toml
- circuits/src/zk_gadgets/comparators.rs
- circuits/src/zk_gadgets/edwards.rs
- circuits/src/zk_gadgets/mod.rs
- circuits/src/zk_gadgets/nonnative.rs
- circuits/src/zk_gadgets/select.rs
- crypto/src/fields.rs
This PR adds the initial completed implementation of ZK gadgetry for Edwards curve arithmetic. This includes point addition and scalar multiplication.
We will compose these gadgets into more abstract gadgets that verify the soundness of elliptic curve cryptosystem operations (e.g. ElGamal-EC encryption and EdDSA verification).
- Tested all operations on elliptic curves against the Arkworks Ed25519 implementation
> circuits: zk-gadgets: edwards: Add Edwards curve gadget implementation

- circuits/src/zk_circuits/valid_match_mpc.rs
- circuits/src/zk_circuits/valid_wallet_create.rs
- circuits/src/zk_gadgets/arithmetic.rs
- circuits/src/zk_gadgets/bits.rs
- circuits/src/zk_gadgets/comparators.rs
- circuits/src/zk_gadgets/merkle.rs
- circuits/src/zk_gadgets/nonnative.rs
- circuits/src/zk_gadgets/poseidon.rs
- circuits/src/zk_gadgets/select.rs
I removed the `CompressedRistretto` return type in the `mpc-bulletproof` package because it's useless. This commit reflects this change applies to the consumer side of the library.
> circuits: Update `mpc-bulletproof` usage after interface change

- Cargo.toml
- circuit-macros/Cargo.toml
- circuit-macros/src/lib.rs
- circuit-macros/tests/test_macros.rs
- circuits/Cargo.toml
- circuits/src/tracing.rs
- circuits/src/zk_gadgets/arithmetic.rs
- circuits/src/zk_gadgets/comparators.rs
This PR adds the `circuit_trace` attribute-like procedural macro in the `circuit-macros` crate. This macro is attached to gadgets that allocate constraints in the constraint system and modifies the gadget code to trace metrics through the circuit's execution.
This will enable us to write benchmarks with constraint system specific metrics and optimize around those at a fine granularity.
The tracer is implemented as a procedural macro that takes as input a function and produces three functions as a result:
- The original function, with `_impl` appended and visibility erased (e.g. public methods now private) so that the associated function interface of the target object does not change.
- A dummy "trampoline" implementation that simply calls the `_impl` method. This is conditionally compiled …
> circuit-macros: `circuit_trace`: Implement circuit tracer procedural macro

- circuits/Dockerfile
- circuits/integration/mpc_circuits/match.rs
- circuits/integration/zk_circuits/valid_match_mpc.rs
- circuits/src/types/balance.rs
- circuits/src/types/fee.rs
- circuits/src/types/handshake_tuple.rs
- circuits/src/types/mod.rs
- circuits/src/types/order.rs
- circuits/src/types/wallet.rs
- circuits/src/zk_circuits/mod.rs
- circuits/src/zk_circuits/valid_match_mpc.rs
- circuits/src/zk_circuits/valid_wallet_create.rs
- circuits/src/zk_circuits/valid_wallet_update.rs
- circuits/src/zk_gadgets/comparators.rs
- circuits/src/zk_gadgets/gates.rs
- circuits/src/zk_gadgets/merkle.rs
- crypto/src/fields.rs
This PR gives the initial implementation of the statement `VALID WALLET UPDATE` from Appendix A.2 of the [whitepaper](https://renegade.fi/whitepaper.pdf).
This essentially states that any deposits, withdraws, new order placements, and internal transfers have correctly updated the wallet state. The commitment to the new wallet is passed as a public variable so that it is verified before being entered into the state tree.
Left to a subsequent PR are bounds checks (where appropriate) and a more comprehensive test suite for the various functionalities of this circuit.
- Tested a proof in which a user creates a new order
> circuits: zk-circuits: valid-wallet-update: Implement `VALID WALLET UPDATE`

- circuits/Dockerfile
- circuits/src/types/handshake_tuple.rs
- circuits/src/types/order.rs
- circuits/src/zk_circuits/valid_match_mpc.rs
- circuits/src/zk_circuits/valid_wallet_create.rs
- circuits/src/zk_circuits/valid_wallet_update.rs
- circuits/src/zk_gadgets/arithmetic.rs
- circuits/src/zk_gadgets/bits.rs
- circuits/src/zk_gadgets/comparators.rs
- circuits/src/zk_gadgets/edwards.rs
- circuits/src/zk_gadgets/gates.rs
- circuits/src/zk_gadgets/merkle.rs
- circuits/src/zk_gadgets/nonnative.rs
- circuits/src/zk_gadgets/poseidon.rs
- circuits/src/zk_gadgets/select.rs
This PR is a few small cleanups that:
1. Make the gadget interfaces more consistent and tracer-friendly
2. Fixes a broken integration test that stemmed from adding timestamps to the order type.
> circuits: zk-circuits: Cleanup interfaces and fix integration test bugs

- circuit-macros/tests/test_macros.rs
- circuits/src/zk_circuits/valid_wallet_update.rs
- circuits/src/zk_gadgets/edwards.rs
- circuits/src/zk_gadgets/nonnative.rs
This PR adds the two final checks necessary to complete the initial write of `VALID WALLET UPDATE`. These are:
1. That for an external withdraw, or an internal transfer, the now-nullified wallet has a balance covering this transfer. This is implicitly done by first checking that all existing balances were updated correctly, and then checking that a balance previously existed for the transferred mint.
2. After the balances are updated; they should be non-negative. This is done efficiently by bounding the balances by a power of 2 (in our case $2^{64}$), taking the bit decomposition of only the first $n = 64$ bits, and then reconstructing the value from the balance `Scalar` from these bits. If the value is non-negative, it can be reconstructed from 64 bits; if it is negative it cannot be …
> circuits: zk-circuits: `VALID WALLET UPDATE`: Constrain bounds checks on balances

- circuits/src/types/balance.rs
- circuits/src/types/fee.rs
- circuits/src/types/order.rs
- circuits/src/zk_circuits/mod.rs
- circuits/src/zk_circuits/valid_commitments.rs
- circuits/src/zk_circuits/valid_match_mpc.rs
- circuits/src/zk_circuits/valid_wallet_update.rs
- circuits/src/zk_gadgets/commitments.rs
- circuits/src/zk_gadgets/mod.rs
This PR adds the initial implementation of the `VALID COMMITMENTS` circuit from the [whitepaper](https://whitepaper.renegade.fi) section A.3.
This proof is used to being the match process. Both parties commit to their inputs to the match and prove that these commitments are valid elements of the state tree.
Left to do:
- More tests around edge cases of fee balances
- Tested various circuit constraints and edge cases from an adversarial prover.
> circuits: zk-circuits: `VALID COMMITMENTS`: Add initial implementation

- circuits/Cargo.toml
- circuits/src/zk_gadgets/fixed_point.rs
- circuits/src/zk_gadgets/mod.rs
- crypto/Cargo.toml
- crypto/src/fields.rs
This PR implements gadgets for allocating and doing arithmetic on fixed point variables within the constraint system. The binary precision is fixed as a constant for simplicity.
- Tested arithmetic (`+` and `*`) between fixed-point variables, as well as between fixed-point variables and an integer value.
Note that when testing, the expected result is sometimes off due to floating point imprecision; so we bound the difference between expected and computed result by some percentage of the computed result.
> circuits: zk-gadgets: fixed-point: Implement fixed point arithmetic

- circuits/integration/mpc_circuits/match.rs
- circuits/integration/zk_circuits/valid_match_mpc.rs
- circuits/src/lib.rs
- circuits/src/mpc_circuits/match.rs
- circuits/src/types/fee.rs
- circuits/src/types/handshake_tuple.rs
- circuits/src/types/match.rs
- circuits/src/types/order.rs
- circuits/src/zk_circuits/mod.rs
- circuits/src/zk_circuits/valid_commitments.rs
- circuits/src/zk_circuits/valid_match_encryption.rs
- circuits/src/zk_circuits/valid_match_mpc.rs
- circuits/src/zk_circuits/valid_wallet_update.rs
- circuits/src/zk_gadgets/commitments.rs
- circuits/src/zk_gadgets/fixed_point.rs
- core/src/handshake/manager.rs
This PR converts much of the match process to use the fixed point variable type to represent rational quantities; with a maximum fractional precision of 32 bits. The fields represented as fixed points are essentially prices, fees, and any intra-circuit derivatives of these values.
- All unit and integration tests pass, match process functions correctly
> circuits: mpc-circuits, zk-circuits: match: Use `FixedPoint` type in match process

- circuits/Cargo.toml
- circuits/integration/zk_circuits/valid_match_mpc.rs
- circuits/src/mpc_gadgets/comparators.rs
- circuits/src/types/fee.rs
- circuits/src/types/handshake_tuple.rs
- circuits/src/zk_circuits/mod.rs
- circuits/src/zk_circuits/valid_match_encryption.rs
- circuits/src/zk_circuits/valid_wallet_create.rs
- circuits/src/zk_gadgets/arithmetic.rs
- circuits/src/zk_gadgets/comparators.rs
- circuits/src/zk_gadgets/fixed_point.rs
This PR makes updates to the existing `VALID MATCH ENCRYPTION` circuit structure after the match process was refactored to use `FixedPoint` variables instead of direct integers. As a result, much of the note validation had to change; including defining how rounding is done in the case of fixed-point imprecision.
A follow up PR will add more test cases for invalid witness types; largely around note structure. This PR already includes invalid ciphertext tests.
- Added invalid witness tests for all encrypted fields
> circuits: zk-circuits: `VALID MATCH ENCRYPTION`: Implement fixed-point arithmetic

- circuits/src/zk_circuits/valid_match_encryption.rs
- circuits/src/zk_gadgets/comparators.rs
This PR adds additional tests for note structure validity; asserting that the notes have the proper fees applies and receive the proper amounts of each token. These tests are done with modified ciphertext to isolate the note-construction constraints.
- Added tests for each volume computed for parties, relayers, and protocol.
- All tests pass.
> circuits: zk-circuits: `VALID MATCH ENCRYPTION`: Add tests for note structure

- circuits/Cargo.toml
- circuits/src/types/balance.rs
- circuits/src/types/fee.rs
- circuits/src/types/keychain.rs
- circuits/src/types/order.rs
- circuits/src/types/wallet.rs
- circuits/src/zk_circuits/valid_commitments.rs
- circuits/src/zk_gadgets/fixed_point.rs
- circuits/src/zk_gadgets/merkle.rs
- core/resources/cluster1_no_wallet.toml
- core/src/api/cluster_management.rs
- core/src/api/gossip.rs
- core/src/gossip/cluster.rs
- core/src/gossip/heartbeat.rs
- core/src/gossip/jobs.rs
- core/src/gossip/server.rs
- core/src/gossip/worker.rs
- core/src/handshake/manager.rs
- core/src/main.rs
- core/src/network_manager/manager.rs
- core/src/network_manager/worker.rs
- core/src/proof_generation/jobs.rs
- core/src/proof_generation/proof_manager.rs
- core/src/state/orderbook.rs
- core/src/state/state.rs
- core/src/state/wallet.rs
This PR adds logic around gossiping proofs between cluster peers. Specifically, when a peer joins their cluster, they are asked by existing cluster peers to replicate managed wallets locally.
When a peer receives a `Replicate` request, it enters all orders into the locally maintained order book in the `Received` state, and publishes a Gossipsub message onto the network requesting a proof of `VALID COMMITMENTS` from a peer who has one.
Any peer may respond; and the newly added cluster peer updates the order's state with the proof.
Todo:
- Authenticate proof responses with the cluster key. This will come as part of a broader todo around how we manage cluster signatures. The current approach is good, but needs some refactoring to fit in requests like this.
- Unit tests
- Tested the case in …
> core: gossip: Gossip about proofs of `VALID COMMITMENTS`

- core/resources/wallets2.json
- core/src/api/cluster_management.rs
- core/src/api/gossip.rs
- core/src/gossip/cluster.rs
- core/src/gossip/jobs.rs
- core/src/gossip/server.rs
- core/src/handshake/jobs.rs
- core/src/handshake/manager.rs
- core/src/network_manager/composed_protocol.rs
- core/src/network_manager/manager.rs
- core/src/state/orderbook.rs
This PR refactors how we handle cluster authentication at the network level. The previous implementation was likely to cause bugs for two reasons:
- The signature verification logic was repeated and handled in each request handler.
- Nothing in the code enforced a request/response type to explicitly require a signature.
This PR refactors these issues to avoid future bugs such that:
- Signature generation and verification is centralized in the gossip and pubsub types directly.
- This relies on a method `requires_cluster_signature` that explicitly requires each enum variant to return `true` or `false` -- future additions to the request/response and pubsub APIs will require the author to explicitly decide whether a message type requires a cluster authenticated link.
- Ad-hoc verified that …
> core: network-manager: Refactor cluster auth signatures for safety

- core/resources/cluster2.toml
- core/src/api/handshake.rs
- core/src/api/heartbeat.rs
- core/src/api/orderbook_management.rs
- core/src/config.rs
- core/src/gossip/cluster.rs
- core/src/gossip/heartbeat.rs
- core/src/gossip/jobs.rs
- core/src/gossip/orderbook.rs
- core/src/gossip/types.rs
- core/src/gossip/worker.rs
- core/src/handshake/handshake_cache.rs
- core/src/handshake/jobs.rs
- core/src/handshake/manager.rs
- core/src/handshake/state.rs
- core/src/network_manager/manager.rs
- core/src/state/mod.rs
- core/src/state/orderbook.rs
- core/src/state/peers.rs
- core/src/state/priority.rs
- core/src/state/state.rs
- core/src/state/wallet.rs
This PR makes a few modifications to the handshake scheduler:
1. The scheduler scores are assessed at multiple granularities:
- Each cluster has a handshake score that is decremented when toxic behavior (hangups, invalid commitment proofs, spam) are detected
- Each order has a handshake score that can be adjusted based on locality, IoIs, etc
2. To support this form of scheduling I denormalized much of the state wrt wallets and handshake scores
3. The scheduler awaits a proof of `VALID COMMITMENTS` for both orders before scheduling a handshake on an order pair
- Tested the handshake flow, verified that a peer did not accept or initiate a handshake on an order pair until it had proved and/or verified each proof of `VALID COMMITMENTS`.
- Verified that state was broadly …
> core: handshake: Refactor handshake scheduling and gate on `VALID COMMITMENTS`

- core/src/api/gossip.rs
- core/src/api/heartbeat.rs
- core/src/gossip/cluster.rs
- core/src/gossip/heartbeat.rs
- core/src/gossip/jobs.rs
- core/src/gossip/orderbook.rs
- core/src/gossip/server.rs
- core/src/gossip/worker.rs
- core/src/handshake/manager.rs
- core/src/handshake/worker.rs
- core/src/network_manager/manager.rs
- core/src/state/orderbook.rs
- core/src/state/peers.rs
- core/src/state/state.rs
- core/src/state/wallet.rs
This PR makes another (smaller) refactor to the handshake scheduling flow that chooses a match candidate order from a set of locally managed, verified orders; rather than round robin on managed wallets.
As well this PR makes a few small improvements and fixes a few small gossip bugs along the way:
1. Peers need not authenticate into their cluster explicitly through a `ClusterAuth` message. The `PeerInfo` struct passed between nodes via heartbeat contains a signature of the peer's ID with the cluster private key. When a new peer is discovered, this signature is verified, authenticating the peer into their cluster in the `PeerIndex` (regardless of whether the local peer is in this cluster).
2. When a peer uses a node to bootstrap into the network, the bootstrap node should index the new …
> core: handshake: scheduler: Refactor order scheduling and fix a few bugs

- circuits/integration/mpc_circuits/match.rs
- circuits/integration/zk_circuits/valid_match_mpc.rs
- circuits/src/lib.rs
- circuits/src/mpc.rs
- circuits/src/types/balance.rs
- circuits/src/types/fee.rs
- circuits/src/types/handshake_tuple.rs
- circuits/src/types/match.rs
- circuits/src/types/note.rs
- circuits/src/types/order.rs
- circuits/src/zk_circuits/mod.rs
- circuits/src/zk_circuits/valid_commitments.rs
- circuits/src/zk_circuits/valid_match_encryption.rs
- circuits/src/zk_circuits/valid_settle.rs
- circuits/src/zk_circuits/valid_wallet_update.rs
- circuits/src/zk_gadgets/elgamal.rs
- core/src/handshake/encumber.rs
- core/src/handshake/error.rs
- core/src/handshake/manager.rs
- core/src/handshake/match.rs
- core/src/handshake/mod.rs
- core/src/handshake/state.rs
- core/src/main.rs
- core/src/proof_generation/jobs.rs
- core/src/proof_generation/proof_manager.rs
- core/src/state/state.rs
- core/src/state/wallet.rs
This PR makes the necessary initial code path and state changes for encrypting a match and submitting it on chain after an MPC. Specifically this involves:
1. Tracking fees and randomness in the handshake state; these are used when building and blinding notes
2. Implementing MPC functionality to share plaintext values after a match (e.g. for fees)
As well, this PR adds the note construction logic as an initial block in the submission flow.
- Unit tests
> core: handshake: Setup initial code structure for post-match encryption

- circuits/src/zk_circuits/valid_match_encryption.rs
- circuits/src/zk_gadgets/elgamal.rs
- circuits/src/zk_gadgets/fixed_point.rs
- core/src/handshake/encumber.rs
- core/src/handshake/error.rs
- core/src/handshake/manager.rs
- core/src/handshake/match.rs
- core/src/handshake/state.rs
- core/src/handshake/worker.rs
- core/src/main.rs
- core/src/proof_generation/jobs.rs
- core/src/proof_generation/proof_manager.rs
- core/src/state/state.rs
This PR connects together the handshake manager's match flow with the proof manager's creation of `VALID MATCH ENCRYPTION`. The flow for matches as it is currently implemented is now:
1. Each party generates a proof of `VALID COMMITMENTS` and gossips this proof through the network.
2. Local peers verify remote proofs; once verified, a remote order is eligible to be scheduled for handshake.
3. Once a handshake is initiated, the peers perform the match MPC and collaboratively prove `VALID MATCH MPC`.
4. The peers each individually construct notes and and encryptions for the match; and prove `VALID MATCH ENCRYPTION`. This step is redundant across peers, but necessarily so
Left for completion:
- Proof linkability; to ensure input consistency between proofs, we need to link Pedersen …
> core: handshake: encumber: Generate proof of `VALID MATCH ENCRYPTION`

- circuits/integration/mpc_circuits/match.rs
- circuits/integration/zk_circuits/valid_match_mpc.rs
- circuits/integration/zk_gadgets/mod.rs
- circuits/src/lib.rs
- circuits/src/types/balance.rs
- circuits/src/types/fee.rs
- circuits/src/types/handshake_tuple.rs
- circuits/src/types/match.rs
- circuits/src/types/order.rs
- circuits/src/zk_circuits/valid_commitments.rs
- circuits/src/zk_circuits/valid_match_encryption.rs
- circuits/src/zk_circuits/valid_match_mpc.rs
- circuits/src/zk_gadgets/arithmetic.rs
- circuits/src/zk_gadgets/bits.rs
- circuits/src/zk_gadgets/fixed_point.rs
- core/src/handshake/encumber.rs
- core/src/handshake/manager.rs
- core/src/handshake/match.rs
- core/src/handshake/state.rs
- core/src/proof_generation/proof_manager.rs
- core/src/state/orderbook.rs
- core/src/state/state.rs
- core/src/types.rs
The basic idea of the match process is to:
1. Verify that inputs (orders, balances, fees, etc) are valid members of the state tree
2. Verify that the matching engine is run correctly on the inputs
3. Verify that the outputs of the matching engine are properly encrypted for end user data-availability.
Only **2** needs to be done inside of an MPC, so to limit the computation inside of the MPC (quite expensive) we only add the constraints of the matching engine to the collaborative proof. The challenge then becomes enforcing input consistency between proofs; i.e. enforcing that the order used in the proof of `VALID COMMITMENTS` is the same order used as input to the matching engine (`VALID MATCH MPC`).
We do this by sharing commitments across proofs. That is, instead of committing to a …
> core: handshake: match: Link validity, match, and encryption proofs with shared commitments

- circuits/src/lib.rs
- circuits/src/types/balance.rs
- circuits/src/types/fee.rs
- circuits/src/types/mod.rs
- circuits/src/types/order.rs
- circuits/src/types/wallet.rs
- circuits/src/zk_circuits/valid_commitments.rs
- circuits/src/zk_gadgets/fixed_point.rs
- circuits/src/zk_gadgets/merkle.rs
- core/src/api/cluster_management.rs
- core/src/api/gossip.rs
- core/src/gossip/errors.rs
- core/src/gossip/jobs.rs
- core/src/gossip/orderbook.rs
- core/src/handshake/encumber.rs
- core/src/handshake/match.rs
- core/src/network_manager/manager.rs
- core/src/proof_generation/proof_manager.rs
- core/src/state/state.rs
This PR makes two meaningful changes:
1. Add linkable commitments for wallet randomness hashes used to derive note randomness; as well as attaching `pk_settle` to the statement of `VALID COMMITMENTS` so that it may be linked with `VALID MATCH ENCRYPTION`.
2. Peers now gossip with one another about the witness and linkable commitments used when proving `VALID COMMITMENTS`. This is done to ensure that if a peer receives a proof of `VALID COMMITMENTS` from a cluster peer; it has access to the commitments used so that it may link these commitments into other proofs.
- Unit tests + integration tests
- Tested two cases for sharing validity proof witnesses, validating that the witness was appropriately gossiped:
- A cluster peer finishes a proof of `VALID COMMITMENTS` and then gossips it to …
> core: gossip: Gossip within cluster about proof-linking commitments

- core/Cargo.toml
- core/src/chain_events/error.rs
- core/src/chain_events/listener.rs
- core/src/chain_events/mod.rs
- core/src/chain_events/worker.rs
- core/src/config.rs
- core/src/main.rs
This PR adds the initial code structure and event polling loop for the `OnChainEventListener`. This worker primarily acts as a relay that:
1. Polls a StarkNet gateway JSON-RPC node for new events coming from the Darkpool contract.
2. Dispatches relevant events as jobs to other workers in the relayer
Currently, we poll the JSON-RPC API (hitting `getEvents`) because the StarkNet API does not have an events websocket. If, in the future, they add a websocket; we will make the changes here.
- Unit tests
- Ran a relayer, submitted a new wallet to the [Goerli contract](https://goerli.voyager.online/contract/0x07d45b975709b894c87ef0318b4f20924e5542ce85116d523c2faef602e491a0#transactions), verified that a `Merkle_root_updated` event was consumed by the relayer once the transaction reached …
> core: chain-events: Bootstrap on-chain event listener

- core/src/chain_events/error.rs
- core/src/chain_events/listener.rs
- core/src/handshake/error.rs
- core/src/handshake/jobs.rs
- core/src/handshake/manager.rs
- core/src/handshake/match.rs
- core/src/handshake/state.rs
- core/src/main.rs
- core/src/state/orderbook.rs
- crypto/Cargo.toml
- crypto/src/fields.rs
When a match nullifier is spent on chain; future matches using that nullifier will no longer be valid (this is the point of a nullifier). Peers that have in-flight handshakes on an order referencing that nullifier should shoot down (terminate) the match computation as soon as possible, and certainly not open the match result if the nullifier is known to be spent. Doing so would leak privacy.
This PR adds:
1. An MPC Shootdown flow in the handshake manager; built on unit type, bounded crossbeam channels that serve as "cancel channels".
2. Event listener dispatch in the on-chain event listener -- specifically to enqueue an MPC shootdown job in the handshake manager's work queue when a `Nullifier_spent` event is emitted from the contract.
- Unit tests
- The flow is a bit hard to test …
> core: chain-events: listener: Add MPC shootdowns when nullifier is spent on-chain

- circuits/src/types/wallet.rs
- core/src/api/orderbook_management.rs
- core/src/chain_events/listener.rs
- core/src/gossip/cluster.rs
- core/src/gossip/jobs.rs
- core/src/gossip/orderbook.rs
- core/src/handshake/jobs.rs
- core/src/main.rs
- core/src/network_manager/manager.rs
- core/src/state/orderbook.rs
- core/src/state/state.rs
- core/src/state/wallet.rs
We previously introduced MPC shootdown to cancel in-flight MPCs on nullified orders. This PR adds the second half of this effort: disable future MPCs from being scheduled on orders after their nullifiers are seen on-chain. 
This involves indexing orders by their match nullifier and transitioning their state to `Cancelled` in the `OnChainEventListener` when a nullifier is witnessed.
- Hit `update_wallet` on Goerli with a nullifier of one of the wallets used by an active relayer. Verified that once the event was emitted on-chain, the relayer cancelled the order.
> core: state: orderbook: Cancel orders when their nullifier is witnessed on-chain

- core/Cargo.toml
- core/src/api_server/http_handlers.rs
- core/src/chain_events/listener.rs
- core/src/config.rs
- core/src/default_wrapper.rs
- core/src/error.rs
- core/src/gossip/cluster.rs
- core/src/gossip/errors.rs
- core/src/gossip/heartbeat.rs
- core/src/gossip/orderbook.rs
- core/src/gossip/server.rs
- core/src/gossip/worker.rs
- core/src/handshake/encumber.rs
- core/src/handshake/handshake_cache.rs
- core/src/handshake/manager.rs
- core/src/handshake/match.rs
- core/src/handshake/state.rs
- core/src/handshake/worker.rs
- core/src/main.rs
- core/src/network_manager/manager.rs
- core/src/network_manager/worker.rs
- core/src/state/orderbook.rs
- core/src/state/peers.rs
- core/src/state/priority.rs
- core/src/state/state.rs
- core/src/state/tui.rs
- core/src/state/wallet.rs
This PR refactors most of the workers and state synchronization to be `async`. The workers were originally somewhat synchronous to accommodate CPU bound workloads. However, we've mostly siloed compute intensive workloads to the proof manager, which remains synchronous. 
The remaining workers are largely async compatible -- consisting of network calls with simple locking and message passing. This also makes the worker framework fit much nicer with the type of logic we are writing for on-chain event consumption.
- Unit tests
- Tested gossip and matching engine functionalities of the relayer ad-hoc
> core: handshake, gossip, state: Refactor workers to be `async`

- core/src/default_wrapper.rs
- core/src/gossip/errors.rs
- core/src/gossip/heartbeat.rs
- core/src/gossip/orderbook.rs
- core/src/gossip/server.rs
- core/src/gossip/worker.rs
- core/src/main.rs
- crypto/src/fields.rs
This PR adds an on-chain check in the new async-capable gossip server that ensures nullifiers are not spent when matching on orders.
- Unit tests
- Tested both the case in which an unspent and spent nullifier were submitted
> core: gossip: orderbook: Check nullifier on-chain before accepting order

- circuits/Cargo.toml
- circuits/src/lib.rs
- core/src/config.rs
- core/src/error.rs
- core/src/main.rs
- core/src/state/initialize.rs
- core/src/state/mod.rs
- core/src/state/state.rs
- core/src/state/wallet.rs
- crypto/src/fields.rs
This PR makes the initial connection between the p2p network and the on-chain Merkle state.
Specifically, when a wallet is added to a node's list of managed wallets, the node will:
1.  Scan on-chain state to find the entry of the wallet in the commitment tree, this gives the wallet's leaf index.
2. Scan on-chain state to find the last known change to each of the wallet's siblings in its commitment authentication path.
3. Construct the Merkle authentication proof for the wallet from the last updates to the siblings
4. Use this proof in `VALID COMMITMENTS` and index it with the wallet.
- Unit tests
- Added two wallets' commitments to the Goerli state by calling `new_wallet`, ran two relayers against these wallets, verified that both created valid authentication proofs and then matched …
> core: state: initialize: Generate `VALID COMMITMENTS` from on-chain Merkle state

- core/src/chain_events/error.rs
- core/src/chain_events/listener.rs
- core/src/main.rs
- core/src/proof_generation/jobs.rs
- core/src/proof_generation/proof_manager.rs
- core/src/state/initialize.rs
- core/src/state/mod.rs
- core/src/state/wallet.rs
This PR gives the steady state event consumption for Merkle updates. In particular, for every Merkle insertion event, the on-chain event listener:
1. Updates any internal nodes in the authentication paths of the wallets
2. Determines whether any proofs of `VALID COMMITMENTS` are now stale as a result of the root update
3. If so, enqueues a job to the proof manager to re-prove `VALID COMMITMENTS` and updates the proof in the global state once it receives a reply.
Left TODO are:
- Incorporate updated proofs into scheduling; i.e. do not schedule on peer orders that have stale `VALID COMMITMENTS` proofs.
- Gossip about updated proofs within a cluster, so that peers need not duplicate the re-proving work. Here we may want to randomize `needs_new_commitment_proof` so that it is unlikely that …
> core: chain-events: listener: Update wallet Merkle state and regen proofs

- core/src/api_server/http.rs
- core/src/api_server/http/network.rs
- core/src/api_server/http/order_book.rs
- core/src/api_server/http/wallet.rs
- core/src/external_api/http/mod.rs
- core/src/external_api/http/network.rs
- core/src/external_api/http/order_book.rs
- core/src/external_api/http/wallet.rs
- core/src/external_api/types.rs
- core/src/gossip/types.rs
This PR follows up on the previous PR, adding the rest of the `GET` endpoints we plan to ship initially. These are:
- `/wallet/:id/fees`
- `/order_book/orders`
- `/order_book/order/:id`
- `/network`
- `/network/clusters/:id`
- `/network/peers/:id`
- Ad hoc tested each of the new endpoints
> core: api-server: http: Implement remaining initial `GET` endpoints

- core/src/api_server/error.rs
- core/src/api_server/http.rs
- core/src/api_server/http/wallet.rs
- core/src/external_api/http/wallet.rs
- core/src/external_api/types.rs
- core/src/main.rs
- core/src/proof_generation/jobs.rs
- core/src/proof_generation/proof_manager.rs
- core/src/state/wallet.rs
- core/src/tasks/create_new_wallet.rs
- core/src/tasks/mod.rs
This PR adds the initial handler for the `/v0/wallet` API route. As spillover, this also adds the `task` abstraction to the relayer which handles long running, largely asynchronous tasks.
One such example is the task of creating a new wallet, which is largely divided into a few steps:
1. Prove `VALID NEW WALLET` on the empty wallet
2. Submit the proof and commitment on-chain, await transaction success
3. Re-construct the Merkle inclusion proof for the wallet in the on-chain state
4. Prove `VALID COMMITMENTS` or await wallet updates and prove `VALID WALLET UPDATE`
Down the line we will have a task driver backing these tasks which handles reliability concerns; and a cluster-wide task tracker that fails over automatically.
- Created a new wallet through the API, verified that the proof was …
> core: api-server: http: Add initial `POST /v0/wallet` handler

- core/Cargo.toml
- core/src/api_server/http.rs
- core/src/api_server/http/price_report.rs
- core/src/api_server/http/wallet.rs
- core/src/api_server/worker.rs
- core/src/chain_events/error.rs
- core/src/chain_events/listener.rs
- core/src/config.rs
- core/src/gossip/orderbook.rs
- core/src/gossip/server.rs
- core/src/main.rs
- core/src/starknet_client/client.rs
- core/src/starknet_client/error.rs
- core/src/starknet_client/mod.rs
- core/src/state/initialize.rs
- core/src/state/mod.rs
- core/src/state/wallet.rs
- core/src/tasks/create_new_wallet.rs
- crypto/Cargo.toml
This PR adds additional logic in the `create-new-wallet` task that:
- Submits the wallet on-chain
- Awaits the `new_wallet` transaction's completion by polling transaction status
- Once completed, scans the transaction history backwards to recover the Merkle entry and authentication path of the new wallet.
Left to do in this task are:
- Index the wallet in the global state once its Merkle path is found
- Create a proof of `VALID COMMITMENTS` for the wallet
- Hit the `POST /v0/wallet` endpoint and verified that the above task steps executed correctly. Verified that the recovered path was the correctly emitted one from contract events.
> core: tasks: create-new-wallet: Submit wallet on-chain and recover Merkle proof

- circuits/src/zk_circuits/valid_match_encryption.rs
- circuits/src/zk_circuits/valid_settle.rs
- circuits/src/zk_circuits/valid_wallet_create.rs
- circuits/src/zk_gadgets/elgamal.rs
- core/src/handshake/encumber.rs
- core/src/proof_generation/jobs.rs
- core/src/starknet_client/client.rs
- core/src/starknet_client/error.rs
- core/src/tasks/create_new_wallet.rs
- crypto/Cargo.toml
- crypto/src/elgamal.rs
- crypto/src/fields.rs
- crypto/src/lib.rs
This PR adds the proof of `VALID WALLET CREATE` as an uninterpreted blob to the `new_wallet` transaction, as well as the initial wallet's ciphertext. This completes the initial implementation of the `create_new_wallet` task.
We will need to re-structure these blobs when we start actually validating proofs and storing encryptions on-chain. 
- Hit `POST /v0/wallet` to create a new wallet, verified that the transaction was created with the ciphertext and proof blobs, and was successfully accepted on Starknet Goerli
> core: tasks: create-new-wallet: Add proof and wallet ciphertext blobs to `new_wallet` tx

- README.md
- circuits/src/zk_circuits/valid_wallet_update.rs
- core/src/api_server/http.rs
- core/src/api_server/http/wallet.rs
- core/src/external_api/http/wallet.rs
- core/src/proof_generation/jobs.rs
- core/src/proof_generation/proof_manager.rs
- core/src/starknet_client/client.rs
- core/src/starknet_client/error.rs
- core/src/starknet_client/mod.rs
- core/src/state/wallet.rs
- core/src/tasks/create_new_order.rs
- core/src/tasks/create_new_wallet.rs
- core/src/tasks/mod.rs
- core/src/types.rs
This PR adds the bulk of the logic for the order creation API `POST /wallet/:id/orders` and the task `create-new-order`. This task takes the following steps:
- Prove `VALID WALLET UPDATE` for the old and new wallet pair
- Submit this to the contract, calling `update_wallet`
- Await transaction finality
- Re-prove `VALID COMMITMENTS` for each order in the wallet; the use of the nullifier on-chain nullifies their proofs
Left to do in a follow up is:
- Index these orders in the global state
- Clean up stale orders that the new wallet replaces
- Verify that once an order has gone through the above steps, it may be matched by a counterparty
As well, we will soon want to add some form of task manager with retries over the task abstraction. It is becoming clear that the APIs are flakey enough to …
> core: tasks: create-new-order: Add initial order creation API + task

- core/src/api_server/http.rs
- core/src/api_server/http/wallet.rs
- core/src/api_server/worker.rs
- core/src/external_api/http/wallet.rs
- core/src/main.rs
- core/src/tasks/create_new_order.rs
- core/src/tasks/create_new_wallet.rs
- core/src/tasks/driver.rs
- core/src/tasks/mod.rs
This PR adds the `TaskDriver` abstraction, which tracks task state and drives tasks forward with retry logic. In testing the tasks already defined, the flows are flakey enough -- largely due to StarkNet API instability and the `starknet-rs` library being out of date -- that we need to retry certain parts of the task.
These tasks take a while however, and it's worth it to support partial retries from the get-go. For example, after awaiting transaction finality, looking up Merkle state sometimes fails with an unsupported deserialization. We'd not like to retry the entire flow of prove -> submit -> await finality.
- Tested both `create_new_wallet` and `create_new_order` with retries
> core: task: driver: Add `TaskDriver` for automatic partial retries within a task

- core/resources/wallets1.json
- core/src/chain_events/listener.rs
- core/src/state/state.rs
- core/src/state/wallet.rs
- core/src/tasks/create_new_order.rs
- core/src/tasks/driver.rs
This PR completes the order creation task which:
1. Computes a proof of `VALID WALLET UPDATE`
2. Submits this on-chain and awaits transaction confirmation
3. Finds the updated Merkle path for the new wallet commitment
4. Re-prove `VALID COMMITMENTS` for each order in the wallet -- or prove it for the first time in the case that a new order is added
5. Update the global state with the newly updated orders.
- Tested the following flow end-to-end:
- Setup a counterparty on the network with an order resting on the book that matches the one I create later on
- Created a new wallet via `POST /v0/wallet`
- Created a new order via `POST /v0/wallet/:id/orders`
- Verified that the new order was committed into the wallet, and submitted on-chain.
- Verified that the resting order matched with the new …
> core: tasks: new-order: Complete `create-new-order` task

- core/Cargo.toml
- core/src/api_server/http.rs
- core/src/api_server/http/wallet.rs
- core/src/external_api/http/wallet.rs
- core/src/external_api/mod.rs
- core/src/starknet_client/client.rs
- core/src/starknet_client/mod.rs
- core/src/starknet_client/types.rs
- core/src/state/wallet.rs
- core/src/tasks/create_new_order.rs
- core/src/tasks/deposit_balance.rs
- core/src/tasks/driver.rs
- core/src/tasks/mod.rs
This PR adds the initial implementation of the `deposit-balance` relayer task. This is the entrypoint of ERC20 tokens into the darkpool. The user submits this request to the relayer after finalizing an ERC20 allowance for the contract to custody the token. The relayer then:
- Proves `VALID WALLET UPDATE` for the wallet state transition
- Submits an `update_wallet` transaction to the contract
- Awaits finality and looks up the new Merkle authentication path for the wallet
- Re-proves `VALID COMMITMENTS` for each order in the wallet
- Indexes the new state
- Tested the end-to-end flow
- TODO: Test the full user onboarding flow: wallet create -> deposit -> order create -> match.
> core: tasks: deposit-balance: Add balance deposit task

- core/src/api_server/http.rs
- core/src/api_server/http/wallet.rs
- core/src/external_api/http/wallet.rs
- core/src/starknet_client/types.rs
- core/src/tasks/driver.rs
- core/src/tasks/external_transfer.rs
- core/src/tasks/mod.rs
This PR adds the `/wallet/:id/balances/:mint/withdraw` endpoint and handler. This handler follows a similar flow to the deposit handler, except that the direction on the external transfer tuple is flipped (0 = deposit, 1 = withdraw). So, this PR simply changes the deposit handler to be generic over deposit/withdraw.
- Tested the following flow:
- Deposited into a Darkpool wallet, verified ERC20 balances visible on-chain decremented for the originating wallet.
- Withdrew the balance back from the darkpool to the wallet, verified that ERC20 balances visible on-chain returned to their original values
> core: api-server: http: Add `/wallet/:id/balances/:mint/withdraw` handler

- circuits/src/types/order.rs
- core/src/api_server/http.rs
- core/src/api_server/http/wallet.rs
- core/src/external_api/http/wallet.rs
- core/src/external_api/types.rs
- core/src/starknet_client/client.rs
- core/src/starknet_client/helpers.rs
- core/src/starknet_client/mod.rs
- core/src/tasks/create_new_order.rs
- core/src/tasks/create_new_wallet.rs
- core/src/tasks/driver.rs
- core/src/tasks/external_transfer.rs
- core/src/tasks/lookup_wallet.rs
- core/src/tasks/mod.rs
- core/src/tasks/settle_match.rs
- crypto/src/elgamal.rs
This PR adds the `/v0/wallet/lookup` implementation which takes the following task flow:
1. Call the `get_wallet_update` view function in the contract to get the last transaction hash that updated a given wallet
2. Pull the calldata from that transaction, re-structure and decrypt the ciphertext blob into a wallet
3. Find the Merkle authentication path for the wallet commitment in the contract commitment tree.
4. Prove `VALID COMMITMENTS` for all orders in the wallet
- Created a new wallet, then shut down the relayer, started it back up and hit the endpoint. Verified that the relayer then recovered the wallet from contract storage, and hit `GET /v0/wallet/:id` to fetch the wallet, verified its fields were as expected.
> core: tasks: lookup-wallet: Add API to lookup wallet in contract storage

- circuits/src/types/transfers.rs
- circuits/src/zk_circuits/valid_wallet_update.rs
- core/src/api_server/http.rs
- core/src/api_server/http/wallet.rs
- core/src/external_api/http/wallet.rs
- core/src/starknet_client/client.rs
- core/src/tasks/mod.rs
- core/src/tasks/update_wallet.rs
This PR adds internal transfer support to the public API through the `update_wallet` flow.
The changes to the task are minimal, essentially just requiring that we encrypt the internal transfer if one is present.
- Tested the new endpoint, verified its functionality
> core: api-server: http: Add `/wallet/:id/balances/:mint/internal_transfer`

- circuits/Cargo.toml
- circuits/src/types/keychain.rs
- core/Cargo.toml
- core/src/api_server/http.rs
- core/src/api_server/http/network.rs
- core/src/api_server/http/order_book.rs
- core/src/api_server/http/price_report.rs
- core/src/api_server/http/task.rs
- core/src/api_server/http/wallet.rs
- core/src/api_server/mod.rs
- core/src/api_server/router.rs
- core/src/external_api/mod.rs
This PR adds authentication to endpoints returning or modifying wallet-private data. The authentication requires a signature and signature expiration UNIX timestamp to be attached as headers `renegade-auth` and `renegade-auth-expiration` respectively.
The signature is the signature of the request body concatenated with the expiration timestamp with `sk_root`.
- Tested the various wallet flows through the API with signatures attached
> core: api-server: http: Add API authentication via `sk_root` signature

- core/src/api_server/http/price_report.rs
- core/src/api_server/websocket.rs
- core/src/api_server/websocket/handler.rs
- core/src/api_server/websocket/price_report.rs
- core/src/api_server/worker.rs
- core/src/price_reporter/jobs.rs
- core/src/price_reporter/manager.rs
- core/src/price_reporter/mod.rs
- core/src/price_reporter/tokens.rs
This PR makes a refactor of the websocket API server into a router/handler based approach. The idea being that this allows us to cleanly build topic-specific logic for subscribing and unsubscribing (e.g. the price report topics must allocate jobs in the `PriceReportManager`).
This PR also implements the initial routes for price reports and handshake status updates.
The rest of the route implementations will come in a follow up.
- Tested price reporting websocket topics locally
> core: api-server: websocket: Refactor into router/handler model

- core/src/api_server/mod.rs
- core/src/api_server/router.rs
- core/src/api_server/websocket.rs
- core/src/api_server/websocket/handler.rs
- core/src/api_server/websocket/price_report.rs
- core/src/api_server/websocket/task.rs
- core/src/api_server/websocket/wallet.rs
- core/src/external_api/websocket.rs
This PR implements authentication for the websocket API. This involves checking that the client has signed the request body with `sk_root` -- just as in the HTTP api.
Auth is only attached to the wallet update topic for the moment.
- Unit tests
- Tested both unauthenticated and authenticated (with and without valid signatures) routes.
> core: api-server: websocket: Add websocket API authentication

- Cargo.toml
- core/Cargo.toml
- core/src/config.rs
- core/src/gossip/orderbook.rs
- core/src/gossip/types.rs
- core/src/main.rs
- core/src/network_manager/composed_protocol.rs
- core/src/network_manager/error.rs
- core/src/network_manager/manager.rs
- core/src/network_manager/worker.rs
- core/src/state/peers.rs
- core/src/state/state.rs
This PR updates the core networking logic around peer discovery; part of this involves upgrading libp2p to incorporate some recent, convenient interface changes.
The core protocol changes are as follows:
- Make more direct use of the `Identify` protocol that was already in place. That is, when a response is received from this protocol with a piggybacked `observed_addr`, the local node stores the `observed_addr` so that it may gossip its now-known public IP address to its peers.
- Accept a known `public_ip` as a config parameter. This is especially useful for bootstrap servers, which should know their public IP ahead of time so that they may gossip a dialable address to all bootstrap clients.
- Tested bootstrapping of both remote and locally run nodes, both intra-cluster …
> core: network-manager: Discover `local_addr` through `Identify` gossip

- circuits/src/lib.rs
- circuits/src/types/balance.rs
- circuits/src/types/fee.rs
- circuits/src/types/keychain.rs
- circuits/src/types/order.rs
- circuits/src/types/wallet.rs
- circuits/src/zk_gadgets/nonnative.rs
This PR adds type definitions for wallet secret shares, including types that are allocated in a constrain system, and commitments to secret shares. These types will be the building blocks for the circuit redesign as a next step.
The refactored types are:
- balances
- orders
- fees
- keychain
- wallet
- CI will fail while the refactor is in progress, no testing done.
> circuits: types: Add secret share types

- circuits/src/lib.rs
- circuits/src/types/fee.rs
- circuits/src/types/wallet.rs
- circuits/src/zk_circuits/mod.rs
- circuits/src/zk_circuits/valid_wallet_create.rs
- circuits/src/zk_gadgets/commitments.rs
- circuits/src/zk_gadgets/nonnative.rs
This PR adds in the new definition of the `VALID WALLET CREATE` circuit to the refactor. This circuit validates that:
1. The commitment to the private wallet shares is correctly computed. This commitment is given as a public variable.
2. The underlying wallet, constructed as a combination of secret shares, is a valid, zero'd out wallet.
- Unit tests pass, tested cases for cheating prover on invalid commitment, non-zero order, and non-zero balance.
> circuits: zk-circuits: `VALID WALLET CREATE`: Implement refactored circuit

- circuits/src/lib.rs
- circuits/src/types/wallet.rs
- circuits/src/zk_circuits/mod.rs
- circuits/src/zk_circuits/valid_wallet_update.rs
- circuits/src/zk_gadgets/commitments.rs
- circuits/src/zk_gadgets/gates.rs
This PR implements the new design of `VALID WALLET UPDATE` which checks that:
- Previous wallet shares are valid entries in the state tree
- The previous wallet share nullifiers were correctly computed
- The commitment to the new private wallet shares is correctly computed
- The wallet has a `pk_root` value equal to one given in the statement
- The wallet transition is valid:
- Updates to balances are the correct application of an external transfer
- Updates to orders are correctly timestamped
- Unit tests pass; verified many different cases:
- Valid order placement and cancellation
- Invalid order updates with incorrect timestamps
- Valid deposit/withdrawal
- Invalid deposit/withdrawal with maliciously engineered balance updates
> circuits: zk-circuits: `VALID WALLET UPDATE`: Implement new design

- circuits/src/mpc_gadgets/poseidon.rs
- circuits/src/zk_circuits/mod.rs
- circuits/src/zk_circuits/valid_reblind.rs
- circuits/src/zk_gadgets/poseidon.rs
This PR adds the implementation of the `VALID REBLIND` circuit. This circuit is used to re-blind a wallet ahead of an attempted match to preserve anonymity. The circuit checks that:
- The inputs to the reblinding are valid, non-nullified elements of the state tree
- A commitment to the new private shares is correctly computed
- The prover knows `sk_match`
- The reblinding results from a valid sampling of the wallet's CSPRNGs, then applied to the old blinding
- Unit tests pass, tested the following cases among others:
- Incorrectly sampled blinder
- Incorrectly sampled secret share
- Incorrectly applied blinder and secret share
- Spurious wallet modifications during reblinding
- Invalid state inputs
- Unauthorized prover
> circuits: zk-circuits: `VALID REBLIND`: Implement circuit

- circuits/src/zk_circuits/mod.rs
- circuits/src/zk_circuits/valid_settle.rs
This PR implements the `VALID SETTLE` circuit, which is linked to a proof of `VALID MATCH MPC` and checks the computational integrity of the updated secret shares of *both* parties. This check amounts to:
- Both parties have had the matched orders' amount decreased by the match amount
- Both parties have had the balances they sent in the match decreased by the match amounts
- Both parties have had the balances they received in the match increased by the match amounts
- All other wallet elements remain unchanged
- Unit tests pass; tested various malicious prover cases in which the prover modifies an element incorrectly
> circuits: zk-circuits: `VALID SETTLE`: Implement redesigned circuit

- circuits/src/zk_circuits/valid_commitments.rs
- circuits/src/zk_circuits/valid_reblind.rs
- circuits/src/zk_circuits/valid_settle.rs
- circuits/src/zk_circuits/valid_wallet_update.rs
- core/src/chain_events/listener.rs
- core/src/external_api/types.rs
- core/src/gossip/cluster.rs
- core/src/gossip/errors.rs
- core/src/gossip/jobs.rs
- core/src/gossip/orderbook.rs
- core/src/gossip_api/gossip.rs
- core/src/gossip_api/orderbook_management.rs
- core/src/handshake/jobs.rs
- core/src/handshake/manager.rs
- core/src/handshake/match.rs
- core/src/handshake/state.rs
- core/src/main.rs
- core/src/network_manager/manager.rs
- core/src/proof_generation/jobs.rs
- core/src/proof_generation/mod.rs
- core/src/proof_generation/proof_manager.rs
- core/src/starknet_client/client.rs
- core/src/state/orderbook.rs
- core/src/state/state.rs
- core/src/state/wallet.rs
- core/src/tasks/settle_match.rs
- core/src/types.rs
This PR makes the initial changes to bring the `core` crate into compatibility with the redesigned circuits. Specifically, it changes the types, interfaces, state, and messages of the `core` crate to fit the new paradigm of secret shares as the primary state element.
As well, this PR refactors the gossip protocol to consider validity proofs in a tuple of `(ValidReblind, ValidCommitments)`.
- Refactor the `tasks` crate
- Add in new commitment links between proofs
- Remove dead code
- `core` does not yet build so unit tests fail
- Clippy returns no errors on all modules except `tasks`
> core: Refactor types to fit encryption redesign

- circuits/src/lib.rs
- circuits/src/zk_circuits/mod.rs
- circuits/src/zk_circuits/valid_commitments.rs
- circuits/src/zk_circuits/valid_reblind.rs
- core/src/main.rs
- core/src/tasks/helpers.rs
- core/src/tasks/initialize_state.rs
- core/src/tasks/mod.rs
This PR refactors the `initialize-state` task to fit the secret share pattern in the encryption redesign.
At a high level, the changes are:
- Find merkle authentication paths for both the public and private wallet shares separately
- Prove both `VALID REBLIND` once for each wallet and `VALID COMMITMENTS` for each order in the wallet. Store both of these (heap allocated) proofs in the global state.
- Will defer testing concrete functionality until the rest of the tasks are refactored, easier to test the whole flow end-to-end.
> core: tasks: intialize-state: Refactor task to fit encryption redesign

- core/src/api_server/http.rs
- core/src/api_server/http/wallet.rs
- core/src/proof_generation/jobs.rs
- core/src/starknet_client/client.rs
- core/src/state/orderbook.rs
- core/src/tasks/helpers.rs
- core/src/tasks/update_wallet.rs
This PR refactors the `update-wallet` task to fit the secret sharing scheme of the encryption redesign. Specifically, this involves:
- Change the proofs of `VALID WALLET UPDATE` to fit the new design
- Change the post-tx logic to prove both `VALID REBLIND` as well as `VALID COMMITMENTS`
- Change the wallet update to index both the public and private share Merkle openings
- Did not test the functionality in goerli; will wait til all tasks are done.
> core: tasks: update-wallet: Refactor to fit encryption redesign

- circuits/src/types/wallet.rs
- core/src/handshake/match.rs
- core/src/starknet_client/client.rs
- core/src/tasks/settle_match.rs
This PR refactors the `settle-match` task to fit the new secret-share centric system redesign. Match and settle are now atomic so the flow of this task is now:
- Update the wallet shares for *both* wallets and prove `VALID SETTLE` which validates the update
- Submit the match to the contract via the `match` function and await transaction completion
- Find the new wallet in the Merkle tree and re-prove `VALID REBLIND` for the wallet and `VALID COMMITMENTS` for each order.
- I am deferring functionality testing in Goerli until we have completely `lookup-wallet` as this greatly eases the end-to-end testing burden.
> core: tasks: settle-match: Update task after encryption redesign

- core/src/api_server/http/wallet.rs
- core/src/chain_events/error.rs
- core/src/chain_events/listener.rs
- core/src/config.rs
- core/src/external_api/http/wallet.rs
- core/src/main.rs
- core/src/starknet_client/client.rs
- core/src/starknet_client/helpers.rs
- core/src/starknet_client/mod.rs
- core/src/tasks/create_new_wallet.rs
- core/src/tasks/lookup_wallet.rs
- core/src/tasks/update_wallet.rs
This PR refactors the `lookup-wallet` task to fit the encryption redesign, the specific changes are:
- Instead of looking up a direct mapping from `pk_view`, we iterate over the blinder shares generated by the csprng and lookup the most recently used `public_blinder_share`.
- We index Merkle entries for both public and private shares
- We prove `VALID REBLIND` at the wallet level, and `VALID COMMITMENT` for each order in the wallet
- Will test the whole system end-to-end and open a PR that fixes all bugs then.
> core: tasks: lookup-wallet: Refactor task wrt encryption redesign

- core/src/chain_events/listener.rs
- core/src/config.rs
- core/src/main.rs
- core/src/starknet_client/client.rs
- core/src/tasks/create_new_wallet.rs
- core/src/tasks/settle_match.rs
- core/src/tasks/update_wallet.rs
This PR aims to use `PENDING` state for confirmation, rather than `ACCEPTED_ON_L2`. These two states are equivalent while StarkNet is still single-sequencer, and we get significantly better time-to-confirmation by using `PENDING`.
Main changes:
* Use `PENDING` everywhere, including in events streaming and transaction polling.
* Add support for multi-account rotation when submitting transactions. The StarkNet sequencer has a nonce check bug, such that multiple transactions from a single account are not possible within a single `PENDING` block, so we rotate between accounts for each tx.
* Stream a WalletUpdate event immediately after the transaction is confirmed as `PENDING`, rather than after `VALID_COMMITMENTS` proofs are generated.
> core: Use `PENDING` state for finality, rather than `ACCEPTED_ON_L2`

- circuits/Cargo.toml
- circuits/src/lib.rs
- circuits/src/types/balance.rs
- circuits/src/types/fee.rs
- circuits/src/types/keychain.rs
- circuits/src/types/order.rs
- circuits/src/types/wallet.rs
- circuits/src/zk_circuits/commitment_links.rs
- circuits/src/zk_circuits/mod.rs
- circuits/src/zk_circuits/valid_commitments.rs
- circuits/src/zk_circuits/valid_reblind.rs
- circuits/src/zk_circuits/valid_settle.rs
- circuits/src/zk_gadgets/fixed_point.rs
- circuits/src/zk_gadgets/nonnative.rs
- core/src/api_server/http/wallet.rs
- core/src/gossip/orderbook.rs
- core/src/handshake/manager.rs
- core/src/handshake/match.rs
- core/src/starknet_client/helpers.rs
- core/src/state/wallet.rs
- core/src/tasks/helpers.rs
- core/src/tasks/initialize_state.rs
- core/src/tasks/settle_match.rs
- core/src/tasks/update_wallet.rs
- integration-helpers/src/mpc_network/mocks.rs
This PR adds commitment linking between elements of the proofs used in the match process -- `VALID REBLIND`, `VALID COMMITMENTS`, and `VALID MATCH MPC`, and `VALID SETTLE`.
The linked elements are:
- re-blinded wallet shares between `VALID REBLIND` and `VALID COMMITMENTS`.
- augmented wallet shares between `VALID COMMITMENTS` and `VALID SETTLE`
- balances, orders, and fees between `VALID COMMITMENTS` and `VALID MATCH MPC`
> core, circuits: Link witness elements between `VALID COMMITMENT`, `VALID REBLIND`, `VALID SETTLE`

- circuits/src/lib.rs
- circuits/src/zk_circuits/valid_commitments.rs
- circuits/src/zk_circuits/valid_match_mpc.rs
- circuits/src/zk_circuits/valid_reblind.rs
- circuits/src/zk_circuits/valid_settle.rs
- circuits/src/zk_circuits/valid_wallet_create.rs
- circuits/src/zk_circuits/valid_wallet_update.rs
- circuits/src/zk_gadgets/arithmetic.rs
- circuits/src/zk_gadgets/bits.rs
- circuits/src/zk_gadgets/comparators.rs
- circuits/src/zk_gadgets/elgamal.rs
- circuits/src/zk_gadgets/merkle.rs
- circuits/src/zk_gadgets/nonnative.rs
- circuits/src/zk_gadgets/poseidon.rs
- circuits/src/zk_gadgets/select.rs
Adds a method `apply_constraints` to the `SingleProverCircuit` trait, which encapsulates the logic of building the actual constraints in the system given the allocated witness and statement variables.
This will be used in the constraint intermediate representation / export tool to build circuit weight matrices in a manner that is generic over the circuit itself
> circuits: zk_circuits, zk_gadgets: add `apply_constraints` method to `SingleProverCircuit` trait

- circuits/src/zk_circuits/commitment_links.rs
- circuits/src/zk_circuits/mod.rs
- circuits/src/zk_circuits/valid_commitments.rs
- circuits/src/zk_circuits/valid_match_mpc.rs
- circuits/src/zk_circuits/valid_reblind.rs
- circuits/src/zk_circuits/valid_settle.rs
- circuits/src/zk_circuits/valid_wallet_create.rs
- circuits/src/zk_circuits/valid_wallet_update.rs
- circuits/src/zk_gadgets/arithmetic.rs
- circuits/src/zk_gadgets/bits.rs
- circuits/src/zk_gadgets/comparators.rs
- circuits/src/zk_gadgets/elgamal.rs
- circuits/src/zk_gadgets/fixed_point.rs
- circuits/src/zk_gadgets/gates.rs
- circuits/src/zk_gadgets/merkle.rs
- circuits/src/zk_gadgets/mod.rs
- circuits/src/zk_gadgets/poseidon.rs
- circuits/src/zk_gadgets/select.rs
- circuits/src/zk_gadgets/wallet_operations.rs
This PR makes the necessary changes to the `zk-gadgets` and `zk-circuits` crates to use the new `circuit_type` macro to derive types.
- Unit tests pass, though CI may not
> circuits: zk-gadgets, zk-circuits: Refactor implementation after type refactor

- circuit-macros/src/circuit_type/multiprover_circuit_types.rs
- circuits/src/mpc_circuits/match.rs
- circuits/src/mpc_gadgets/comparators.rs
- circuits/src/traits.rs
- circuits/src/types/match.rs
- circuits/src/types/mod.rs
- circuits/src/zk_circuits/valid_commitments.rs
- circuits/src/zk_circuits/valid_match_mpc.rs
- circuits/src/zk_circuits/valid_settle.rs
- circuits/src/zk_circuits/valid_wallet_update.rs
- circuits/src/zk_gadgets/arithmetic.rs
- circuits/src/zk_gadgets/comparators.rs
- circuits/src/zk_gadgets/fixed_point.rs
- circuits/src/zk_gadgets/select.rs
This PR adds the initial changes to the `match` MPC and ZK-MPC circuits for midpoint orders. Specifically, the changes are:
- Remove `execution_price` from the `MatchResult` type and take in a price as part of the witness from each party. The parties should agree upon these prices outside of the circuit.
- Remove the computation of the midpoint price in the circuit, the execution price is the agreed upon price.
- Add in checks that the balance covers the matched amount at the executed price.
- Add in checks that the matched amount is less than those specified in the order
The following are left for another PR:
- Price protection; i.e. buy side can specify a maximum price, sell side can specify a minimum price
- Integration and unit tests
- None; will follow up in another PR for testing …
> circuits: zk-circuits: Add midpoint orders to `VALID MATCH MPC`

- circuits/Cargo.toml
- circuits/integration/main.rs
- circuits/integration/mpc_circuits/match.rs
- circuits/integration/zk_circuits/valid_match_mpc.rs
- circuits/src/lib.rs
- circuits/src/types/order.rs
- circuits/src/zk_circuits/mod.rs
- circuits/src/zk_circuits/valid_commitments.rs
- circuits/src/zk_circuits/valid_settle.rs
- circuits/src/zk_circuits/valid_wallet_create.rs
- circuits/src/zk_circuits/valid_wallet_update.rs
- circuits/src/zk_gadgets/fixed_point.rs
- circuits/src/zk_gadgets/select.rs
This PR adds a test case suite for `VALID MATCH MPC` to the integration tests. These tests cover the bulk of matching engine edge cases: mismatched order, incorrect balances, incorrect amounts, invalid intermediate values, etc. 
- Price protection
- Integration and unit tests in `circuits` pass, though CI will not build here because `core` has not ingested these changes.
> circuits: integration: Add integration tests for `match` and `VALID MATCH MPC`

- circuits/integration/mpc_circuits/match.rs
- circuits/integration/zk_circuits/valid_match_mpc.rs
- circuits/src/types/mod.rs
- circuits/src/types/order.rs
- circuits/src/zk_circuits/mod.rs
- circuits/src/zk_circuits/valid_commitments.rs
- circuits/src/zk_circuits/valid_match_mpc.rs
- circuits/src/zk_circuits/valid_settle.rs
- circuits/src/zk_circuits/valid_wallet_update.rs
- circuits/src/zk_gadgets/select.rs
This PR adds price protection to the `Order` struct and enforces the price protection in `VALID MATCH MPC`.
Price protection is implemented as a `worst_case_price` that represents a maximum price for buy side orders and a minimum price for sell side orders.
- Unit tests in `circuits` pass, though CI will fail here because `core` has not consumed the midpoint changes
- Integration tests in `circuits` pass
> circuits: zk-circuits: `VALID MATCH MPC`: Add price protection constraints

- core/src/config.rs
- core/src/gossip_api/handshake.rs
- core/src/handshake/error.rs
- core/src/handshake/manager.rs
- core/src/handshake/manager/match.rs
- core/src/handshake/manager/price_agreement.rs
- core/src/handshake/mod.rs
- core/src/handshake/worker.rs
- core/src/main.rs
- core/src/price_reporter/errors.rs
- core/src/price_reporter/exchange/uni_v3.rs
- core/src/price_reporter/reporter.rs
- core/src/price_reporter/tokens.rs
- core/src/price_reporter/worker.rs
- core/src/state/state.rs
- core/src/tasks/settle_match.rs
This PR integrates the price streams from the `price-reporter` module with the handshake price proposal logic. Specifically, the proposer peeks at the median price for a set of assets, one of which it intends to match on, and proposes these prices to the peer. The peer then peeks their own observed midpoints and validates that the proposed prices are within some tolerance.
Two simplifying assumptions are made in this implementation that will be revisited later:
- We propose a static subset of common asset pairs to mask the desired pair. A better strategy would be to propose a random subset of asset pairs, also including the desired pair, and possibly weighted by trading volume.
- When we validate prices, we only look at max deviation. We'd really like to look at other things as well: for …
> core: handshake: Consumer prices from price reporter for handshake

- core/src/price_reporter/exchange/uni_v3.rs
The `web3::WebSocket` occasionally fails and needs to be reset. This is done by forwarding an error to the `ConnectionMuxer` which drops the poisoned connection and restarts it. 
The initial implementation did not properly forward errors up the stack, meaning the connection was never reset.
- Ad hoc tests
> core: price-reporter: uni-v3: Forward connection errors 

- core/src/gossip/orderbook.rs
- core/src/price_reporter/exchange/kraken.rs
- core/src/price_reporter/exchange/okx.rs
- core/src/proof_generation/proof_manager.rs
- core/src/tasks/update_wallet.rs
The `update-wallet` task previously was using the old Merkle authentication path when re-proving `VALID REBLIND` (post update). Instead, the task should find the updated wallet's Merkle path and use this in the proof instead.
As well, this PR fixes a bug in which an invalid order validity proof is broadcast where:
1. A node receives the invalid proof and fails to verify it
2. The node then continues requesting and attempting to verify the invalid proof indefinitely
The fix is to index the order in the `Received` state before the proof is verified and only transition to `Verified` after verification is complete. For invalid proofs, this means the order is stuck in the `Received` state until a managing node pushes a valid proof via `UpdateWalletValidityProof`. …
> core: tasks: update-wallet: Fix merkle path used in `VALID REBLIND`

- core/src/gossip/orderbook.rs
- core/src/handshake/manager.rs
- core/src/handshake/manager/price_agreement.rs
- core/src/handshake/worker.rs
- core/src/main.rs
- core/src/price_reporter/exchange/kraken.rs
- core/src/price_reporter/exchange/okx.rs
- core/src/price_reporter/reporter.rs
- core/src/price_reporter/tokens.rs
- core/src/proof_generation/proof_manager.rs
- core/src/tasks/update_wallet.rs
For now, we specify order asset pairs in terms of their Starknet addresses, but measure prices in terms of Eth mainnet addresses. This may change when we implement a custom bridging scheme, but for now we must translate addresses.
- Ad hoc match tests
> core: handshake: price-agreement: Convert token addrs to ETH mainnet

- circuits/src/types/order.rs
- core/src/api_server/http.rs
- core/src/api_server/http/wallet.rs
- core/src/external_api/http/wallet.rs
- core/src/price_reporter/exchange/uni_v3.rs
- core/src/state/state.rs
- core/src/tasks/helpers.rs
After an order is filled, it is not removed from the secret share state (the settling party may not own the wallet and thus cannot zero filled orders). This PR makes two improvements to how these orders are handled:
- Do not create validity proofs for, gossip about, or index zero-amount orders
- Add a `/wallet/:id/orders/:id/update` endpoint so that a now-zero order can be updated directly to a new order without cancelling and re-creating.
- Tested the match flow, verified that the zero'd order was not re-indexed in the network order book
- Tested the update order endpoint, verified that it correctly overwrote the zero'd order
> core: handshake: Better handle zero'd orders after complete fill

- core/src/api_server/http/wallet.rs
- core/src/external_api/http/wallet.rs
- core/src/tasks/settle_match.rs
This PR fixes a couple bugs that prevent chained matches:
1. In the `settle-match` task, we previously were not properly re-blinding the wallet and recomputing its Merkle inclusion proof. This PR fixes that
2. The `/wallet/:id/orders/:id/update` endpoint needs to re-assign `OrderIdentifier`s to updated orders. This is because stale identifiers are used as match engine cache keys, so if an updated order maintains its identifier, it may never be matched by counterparties that believe they have already matched it.
- Tested the end-to-end flow of matching an order, topping off the order on the filled counterparty's side, and then re-matching to fill more of the unfilled counterparty's side.
> core: tasks: settle-match: Fix bugs preventing chained matches

- circuits/src/zk_circuits/valid_wallet_update.rs
- core/Cargo.toml
- core/src/api_server/http/wallet.rs
- core/src/state/wallet.rs
When creating a proof of `VALID WALLET UPDATE`, it is important that all orders and balances are input to the proof in the same order as the secret shares committed to in the contract. To enable this, this PR switches the data structure underlying a wallet's orders and balances to `indexmap` which yields an iterator ordered by insertion order.
As well, this PR changes `/wallet/:id/orders/:id/update` to update in-place so that insertion order is again preserved.
- Tested the flow of fetching a wallet from on-chain, then calling `VALID WALLET UPDATE`. Verified that the proof was valid.
> core: state: wallet: Track orders/balances with `indexmap` for ordering

- core/src/state/orderbook.rs
If we leave the mapping from the old nullifier to the new one, consumed nullifier events may shootdown a fresh order and prevent it from being matched
- Ad hoc proofs being gossiped
> core: state: orderbook: Remove old nullifier when order re-indexed

- core/src/config.rs
- core/src/main.rs
- core/src/price_reporter/manager.rs
- core/src/price_reporter/worker.rs
- core/src/state/tui.rs
This PR changes the way we disable the price reporter to simply ignore jobs, instead of trying to cancel the worker. Long term we can do something more efficient that deallocates the thread, but for now this is sufficient.
- Disabled the price reporter, verified that the rest of the relayer worked properly
> core: price-reporter: properly disable price reporter with flag

- core/src/config.rs
- core/src/main.rs
- core/src/network_manager/worker.rs
By default we bind to `0.0.0.0` which listens and sends on all network interfaces. However, we sometimes want to specify a specific network interface to send/receive on. 
One such example is the bootstrap cluster; it is provisioned with a static IP so that it may be reached at a known address, but this IP is attached to a non-default network interface on the node. If the bootstrap node binds to all network interfaces, it may receive traffic on the interface of the static IP and send traffic on a different interface. This will be blocked by symmetric NATs as the response will seem to come from a different hostport. For this reason, we bind the bootstrap nodes to only the network interface on which we provision the static IP.
- Tested bootstrapping into the network from my local node, which …
> core: config: Add `bind_addr` argument for specific interface binding

- core/src/price_reporter/exchange/coinbase.rs
- core/src/price_reporter/reporter.rs
This PR makes two updates to the price reporter that stabilize prices:
1. Allow a longer interval on stale prices; from 5s to 20s. It is common that some exchanges won't report updates when no price action is detected, so we lengthen the interval. Long term we may want different intervals for different base assets.
2. Ignore infinite and default prices when updating the atomic state. So instead of updating a non-zero, non-infinite price to 0 of `inf`, we let the price go stale and error that way instead. This is a common issue when e.g. Coinbase's book has no orders on it.
- Tested the price reporter over an extended period of time, verified that the number of invalid price reports dropped significantly
> core: price-reporter: Stabilize price reporter

- circuits/src/types/order.rs
- circuits/src/zk_circuits/valid_match_mpc.rs
- core/src/handshake/jobs.rs
- core/src/handshake/manager.rs
- core/src/handshake/manager/internal_engine.rs
- core/src/main.rs
- core/src/state/orderbook.rs
- core/src/state/state.rs
This PR completes the first half of the internal order book feature; leaving settlement for a follow up. The changes are:
- Implement `SingleProverCircuit` for `VALID MATCH MPC`
- Add a job to run the internal matching engine on an order in the handshake manager
- Enqueue this job whenever an order becomes first available for match scheduling
- Forward successful matches to the task driver for settlement
- Recursive matches: if we partially fill an order via the internal order book, re-enqueue an `InternalMatchingEngine` job to the handshake manager so that we may try to fill more of the order internally
- We may want to periodically run the `InternalMatchingEngine` job to pick up any orders that get left behind as a result of bugs
- Tested the plaintext …
> core: handshake: internal-engine: Add internal matching engine

- core/src/handshake/manager/internal_engine.rs
- core/src/tasks/driver.rs
- core/src/tasks/settle_match.rs
- core/src/tasks/settle_match_internal.rs
This PR fixes a few bugs with the internal matching engine:
- Orders should be nullified during settlement ahead of when their new validity proofs are created. This prevents the internal engine from attempting to double match before new validity proofs are created
- Orders that have zero volume should be ignored by the engine
- Tested a recursive internal match in which one buy side order is recursively matched by two separate sell side orders, both of which it fills entirely.
> core: tasks: settle-match-internal: Fix execution bugs and recursive match

- core/src/config.rs
- core/src/external_api/mod.rs
- core/src/state/state.rs
- core/src/tasks/helpers.rs
- core/src/tasks/initialize_state.rs
Adds the `disable_fee_validation` flag, which disables the check that a wallet's fee is nonzero. This is useful for either a testnet or for a private cluster.
Tested with both 1) the full testing suite of `renegade-js` version `3.0.1`, and 2) an order placement in the browser.
> core: config, api-server: Add `disable_fee_validation` flag, and serialize an empty request/response as `null`

- crypto/Cargo.toml
- crypto/benches/elgamal.rs
- crypto/benches/poseidon.rs
- crypto/src/constants.rs
- crypto/src/elgamal.rs
- crypto/src/fields.rs
- crypto/src/hash.rs
- crypto/src/lib.rs
This PR makes the initial steps to refactor `renegade` over the Stark curve by refactoring the `crypto` crate. This crate defines `crypto` utilities such as:
- Poseidon hashes
- Field conversions
- Elgamal encryptions
- Crate tests pass, though CI will be red as the rest of the crates are not refactored
> crypto: Refactor implementation over Stark curve

- integration-helpers/Cargo.toml
- integration-helpers/src/mpc_network.rs
- integration-helpers/src/mpc_network/mocks.rs
This PR refactors the `integration-helpers` crate to work over the new `mpc-stark` library, i.e. over the Stark curve. This largely involves deleting helper code that has been replaced by functionality in the `MpcFabric`.
- CI will fail until other crates are refactored
> integration-helpers: Refactor over Stark curve

- circuits/src/lib.rs
- circuits/src/mpc_gadgets/bits.rs
- circuits/src/zk_gadgets/arithmetic.rs
- circuits/src/zk_gadgets/bits.rs
- circuits/src/zk_gadgets/comparators.rs
- circuits/src/zk_gadgets/elgamal.rs
- circuits/src/zk_gadgets/fixed_point.rs
- circuits/src/zk_gadgets/merkle.rs
- circuits/src/zk_gadgets/poseidon.rs
- circuits/src/zk_gadgets/select.rs
- circuits/src/zk_gadgets/wallet_operations.rs
This PR updates the `zk-gadgets` module to operate over the Stark curve. This largely involves changing interfaces where they differ between the old `mpc-ristretto` and the new `mpc-stark`.
- CI will fail locally until refactor is complete
> circuits: zk-gadgets: Update gadgets after Stark curve refactor

- circuits/Cargo.toml
- circuits/benches/valid_reblind.rs
- circuits/src/zk_circuits/mod.rs
- circuits/src/zk_circuits/valid_reblind.rs
This PR refactors the implementation of `VALID REBLIND` to work over the Stark curve. This PR also adds benchmarks for the following:
- Constraint generation latency
- Prover latency
- Verifier latency
- CI will fail until refactor is complete
> circuits: zk-circuits: `VALID REBLIND`: Refactor over stark curve

- circuits/Cargo.toml
- circuits/benches/valid_settle.rs
- circuits/src/zk_circuits/mod.rs
- circuits/src/zk_circuits/valid_settle.rs
This PR refactors the implementation of `VALID SETTLE` to operate over the Stark curve. As well, this PR introduces benchmarks for:
- Constraint generation latency
- Prover latency
- Verifier latency
- CI will remain red until refactor is complete
> circuits: zk-circuits: `VALID SETTLE`: Refactor over Stark curve

- circuits/integration/main.rs
- circuits/integration/mpc_circuits/match.rs
This PR refactors the integration tests for the `match` MPC to operate over the Stark curve. This is essentially just making interface changes and simplifications to the tests such that they fit the new `MpcFabric` interface
- Benchmarks for the MPC and collaborative proof
- Refactor the `commitment_links` module
- CI will remain red until the refactor is complete
> circuits: integration: match: Refactor match MPC tests over the Stark curve

- circuit-types/src/fixed_point.rs
- circuit-types/src/lib.rs
- circuit-types/src/macro_tests.rs
- circuit-types/src/traits.rs
- circuits/integration/mpc_circuits/match.rs
- circuits/integration/zk_circuits/valid_match_mpc.rs
- circuits/integration/zk_gadgets/arithmetic.rs
- circuits/integration/zk_gadgets/bits.rs
- circuits/integration/zk_gadgets/poseidon.rs
- circuits/src/lib.rs
- circuits/src/zk_circuits/valid_match_mpc.rs
- circuits/src/zk_gadgets/arithmetic.rs
- circuits/src/zk_gadgets/bits.rs
- circuits/src/zk_gadgets/comparators.rs
- circuits/src/zk_gadgets/fixed_point.rs
- circuits/src/zk_gadgets/gates.rs
- circuits/src/zk_gadgets/poseidon.rs
- circuits/src/zk_gadgets/select.rs
This PR ingests the interface and lifetime parameter changes introduced to `MpcProver` in [this PR](https://github.com/renegade-fi/mpc-bulletproof/pull/8)
These changes are:
- Force the prover to take ownership of all fields
- Remove all lifetime parameters as they are now unnecessary
> circuits, circuit-types: Ingest interface changes to `MpcProver`

- circuits/Cargo.toml
- circuits/benches/match.rs
- circuits/src/zk_circuits/commitment_links.rs
- circuits/src/zk_circuits/mod.rs
- circuits/src/zk_circuits/valid_match_mpc.rs
This PR makes the following changes:
- Refactors  the `commitment_links` module over the Stark curve -- this only required a one-line change
- Adds benchmarks for the `match` MPC and the `VALID MATCH MPC` collaborative proof (constraint generation, prover latency, and verification latency)
- CI will remain red until the refactor is complete
> circuits: benches: match: Add `VALID MATCH MPC` benchmarks

- circuit-types/src/traits.rs
- circuits/benches/match.rs
- circuits/integration/mpc_circuits/match.rs
- circuits/integration/mpc_gadgets/arithmetic.rs
- circuits/integration/mpc_gadgets/bits.rs
- circuits/integration/mpc_gadgets/comparators.rs
- circuits/integration/mpc_gadgets/modulo.rs
- circuits/integration/zk_circuits/valid_match_mpc.rs
- circuits/integration/zk_gadgets/arithmetic.rs
- circuits/integration/zk_gadgets/bits.rs
- circuits/src/lib.rs
- circuits/src/mpc_circuits/match.rs
- circuits/src/mpc_gadgets/arithmetic.rs
- circuits/src/mpc_gadgets/bits.rs
- circuits/src/mpc_gadgets/comparators.rs
- circuits/src/mpc_gadgets/fixed_point.rs
- circuits/src/mpc_gadgets/modulo.rs
- circuits/src/mpc_gadgets/poseidon.rs
- circuits/src/zk_circuits/valid_match_mpc.rs
- circuits/src/zk_gadgets/arithmetic.rs
- circuits/src/zk_gadgets/bits.rs
- circuits/src/zk_gadgets/comparators.rs
- circuits/src/zk_gadgets/fixed_point.rs
- circuits/src/zk_gadgets/gates.rs
- circuits/src/zk_gadgets/poseidon.rs
- circuits/src/zk_gadgets/select.rs
This PR cleans up the MPC and ZK circuits and gadgets implementation after the Stark curve refactor of the `circuits` crate completed. This largely revolves around two big changes:
- Remove unused lifetimes from gadget and circuit interfaces now that `MpcProver` has removed its lifetimes
- Pass `MpcFabric` by reference when possible. The `MpcFabric` type already has a fairly efficient `Clone` impl, but this simplifies interfaces and avoids some of the cloning overhead for very large circuits that clone frequently
> circuits: Cleanup crate after Stark curve refactor

- core/Cargo.toml
- core/src/chain_events/listener.rs
- core/src/gossip/worker.rs
- core/src/price_reporter/exchange/uni_v3.rs
- core/src/starknet_client/client.rs
- core/src/tasks/create_new_wallet.rs
- core/src/tasks/settle_match.rs
- core/src/tasks/settle_match_internal.rs
- core/src/tasks/update_wallet.rs
- crypto/Cargo.toml
Rebase our StarkNet client onto the most recent version of `starknet-rs`, as it has upstream changes that are necessary for new RPC specs.
* Rust unit tests pass.
* Integration tests with `renegade-js` pass. This particular branch does not pass, but a rebased `testnet` branch on top of these changes works.
We use certain deprecated methods, since even though they're "deprecated", there is no equivalent RPC-compliant version that does not directly contact the sequencer. We will remove this once the RPC is up-to-date.
> core: stark_client, chain_events: Rebase onto most recent starknet-rs

- core/Cargo.toml
- core/src/main.rs
- state/Cargo.toml
- state/src/tui.rs
The debug TUI was broken during the crate refactor because it is gated behind a feature flag that was removed. This PR removes this conditional compilation and simply depends on `cli_args.debug` to switch on/off the TUI mode
- Tested the TUI, verified its functionality
> core, state: Fix debug TUI

- .dockerignore
- circuits/Cargo.toml
- circuits/integration/main.rs
- task-driver/Cargo.toml
- task-driver/Dockerfile
- task-driver/docker-compose.yml
- task-driver/integration/main.rs
- test-helpers/src/macros.rs
- util/Cargo.toml
- util/src/lib.rs
- util/src/logging.rs
This PR sets up the testing harness for the `task-driver` integration tests. This involves:
- Generalizing some of the helpers used for integration test setup in the `circuits` crate (the only other crate with formal integration tests)
- Setting up a docker compose style stack, currently just with a copy of the relayer running the tests
- Adding an integration test harness using the harness defined in the `test-helpers` crate.
- Add a devnet sequencer to the `docker-compose`
- Add integration tests to the crate
- Ran the integration tests, verified that the dummy test passed
> task-driver: Setup integration test harness

- .dockerignore
- Cargo.toml
- bin/cargo-integrate
- docker/contracts/Dockerfile
- docker/devnet/Dockerfile
- starknet-client/src/client.rs
- task-driver/Cargo.toml
- task-driver/Dockerfile
- task-driver/docker-compose.yml
- task-driver/integration/main.rs
- test-helpers/Cargo.toml
- test-helpers/src/contracts.rs
- test-helpers/src/lib.rs
This PR sets up a devnet sequencer for integration testing the `tasks` crate. Much of this infra is re-usuable and will be used across various crates. The setup is as follows:
1. A docker image the builds our contract sources from `main:HEAD` of `renegade-contracts` so that encapsulating containers may pull pre-built sources in.
2. A docker container that wraps `shardlabs/devnet-sequencer` and installs the `starknet-sierra-compile` binary at the version we use to compile contracts.
3. A docker container that runs the integration tests for the `task-driver` with access to the compiled contract artifacts.
- Integration tests against devnet with forked state are passing
> task-driver: integration: Setup devnet sequencer for integration tests

- config/src/lib.rs
- state/Cargo.toml
- state/src/lib.rs
- state/src/mock.rs
This PR adds a mock for the `RelayerState` object so that it may be injected into integration tests. This also adds a more explicit `Default` behavior to the `RelayerConfig` object.
The mock follows a builder pattern to expose the flags that the `RelayerState` constructor consumes.
> state, config: Mock `RelayerState` object for integration tests

- .github/workflows/test.yml
- Cargo.toml
- circuit-macros/Cargo.toml
- circuit-types/Cargo.toml
- circuits/Cargo.toml
- circuits/src/zk_circuits/valid_settle.rs
- circuits/src/zk_circuits/valid_wallet_create.rs
- circuits/src/zk_circuits/valid_wallet_update.rs
- workers/proof-manager/Cargo.toml
- workers/proof-manager/src/lib.rs
- workers/proof-manager/src/mock.rs
This PR creates a mock for the `ProofManager` that immediately returns a dummy (invalid) proof. This will be used in integration tests to remove proof generation latency from the test critical path.
- Added a test to verify the data path of the mock
> workers: proof-manager: Define mock manager that skips proving

- circuits/benches/valid_wallet_create.rs
This PR adds benchmarks on `VALID WALLET CREATE` prover, verifier, and constraint generation latency on the full sized circuits, with parameters taken from the system wide `constants` crate.
> circuits: benches: valid-wallet-create: Add full sized benchmarks

- circuits/benches/valid_wallet_create.rs
- circuits/benches/valid_wallet_update.rs
- circuits/src/zk_circuits/mod.rs
- circuits/src/zk_circuits/valid_reblind.rs
- circuits/src/zk_circuits/valid_wallet_update.rs
This PR adds full sized (i.e. using the sizing constants defined in the `constants` crate) benchmarks for the `VALID WALLET UPDATE` circuit. As well, this PR re-implements a test helper function `create_multi_opening` to work efficiently on larger inputs, avoiding constructing the entire Merkle tree.
> circuits: benches: `VALID WALLET UPDATE`: Add full sized benchmark

- circuits/benches/valid_reblind.rs
- circuits/src/zk_circuits/valid_reblind.rs
This PR adds full sized benchmarks for the `VALID REBLIND` circuit using the constants defined in the `constants` crate.
- Ran benchmarks
> circuits: benches: `VALID REBLIND`: Add full sized benchmarks

- circuits/benches/valid_commitments.rs
- circuits/src/zk_circuits/valid_commitments.rs
This PR adds full sized benchmarks for the `VALID COMMITMENTS` circuit. The sizing constants on these benchmarks are taken from the `constants` crate.
> circuits: benches: `VALID COMMITMENTS`: Add full sized benchmarks

- circuits/benches/valid_settle.rs
- circuits/src/zk_circuits/valid_settle.rs
This PR adds full sized benchmarks for the `VALID SETTLE` circuit. Sizing constants are taken from the system wide constants defined in the `constants` crate.
> circuits: benches: `VALID SETTLE`: Add full size benchmarks

- test-helpers/Cargo.toml
- test-helpers/src/mpc_network.rs
- test-helpers/src/mpc_network/mock_with_delay.rs
- test-helpers/src/mpc_network/mocks.rs
This PR adds a `MockNetworkWithDelay` that mocks a non-zero point-to-point latency between nodes. This will be used in MPC benchmarks to simulate various connection latencies.
- Possibly add bandwidth as an axis to mock on
> test-helpers: mpc-network: mock-with-delay: Add delayed network mock

- .gitignore
- Cargo.toml
- circuits/Cargo.toml
- circuits/benches/match.rs
- circuits/benches/valid_commitments.rs
- circuits/benches/valid_reblind.rs
- circuits/benches/valid_settle.rs
- circuits/benches/valid_wallet_create.rs
- circuits/benches/valid_wallet_update.rs
This PR adds the `large_benchmarks` feature flag to the `circuits` crate to conditionally enable the larger sized benchmarks on the circuits. These benchmarks can be very long running and are not very useful for performance analysis (as compared to their smaller counterparts), so they are disabled by default.
- Ran all benchmarks to verify the feature flag works
> circuits: benches: Add compile-time flag to enable large benchmarks

- core/src/main.rs
- starknet-client/src/client.rs
- task-driver/integration/main.rs
- task-driver/src/create_new_wallet.rs
- task-driver/src/settle_match.rs
- task-driver/src/settle_match_internal.rs
- task-driver/src/update_wallet.rs
This PR migrates the `StarknetClient` to use only the JSON-RPC api, and not the sequencer gateway. The gateway will be deprecated as Starknet decentralizes, so this change is necessary eventually. As well, this change allows us to test against more recent sequencer versions and implementations, like Katana.
> starknet-client: Remove the use of the sequencer gateway API

- circuits/src/zk_circuits/valid_wallet_create.rs
- starknet-client/src/types.rs
This PR exposes the `SizedWitness` / `SizedStatement` types from the `VALID WALLET CREATE` test helpers, and makes the fields of the `StarknetU256` public, so that they may be better reused in e2e tests in the `renegade-contracts` repo
> circuits, starknet-client: expose test helper types

- circuit-types/src/traits.rs
- circuits/benches/match.rs
- circuits/benches/valid_commitments.rs
- circuits/benches/valid_reblind.rs
- circuits/benches/valid_settle.rs
- circuits/benches/valid_wallet_create.rs
- circuits/benches/valid_wallet_update.rs
- circuits/src/lib.rs
- circuits/src/zk_circuits/valid_match_mpc.rs
This PR changes the `BulletproofGens` used by the prover and verifiers in the `circuits` crate to be statically allocated via `lazy_static`. This removes the need to allocate them in the prove/verify critical path, which proves time consuming for large circuits.
> circuits: Pre-allocate `BulletproofGens` for circuits

- bin/cargo-integrate
- circuits/docker-compose.yml
- docker/contracts/Dockerfile
- docker/devnet/Dockerfile
- docker/devnet/setup-sequencer.sh
- task-driver/docker-compose.yml
- task-driver/integration/main.rs
- test-helpers/Cargo.toml
- test-helpers/src/contracts.rs
This PR sets up a [katana](https://book.dojoengine.org/toolchain/katana/overview.html) node in CI for integration tests to run against. This setup depends on a locally available image with the contract sources compiled within them. The katana sequencer copies the contract sources from this image, deploys them to the sequencer, then dumps the state of the sequencer so that it may be started back up with pre-deployed contracts.
- Tested a nullifier check integration test in the `task-driver` integration tests against the sequencer stack
> docker: devnet: Run Katana node with pre-deployed contracts for tests

- Cargo.toml
- common/src/types/chain_id.rs
- config/src/lib.rs
- core/src/main.rs
- starknet-client/Cargo.toml
- starknet-client/src/client.rs
- starknet-client/src/client/chain_state.rs
- starknet-client/src/client/contract_interaction.rs
- starknet-client/src/error.rs
- starknet-client/src/helpers.rs
- starknet-client/src/lib.rs
- starknet-client/src/types.rs
- task-driver/integration/main.rs
- task-driver/src/create_new_wallet.rs
- task-driver/src/settle_match.rs
- task-driver/src/settle_match_internal.rs
- task-driver/src/update_wallet.rs
- test-helpers/src/contracts.rs
- workers/chain-events/src/listener.rs
- workers/chain-events/src/worker.rs
This PR updates the `starknet-client` to match the Cairo 1 contracts that are now deployed. This involves:
- Updating the `starknet` dependency to target `0.5` and inheriting all the library changes that come along with that. Notably the removal of the pending block from most interfaces.
- Updating selectors for changed names in the new contracts
- Refactoring the `starknet-client` to aid discoverability now that the code size has grown
- Existing tests pass
- I will add integration tests for the client in a follow up
> starknet-client: Update client to match Cairo 1.0 contract interface

- circuit-types/src/lib.rs
- circuits/benches/match.rs
- circuits/integration/mpc_circuits/match.rs
- circuits/src/mpc_circuits/match.rs
- workers/handshake-manager/src/manager/match.rs
This PR restructures the `match` MPC circuit to take `AuthenticatedLinkableOrder` types directly instead of the un-linked `AuthenticatedOrder` types. this allows us to avoid re-allocation at MPC time (once for the linkable type and once for the un-linked type) and instead use the same, pre-allocated types across both the `match` MPC and the collaborative proof of `VALID MATCH MPC`.
> circuits: mpc-circuits: match: Take commitment linked orders directly

- circuits/Cargo.toml
- circuits/benches/full_match.rs
- workers/handshake-manager/src/manager/match.rs
This PR adds a `full_match` benchmark which benchmarks the full process of executing an MPC to generate a witness and then collaboratively proving `VALID MATCH MPC` on that witness. The benchmark runs two separate `main` methods based on whether the `stats` feature flag is enabled:
- If `stats` is enabled, the `main` method simply runs a single MPC and allows the `MpcFabric` to dump statistics on exit
- If `stats` is disabled, the benchmark is a criterion benchmark on three different latencies -- those used in the other MPC benchmarks.
- Ran benchmarks in both `--features "... stats"` and without `stats`
> circuits: benches: full-match: Add full match (MPC + proof) benchmark

- starknet-client/Cargo.toml
- starknet-client/Dockerfile
- starknet-client/docker-compose.yml
- starknet-client/integration/main.rs
- test-helpers/src/assertions.rs
- test-helpers/src/lib.rs
This PR adds the skeleton for the `starknet-client` integration tests. This includes a docker compose setup for compiling the contracts, deploying them to a devnet, and then running the integration tests in a node targeting this devnet. Included is a sample PR for checking a dummy nullifier is not used immediately after the contract is initialized.
- Unit and integration tests pass, including the nullifier test added with this PR
> starknet-client: integration: Add integration test skeleton

- circuit-types/src/merkle.rs
- circuits/integration/mpc_circuits/match.rs
- circuits/integration/mpc_gadgets/arithmetic.rs
- circuits/integration/mpc_gadgets/bits.rs
- circuits/integration/mpc_gadgets/comparators.rs
- circuits/integration/mpc_gadgets/modulo.rs
- circuits/integration/mpc_gadgets/poseidon.rs
- circuits/integration/types/sharing.rs
- circuits/integration/zk_circuits/valid_match_mpc.rs
- circuits/integration/zk_gadgets/arithmetic.rs
- circuits/integration/zk_gadgets/bits.rs
- circuits/integration/zk_gadgets/poseidon.rs
- circuits/src/zk_circuits/mod.rs
- renegade-crypto/src/fields.rs
- starknet-client/Cargo.toml
- starknet-client/Dockerfile
- starknet-client/docker-compose.yml
- starknet-client/integration/chain_state.rs
- starknet-client/integration/helpers.rs
- starknet-client/integration/main.rs
- starknet-client/src/client.rs
- starknet-client/src/client/chain_state.rs
- starknet-client/src/helpers.rs
- starknet-client/src/lib.rs
- task-driver/integration/create_new_wallet.rs
- task-driver/integration/main.rs
- test-helpers/src/assertions.rs
- test-helpers/src/types.rs
- util/src/runtime.rs
This PR adds integration tests for:
- Fining a wallet commitment in the contract state
- Finding a Merkle path in the contract state
- Recovering wallet shares from a transaction
This PR also restructures the way in which calldata is parsed from `InvokeV1` transactions.
> starknet-client: Add chain state integration tests

- common/src/types/proof_bundles.rs
- starknet-client/integration/helpers.rs
- task-driver/src/helpers.rs
- task-driver/src/initialize_state.rs
- workers/handshake-manager/src/manager/match.rs
- workers/proof-manager/src/mock.rs
- workers/proof-manager/src/proof_manager.rs
This PR changes the runtime representation of all proof types to be heap-allocated. This avoids stack overflows (especially in Tokio contexts) and crowding the stack with infrequently accessed values.
> common: types: proof-bundles: Allocate all proof bundles on heap

- task-driver/src/create_new_wallet.rs
- task-driver/src/settle_match.rs
- task-driver/src/settle_match_internal.rs
- task-driver/src/update_wallet.rs
This PR removes calls to `StarknetClient::poll_transaction_completed` for now. This method needs refactoring and must paper over some API changes upsteam, so for now we simply do not call it.
The implication of not waiting for finality is that the next step of each task (finding Merkle paths) will likely fail and need to be retried a few times as the network finalizes and gossips the transaction.
> task-driver: Do not await transaction finality

- common/src/types/wallet.rs
- starknet-client/Cargo.toml
- starknet-client/src/client.rs
- starknet-client/src/client/chain_state.rs
- starknet-client/src/client/pathfinder.rs
- starknet-client/src/error.rs
- task-driver/src/create_new_wallet.rs
- task-driver/src/settle_match.rs
- task-driver/src/settle_match_internal.rs
- task-driver/src/update_wallet.rs
This PR changes the `starknet-client` to the use the `pathfinder_getTransactionStatus` API to poll transaction finality instead of the `starknet_getTransactionReceipt` API. This API is more stable, and more consistently reports finality information. As well, we do not need any element on a transaction's receipt except its finality status.
- Integration tests for `starknet-client` pass
- Integration tests for `task-driver` pass
> starknet-client: pathfinder: Use pathfinder API to poll transaction finality

- circuit-types/Cargo.toml
- circuit-types/src/keychain.rs
- circuits/src/zk_circuits/mod.rs
- common/src/types/wallet.rs
- state/src/wallet.rs
- workers/api-server/Cargo.toml
- workers/api-server/src/lib.rs
This PR updates the `PublicSigningKey` type to be a representation of a `StarkPoint` (namely, the `Scalar`s needed to represent a point's affine coordinates), and the `SecretSigningKey` type to be a `Scalar`, as expected for ECDSA over the STARK curve in accordance with the [IETF spec](datatracker.ietf.org/doc/html/rfc6979).
This PR also stubs out some changes to the API, namely it temporarily removes request signature verification logic, pending a future PR where STARK ECDSA is implemented.
All unit tests pass (including an updated serialization / deserialization test for the `PublicSigningKey`), and the affected integration tests (those in the `circuits` crate) pass.
> circuit-types: replaced signing key types with StarkPoint & Scalar

- circuit-types/Cargo.toml
- circuit-types/src/keychain.rs
- circuits/src/zk_circuits/mod.rs
- common/src/types/wallet.rs
- state/src/wallet.rs
- workers/api-server/Cargo.toml
- workers/api-server/src/lib.rs
This PR reverts the last two commits, which introduced changes to the signing key types in anticipation of the implementation of ECDSA over the STARK curve.
This was reverted to keep `main` stable for our upcoming demo.
The changes will be preserved & built on top of in a separate branch.
> reverted circuit-types stark curve ecdsa keychain changes

- bin/cargo-integrate
- starknet-client/src/client/chain_state.rs
- task-driver/Cargo.toml
- task-driver/integration/helpers.rs
- task-driver/integration/main.rs
- task-driver/integration/tests/update_wallet.rs
- test-helpers/src/macros.rs
This PR adds additional `update-wallet` tests including:
- Adding and removing fees
- Depositing and withdrawing balances from the pool. This makes use of the pre-deployed `ETH` ERC-20 on the katana devnet node
> task-driver: integration: update-wallet: Add additional tests with ERC20 deposit + withdrawal

- renegade-crypto/Cargo.toml
- renegade-crypto/src/ecdsa.rs
- renegade-crypto/src/lib.rs
This PR introduces signature generation & verification primitives for ECDSA over the STARK curve in accordance with the [IETF RFC 6979 specification](https://datatracker.ietf.org/doc/html/rfc6979).
This also includes some basic unit tests asserting proper verification (or lack thereof) of valid / invalid signatures, which pass.
These primitives will be worked into the `api-server` and `circuit-types` crates in a future PR for the signing of API requests and proof statements.
> renegade-crypto: ecdsa: implement message hashing & signing primitives

- circuit-types/src/keychain.rs
- circuits/src/zk_circuits/mod.rs
- common/src/types/wallet.rs
- renegade-crypto/src/ecdsa.rs
- workers/api-server/Cargo.toml
- workers/api-server/src/lib.rs
This PR replaces the wallet request authentication logic with STARK curve ECDSA signature verification.
There are no tests for the API server crate, so these changes will have to be tested ad-hoc when they are integrated into the client
> api-server: replaced wallet request auth w/ stark curve ecdsa

- renegade-crypto/src/ecdsa.rs
This PR fixes the reduction of a keccak hash output to a scalar in the `ecdsa` module to match the Cairo keccak implementation, which expects little-endian `u256`s as input but returns a big-endian `u256`.
All of the `ecdsa` unit tests pass.
> renegade-crypto: ecdsa: reverse keccak byte output

- external-api/src/types.rs
- workers/handshake-manager/src/manager.rs
This PR makes two small changes to match assumptions made in the javascript SDK:
- Order mints are specified by their ETH-L1 addresses, not the Starknet address
- Default order type must be changed to `OrderType::Midpoint` now that we only support midpoint addresses, this field is displayed on the client side
> external-api, handshake-manager: Update `Order` API assumptions to match SDK

- Cargo.toml
- statev2/Cargo.toml
- statev2/src/lib.rs
- statev2/src/storage/db.rs
- statev2/src/storage/error.rs
- statev2/src/storage/mod.rs
- statev2/src/storage/traits.rs
This PR beings the storage refactor by exposing a simple key-value interface over an `mdbx` embedded instance. Currently, this interface only exposes `set` and `get` methods, but we will add transactional semantics in a follow up PR
- Simple unit tests pass
> statev2: storage: db: Initialize database interface

- statev2/src/storage/db.rs
- statev2/src/storage/error.rs
This PR adds a set of transactional semantics over the `mdbx` database wrapper. Together these wrappers effectively provide a cleaner (fewer flags) interface to the db, and automatic serialization/deserialization to the caller's expected type. This thin wrapper will be composed into higher layers of abstraction by the replication layer and application logic.
As well, this PR adds a number of tests for various basic cases as well as transaction isolation, crash recovery, etc.
> statev2: db: Add transaction semantics and full functionality test cases

- statev2/src/lib.rs
- statev2/src/storage/cursor.rs
- statev2/src/storage/db.rs
- statev2/src/storage/error.rs
- statev2/src/storage/mod.rs
This PR adds an initial `Cursor` implementation on top of the database. This wraps an internal cursor and provides a serialization/deserialization layer on top of the cursor.
We could have used the `libdmbx::orm` module to do this ([link](https://docs.rs/libmdbx/latest/libmdbx/orm/index.html)), but this is a bit restrictive in that *all* tables must have a model at database creation time. Some tables will store heterogenous data (e.g. metadata tables), so the ORM doesn't quite give us what we want.
- Planning to add more tests in a follow up PR
> statev2: storage: cursor: Add `Cursor` implementation

- statev2/Cargo.toml
- statev2/src/storage/cursor.rs
This PR adds a full unit test suite for the `Cursor` interface. Of particular interest is sorted iteration: we currently sort numeric keys by casting them to a string. This is okay for now, but should we want more advanced sorting we can implement a hook into the [`MDBX_DUPSORT`](https://erthink.github.io/libmdbx/group__c__dbi.html#ggafe3bddb297b3ab0d828a487c5726f76aaed33d978b4e23b7c1659e8106e9c7acd:~:text=comparison%20for%20keys.-,MDBX_DUPSORT,-Use%20sorted%20duplicates) interface.
> storage: cursor: Add cursor unit tests

- statev2/Cargo.toml
- statev2/src/lib.rs
- statev2/src/replication/error.rs
- statev2/src/replication/log_store.rs
- statev2/src/replication/mod.rs
- statev2/src/storage/cursor.rs
- statev2/src/storage/error.rs
- statev2/src/storage/mod.rs
The `raft` needs a [`Storage`](https://docs.rs/raft/latest/raft/storage/trait.Storage.html) impl to read its log, metadata, snapshots, etc from. Concretely we use the embedded `mdbx` instance in the storage layer as the underlying persistence mechanism. 
This means that the DB serves two purposes:
- Store the state machine of the relayer and its cluster
- Store the raft log and metadata used to form consensus over the relayer's state machine
This PR implements the `Storage` trait for `LogStore` which functions as the plumbing between the storage and replication layers.
- Will add tests in a follow up PR
> statev2: replication: log-store: Add `LogStore` implementation

- statev2/Cargo.toml
- statev2/src/lib.rs
- statev2/src/replication/error.rs
- statev2/src/replication/log_store.rs
- statev2/src/replication/mod.rs
- statev2/src/replication/raft_node.rs
- statev2/src/storage/db.rs
This PR takes the first steps towards including the `raft` consensus engine in our `statev2` replication layer. This involves a few changes to the `LogStore` implementation to bring it into compatibility with the `RaftNode`'s use. Specifically we:
- Apply a default snapshot when the `LogStore` is initialized
- Fall back to this default when other values are not available in storage
> statev2: replication: raft-node: Add initial raft node implementation

- statev2/Cargo.toml
- statev2/src/lib.rs
- statev2/src/replication/error.rs
- statev2/src/replication/log_store.rs
- statev2/src/replication/mod.rs
- statev2/src/replication/network.rs
- statev2/src/replication/raft_node.rs
This PR implements the main driver loop for the raft consensus engine. This event loop effectively serves two purposes:
- Poll for inbound messages from the network
- Process the ready state from the consensus engine, this involves:
- Handling outbound messages to peers, generated by the consensus engine
- Committing log entries and applying them to the state machine
- Appending new (uncommitted) log entries to the persisted log
- Applying config and hard state changes
This process connects the raft consensus engine to the storage and networking layers.
- Testing of the event loop will be done via the functional unit imposed by defining *our* state transitions, so for now it is expected that this implementation is buggy
> statev2: replication: raft-node: Add raft loop handler implmentation

- circuit-types/src/balance.rs
- circuit-types/src/wallet.rs
- circuits/integration/mpc_circuits/match.rs
- circuits/integration/zk_circuits/valid_match_mpc.rs
- circuits/src/zk_circuits/mod.rs
- circuits/src/zk_circuits/valid_commitments.rs
- circuits/src/zk_circuits/valid_match_mpc.rs
- circuits/src/zk_circuits/valid_settle.rs
- circuits/src/zk_circuits/valid_wallet_update.rs
This PR changes the structure of the `Wallet` and `Balance` types to begin implementation of the fee design. These structural changes simplify fees to a single fixed point take that a relayer may capture. As well, we introduce the notion of a `managing_cluster` to the `Wallet`.
This PR also removes many of the fee-centric constraints in the circuit so that the crates compile. These circuits will be updated in follow up PRs
- Unit and integration tests pass for `circuits` and `circuit-types`
- CI will remain red while the code is in an intermediate state
> circuit-types, circuits: Update `Wallet` and `Balance` structs for fee impl

- circuits/src/zk_circuits/valid_wallet_create.rs
This PR makes the updates necessary to support the fee implementation in `VALID WALLET CREATE`. Because `VALID WALLET CREATE` only deals with the fees implicitly in its implementation, I only added a test for the added functionality already covered by the existing implementation.
- All unit and integration tests pass in the `circuits` crate
- CI will remain red while the fee implementation is in progress
> circuits: zk-circuits: `VALID WALLET CREATE`: Add non-zero fee balance test

- .gitignore
- circuit-types/src/fixed_point.rs
- circuit-types/src/match.rs
- circuits/benches/match.rs
- circuits/integration/mpc_circuits/match.rs
- circuits/integration/zk_circuits/valid_match_mpc.rs
- circuits/src/mpc_circuits/match.rs
- circuits/src/zk_circuits/valid_match_mpc.rs
- circuits/src/zk_circuits/valid_settle.rs
- constants/src/lib.rs
This PR computes the protocol fee takes in the `match` MPC as a publically known fixed point constant multiplied by the volumes of each asset matched.
Relayer fees and the integration of both fee types into the `VALID MATCH MPC` and `VALID SETTLE` circuits will come in a follow up.
- Added unit tests for the fee take
> circuits: mpc-circuits: match: Compute protocol fee takes in MPC circuit

- circuit-types/src/fixed_point.rs
- circuit-types/src/match.rs
- circuit-types/src/order.rs
- circuits/benches/full_match.rs
- circuits/benches/match.rs
- circuits/integration/mpc_circuits/match.rs
- circuits/integration/zk_circuits/valid_match_mpc.rs
- circuits/src/mpc_circuits/match.rs
- circuits/src/zk_circuits/valid_match_mpc.rs
- circuits/src/zk_circuits/valid_settle.rs
This PR adds the computation of the relayer fee take to the match mpc. This is concretely done as follows: the relayers each input a fee term to the MPC which is multiplied by the base amount in the match. The implicit assumption is that the buy side relayer (sells the quote token to buy the base) has pre-multiplied the fee take by the execution price to change units into the quote token. This assumption is constrained in the match proof that follows.
Integration of this fee computation and the protocol fee computation into the proofs of `VALID MATCH MPC` and `VALID SETTLE` will be done in a follow up.
- CI will fail until the fee implementation is further along
> circuits: mpc-circuits: match: Compute relayer fee takes in MPC circuit

- docker/devnet/setup-sequencer.sh
This PR deploys an ERC20 contract for a USDC token to the Katana devnet. 
- Ran the devnet node and ran a few ERC20 calls against the Katana node using `starkli`
> docker: devnet: Deploy USDC erc20 with devnet setup

- docker/frontend-test-stack/Dockerfile
- docker/frontend-test-stack/config.toml
This PR builds the relayer in release mode and switches the chain ID to katana in the config
> docker: frontend-test-stack: Build relayer in release mode

- statev2/proto/Cargo.toml
- statev2/proto/build.rs
- statev2/proto/proto/common.proto
- statev2/proto/proto/orders.proto
- statev2/proto/proto/peers.proto
- statev2/proto/proto/state_transitions.proto
- statev2/proto/proto/wallet.proto
- statev2/proto/src/lib.rs
This PR adds protobuf definitions for all state types that currently have setter methods in the existing state implementation.
As well, this PR derives a builder pattern for all generated protobuf types.
- Tested the builder pattern
> statev2: proto: Add proto definitions for all existing state transitions

- common/Cargo.toml
- common/src/types/gossip.rs
- external-api/src/bus_message.rs
- state/src/state.rs
- statev2/proto/Cargo.toml
- statev2/proto/src/error.rs
- statev2/proto/src/lib.rs
- statev2/state/Cargo.toml
- statev2/state/src/applicator/error.rs
- statev2/state/src/applicator/mod.rs
- statev2/state/src/applicator/peer_index.rs
- statev2/state/src/lib.rs
- statev2/state/src/storage/db.rs
The `StateApplicator` is in charge of appling state transitions to the storage layer. If we think of our state primitive as a distributed log that forms consensus over a sequence of state transition RPCs, the `StateApplicator` is then the RPC server executing these requests.
This PR also adds setters for the `PeerIndex` methods that store peer information and cluster membership information
- Tested peer addition and removal
> statev2: applicator: Create state applicator and add peer index setter methods

- common/src/types/network_order.rs
- statev2/proto/Cargo.toml
- statev2/proto/proto/orders.proto
- statev2/proto/src/lib.rs
- statev2/state/Cargo.toml
- statev2/state/src/applicator/error.rs
- statev2/state/src/applicator/mod.rs
- statev2/state/src/applicator/order_book.rs
- statev2/state/src/lib.rs
- statev2/state/src/storage/db.rs
This PR adds state transition handler for order book types. This includes:
- Adding new orders to the book
- Attaching validity proofs for an order
- Nullifying orders when their nullifiers are witnessed on-chain
> statev2: applicator: order-book: Add order book state transition handlers

- statev2/proto/Cargo.toml
- statev2/proto/proto/wallet.proto
- statev2/proto/src/lib.rs
- statev2/state/src/applicator/order_book.rs
This PR adds type conversion methods from wallet types in the proto definition to wallet types in the runtime/state index definition. These type definitions will be used by the `StateApplicator` to process messages
> statev2: proto: Add `Wallet` type conversion methods

- common/src/types/merkle.rs
- common/src/types/wallet.rs
- external-api/src/types.rs
- statev2/proto/proto/wallet.proto
- statev2/proto/src/lib.rs
- statev2/state/Cargo.toml
- statev2/state/src/applicator/mod.rs
- statev2/state/src/applicator/order_book.rs
- statev2/state/src/applicator/wallet_index.rs
- task-driver/src/lookup_wallet.rs
- workers/chain-events/src/listener.rs
This PR adds state transition handlers for the wallet index. This includes only adding and updating wallets at the moment. Deleting wallets and more complicated patterns may come down the line, for now this PR only seeks parity with existing functionality.
Additionally, I went ahead and removed the `proof_staleness` method on the `Wallet` object. This is no longer used and was getting in the way of implementations I wanted to make.
- Tested both state transitions
> statev2: state: applicator: Add wallet index state transition handlers

- Cargo.toml
- common/Cargo.toml
- core/Cargo.toml
- statev2/proto/Cargo.toml
- statev2/proto/build.rs
- statev2/proto/src/lib.rs
- statev2/state/Cargo.toml
- statev2/state/src/applicator/mod.rs
- statev2/state/src/applicator/wallet_index.rs
- statev2/state/src/replication/error.rs
- statev2/state/src/replication/log_store.rs
- statev2/state/src/replication/network.rs
- statev2/state/src/replication/raft_node.rs
- task-driver/Cargo.toml
- workers/api-server/Cargo.toml
- workers/chain-events/Cargo.toml
- workers/handshake-manager/Cargo.toml
- workers/proof-manager/Cargo.toml
This PR takes the first step in pulling together the replication, storage, and applicator layers by accepting state transition proposals from outside the state management module. The flow is:
1. An inbound proposal reaches the raft event loop via the `proposals_queue` channel
2. The raft node proposes the state transition to the cluster
3. The raft group appends the state transition to the log, forms consensus over the entry, then commits the log entry
4. The raft nodes individually forward the now-committed state transition to the `StateApplicator` to apply the state transition
- Tested state application of a new wallet to test the communication flow
> statev2: applicator, replication: Accept inbound proposals, and apply state transitions

- workers/price-reporter/src/exchange/coinbase.rs
This PR updates the payload used for authentication with the Coinbase API to use timestamps with 10 digits instead of 7.
> price-reporter: Update Coinbase API WebSocket auth

- circuits/integration/main.rs
- starknet-client/integration/main.rs
- statev2/proto/src/lib.rs
- statev2/state/Cargo.toml
- statev2/state/src/applicator/mod.rs
- statev2/state/src/replication/log_store.rs
- statev2/state/src/replication/raft_node.rs
- task-driver/integration/main.rs
- util/Cargo.toml
- util/src/logging.rs
This PR adds logic to add and remove peers and learners from a raft cluster. As well, this PR fixes a few `LogStore` bugs that popped up during implementation.
Testing coverage will be increased in a future PR.
- Tested the case in which a peer joins the cluster and receives replication messages
> statev2: replication: raft-node: Implement cluster join logic

- Cargo.lock
- common/Cargo.toml
- common/src/types/wallet.rs
- external-api/src/types.rs
- statev2/proto/src/lib.rs
- task-driver/src/driver.rs
- task-driver/src/lookup_wallet.rs
- task-driver/src/settle_match_internal.rs
- task-driver/src/update_wallet.rs
- workers/api-server/src/http/wallet.rs
- workers/handshake-manager/src/manager/internal_engine.rs
Concurrent updates result in confusing state from the client's perspective when one of the updates fails. For now we prevent concurrent updates alltogether. We will introduce a more sophisticated update sequencing and queuing primitive when our state is over a raft.
> common: wallet: Add wallet-level lock to prevent concurrent updates

- Cargo.lock
- Cargo.toml
- common/Cargo.toml
- external-api/src/http/wallet.rs
- state/Cargo.toml
- statev2/proto/Cargo.toml
- workers/api-server/src/http/wallet.rs
This PR fixes a bug where internal matches would not be found for orders that had been updated using the update orders route, due to an issue with mutating keys of IndexMap.
> workers: Remove key mutation when updating orders

- common/src/types/handshake.rs
- docker/devnet/Dockerfile
- task-driver/integration/helpers.rs
- task-driver/integration/tests/mod.rs
- task-driver/integration/tests/settle_match.rs
- task-driver/integration/tests/update_wallet.rs
- task-driver/src/settle_match_internal.rs
This PR adds tests for the `settle-match-internal` task in the task driver. This task is responsible for settling a match generated by the internal matching engine and updating the global state to reflect this update.
Going to add more tests in a follow up, this PR mostly introduces useful scaffolding.
- Tested a simple settle match process
> task-driver: integration: settle-match: Add settle-match-internal tests

- constants/Cargo.toml
- constants/src/lib.rs
- renegade-crypto/Cargo.toml
- renegade-crypto/src/hash.rs
- renegade-crypto/src/hash/poseidon2.rs
- renegade-crypto/src/lib.rs
In WASM contexts (i.e. contracts) we cannot import `ark-mpc`. Aside we only superficially use this crate for its types, so it is unimportant to certain functionalities, i.e. hashing. This PR introduces a feature flag `non-wasm` on by default that allows wasm targets to disable wasm-incompatible features.
> renegade-crypto, constants: Gate `ark-mpc` dependency behind feature flag

- Cargo.lock
- Cargo.toml
- circuit-types/Cargo.toml
- circuit-types/src/errors.rs
- circuit-types/src/traits.rs
- constants/Cargo.toml
- constants/src/lib.rs
- renegade-crypto/src/hash/constants.rs
This PR refactors the `traits` module in the `circuit-types` crates to reflect the new plonkish arithmetization and multiprover paradigm. Of notable difference:
- The plonk arithmetization requires one gate per addition, so we do not have the `Variable` and `LinearCombination` distinction that Dalek gave. This simplifies the associated types on Variable types. As well, it allow us to reuse variable types between single and multi prover
- We no longer have a need for proof linkable types, the proof linking scheme will come later
- Commitment types are removed, Plonk commits to its witness using KZG, which is unstructured wrt runtime types
- CI passes for the crate
> circuit-types: traits: Refactor traits over plonk proof system

- Cargo.lock
- test-helpers/Cargo.toml
- test-helpers/src/mpc_network.rs
- test-helpers/src/mpc_network/mock_with_delay.rs
- test-helpers/src/mpc_network/mocks.rs
This PR refactors the `test-helpers` crate over the new `ark-mpc` implementation. This largely involves attaching generics that represent the curve group now that the MPC implementation is curve-generic.
> test-helpers: Refactor over new `ark-mpc` implementation

- Cargo.lock
- circuit-macros/src/circuit_type/singleprover_circuit_types.rs
- circuit-types/Cargo.toml
- circuit-types/src/fixed_point.rs
- circuit-types/src/macro_tests.rs
- circuit-types/src/traits.rs
This PR refactors the fixed point arithmetic implementation over the new `mpc-jellyfish` circuits. This includes types for native FP arithmetic, in-circuit arithmetic, and mpc fixed point arithmetic.]
- Tested arithmetic operations of all forms of fixed point
> circuit-types: fixed-point: Refactor fixed point arithmetic over new circuits

- Cargo.lock
- circuit-types/Cargo.toml
- circuits/Cargo.toml
- circuits/src/mpc_gadgets/arithmetic.rs
- circuits/src/mpc_gadgets/bits.rs
- constants/src/lib.rs
This PR refactors the arithmetic and bitwise MPC gadgets over the new `ark_mpc` library and adds unit tests for important gadgets that were previously only tested in integration tests. Some gadgets don't have tests as they are implicitly tested elsewhere.
> circuits: mpc-gadgets: arithmetic, bits: Refactor implementations and add unit tests

- circuits/src/mpc_gadgets/bits.rs
- circuits/src/mpc_gadgets/comparators.rs
- circuits/src/mpc_gadgets/modulo.rs
This PR refactors the `bits`, `comparators`, and `modulo` mpc gadgets and adds tests for previously untested (or only tested in integration tests) gadgets. Some gadgets are tested implicitly through others.
- Added tests for refactored gadgets
> circuits: mpc-gadgets: bits, comparators, modulo: Refactor + add tests

- Cargo.lock
- circuits/Cargo.toml
- circuits/src/zk_gadgets/poseidon.rs
This PR refactors the Poseidon gadget to work over the new `mpc-plonk` system. This gadget also works for both single and multiprovers. I added a test for coherence with the sponge defined in `renegade-crypto`.
> circuits: zk-gadgets: poseidon: Refactor and add unit tests

- circuit-macros/src/circuit_type/singleprover_circuit_types.rs
- circuit-types/src/balance.rs
- circuit-types/src/fee.rs
- circuit-types/src/keychain.rs
- circuit-types/src/lib.rs
- circuit-types/src/macro_tests.rs
- circuit-types/src/match.rs
- circuit-types/src/merkle.rs
- circuit-types/src/order.rs
- circuit-types/src/traits.rs
- circuit-types/src/transfers.rs
- circuit-types/src/wallet.rs
This PR introduces a boolean type to MPC and ZK circuits. This necessitates that variable types have a reference to the underlying constraint system when they are deserialized, so that they may apply constraints on their underlying variables. For the boolean type this adds a constraint that the value is boolean (i.e. $x(1 -x) \stackrel{?}{=} 0$)
> circuit-types: Add boolean type and `BoolVar`, `AuthenticatedBool` analogs

- circuit-macros/src/circuit_type/singleprover_circuit_types.rs
- circuit-types/src/balance.rs
- circuit-types/src/fee.rs
- circuit-types/src/fixed_point.rs
- circuit-types/src/keychain.rs
- circuit-types/src/lib.rs
- circuit-types/src/macro_tests.rs
- circuit-types/src/match.rs
- circuit-types/src/merkle.rs
- circuit-types/src/order.rs
- circuit-types/src/traits.rs
- circuit-types/src/transfers.rs
- circuit-types/src/wallet.rs
- circuits/src/zk_gadgets/bits.rs
- circuits/src/zk_gadgets/poseidon.rs
- circuits/src/zk_gadgets/select.rs
This PR removes the use of `ConstraintSystem` in the `circuit-types` and `circuit-macros` crates following changes to the upstream to merge `ConstraintSystem` and `Circuit`.
> circuit-types, circuit-macros: Remove `ConstraintSystem` use

- Cargo.lock
- circuit-types/src/merkle.rs
- circuits/src/zk_gadgets/merkle.rs
- circuits/src/zk_gadgets/poseidon.rs
This PR refactors the Merkle tree gadget implementation and adds unit tests for valid and invalid witness cases.
> circuits: zk-gadgets: merkle: Refactor and add unit tests

- Cargo.lock
- circuit-types/src/fixed_point.rs
- circuits/src/zk_gadgets/arithmetic.rs
- circuits/src/zk_gadgets/fixed_point.rs
- circuits/src/zk_gadgets/mod.rs
- circuits/src/zk_gadgets/wallet_operations.rs
This PR refactors the `arithmetic`, `fixed-point`, and `wallet-operations` modules of the `zk-gadgets` to work over the new `mpc-jellyfish` system. I also added unit tests for all refactored gadgets, some are tested implicitly.
> circuits: zk-gadgets: arithmetic, fixed-point, wallet-operations: Refactor and add unit tests

- Cargo.lock
- Cargo.toml
- circuit-types/Cargo.toml
- circuit-types/src/errors.rs
- circuit-types/src/lib.rs
- circuit-types/src/traits.rs
- circuits/Cargo.toml
- circuits/src/lib.rs
- circuits/src/zk_circuits/mod.rs
- circuits/src/zk_circuits/valid_wallet_create.rs
This PR makes the changes necessary to support full ZK prove/verify flows and uses this to refactor the `VALID WALLET CREATE` circuit. This includes structuring how the proving and verifying keys fit into the `SingleProverCircuit` and `MultiProverCircuit` traits.
> circuits: zk-circuits: valid-wallet-create: Refactor over `mpc-plonk`

- circuits/src/zk_circuits/mod.rs
- circuits/src/zk_circuits/valid_commitments.rs
- circuits/src/zk_circuits/valid_wallet_update.rs
- circuits/src/zk_gadgets/comparators.rs
- circuits/src/zk_gadgets/fixed_point.rs
This PR refactors the `VALID COMMITMENTS` circuit over `mpc-plonk`. This circuit is proved once per order and allows a relayer to augment a wallet with balances for received mints in a trade.
> circuits: zk-circuits: valid-commitments: Refactor over `mpc-plonk`

- .github/workflows/clippy.yml
- circuit-types/src/lib.rs
- circuit-types/src/traits.rs
- circuit-types/src/wallet.rs
- circuits/src/lib.rs
- circuits/src/zk_circuits/mod.rs
- circuits/src/zk_circuits/valid_commitments.rs
- circuits/src/zk_circuits/valid_reblind.rs
- circuits/src/zk_circuits/valid_wallet_create.rs
- circuits/src/zk_circuits/valid_wallet_update.rs
- circuits/src/zk_gadgets/merkle.rs
- circuits/src/zk_gadgets/select.rs
- circuits/src/zk_gadgets/wallet_operations.rs
This PR refactors `VALID REBLIND` over the `mpc-plonk` system. This proof samples new shares for the wallet ahead of a match so that it is statistically indistinguishable from a random wallet, even given a previous match. 
This PR also adds a couple lint rules to deny useless pass by value and mutable reference. This comes from an observation that the `circuits` crate did a lot of unnecessary cloning to fit poorly-specified interfaces.
> circuits: zk-circuits: valid-reblind: Refactor over `mpc-plonk`

- Cargo.lock
- arbitrum-client/Cargo.toml
- arbitrum-client/src/abi.rs
- arbitrum-client/src/client/contract_interaction.rs
- arbitrum-client/src/client/event_indexing.rs
- arbitrum-client/src/constants.rs
- arbitrum-client/src/errors.rs
- arbitrum-client/src/helpers.rs
This PR adds the `fetch_public_shares_from_tx` method to the Arbitrum client, allowing it to read a wallet's public secret shares from calldata.
Currently, this method only expects to parse shares from calldata where the {`new_wallet`, `update_wallet`, `process_match_settle`} call was a top-level call issued by an EOA, for simplicity. I've added a todo for parsing shares from calldata where the Darkpool function was called by another contract, I felt it was not worth trying to implement before having an integration testing stack.
This marks the end of the core functionality required by the client, the next PRs will focus on integration testing of the client, after which I'll focus on deprecating the Starknet client throughout the relayer in favor of the Arbitrum client.
> arbitrum-client: fetch_public_shares_from_tx

- Cargo.lock
- circuit-types/src/fixed_point.rs
- circuit-types/src/lib.rs
- circuit-types/src/macro_tests.rs
- circuit-types/src/match.rs
- circuit-types/src/order.rs
- circuit-types/src/traits.rs
- circuits/Cargo.toml
- circuits/src/lib.rs
- circuits/src/mpc_circuits/match.rs
- circuits/src/zk_circuits/mod.rs
- circuits/src/zk_circuits/valid_commitments.rs
- circuits/src/zk_circuits/valid_match_mpc.rs
- circuits/src/zk_circuits/valid_wallet_create.rs
- circuits/src/zk_circuits/valid_wallet_update.rs
- circuits/src/zk_gadgets/bits.rs
- circuits/src/zk_gadgets/comparators.rs
- circuits/src/zk_gadgets/fixed_point.rs
- circuits/src/zk_gadgets/select.rs
- util/src/matching_engine.rs
This PR refactors the `VALID MATCH MPC` circuit over the `mpc-plonk` system. This method proves validity of a match that results from an MPC or the internal matching engine.
Note that we intend to combine this circuit with `VALID SETTLE`, this will come in a follow up PR.
Also deferred to a follow up are more extensive unit tests -- this circuit is tested heavily in integration tests, but given the new mocking interface for MPCs, it makes sense to test them in unit as well.
- Tested prove/verify
> circuits: zk-circuits: valid-match-mpc: Refactor over `mpc-plonk`

- circuit-macros/src/circuit_type.rs
- circuit-macros/src/circuit_type/secret_share_types.rs
- circuit-types/src/traits.rs
- circuit-types/src/wallet.rs
- circuits/src/zk_circuits/valid_commitments.rs
- circuits/src/zk_circuits/valid_match_settle/mod.rs
- circuits/src/zk_circuits/valid_match_settle/multi_prover.rs
- circuits/src/zk_circuits/valid_match_settle/single_prover.rs
- circuits/src/zk_gadgets/comparators.rs
This PR merges the match and settle circuits into one. This is necessary to enable proof linking across all proofs. This PR also refactors the circuits over the `mpc-plonk` system.
This circuit now validates the execution of the matching engine as well as the execution of the settlement logic into the two parties' wallets.
Along the way it was necessary to build a multiprover `==` gadget, this exposes an interface to test equality on only public values -- i.e. those that have been opened. We use this only on statement types (indices) so this is safe.
> circuits: zk-circuits: valid-match-settle: Merge match and settle circuits

- circuit-types/src/lib.rs
- circuits/src/mpc_circuits/match.rs
- circuits/src/mpc_circuits/mod.rs
- circuits/src/mpc_circuits/settle.rs
- circuits/src/mpc_gadgets/comparators.rs
- circuits/src/zk_circuits/valid_match_settle/mod.rs
This PR adds the `settle` circuit to the `mpc-circuits` module. This circuit settles a shared match object into two wallets after the `match` circuit runs. This completes the process of constructing a shared witness and statement for `VALID MATCH SETTLE`.
Note that the settlement indices here are public to provide efficiency. These indices are already made public in the statement type of `VALID COMMITMENTS` so they will simply be pulled from that proof's statement at match time.
> circuits: mpc-ciruits: settle: Add settlement ciruit

- Cargo.lock
- arbitrum-client/Cargo.toml
- arbitrum-client/integration/constants.rs
- arbitrum-client/integration/helpers.rs
- arbitrum-client/integration/main.rs
This PR sets up scaffolding for integration tests for the Arbitrum client. This defines CLI arguments for running integration tests, the subsequent integration test arguments, and the invocation of the `integration_test_main` macro. No tests are defined yet, and the docker-compose stack from the Starknet client tests is not yet replicated.
Next steps will be to set up the tests themselves, at first running them against a separately-instantiated devnet, with a docker-compose stack to follow.
> arbitrum-client: add integration test setup

- Cargo.lock
- arbitrum-client/Cargo.toml
- arbitrum-client/integration/helpers.rs
- arbitrum-client/integration/main.rs
- arbitrum-client/src/client/contract_interaction.rs
- arbitrum-client/src/helpers.rs
- arbitrum-client/src/types.rs
- circuits/src/zk_circuits/mod.rs
- circuits/src/zk_gadgets/mod.rs
This PR introduces the setup of pre-allocated state in the Arbitrum client integration tests, including the necessary helpers to implement this.
It's worth noting that the client in the integration tests will assume that the contracts have had the appropriate verification keys set prior to the test beginning. This will be implemented as another script in the contracts repo which will be invoked within the docker compose stack for the devnet.
At the moment, we use the actual circuitry (on the smaller `(2, 2, 1)` parameter set) in the integration tests for ease of use with existing relayer utilities. If this proves burdensome in terms of proving time in integration tests, or failing proofs (which is out of scope for the client integration tests), I will write dummy circuits that expect the …
> arbitrum-client: integration: setup pre-allocated state

- Cargo.lock
- common/src/types/exchange.rs
- config/Cargo.toml
- config/src/lib.rs
- core/src/main.rs
- workers/price-reporter/src/reporter.rs
- workers/price-reporter/src/worker.rs
This PR adds a `--disabled-exchanges` flag which allows the CLI to specify which exchanges to disable. This replaces the ad-hoc `--disable-binance` flag.
- Disabled binance and uniswap using the flag, verified that price reports excluded them
> config: Add `disabled-exchanges` flag

- Cargo.lock
- arbitrum-client/Cargo.toml
- arbitrum-client/integration/helpers.rs
- arbitrum-client/integration/main.rs
- arbitrum-client/src/client/contract_interaction.rs
- arbitrum-client/src/client/event_indexing.rs
- arbitrum-client/src/errors.rs
- arbitrum-client/src/helpers.rs
- arbitrum-client/src/types.rs
- circuit-types/src/keychain.rs
- circuit-types/src/lib.rs
- circuit-types/src/transfers.rs
- circuits/src/zk_circuits/mod.rs
- common/src/types.rs
This PR changes the interfaces of the Arbitrum client's contract interaction methods to accept the proof bundle types created by the relayer. It also adds the necessary conversion logic between relayer and contract statement types to support this, which notably changes the structure of ECDSA public signing keys to store both the `x` and `y` affine coordinates of the (in our case, `secp256k1`) curve point representing the public key.
Existing integration tests pass.
> arbitrum-client: use proof bundle types in contract interaction methods

- Cargo.lock
- circuit-types/src/match.rs
- circuit-types/src/order.rs
- circuits/integration/mpc_circuits/match_settle.rs
- circuits/src/lib.rs
- circuits/src/mpc_circuits/settle.rs
- circuits/src/zk_circuits/valid_commitments.rs
- circuits/src/zk_circuits/valid_match_settle/mod.rs
- circuits/src/zk_circuits/valid_match_settle/multi_prover.rs
- circuits/src/zk_circuits/valid_match_settle/single_prover.rs
- util/Cargo.toml
- util/src/lib.rs
- util/src/matching_engine.rs
This PR refactors the settlement logic to live in the `util` crate, matching the paradigm established with the matching engine. This allows all downstream crates to use the same settlement logic.
> util: matching-engine: Centralize settlement logic into util crate

- Cargo.lock
- common/src/types/wallet.rs
- task-driver/Cargo.toml
- task-driver/src/create_new_wallet.rs
- task-driver/src/driver.rs
- task-driver/src/helpers.rs
- task-driver/src/lib.rs
- workers/network-manager/Cargo.toml
- workers/network-manager/src/composed_protocol.rs
- workers/network-manager/src/lib.rs
- workers/network-manager/src/manager/control_directives.rs
- workers/network-manager/src/worker.rs
This PR refactors:
- A small bit of the `network-manager` to work with the new `mpc-plonk` system
- The `create-new-wallet` task in the `task-driver` to work with the new `mpc-plonk` system and the `arbitrum-client`
> network-manager, task-driver: create-new-wallet Refactor over `mpc-plonk`

- Cargo.lock
- arbitrum-client/Cargo.toml
- arbitrum-client/integration/constants.rs
- arbitrum-client/integration/main.rs
- arbitrum-client/src/client/contract_interaction.rs
- arbitrum-client/src/client/event_indexing.rs
- arbitrum-client/src/client/mod.rs
- arbitrum-client/src/errors.rs
This PR removes the `merkle_event_source` field from the Arbitrum client now that the delegatecall implementation is fixed contract-side. Additionally, we add logging of the transaction hash for successful transactions.
Event indexing integration tests pass.
> arbitrum-client: remove merkle event source field & add logging

- Cargo.lock
- common/src/types/network_order.rs
- external-api/src/types.rs
- state/src/orderbook.rs
- statev2/proto/Cargo.toml
- statev2/proto/src/lib.rs
This PR persists timestamps of NetworkOrder objects so that when the global orderbook is fetched, timestamps accurately represent when the order was received.
> workers: Persist timestamps in global orderbook

- Cargo.lock
- arbitrum-client/src/abi.rs
- arbitrum-client/src/client/mod.rs
- arbitrum-client/src/constants.rs
- arbitrum-client/src/errors.rs
- arbitrum-client/src/lib.rs
- common/src/types/wallet.rs
- config/src/lib.rs
- core/src/main.rs
- external-api/src/types.rs
- renegade-crypto/Cargo.toml
- renegade-crypto/src/fields.rs
- state/src/state.rs
- state/src/wallet.rs
- statev2/proto/src/lib.rs
- task-driver/src/lookup_wallet.rs
- workers/chain-events/Cargo.toml
- workers/chain-events/src/error.rs
- workers/chain-events/src/lib.rs
- workers/chain-events/src/listener.rs
- workers/chain-events/src/worker.rs
This PR refactors the `chain-events` worker over the new arbitrum client. This worker has two primary tasks:
- MPC shootdowns: when a nullifier is seen on chain, all in-flight matches on that nullifier should be cancelled.
- Merkle proof updates: as roots in Merkle proofs stale, they leak information about _when_ an obfuscated wallet was last update (or at least a bound on this value), we need to refresh Merkle proofs every so often to avoid this.
This PR does not handle the Merkle refresh logic yet. This will be in a follow up.
> workers: chain-events: Refactor implementation over new arbitrum client

- Cargo.lock
- task-driver/src/driver.rs
- task-driver/src/lib.rs
- task-driver/src/update_merkle_proof.rs
- task-driver/src/update_wallet.rs
- workers/chain-events/Cargo.toml
- workers/chain-events/src/error.rs
- workers/chain-events/src/listener.rs
This PR adds a task `update-merkle-proofs` to update the Merkle proof of a given wallet to reference the latest known root. This task is used by the event listener to update stale proofs for privacy.
> task-driver: update-merkle-proof: Define task to update wallet merkle proofs

- external-api/src/types.rs
This PR adds the `update_locked` field to the Wallet type so that the field is present when the type conversion happens within `GetWalletHandler`. For use in the frontend to disable functionality when the wallet is undergoing any wallet update operations.
> external-api: Add update_locked field to Wallet type to expose field to API

- docker/contracts/deploy_contracts.sh
This PR adds a step to the `deploy_contracts.sh` script to optionally deploy a dummy ERC-20 contract to the devnet if the `DEPLOY_DUMMY_ERC20` env var is set, using the new option in the scripts CLI
**Testing:**
Ad-hoc testing of the arbitrum client integration testing stack with the environment variable set shows the erc20 contract being deployed.
> docker: contracts: optionally deploy dummy erc20

- arbitrum-client/docker-compose.yml
This PR bumps the healthcheck timeout for the contract deployment docker compose service to ensure that the integration tests can run on an initial clone of the repo (of course, one must clone with `--recurse-submodules`). This is necessary because in an initial clone, the nitro stack must also pull and build all of its images, which, although concurrent with the building of our own integration stack, takes long enough that the healthcheck fails.
> arbitrum-client: give contract deployment service generous timeout

- Cargo.lock
- arbitrum-client/integration/constants.rs
- arbitrum-client/integration/helpers.rs
- arbitrum-client/integration/main.rs
- arbitrum-client/src/abi.rs
- arbitrum-client/src/client/mod.rs
- arbitrum-client/src/types.rs
- circuit-types/src/order.rs
- config/src/lib.rs
- task-driver/Cargo.toml
- task-driver/integration/helpers.rs
- task-driver/integration/main.rs
- task-driver/integration/tests/create_new_wallet.rs
- task-driver/integration/tests/lookup_wallet.rs
- task-driver/integration/tests/mod.rs
- task-driver/integration/tests/settle_match.rs
- task-driver/integration/tests/update_wallet.rs
- test-helpers/src/arbitrum.rs
- test-helpers/src/lib.rs
- util/src/arbitrum.rs
This PR refactors the `task-driver` integration tests over the `mpc-plonk` and `arbitrum-client` implementations. These tests are not passing, waiting for our integration testing stack to stabilize.
Some helpers were generalized out of `arbitrum-client/integration` into `utils`
> task-driver: integration: Refactor tests over `mpc-plonk` + `arbitrum-client`

- renegade-crypto/Cargo.toml
This PR makes the `ethers-core` dependency in `renegade-crypto` be optionally included only when the `non-wasm` feature is set
> renegade-crypto: shield ethers-core dep behind non-wasm flag

- Cargo.lock
- circuit-types/src/keychain.rs
- external-api/Cargo.toml
- external-api/src/bus_message.rs
- external-api/src/http/order_book.rs
- external-api/src/http/wallet.rs
- external-api/src/lib.rs
- external-api/src/types.rs
- task-driver/integration/helpers.rs
- task-driver/integration/tests/lookup_wallet.rs
- task-driver/integration/tests/settle_match.rs
- task-driver/integration/tests/update_wallet.rs
- task-driver/src/create_new_wallet.rs
- util/Cargo.toml
- util/src/hex.rs
- util/src/lib.rs
- workers/api-server/src/http/order_book.rs
- workers/api-server/src/http/wallet.rs
This PR changes all key types to be serialized and deserialized to/from hex strings at the API layer. 
- Tested with `POST /v0/wallet/`
> external-api: (De)serialize all keys from/to hex strings

- arbitrum-client/integration/constants.rs
- arbitrum-client/integration/main.rs
- arbitrum-client/src/abi.rs
- arbitrum-client/src/client/contract_interaction.rs
- arbitrum-client/src/client/event_indexing.rs
- arbitrum-client/src/helpers.rs
- arbitrum-client/src/types.rs
- docker/contracts/deploy_contracts.sh
This PR updates the Arbitrum client to adapt to the new contract interface, in which, namely, there are no longer any setter methods, and events/external methods expect/return `uint256` types where `Scalar`s are used, as opposed to `bytes`. This also makes event parsing more straightforward, in that we no longer need to generate a hash of the serialized `Scalar` to listen for events containing it.
`arbitrum-client` integration tests pass.
> arbitrum-client, docker: adapt to new contract interface

- docker/contracts/deploy_contracts.sh
This PR removes the `--test` flag from the invocation of the `deploy-proxy` script, as it is no longer expected.
> docker: contracts: deploy-proxy script doesn't need test flag

- docker/contracts/Dockerfile
- docker/contracts/deploy_contracts.sh
This PR amends the `deploy_contracts` script to also deploy the verification keys contract if the `$NO_VERIFY` flag is unset. It does this in a manner that ensures that dependencies cached from the image build are used for all the relevant contracts (now that we have different compilation settings for the verifier contract).
A dangling TODO here is to ensure that the verification keys in the contracts repo, which are written to the deployed contract, are the same (or at least use the same SRS) as those used in any relayer-side integration tests that test smart contract verification. Since we don't have any such integration testing stacks completely ported over to the Arbitrum client yet, this is left for a future PR (it requires a bit of thought around SRS generation).
The existing …
> docker: deploy vkeys contract if NO_VERIFY is unset

- arbitrum-client/integration/contract_interaction.rs
- arbitrum-client/integration/event_indexing.rs
- arbitrum-client/integration/helpers.rs
- arbitrum-client/src/client/contract_interaction.rs
- arbitrum-client/src/client/mod.rs
This PR makes a couple changes to how preallocated state is managed for the Arbitrum client integration tests:
1. Merkle state is now cleared at the beginning of the tests which need a blank slate, removing the need for all tests to clear at the end, and ensuring that a blank slate is used even if previous tests fail before clearing
2. We reset the deploy block of the client for the tests which need a blank slate. This fixes a testing bug where, if more than 3 previous tests were run which didn't reset the Merkle state, the authentication path in the `test_find_merkle_path` test would be incorrect (as the sibling of the 3rd commitment would no longer be the empty leaf value)
Arbitrum client integration tests pass, even after running more than 3 non-clearing tests in a row and running …
> arbitrum-client: reset preallocated state properly at test start

- Cargo.lock
- circuits/benches/full_match.rs
- circuits/src/mpc_gadgets/bits.rs
- circuits/src/mpc_gadgets/comparators.rs
- circuits/src/mpc_gadgets/modulo.rs
- task-driver/integration/helpers.rs
- test-helpers/src/mpc_network.rs
This PR refactors a few gadgets in the `match-settle` critical path to use fewer gates -- thereby lightening the load on the executor. As well, we remove the `bit_xor` and `bit_xor_public` methods in favor of the optimized methods in `ark-mpc`.
> circuits: mpc-gadgets: Optimize gate allocation in match-settle

- .gitignore
- Cargo.lock
- external-api/src/http/wallet.rs
- task-driver/src/driver.rs
- workers/api-server/Cargo.toml
- workers/api-server/src/auth.rs
- workers/api-server/src/http/wallet.rs
This PR changes the signature verification scheme to expect signatures encoded in base 64. This is how the relayer functioned before the refactor and what is expected in both the frontend and the dev tool proxy.
- Tested against the internal proxy's signatures
> api-server: auth: Expect signatures as b64 encoded bytes

- Cargo.lock
- Cargo.toml
- circuit-types/src/keychain.rs
- circuit-types/src/order.rs
- circuit-types/src/traits.rs
- circuits/src/zk_circuits/mod.rs
- circuits/src/zk_circuits/valid_commitments.rs
- circuits/src/zk_circuits/valid_match_settle/mod.rs
- circuits/src/zk_circuits/valid_reblind.rs
- circuits/src/zk_circuits/valid_wallet_create.rs
- circuits/src/zk_circuits/valid_wallet_update.rs
- common/src/types/wallet.rs
- state/src/state.rs
- statev2/state/src/replication/log_store.rs
- task-driver/integration/tests/update_wallet.rs
- task-driver/src/lookup_wallet.rs
- task-driver/src/settle_match.rs
- workers/api-server/src/http/wallet.rs
- workers/gossip-server/src/heartbeat.rs
- workers/gossip-server/src/orderbook.rs
- workers/handshake-manager/src/state.rs
- workers/price-reporter/src/exchange/coinbase.rs
- workers/proof-manager/src/mock.rs
This PR changes the behavior of the mock proof manager to check constraint satisfaction of the witness and statement. This allows us to check the validity of witness, statement pairs generated by the tasks.
As a result, this PR fixes a few bugs in the task driver integration tests.
- Integration tests mostly pass, some error for nitro specific reasons which will be fixed when time permits.
> proof-manager: mock: Check constraint satisfaction in mock

- circuit-macros/src/circuit_type.rs
- circuit-macros/src/circuit_type/singleprover_circuit_types.rs
- circuit-types/src/macro_tests.rs
- circuit-types/src/order.rs
- circuit-types/src/traits.rs
- circuit-types/src/transfers.rs
This PR adds a `NUM_SCALARS` constant to the `BaseType` trait. This allows us to determine the number of scalars needed to serialize a circuit type. This will be used for determining layouts in the proof linking implementation.
- Tested the `NUM_SCALARS` derivation
> circuit-types: traits: Add `NUM_SCALARS` constant to `BaseType` trait

- Cargo.lock
- circuit-types/src/traits.rs
- circuits/src/zk_circuits/mod.rs
- circuits/src/zk_circuits/valid_commitments.rs
- circuits/src/zk_circuits/valid_match_settle/mod.rs
- circuits/src/zk_circuits/valid_reblind.rs
This PR takes the first step toward implementing proof linking: defining layout relationships between circuits. This is done by introducing two methods to the `SingleProverCircuit` trait:
1. `proof_linking_groups`: This method allows implementing circuits to define the proof linking groups they allocate, and reference the layouts of other circuits to specify individual group layouts. `VALID REBLIND` and `VALID MATCH SETTLE` both override the default implementation to reference `VALID COMMITMENTS`'s layout.
2. `get_circuit_layout`: Generates a circuits layout by using dummy wire values with the correct circuit topology. The circuit layouts are effectively static, so we cache them in a global `CIRCUIT_LAYOUT_CACHE` for use after they are first generated.
- Add logic to specify _which_ …
> circuits: zk-circuits: Define proof linking relationships between circuits

- Cargo.lock
- circuit-macros/src/circuit_type.rs
- circuit-macros/src/circuit_type/proof_linking.rs
- circuit-macros/src/circuit_type/singleprover_circuit_types.rs
- circuit-types/src/macro_tests.rs
This PR implements the single-prover variant of the macro derived link group witness allocation. This works by overriding the `create_witness` method on the `CircuitBaseType` impl for types that need proof linking. The macro constructs a list of linking groups needed for each witness element and constructs a `create_witness` implementation that calls `cs.create_variable_with_link_groups(var, &groups)` for each witness element.
The syntax for specifying a witness element with link groups is as follows:
```rust
#[circuit-type(singleprover)]
struct TestWitness {
pub a: u64, // no link needed
#[link_groups = "group1, group2, ..."]
pub b: bool
}
```
For which the macro will expand to `cs.create_variable_with_link_groups(b, &["group1".to_string(), "group2".to_string()])`
- Implementation for …
> circuit-macros: proof-linking: Implement linking witness allocation

- Cargo.lock
- circuit-macros/src/circuit_type/mpc_types.rs
- circuit-macros/src/circuit_type/multiprover_circuit_types.rs
- circuit-macros/src/circuit_type/proof_linking.rs
- circuit-types/src/macro_tests.rs
This PR extends #319 to include support for multiprover circuits. This method by which this is done is essentially the same, though note that we need both the mpc and base type in context to infer proof links.
- Apply proof linking macro to the application level circuit types
- Macros unit tests pass
- Unit tests generally fail because the macros have not yet been applied to circuit types.
> circuit-macros: proof-linking: Define multipirover group witness allocation

- circuit-macros/src/circuit_type/proof_linking.rs
- circuit-types/src/traits.rs
- circuits/src/zk_circuits/mod.rs
- circuits/src/zk_circuits/valid_commitments.rs
- circuits/src/zk_circuits/valid_match_settle/mod.rs
- circuits/src/zk_circuits/valid_reblind.rs
This PR annotates the witness types of `VALID REBLIND`, `VALID COMMITMENTS`, and `VALID MATCH SETTLE` with the proof-linking `link_groups` attribute. This allocates the witness types into their appropriate link groups.
- Add helpers to prove and verify the linking relation between proofs
- Call these helpers in the appropriate locations throughout the relayer
- All unit tests now pass, more to be added when the proof linking helpers are defined
> circuits: zk-circuits: Add proof-linking to witness types

- arbitrum-client/src/conversion.rs
- circuit-types/src/match.rs
- circuit-types/src/traits.rs
- circuits/integration/mpc_circuits/match_settle.rs
- circuits/src/lib.rs
- circuits/src/mpc_circuits/settle.rs
- circuits/src/zk_circuits/valid_commitments.rs
- circuits/src/zk_circuits/valid_match_settle/mod.rs
- task-driver/src/helpers.rs
- util/src/matching_engine.rs
This PR changes the type from `u64` -> `usize` for settlement indices in circuit types. This makes out-of-circuit indexing for e.g. witness generation much easier. Concretely this involves:
- Define a base type impl for `usize`
- Replace all instances of u64 with usize
The one exception is in `arbitrum-client`. I keep the types `u64` here to ensure correct serialization independent of machine architecture. @akirillo Please let me know if this is unnecessary.
> circuit-types: Impl for `usize` and use in `OrderSettlementIndices`

- circuits/src/lib.rs
- circuits/src/zk_gadgets/fixed_point.rs
This PR fixes two edge cases on `FixedPointGadget::constrain_eq_integer_ignore_fraction`:
1. The case in which the integer and fixed point value are identically equal (not just modulo 1)
2. The case in which the difference between integer and fraction is exactly 1, or slightly larger
- Tested the edge cases discussed above
> circuits: fixed-point: Fix `constrain_eq_integer_ignore_fraction`

- task-driver/src/settle_match_internal.rs
This PR fixes a bug with the `settle-internal-match` task wherein the shares used for the `VALID MATCH SETTLE` witness were the reblinded shares _not_ the augmented shares that result from `VALID COMMITMENTS`. The post-settlement shares were correct, causing `VALID MATCH SETTLE` to fail proving through the internal flow.
- @sehyunc will test via the frontend flow
> task-driver: match-internal: Use correct augmented shares in witness

- arbitrum-client/integration/contract_interaction.rs
- arbitrum-client/integration/helpers.rs
- arbitrum-client/src/client/contract_interaction.rs
- arbitrum-client/src/conversion.rs
- common/src/types/proof_bundles.rs
- task-driver/integration/helpers.rs
- task-driver/integration/tests/settle_match.rs
- task-driver/src/create_new_wallet.rs
- task-driver/src/helpers.rs
- task-driver/src/settle_match.rs
- task-driver/src/settle_match_internal.rs
- task-driver/src/update_wallet.rs
- workers/handshake-manager/src/manager/match.rs
- workers/proof-manager/src/mock.rs
- workers/proof-manager/src/proof_manager.rs
This PR changes the proof bundles to use `Arc` instead of `Box` to heap allocate. These bundles are effectively read only once they are created and `Arc` provides a much more convenient (thread safe) and efficient (atomic incr) clone method. I also changed the location in which these bundles were consumed to allow a borrow to the proof bundle and only clone necessary fields.
> common: type: proof-bundles: Use `Arc` to heap allocate instead of `Box`

- task-driver/integration/tests/settle_match.rs
- task-driver/src/create_new_wallet.rs
- task-driver/src/helpers.rs
- task-driver/src/settle_match_internal.rs
- task-driver/src/update_wallet.rs
This PR takes the steps to prove the `VALID REBLIND` <-> `VALID COMMITMENTS` link in the task driver's helper to update a wallet's validity proofs.
- Unit tests pass crate wide, next step is to validate this in gossip
> task-driver: helpers: Prove reblind <-> commitments link

- .gitmodules
- docker/sequencer/Dockerfile
- docker/sequencer/deploy_contracts.sh
This PR introduces a minimal `sequencer` Docker image that has our contracts predeployed to it during the build stage.
This sequencer is configured to run without requiring `geth` or `redis` services colocated in the docker-compose stack.
This also requires no volumes. The plan wrt the `deployments.json` file is to copy it directly from the final build stage of the `sequencer` image into the `relayer` image.
Currently, this uses ~the same contract deployment script as we used to, I'll make the changes to e.g. remove `NO_VERIFY` later.
Additionally, this PR does not yet incorporate these changes into the `arbitrum-client` integration testing stack, that is saved for the next PR.
**Testing:**
I tested ad-hoc, using the `test_nullifier_set` method in the `renegade-contracts` repo, that the …
> docker: sequencer: minimal image w/ predeployed contracts

- circuits/src/zk_circuits/proof_linking.rs
- common/src/types/proof_bundles.rs
- gossip-api/src/gossip.rs
- workers/gossip-server/src/errors.rs
- workers/gossip-server/src/orderbook.rs
- workers/network-manager/src/error.rs
- workers/network-manager/src/manager/pubsub.rs
This PR adds proof link verification to the order book gossip flow. That is, after the recipient of a gossip validity bundle verifies the two R1CS proofs (`VALID COMMITMENTS` and `VALID REBLIND`), it will verify the proof-link between them.
- Spun up two nodes, created an order on one, ensured that the other received the proof and correctly validated the link bundle.
> gossip: orderbook: Validate reblind <-> commitments proof link on gossiped orders

- common/src/types/proof_bundles.rs
- task-driver/integration/tests/settle_match.rs
- task-driver/src/settle_match.rs
- task-driver/src/settle_match_internal.rs
- workers/handshake-manager/src/manager.rs
- workers/handshake-manager/src/manager/match.rs
This PR generates `VALID COMMITMENTS` <-> `VALID MATCH SETTLE` proof links for both parties in a match during the match MPC. These are then structured into a `MatchBundle` before being sent to the `TaskDriver` for settlement.
- Internal matching engine linking
- Change the arbitrum client to accept proof links
- Test this flow with the new integration testing stack
> handshake-manager: match: Generate proof links in collaborative match

- Cargo.lock
- circuit-types/Cargo.toml
- circuit-types/src/lib.rs
- circuit-types/src/srs.rs
- renegade-crypto/src/fields.rs
This PR sets up the system-wide SRS by pulling directly from the BN128 powers of tau `.ptau` file from [the iden3 repo](https://github.com/iden3/snarkjs?tab=readme-ov-file#7-prepare-phase-2).
This PR also adds parsing logic for the `.ptau` file into the `UnivariateUniversealParams` struct used in `mpc-jellyfish`. This parsing logic is borrowed heavily from [`ppot-rs`](https://docs.rs/crate/ppot-rs/0.1.1) but with modifications to include the SRS in the compiled binary (as opposed to an external file) and lazily parse it.
- More thorough parsing tests -- i.e. test the structure of the parsed SRS.
- Remove the `TESTING_SRS` defined in `lib.rs`
- Tested parsing
> circuit-types: srs: Parse SRS from ptau file

- arbitrum-client/docker-compose.yml
- arbitrum-client/src/abi.rs
- arbitrum-client/src/conversion.rs
- docker/sequencer/Dockerfile
- docker/sequencer/deploy_contracts.sh
- task-driver/Dockerfile
- task-driver/docker-compose.yml
- task-driver/integration/helpers.rs
- task-driver/integration/main.rs
- task-driver/integration/tests/settle_match.rs
- task-driver/integration/tests/update_wallet.rs
- test-helpers/src/arbitrum.rs
- util/src/arbitrum.rs
This PR updates the `arbitrum-client` and `task-driver` integration testing stacks to:
1. Use the new Arbitrum sequencer image
2. Make use of the pre-deployed, pre-approved dummy ERC20s in the sequencer image
In the case of the `task-driver` integration testing stack, this meant being able to remove a lot of WETH contract interaction code.
**Testing:**
All of the `arbitrum-client` integration tests other than `process_match_settle` pass, as expected.
All of the `task-driver` integration tests other than `test_update_wallet__place_order`, `test_settle_mpc_match`, `test_settle_internal_match`, and `test_lookup_wallet__invalid_wallet` pass (when using the `NO_VERIFY` flag). However these tests fail for reasons seemingly unrelated to the usage of predeployed ERC20s (as opposed to WETH), those …
> arbitrum-client, task-driver: make use of predeployed erc20s in sequencer

- circuit-types/src/lib.rs
- circuit-types/src/srs.rs
- circuit-types/src/traits.rs
This PR replaces the `TESTING_SRS` of the `circuit-types` library with the SRS parsed by #336. This PR also adds a cache for circuit proving and verifying keys, much like we do for circuit layouts.
Tests pass using this SRS to prove.
- Added tests for SRS composition
- Added tests for shared caching
- Ran relayers to gossip proofs and ensure the proofs are verified correctly
> circuit-types: traits: Use parsed SRS in circuit key generation

- Cargo.lock
- arbitrum-client/integration/contract_interaction.rs
- arbitrum-client/src/abi.rs
- arbitrum-client/src/client/contract_interaction.rs
- arbitrum-client/src/client/event_indexing.rs
- arbitrum-client/src/conversion.rs
- arbitrum-client/src/helpers.rs
- common/src/types/proof_bundles.rs
- task-driver/src/settle_match.rs
- task-driver/src/settle_match_internal.rs
This PR refactors the `arbitrum-client` interface to align with the proof-linking interface changes in the contracts. Specifically the interface changes to [`processMatchSettle`](https://github.com/renegade-fi/renegade-contracts/blob/main/contracts-stylus/src/contracts/darkpool.rs#L355-L363).
- Fix `task-driver` integration tests
- `arbitrum-client` integration tests pass against `renegade-contracts:main`
> arbitrum-client: Add proof-linking interface changes

- circuits/src/lib.rs
- circuits/src/mpc_gadgets/modulo.rs
This PR fixes a flakey test in the `mod2m` gadget. For now the fix is to simply test on smaller values that will not wrap around the field modulus. Long term we need to define a maximum value for signed integers in the MPC gadgets. This will be done when the beaver source is built.
> circuits: mpc-gadgets: modulo: Fix `mod2m` gadget tests

- common/src/types/wallet.rs
- task-driver/integration/helpers.rs
- task-driver/integration/tests/settle_match.rs
- task-driver/integration/tests/update_wallet.rs
- task-driver/src/helpers.rs
This PR fixes the `task-driver` integration tests after the new integration testing stack was introduced in #337. The fixes are small and mostly relate to the setup code in how we allocate initial states into the darkpool.
- All `task-driver` integration tests pass
> task-driver: integration: Fix integration tests

- Cargo.lock
- statev2/state/src/replication/raft_node.rs
This PR changes the mock cluster in our raft node to remove nodes from the `handles` field when calling `remove_node`. This means that the `assert_no_crashes` will not check removed nodes (which may have crashed by being removed).
> statev2: replication: raft-node: Do not check removed nodes for failure

- task-driver/src/settle_match_internal.rs
This PR fixes a bug where the incorrect party ID was being used during the proof linking step of the settle-internal-match task. Tested using the frontend to work.
> task-driver: use correct party id during proof linking

- circuit-types/src/keychain.rs
- util/src/hex.rs
Adds a method to convert the PublicSigningKey to bytes in uncompressed form, for correct serialization to a hex string.
> circuit-types, util: update public key serialization to use uncompressed bytes

- Cargo.lock
- statev2/Cargo.toml
- statev2/src/interface/mod.rs
- statev2/src/interface/notifications.rs
- statev2/src/interface/wallet_index.rs
- statev2/src/lib.rs
- statev2/src/replication/error.rs
- statev2/src/replication/raft_node.rs
- util/src/errors.rs
- util/src/lib.rs
This PR adds a primitive for a caller to await a proposal's completion, either with an error or successfully. This is done via a oneshot channel that the consensus layer maintains. Once a proposal is either accepted or rejected, the consensus layer responds on this channel.
This will be useful for example in the tasks, which cannot be considered complete until a raft entry is successfully appended representing the task's update.
- Modified the tests to await response via this primitive
> statev2: interface: notifications: Add method to wait for proposal

- statev2/src/applicator/order_book.rs
- statev2/src/applicator/peer_index.rs
- statev2/src/applicator/wallet_index.rs
- statev2/src/interface/wallet_index.rs
- statev2/src/replication/log_store.rs
- statev2/src/storage/cursor.rs
- statev2/src/storage/db.rs
- statev2/src/storage/mod.rs
- statev2/src/storage/tx/mod.rs
This PR introduces the `StateTxn` type to the DB. On top of this we will build high level state access primitives that can be re-used between the applicator and the state interface. For now, all callsites still use the raw txn interface. This will be changed once the `StateTxn` implementation is built out.
> statev2: storage: tx: Add tx module and define high level tx

- statev2/src/replication/error.rs
- statev2/src/replication/log_store.rs
- statev2/src/storage/db.rs
- statev2/src/storage/error.rs
- statev2/src/storage/tx/mod.rs
- statev2/src/storage/tx/raft_log.rs
This PR introduces high-level transaction methods for accessing and modifying the raft log, and replaces the manual implementations at callsites.
> statev2: storage: tx: Add raft log access methods

- common/src/types/wallet.rs
- statev2/src/applicator/mod.rs
- statev2/src/applicator/order_book.rs
- statev2/src/applicator/wallet_index.rs
- statev2/src/interface/error.rs
- statev2/src/interface/wallet_index.rs
- statev2/src/lib.rs
- statev2/src/replication/raft_node.rs
- statev2/src/storage/cursor.rs
- statev2/src/storage/tx/mod.rs
- statev2/src/storage/tx/wallet_index.rs
This PR adds getters and setters for the wallet index in the `StateTxn` abstraction. These are borrowed from the original state definition that `statev2` refactors. Some setters are left out involving replicas -- raft takes care of this automatically.
> statev2: storage: tx: Add `wallet_index` access methods

- common/src/types/gossip.rs
- state/src/peers.rs
- state/src/state.rs
- statev2/src/applicator/peer_index.rs
- statev2/src/storage/tx/mod.rs
- statev2/src/storage/tx/peer_index.rs
This PR adds access methods for the `peer_index` to the `StateTxn` interface. This is the last set of access methods we need to add.
> statev2: storage: tx: Add `peer_index` access methods

- docker/sequencer/Dockerfile
- statev2/Cargo.toml
- statev2/src/interface/mod.rs
- statev2/src/interface/notifications.rs
- statev2/src/interface/order_book.rs
- statev2/src/lib.rs
- statev2/src/replication/network.rs
- statev2/src/replication/raft_node.rs
- task-driver/Dockerfile
- task-driver/integration/helpers.rs
- task-driver/integration/main.rs
- task-driver/integration/tests/mod.rs
- task-driver/src/create_new_wallet.rs
- task-driver/src/driver.rs
- task-driver/src/lib.rs
- task-driver/src/lookup_wallet.rs
This PR updates the `new-wallet` and `lookup-wallet` tasks to use the new raft-based state refactor. This includes the integration tests for these two tasks.
- Integration tests pass for refactored tests
- Other tests fail and will be repaired throughout the rest of the refactor
> statev2, task-driver: Update `new-wallet` and `lookup-wallet` tasks

- circuit-types/src/balance.rs
- common/src/types/proof_bundles.rs
- common/src/types/wallet.rs
- statev2/src/interface/wallet_index.rs
- task-driver/integration/tests/mod.rs
- task-driver/integration/tests/update_wallet.rs
- task-driver/src/driver.rs
- task-driver/src/lib.rs
- task-driver/src/lookup_wallet.rs
- task-driver/src/update_wallet.rs
This PR refactors the `update-wallet` task to use the `statev2` implementation. This includes the `update-wallet` integration tests and bugs fixed by getting these test to pass.
I also changed the way in which we add balances and order to a wallet, overriding old (zero'd) values in the case that a wallet is full.
- Integration tests for update-wallet pass
> task-driver: update-wallet: Refactor task to use `statev2`

- task-driver/src/driver.rs
- task-driver/src/lib.rs
- task-driver/src/update_merkle_proof.rs
This PR refactors the `update-merkle-proof` task over the new raft-base statev2 implementation. This is the last task to refactor. Further PRs will focus on refactoring the workers that access these tasks.
- `task-driver` integration tests pass
> task-driver: update-merkle-proof: Refactor task over statev2

- common/src/keyed_list.rs
- common/src/lib.rs
- common/src/ordered_map.rs
- common/src/types/wallet.rs
- task-driver/integration/tests/settle_match.rs
- task-driver/src/driver.rs
- task-driver/src/lib.rs
- task-driver/src/settle_match_internal.rs
- task-driver/src/update_merkle_proof.rs
This PR fixes the way in which we track orders and balances. Specifically we now use the `OrderedMap` type, which is a vector with a map like interface over it for convenience. The mapping methods are implemented via `find` which is efficient for the small vectors we use this data structure for.
- Integration tests that were previously failing with settlement now pass
> common: types: wallet: Track wallet state in correct order

- Cargo.lock
- statev2/src/interface/node_metadata.rs
- statev2/src/interface/order_book.rs
- statev2/src/interface/peer_index.rs
- statev2/src/interface/wallet_index.rs
- workers/chain-events/Cargo.toml
- workers/chain-events/src/error.rs
- workers/chain-events/src/listener.rs
This PR refactors the `chain-events` worker over the `statev2` crate
- Unit tests pass in affected crates
> workeres: chain-events: Refactor to use `statev2`

- .github/workflows/clippy.yml
- Cargo.lock
- statev2/src/applicator/mod.rs
- statev2/src/applicator/order_book.rs
- statev2/src/applicator/peer_index.rs
- statev2/src/applicator/wallet_index.rs
- statev2/src/interface/mod.rs
- statev2/src/interface/order_book.rs
- statev2/src/interface/wallet_index.rs
- statev2/src/lib.rs
- statev2/src/storage/tx/mod.rs
- statev2/src/storage/tx/order_book.rs
- util/src/errors.rs
- workers/handshake-manager/Cargo.toml
- workers/handshake-manager/src/error.rs
- workers/handshake-manager/src/manager.rs
- workers/handshake-manager/src/manager/internal_engine.rs
- workers/handshake-manager/src/manager/match.rs
- workers/handshake-manager/src/manager/price_agreement.rs
- workers/handshake-manager/src/state.rs
- workers/handshake-manager/src/worker.rs
This PR refactors the handshake manager over the `statev2` crate. This includes implementing the bespoke methods in the state interface that the handshake manager needs.
- Unit tests pass for `statev2`
- Tested new methods in `statev2`
- `handshake-manager` testing deferred until `core` is refactored
> workers: handshake-manager: Refactor over `statev2` implementation

- Cargo.lock
- core/Cargo.toml
- core/src/error.rs
- core/src/main.rs
- state/src/lib.rs
- statev2/Cargo.toml
- statev2/src/interface/peer_index.rs
- statev2/src/lib.rs
- statev2/src/replication/network.rs
- statev2/src/tui.rs
This PR refactors the `core` crate over the `statev2` interface. This also involves moving the TUI app definition from the `state` crate into the `statev2` crate.
- Unit tests in `statev2` pass
- Other testing deferred until refactor complete
> statev2, core: Refactor core crate over the `statev2` interface

- state/src/interface/peer_index.rs
- workers/gossip-server/src/errors.rs
- workers/gossip-server/src/lib.rs
- workers/gossip-server/src/orderbook.rs
- workers/gossip-server/src/peer_discovery/bootstrap.rs
- workers/gossip-server/src/peer_discovery/heartbeat.rs
- workers/gossip-server/src/peer_discovery/heartbeat_timer.rs
- workers/gossip-server/src/peer_discovery/mod.rs
- workers/gossip-server/src/server.rs
- workers/gossip-server/src/worker.rs
- workers/job-types/src/gossip_server.rs
- workers/network-manager/src/error.rs
- workers/network-manager/src/manager.rs
- workers/network-manager/src/manager/request_response.rs
This PR refactors the first half of the gossip server to use the new gossip API. This includes orderbook updates and bootstrapping. Heartbeat logic is left for a follow up.
The repo does not build and errors + lints are expected for the moment.
- Testing deferred until repo builds
> workers: gossip-server: Refactor to use the new gossip API

- common/src/lib.rs
- state/src/interface/node_metadata.rs
- state/src/interface/peer_index.rs
- state/src/interface/raft.rs
- state/src/lib.rs
- state/src/replication/error.rs
- state/src/replication/log_store.rs
- state/src/replication/network/traits.rs
- state/src/replication/raft_node.rs
This PR implements automatic peer removal in the state replication layer when the heartbeat sub-protocol determines a peer has failed.
In the standard case this is done through the normal consensus mechanism, wherein quorum is formed over a `StateTransition::RemoveRaftPeer` log entry. In the case that the cluster is of size two and one node dies, quorum cannot be established on such a log. Instead, we have to manually add a log entry to ensure that the raft may continue being available. This is a slight hack -- and certainly breaks raft semantics -- but allows us to be available in the case that only one node remains.
- Unit and ad-hoc tested node failure and removal from the raft. Specifically tested raft availability after this event by producing state updates.
> state: replication: Remove raft nodes when their analogous peer expires

- constants/src/lib.rs
This PR fixes the value of the block number that the darkpool contract is deployed to on testnet.
> constants: Update testnet block number

- common/src/types/token.rs
This PR fixes a small bug in fetching supported exchanges in that we previously checked the `EXCHANGE_TICKERS` map for `Exchange::UniswapV3` which is not present. Now we filter out uniswap
> common: token: Fix bug in querying uniswap supported tokens

- circuit-types/src/match.rs
- common/src/types/handshake.rs
- task-driver/src/create_new_wallet.rs
- task-driver/src/driver.rs
- task-driver/src/lib.rs
- task-driver/src/lookup_wallet.rs
- task-driver/src/settle_match.rs
- task-driver/src/settle_match_internal.rs
- task-driver/src/traits.rs
- task-driver/src/update_merkle_proof.rs
- task-driver/src/update_wallet.rs
This PR refactors the traits on the `task-driver`'s task definitions to build a task queue on top of. Specifically, each task now has:
- A `TaskState`: this type in particular realizes the notion of a commit point in each task. After the commit point has been crossed the task cannot be preempted by a match -- it has modified contract state.
- A `TaskError`: this type segments the error types returned by the task into retryable and fatal, allowing the driver to avoid repeating fallible steps
- A `TaskDescriptor`: this type minimally parameterizes the task and must be serializable. The consensus engine will write the descriptor to storage in the form of a task queue. When a task starts up the `task-driver` will inject the `TaskDescriptor` and a `TaskContext` into the task's constructor. The …
> task-driver: Refactor task traits to allow task queue impl

- bin/release.zsh
- docker/release/Dockerfile
This PR copies all of the requisite dependencies into the release Dockerfile such that the release image can properly build
> docker: release: get Docker image to build

- common/src/types.rs
- common/src/types/task_descriptors.rs
- state/src/lib.rs
- state/src/storage/tx/mod.rs
- state/src/storage/tx/task_queue.rs
- task-driver/src/create_new_wallet.rs
- task-driver/src/lookup_wallet.rs
- task-driver/src/settle_match.rs
- task-driver/src/settle_match_internal.rs
- task-driver/src/update_merkle_proof.rs
- task-driver/src/update_wallet.rs
This PR implements the storage access primitives for the task queue. This includes `append`, `pop`, and `change_state`. Further layers will build on this to change the state of tasks in the queue as the raft logs controlling the queue are committed.
> state: tx: task-queue: Add task queue access methods

- state/src/applicator/error.rs
- state/src/applicator/mod.rs
- state/src/applicator/task_queue.rs
- state/src/interface/mod.rs
- state/src/interface/node_metadata.rs
- state/src/lib.rs
- state/src/replication/raft_node.rs
- state/src/storage/db.rs
- state/src/storage/tx/task_queue.rs
- workers/job-types/src/task_driver.rs
This PR implements the `AppendWalletTask` state transition in the applicator. This transition will append a task to the wallet queue and being running it in the task driver (on the `executor` node) if the queue is empty.
- Unit tests pass for `state`
> state: applicator: Add `AppendWalletTask` state transition + handler

- .github/workflows/upgrade.yml
- bin/release.zsh
This PR adds a Github Action for upgrading the relayer clusters in a given environment. This includes building the relayer image, pushing it to AWS ECR, updating the ECS task definition, and re-deploying the ECS service.
I tested this locally using [nektos/act](https://github.com/nektos/act), and it successfully builds/pushes/deploys.
This approach is admittedly a bit brittle for one reason: we need to exactly match the names of the AWS ECS task definition, service, and cluster, as defined in AWS. This is because none of the associated AWS ECS API endpoints support querying the resource by tag, so we can't make use of a consistent tagging scheme.
For a v1, I think this is fine. Down the line, we could write a more involved script that lists all of the {task definitions, services, …
> add upgrade Github Action

- state/src/interface/mod.rs
- state/src/interface/task_queue.rs
This PR adds interface methods for the task queue. This includes appending and popping from the queue. These methods will be used by other workers to start tasks and by the task driver to mark a task as complete.
- Update callsites to enqueue tasks
- Task preemption
- Task failover
> state: interface: Add task queue getters and setters

- state/src/applicator/mod.rs
- state/src/applicator/task_queue.rs
- state/src/interface/mod.rs
- state/src/interface/task_queue.rs
- state/src/lib.rs
This PR adds a `PopWalletTask` state transition that removes the top task from the wallet's task queue. If the queue is non-empty the next task will start running on its executor node.
> state: applicator: task-queue: Add `PopWalletTask` transition + impl

- .github/workflows/upgrade.yml
This PR changes the way we decide how many clusters to upgrade by using environment-specific variables as opposed to a single `NUM_CLUSTERS` variable regardless of targeting `staging`, `testnet`, or `mainnet`
> ga: upgrade: use env-specific number of clusters

- Cargo.lock
- common/src/types/task_descriptors.rs
- state/src/applicator/mod.rs
- state/src/applicator/task_queue.rs
- state/src/interface/task_queue.rs
- state/src/lib.rs
- state/src/storage/db.rs
- state/src/storage/tx/mod.rs
- state/src/storage/tx/task_queue.rs
- workers/task-driver/Cargo.toml
- workers/task-driver/src/driver.rs
- workers/task-driver/src/error.rs
This PR updates the global state's view of the task execution during state transitions in a task. This is done to allow API introspection into the task status via the `State` object.
- Testing for the API once the task queue is fully integrated
> workers: task-driver: Update global task queue state during task state transitions

- common/src/types/task_descriptors.rs
- state/src/interface/task_queue.rs
- workers/api-server/Cargo.toml
- workers/api-server/src/error.rs
- workers/api-server/src/http.rs
- workers/api-server/src/http/task.rs
- workers/api-server/src/http/wallet.rs
- workers/api-server/src/websocket.rs
- workers/api-server/src/websocket/task.rs
- workers/api-server/src/worker.rs
This PR adjusts the `api-server` to use the task queue when creating tasks. This involves going through the raft-backed state. For now, we await consensus on the queue update in the `api-server`, if this proves too burdensome (unlikely for now) we can return early or have an option to do so.'
- Validity checks at the API layer
- Unit tests pass, will test API more directly after codebase builds
> workers: api-server: Refactor to use new task-queue abstraction

- workers/job-types/src/task_driver.rs
- workers/task-driver/src/driver.rs
- workers/task-driver/src/error.rs
This PR adds a method by which a worker may be notified when a task completes. This is important for flows like handshakes, which require that we complete settlement before the `HandshakeManager` can continue its job.
- Deferred until we fix integration tests in the `task-driver`
> workers: task-driver: Add notifications for task completion

- .github/workflows/upgrade.yml
- bin/release.zsh
- docker/release/Dockerfile
This PR updates the `upgrade` Github Action to make use of [`cargo-chef`](https://github.com/LukeMathWalker/cargo-chef), which implements the "build dependencies first so they can be cached in Docker" pattern that we previously manually attempted.
Additionally, I switched the runner in the build step of our action to use an arm64 [BuildJet](https://buildjet.com/for-github-actions/docs/runners/hardware) machine, which bears a significant improvement in build time.
> docker, ga: use `cargo-chef` & BuildJet

- common/src/types/tasks.rs
- state/src/applicator/task_queue.rs
- state/src/interface/task_queue.rs
- state/src/storage/tx/task_queue.rs
- workers/job-types/src/task_driver.rs
- workers/task-driver/src/driver.rs
This PR adds a `RunImmediate` job type for the `task-driver`. This job will preempt any running tasks on the wallet it modifies and run in place. This will be used for match settlement which should be run as soon as the match completes, bypassing the queue.
However, running a preemption is not always possible: other tasks may have committed state on-chain, and cannot be preempted. In this case the match must fail and the task queue should resume.
- Do not schedule matches on orders with in-flight updates
- State tests pass
- Testing deferred until more components are refactored
> workers: task-driver: Add `RunImmedate` job and initial preemption skeleton

- state/src/applicator/error.rs
- state/src/applicator/mod.rs
- state/src/applicator/task_queue.rs
- state/src/interface/task_queue.rs
- state/src/lib.rs
- state/src/storage/tx/task_queue.rs
- workers/task-driver/src/driver.rs
- workers/task-driver/src/error.rs
This PR implements task queue pausing and unpausing and makes these transitions in the `task-driver` during a `RunImmediate` job. When a queue is paused it places any running tasks onto the queue in the `Queued` state. As well, if a task tries to transition its state when a queue is paused, the raft will fail to apply the log.
In the task driver we check for these failed applications when a task is _first_ committing. If failed, we assume the task has been preempted. 
- State unit tests pass
- Testing deferred until more components implemented
> workers: task-driver: pause and unpause state in `RunImmediate`

- common/src/types/tasks.rs
- state/src/applicator/mod.rs
- state/src/applicator/task_queue.rs
- state/src/interface/task_queue.rs
- state/src/lib.rs
- state/src/storage/tx/mod.rs
- state/src/storage/tx/task_queue.rs
- workers/api-server/src/http/wallet.rs
- workers/chain-events/src/listener.rs
- workers/task-driver/src/driver.rs
This PR removes the notion of a wallet ID as the only task queue key and abstractly indexes task queues by a `TaskQueueKey`. This will allow us to generalize the notion of a queue key. As well, this allows us to derive the queue key from the task descriptor directly, giving a more ergonomic interface.
On top of this we can rebuild the task driver integration tests
- Todo: task driver integration tests
> state: Generalize task queue keys from wallet IDs to abstract keys

- state/src/applicator/mod.rs
- state/src/applicator/task_queue.rs
- state/src/interface/error.rs
- state/src/interface/notifications.rs
- state/src/interface/task_queue.rs
- state/src/lib.rs
- workers/task-driver/integration/helpers.rs
- workers/task-driver/integration/main.rs
- workers/task-driver/integration/tests/create_new_wallet.rs
- workers/task-driver/integration/tests/lookup_wallet.rs
- workers/task-driver/integration/tests/settle_match.rs
- workers/task-driver/integration/tests/update_wallet.rs
- workers/task-driver/src/driver.rs
- workers/task-driver/src/error.rs
- workers/task-driver/src/lib.rs
- workers/task-driver/src/running_task.rs
- workers/task-driver/src/tasks/create_new_wallet.rs
- workers/task-driver/src/traits.rs
This PR refactors the task driver integration tests to use the new raft-backed task queue in the `state` crate. This includes fixing a few bugs that came up along the way.
Notably, the immediate vs non-immediate tasks required some care to handle properly. For this reason I encapsulated more of the task execution logic in a `RunnableTask` struct that can cleanly handle difference in task types. The driver is then responsible only for retries and backoff.
- Integration tests pass
> task-driver: integration: Refactor integration tests over task queue

- Cargo.lock
- circuit-types/src/keychain.rs
- circuit-types/src/wallet.rs
- common/Cargo.toml
- common/src/types/tasks.rs
- common/src/types/wallet.rs
- external-api/src/types.rs
- workers/api-server/src/http/wallet.rs
- workers/chain-events/src/listener.rs
- workers/handshake-manager/src/manager.rs
- workers/handshake-manager/src/manager/internal_engine.rs
- workers/task-driver/integration/helpers.rs
- workers/task-driver/integration/tests/create_new_wallet.rs
- workers/task-driver/integration/tests/lookup_wallet.rs
- workers/task-driver/integration/tests/settle_match.rs
- workers/task-driver/integration/tests/update_wallet.rs
- workers/task-driver/src/tasks/lookup_wallet.rs
- workers/task-driver/src/tasks/settle_match_internal.rs
- workers/task-driver/src/tasks/update_merkle_proof.rs
- workers/task-driver/src/tasks/update_wallet.rs
This PR implements task constructors for each of the task descriptors and changes the callsites to use these constructors. The constructors enforce safety checks: valid blinding, wallet update signatures, etc. And can give an immediate failure in the case a task will not be able to run.
I also removed wallet locks while modifying the `Wallet` type. These are subsumed by the wallet task queue.
- Tested the constructor safety checks for the fallible descriptor types
> common: types: tasks: Implement task constructors with safety checks

- Cargo.lock
- Cargo.toml
- common/src/default_wrapper.rs
- common/src/types.rs
- config/src/lib.rs
- core/src/main.rs
- mock-node/Cargo.toml
- mock-node/src/lib.rs
- state/src/replication/network/traits.rs
- workers/api-server/src/http.rs
- workers/api-server/src/lib.rs
- workers/api-server/src/worker.rs
- workers/job-types/src/gossip_server.rs
- workers/job-types/src/handshake_manager.rs
- workers/job-types/src/network_manager.rs
- workers/job-types/src/price_reporter.rs
- workers/job-types/src/proof_manager.rs
This PR adds a `mock-node` crate to the repo which will form the basis of integration testing the `handshake-manager`, `gossip-server`, and `api-server`. The mock node essentially ties together all desired workers and maintains access to their queues so that tests may directly interact with workers.
- A simple unit test with an api-only node
> mock-node: Define initial mock node for testing

- Cargo.lock
- Cargo.toml
- common/src/default_wrapper.rs
- common/src/types.rs
- common/src/types/token.rs
- config/src/lib.rs
- core/src/main.rs
- mock-node/Cargo.toml
- mock-node/src/lib.rs
- state/src/replication/network/traits.rs
- workers/api-server/src/http.rs
- workers/api-server/src/lib.rs
- workers/api-server/src/worker.rs
- workers/job-types/src/gossip_server.rs
- workers/job-types/src/handshake_manager.rs
- workers/job-types/src/network_manager.rs
- workers/job-types/src/price_reporter.rs
- workers/job-types/src/proof_manager.rs
- workers/price-reporter/Cargo.toml
- workers/price-reporter/src/lib.rs
- workers/price-reporter/src/mock.rs
This PR adds a mock price reporter that will be used in integration tests. The mock reporter simply returns a dummy value for each queried pair.
- I added tests for the mock
- Unit tests pass workspace wide
> workers: price-reporter: mock: Add mock price reporter for tests

- core/Cargo.toml
- mock-node/Cargo.toml
- mock-node/src/lib.rs
- workers/api-server/src/http.rs
- workers/handshake-manager-tests/Cargo.toml
- workers/handshake-manager-tests/src/main.rs
- workers/handshake-manager/docker-compose.yml
- workers/price-reporter/src/mock.rs
This PR updates the handshake manager tests to spawn a configured mock node in the integration stack. I added a dummy test to ensure things run alright, though this will be replaced in a follow-up with actual tests.
- Unit tests pass workspace wide
- Dummy integration does not panic
> workers: handshake-manager-tests: Setup mock node in tests

- external-api/src/http/task.rs
- workers/api-server/src/http.rs
- workers/api-server/src/http/task.rs
This PR adds a `/v0/task_queue/:wallet_id` route and handler that returns a set of queued tasks for a wallet. 
- Tested a simple `GET` against this endpoint
> workers: api-server: Add `/v0/task_queue/:wallet_id` route + handler

- common/src/types/wallet/balances.rs
This PR fixes a bug in the `add_balance` function where the `balance` variable was being overloaded with both the value to be added (deposited) and the balance that was currently in the wallet. This resulted in the post-deposit amount being incorrect (deposits would go from 1, 2, 4, 8, etc.)
- Tested in the frontend
> common: Add wallet balance to request amount when depositing

- workers/api-server/src/http/wallet.rs
This PR ensures that the wallet id that is passed to the relayer in the HTTP request is assigned to the created wallet instead of a random identifier. Copies logic from pre state refactor code: https://github.com/renegade-fi/renegade/blob/150e135d38526036d474cbddb48d10b6c4df4faf/task-driver/src/create_new_wallet.rs#L199
- Tested in the frontend
> workers: Persist wallet id from request in create-wallet task

- Cargo.lock
- state/src/replication/log_store.rs
- state/src/storage/cursor.rs
- state/src/storage/error.rs
- state/src/storage/traits.rs
- state/src/storage/tx/order_book.rs
- state/src/storage/tx/peer_index.rs
- state/src/storage/tx/wallet_index.rs
This PR adds key filters to the cursor type. This allows us to filter only pass keys which are relevant to a query rather than the entire table into the cursor consumer. Filtering is particularly useful when a table has multiple key types in it, e.g. the network order table.
This fixes a bug that occurs when constructing heartbeat messages -- the network order table is incorrectly filtered, and the cursor attempts to deserialize other entry type to `PeerInfo` types. 
I also modified the iterator on the cursor to implement `IntoIterator` so that the semantics are more clear, i.e. iterating consumes the cursor rather than allowing for mutations in between iterations.
- Replicated the bug that @sehyunc observed and verified it was fixed after this PR
> state: storage: cursor: Add key filters

- circuits/src/zk_circuits/valid_wallet_update.rs
This PR updates the `VALID WALLET UPDATE` circuit with a number of changes ahead of audit
- We now require that balance, order, transfer amounts be less than $2^{128}$
- We require that any balance, order, or transfer with zero mint(s) be zero in every field
- We require that fees be paid before any withdrawal on a balance takes place
- We no longer require order mints to be unique (a user may place both a sell and buy order for example)
- We remove the timestamp field from the orders, it currently does nothing
- Added unit tests for each case written in our circuit spec. For failure cases, I removed constraints that enforce the case, verified that the test failed (constraints were satisfied with an invalid witness) then added back the constraints to ablate test malformation.
> circuits: zk-circuits: valid-wallet-update: Add fees and bounds checks

- core/src/main.rs
- mock-node/src/lib.rs
- state/src/applicator/mod.rs
- state/src/applicator/order_book.rs
- state/src/interface/mod.rs
- state/src/interface/node_metadata.rs
- state/src/lib.rs
- state/src/replication/raft_node.rs
This PR starts the internal matching engine on any internally managed order when the validity proof for that order is updated. 
Currently all nodes will run the internal matching engine. Of course, only one will succeed and the others will error submitting the transaction, we can fix this later by adding a `internal_engine_runner: WrappedPeerId` that the proposer of the state transition sets. This is simple enough to get FE integration off the ground.
> state: applicator: order-book: Run internal match engine on proof update

- common/src/types/exchange.rs
- workers/price-reporter/src/errors.rs
- workers/price-reporter/src/manager.rs
- workers/price-reporter/src/reporter.rs
This PR changes the price reporter to not fail on invalid asset pairs, i.e. if no exchange supports the pair. In this case the `Unsupported` message is returned to the caller. 
I tested this through the API to verify that this unsupported information makes its way back to the client.
> workers: price-reporter: Do not fail on invalid pair

- circuits/src/zk_circuits/valid_commitments.rs
- circuits/src/zk_circuits/valid_wallet_update.rs
This PR adds fee implementations and extra constraints to the `VALID COMMITMENTS` circuit.
For each invalid test, I commented out constraints until the test failed, then reintroduced minimal targeted constraints to pass the test.
> circuits: zk-circuits: valid-commitments: Add fees + extra constraints

- Cargo.lock
- arbitrum-client/Dockerfile
- arbitrum-client/src/client/contract_interaction.rs
- arbitrum-client/src/client/event_indexing.rs
- core/Cargo.toml
- core/src/main.rs
- docker/sequencer/Dockerfile
- workers/api-server/src/router.rs
- workers/api-server/src/websocket.rs
- workers/chain-events/src/listener.rs
- workers/handshake-manager/src/manager.rs
- workers/handshake-manager/src/manager/price_agreement.rs
- workers/price-reporter/src/manager.rs
- workers/proof-manager/src/proof_manager.rs
- workers/task-driver/Dockerfile
- workers/task-driver/docker-compose.yml
- workers/task-driver/src/driver.rs
- workers/task-driver/src/tasks/create_new_wallet.rs
- workers/task-driver/src/tasks/lookup_wallet.rs
- workers/task-driver/src/tasks/settle_match.rs
- workers/task-driver/src/tasks/settle_match_internal.rs
- workers/task-driver/src/tasks/update_merkle_proof.rs
- workers/task-driver/src/tasks/update_wallet.rs
This PR adds some (basic, minimal) span structure to the relayer workers - though, for now, we don't do any tracing of the gossip and network manager workers, as they are fairly low-level and high-volume.
This includes a top-level span for each job of each worker, with some sub-spans per API request, per task step, per proof generated, and per Arbitrum client method.
Additionally, I've included in this the usage of `cargo chef` in the Arbitrum client and task driver integration tests, which I used to check on trace generation.
> workers: basic instrumentation

- circuits/src/zk_circuits/valid_match_settle/mod.rs
- circuits/src/zk_circuits/valid_match_settle/multi_prover.rs
- circuits/src/zk_circuits/valid_match_settle/single_prover.rs
This PR adds multiprover changes to the `VALID MATCH SETTLE` circuit including fees and the updated bounds checks in the single prover case. We test verification against the single prover verifier, which implies that the circuits have the same topology.
> circuits: valid-match-settle: Implement fees for multiprover circuit

- circuit-types/src/fixed_point.rs
- circuit-types/src/match.rs
- circuits/src/zk_circuits/mod.rs
- circuits/src/zk_circuits/valid_commitments.rs
- circuits/src/zk_circuits/valid_match_settle/mod.rs
- circuits/src/zk_circuits/valid_match_settle/multi_prover.rs
- circuits/src/zk_circuits/valid_match_settle/single_prover.rs
- constants/src/lib.rs
- util/src/matching_engine.rs
This PR adds fees, extra range constraints, and tests to the single-prover `VALID MATCH SETTLE` circuit. The MPC circuits and the multiprover circuit are deferred for a follow up.
- All unit tests pass except multiprover tests
> circuits: zk-circuits: valid-match-settle: singleprover circuit fees

- circuit-types/src/lib.rs
- circuits/src/zk_circuits/valid_commitments.rs
- circuits/src/zk_circuits/valid_fee_redemption.rs
- circuits/src/zk_gadgets/note.rs
This PR implements the `VALID FEE REDEMPTION` circuit and associated tests. This circuit is used to settle a note into the recipient's wallet. Note settlement is authorized by the recipient proving knowledge of the decryption key associated with the note.
> circuits: valid-fee-redemption: Add circuit implementation + tests

- Cargo.lock
- circuit-types/src/lib.rs
- circuits/src/zk_circuits/valid_commitments.rs
- circuits/src/zk_circuits/valid_fee_redemption.rs
- circuits/src/zk_circuits/valid_offline_fee_settlement.rs
- circuits/src/zk_gadgets/note.rs
This PR adds constraint satisfaction tests for the `VALID OFFLINE FEE SETTLEMENT` circuit. For each test, I commented out the constraints that it tests to ensure the test would fail, then added them back in.
> circuits: valid-offline-fee-settlement: Add constraint tests

- Cargo.lock
- common/Cargo.toml
- common/src/types/tasks.rs
This PR updates the task validity check for `update-wallet` to use Ethers in its commitment signature verification. This changes the signature format to be compatible with the contracts.
> common: tasks: Use Ethers sig verify to match contract implementation

- .github/workflows/upgrade.yml
This PR fixes the `upgrade` Github action to properly construct the cluster names to upgrade. Additionally, we bump the runner hardware, as we were getting OOM-killed during the build phase on the previous runner.
This has been tested on staging and successfully upgrades all of the clusters, single-node clusters included.
> github: fix single-node upgrade action

- common/src/types/tasks.rs
- state/src/applicator/error.rs
- state/src/applicator/order_book.rs
- state/src/applicator/task_queue.rs
- workers/handshake-manager/src/manager/internal_engine.rs
- workers/task-driver/integration/tests/settle_match.rs
- workers/task-driver/src/tasks/settle_match_internal.rs
This PR changes how we run the internal matching engine. Previously, we enqueued an internal matching engine job when the state received an order validity bundle. This is, however, done _during_ execution of other tasks, after their commit point, so the handshake manager would:
1. Find a match
2. Attempt to pause the wallet's task queue to settle the match
3. Fail, because the running task had already reached its commit point
Now, we instead run the internal matching engine on all wallet orders when the wallet task completes
- All `task-driver` integration tests pass
> state: applicator: Run internal matching engine when wallet job commits

- Cargo.lock
- arbitrum-client/Dockerfile
- docker/sequencer/Dockerfile
- docker/sequencer/deploy_contracts.sh
This PR updates the sequencer Dockerfile & contract deployment script to deploy the newly-introduced darkpool core & transfer executor contracts, as well as a Permit2 contract.
Note: the Dockerfile assumes that https://github.com/renegade-fi/renegade-contracts/pull/229 has been merged into `renegade-contracts/main`, so we should not merge this until that is the case.
The sequencer image builds successfully, but I am not yet able to run the existing integration tests (which should not need any changes) due to compilation errors elsewhere in the repo.
@joeykraut I can fix try fixing these errors, but I'm sure you have more context and were already planning on doing so, so I don't want to duplicate work. I can press onward with implementing new functionality / tests and run them when …
> docker: sequencer: deploy new darkpool core & transfer executor contracts

- arbitrum-client/Dockerfile
- circuit-types/src/fixed_point.rs
- circuit-types/src/match.rs
- circuits/benches/valid_wallet_update.rs
- circuits/src/lib.rs
- circuits/src/mpc_circuits/settle.rs
- circuits/src/mpc_gadgets/fixed_point.rs
- circuits/src/zk_circuits/valid_fee_redemption.rs
- circuits/src/zk_circuits/valid_match_settle/mod.rs
- circuits/src/zk_gadgets/wallet_operations.rs
- util/src/matching_engine.rs
This PR adds fee computation and settlement to the `settle` MPC circuit. Single-sided fees are computed and then used to settle the match into the wallets. 
I also added a few fixes for clippy lints in `circuits` -- the repo is compiling enough locally for clippy lints to show up.
- Updated settlement unit tests to account for fees
> circuits: mpc-circuits: settle: Compute & settle fees in MPC

- Cargo.lock
- arbitrum-client/Cargo.toml
- arbitrum-client/integration/contract_interaction.rs
- arbitrum-client/src/abi.rs
- arbitrum-client/src/client/contract_interaction.rs
- arbitrum-client/src/conversion.rs
- common/src/types.rs
- common/src/types/tasks.rs
- common/src/types/transfer.rs
- common/src/types/transfer_aux_data.rs
- docker/sequencer/Dockerfile
- external-api/src/http/wallet.rs
- workers/api-server/src/http/wallet.rs
- workers/task-driver/src/tasks/update_wallet.rs
This PR introduces a `TransferAuxData` type analogous to the one present in the contracts repo which encapsulates auxiliary data needed to validate an external transfer. The type is used in the `update_wallet` `ArbitrumClient` method and throughout the task driver and API server as appropriate (i.e., we now expect this struct to be submitted alongside deposit/withdrawal API requests).
When patching the rest of the repo to compile, everything builds, but updates to the existing Arbitrum client and task driver integration test are deferred for the next PR as there are a lot of helpers to be ported over from the contracts repo.
> arbitrum-client, workers: task-driver, api-server: add `TransferAuxData` to wallet updates

- Cargo.lock
- arbitrum-client/integration/contract_interaction.rs
- arbitrum-client/src/abi.rs
- arbitrum-client/src/client/contract_interaction.rs
- arbitrum-client/src/client/event_indexing.rs
- arbitrum-client/src/conversion.rs
- arbitrum-client/src/helpers.rs
- common/src/types/wallet/mocks.rs
This PR adds a method to the Arbitrum client for calling the `settle_online_relayer_fee` method on the Darkpool. This includes the necessary conversion & event parsing methods.
I've also added an integration test asserting that the method does not revert, and that the correct public shares can be recovered from calldata.
All `arbitrum-client` integration tests pass.
> arbitrum-client: `settle_online_relayer_fee`

- arbitrum-client/integration/contract_interaction.rs
- arbitrum-client/src/client/contract_interaction.rs
- arbitrum-client/src/client/event_indexing.rs
- arbitrum-client/src/conversion.rs
- arbitrum-client/src/helpers.rs
This PR updates the Arbitrum client to be able to call the `settle_offline_fee` method on the darkpool contract, including the necessary conversion and calldata parsing helpers.
I've also added an integration test asserting that the method doesn't revert, and that the correct public wallet shares can be recovered from calldata.
All `arbitrum-client` integration tests pass.
> arbitrum-client: `settle_offline_fee`

- arbitrum-client/integration/contract_interaction.rs
- arbitrum-client/src/client/contract_interaction.rs
- arbitrum-client/src/client/event_indexing.rs
- arbitrum-client/src/conversion.rs
- arbitrum-client/src/helpers.rs
This PR updates the Arbitrum client to be able to call the `redeem_fee` method on the darkpool contract, including the necessary conversion and calldata parsing helpers.
I've also added an integration test asserting that the method doesn't revert and that the correct shares are recovered from calldata.
All `arbitrum-client` integration test pass.
> arbitrum-client: `redeem_fee`

- .gitattributes
- .gitignore
- Cargo.lock
- circuit-types/src/srs.rs
- srs/srs.ptau
This PR splits the SRS into ~50M chunks by running:
```shell
split -d -b 50M srs.ptau srs
```
This brings the SRS chunks below the Github file size limit, allowing us to remove usage of Git LFS, and thus be able to use the `SYSTEM_SRS` in the deploy scripts in `renegade-contracts`.
The unit tests in `srs.rs` pass, and the `valid_fee_redemption` bench mark on the large parameter set runs without issue.
> srs: split srs into 50M chunks

- Cargo.lock
- arbitrum-client/Dockerfile
- arbitrum-client/src/client/mod.rs
- common/src/types/tasks.rs
- state/Cargo.toml
- state/src/applicator/task_queue.rs
- state/src/interface/task_queue.rs
- state/src/storage/db.rs
- state/src/storage/error.rs
- state/src/storage/tx/mod.rs
- state/src/storage/tx/node_metadata.rs
- state/src/storage/tx/task_queue.rs
- test-helpers/Cargo.toml
- test-helpers/src/contract_interaction/transfer_auth/mod.rs
- util/src/arbitrum.rs
- workers/task-driver/Dockerfile
- workers/task-driver/integration/helpers.rs
- workers/task-driver/integration/tests/settle_match.rs
- workers/task-driver/integration/tests/update_wallet.rs
This PR fixes up the integration tests for the task driver given the fees changes.
I'm dealing with a serialization bug related to https://github.com/serde-rs/serde/issues/1682 so the tests do not currently pass. Will fix them up in the next follow up.
> task-driver: integration: Update integration tests with fees changes

- config/src/lib.rs
- core/Cargo.toml
- core/src/main.rs
- docker/release/Dockerfile
- util/Cargo.toml
- util/src/telemetry/mod.rs
- util/src/telemetry/otlp_tracer.rs
This PR removes the usage of compiler flags and environment variables for configuring telemetry with CLI / config file options. This centralizes relayer configuration and makes it more straightforward. I tested these changes ad-hoc by running the relayer locally and setting the values appropriately in a config file, confirming that traces / logs show up in Datadog as expected.
> config: add tracing/logging config options

- Cargo.lock
- config/src/lib.rs
- core/src/main.rs
- util/Cargo.toml
- util/src/telemetry/metrics.rs
- util/src/telemetry/mod.rs
- util/src/telemetry/otlp_tracer.rs
This PR refactors the `telemetry` module to use a builder pattern so that configuration for the various telemetry services is more discoverable and easily configurable as we add functionality.
We use this pattern to introduce a metrics layer that exports metrics to a StatsD endpoint, and additionally leverages the [`metrics_tracing_context`](https://docs.rs/metrics-tracing-context/latest/metrics_tracing_context/) crate to inject span fields as metric labels.
I've tested this ad-hoc by running the relayer with the desired config options + a local Datadog agent and have confirmed that metrics are recorded.
> util: telemetry: expose telemetry builder & add metrics

- Cargo.lock
- workers/handshake-manager-tests/src/mpc_match.rs
- workers/handshake-manager/src/manager/match.rs
- workers/task-driver/src/driver.rs
- workers/task-driver/src/tasks/update_wallet.rs
This PR fixes up two bugs discovered when integration testing the `task-driver` changes:
1. The logic to find an external transfer index was swapped
2. Stack overflows allocating `tokio::oneshot` channels; I increased the stack size available to 5Mb
- `task-driver` integration tests pass
> workers: task-driver: Fix integration tests after fees changes

- circuits/src/zk_gadgets/poseidon.rs
- renegade-crypto/src/hash/poseidon2.rs
This PR fixes a bug in the Poseidon2 sponge implementations in which we were not incrementing `next_index` within the `squeeze` method. This bug is fixed in both the native and circuit definitions, and I added a test for implementation coherence.
> circuits, renegade-crypto: Increment `next_index` in Poseidon squeeze

- circuits/src/zk_gadgets/arithmetic.rs
- circuits/src/zk_gadgets/bits.rs
- circuits/src/zk_gadgets/fixed_point.rs
- circuits/src/zk_gadgets/wallet_operations.rs
This PR makes a fix to the `DivRem` gadget to avoid wraparound. Specifically, we constrain each of `b`, `q`, and `r` to be of bitlength at most `D`. We also disallow `D` from being large enough that `2D` would wrap around the field.
> circuits: zk-gadgets: arithmetic: Prevent wraparound in `DivRem` gadget

- common/src/types/tasks.rs
- workers/task-driver/src/driver.rs
- workers/task-driver/src/tasks/mod.rs
- workers/task-driver/src/tasks/pay_fees.rs
- workers/task-driver/src/tasks/update_wallet.rs
This PR defines the skeleton of the `PayFees` task, which will settle the relayer and protocol fee for a given balance in a given wallet. Implementation is deferred to a follow-up
> task-driver: tasks: pay-fees: Define initial `pay-fees` task

- circuits/src/lib.rs
- constants/src/lib.rs
- workers/task-driver/integration/tests/mod.rs
- workers/task-driver/integration/tests/pay_protocol_fee.rs
This PR adds an integration test for the `PayProtocolFee` task. This test allocates a wallet with a non-zero protocol fee balance then settles this balance into a note.
- All `task-driver` integration tests pass
- All workspace unit tests pass
> task-driver: integration: pay-protocol-fee: Add integration tests

- common/src/types/tasks.rs
- common/src/types/token.rs
- workers/task-driver/src/driver.rs
- workers/task-driver/src/tasks/mod.rs
- workers/task-driver/src/tasks/pay_protocol_fee.rs
- workers/task-driver/src/tasks/pay_relayer_fee.rs
This PR builds the skeleton of the `pay-relayer-fee` task. This task will hold logic for paying relayer fees settled during a match.
Implementation is deferred to a follow-up
> task-driver: tasks: pay-relayer-fee: Implement relayer fee skeleton

- docker/sequencer/Dockerfile
- docker/sequencer/deploy_contracts.sh
- docker/sequencer/devnet_chain_info.json
This PR adds a custom chain configuration for the sequencer, allowing us to use the dedicated devnet chain ID defined in https://github.com/renegade-fi/renegade-contracts/pull/233.
This chain config is a copy of the one used for the [Arbitrum Stylus devnet](https://github.com/OffchainLabs/stylus/blob/stylus/cmd/chaininfo/arbitrum_chain_info.json#L148-L182), but with our own chain ID and chain name.
I ran the `arbitrum-client` integration tests with the new sequencer (against the `andrew/no-verify-guards` branch where these changes are reflected contract-side) and they pass, indicating that the verification guards are satisfied appropriately in the relayer integration tests and the chain IDs line up.
> docker: sequencer: use custom devnet chain info

- config/src/lib.rs
- state/src/interface/node_metadata.rs
- state/src/storage/tx/node_metadata.rs
- workers/api-server/src/http/wallet.rs
This PR overwrites a wallet's `managing_cluster` and `match_fee` with the relayer's configured values when a wallet is created. The client will be updated of the wallet after the creation flow finishes, at which point it will be able to abandon the wallet if either field is set unexpectedly.
> api-server: http: wallet: Overwrite managing cluster & take rate

- circuit-types/src/note.rs
- state/src/interface/node_metadata.rs
- workers/task-driver/src/helpers.rs
- workers/task-driver/src/tasks/mod.rs
- workers/task-driver/src/tasks/pay_offline_fee.rs
- workers/task-driver/src/tasks/pay_relayer_fee.rs
- workers/task-driver/src/tasks/redeem_relayer_fee.rs
This PR implements the `redeem-realyer-fee` logic. Note that we don't need to update validity proofs because relayer wallets don't currently holds orders. 
We also automatically enqueue this task on the relayer's wallet when a relayer fee is settled offline.
Testing is deferred to a follow-up.
> task-driver: redeem-relayer-fee: Implement task logic

- workers/task-driver/integration/helpers.rs
- workers/task-driver/integration/tests/mod.rs
- workers/task-driver/integration/tests/redeem_relayer_fee.rs
- workers/task-driver/integration/tests/settle_match.rs
- workers/task-driver/src/tasks/redeem_relayer_fee.rs
This PR adds integration tests for the relayer fee redemption path. Specifically, we pay a relayer fee from a trader's wallet and verify that the relayer automatically redeems the fee into its own wallet.
- Unit tests pass workspace wide
- All integration tests pass
> task-driver: integration: redeem-relayer-fee: Add integration tests

- config/src/lib.rs
- core/src/main.rs
- mock-node/src/lib.rs
- workers/handshake-manager/src/manager.rs
- workers/handshake-manager/src/manager/price_agreement.rs
- workers/price-reporter/src/exchange.rs
- workers/price-reporter/src/exchange/binance.rs
- workers/price-reporter/src/exchange/coinbase.rs
- workers/price-reporter/src/exchange/connection.rs
- workers/price-reporter/src/exchange/kraken.rs
- workers/price-reporter/src/exchange/okx.rs
- workers/price-reporter/src/exchange/uni_v3.rs
- workers/price-reporter/src/reporter.rs
- workers/price-reporter/src/worker.rs
This PR exposes items from the `workers/price-reporter` crate needed by the standalone price reporter service. Notably, this included separating out an `ExchangeConnectionsConfig` struct that is more lightweight and can be used by the standalone price reporter instead of the entore `PriceReporterConfig`.
> workers: price-reporter: expose necessary items for standalone price reporter

- core/src/setup.rs
This PR fixed a bug wherein the relayer's wallet ID is never setup in the node metadata table. This prevents the relayer from redeeming fees after a match.
- Integration tests pass
- @sehyunc Please check that your flows work with this fix
> core: setup: Set `local-wallet-id` metadata entry at startup

- Cargo.lock
- arbitrum-client/src/abi.rs
- arbitrum-client/src/client/contract_interaction.rs
- circuit-types/src/fixed_point.rs
- circuits/Cargo.toml
- circuits/integration/mpc_circuits/match_settle.rs
- circuits/src/mpc_circuits/settle.rs
- circuits/src/zk_circuits/valid_match_settle/mod.rs
- common/src/types/wallet/keychain.rs
- config/src/lib.rs
- constants/src/lib.rs
- core/src/main.rs
- core/src/setup.rs
- util/Cargo.toml
- util/src/arbitrum.rs
- util/src/matching_engine.rs
- workers/handshake-manager/src/manager/match.rs
- workers/task-driver/Cargo.toml
- workers/task-driver/integration/main.rs
- workers/task-driver/integration/tests/pay_offline_fee.rs
- workers/task-driver/integration/tests/settle_match.rs
- workers/task-driver/src/tasks/pay_offline_fee.rs
- workers/task-driver/src/tasks/settle_match_internal.rs
This PR fetches the protocol's encryption key and take rate from the contract at startup and stores them in a `OnceCell`. To make testing simpler, if the `mocks` feature flag is enabled, the implementation of the `OnceCell` getter methods will fall back to a default.
- Ran a relayer, verified that it fetched the fee and encryption key
> arbitrum-client, util: Lookup protocol fee and key from contract

- common/src/types/token.rs
- config/src/lib.rs
- core/src/main.rs
- mock-node/src/lib.rs
- workers/api-server/src/websocket/price_report.rs
- workers/handshake-manager/src/manager/price_agreement.rs
- workers/job-types/src/price_reporter.rs
- workers/price-reporter/src/errors.rs
- workers/price-reporter/src/exchange/connection.rs
- workers/price-reporter/src/manager.rs
- workers/price-reporter/src/manager/native_executor.rs
- workers/price-reporter/src/mock.rs
- workers/price-reporter/src/reporter.rs
- workers/price-reporter/src/worker.rs
This PR introduces some reorganization of the `manager` module in the price reporter worker ahead of the implementation of the `ExternalPriceReporterExecutor`, which will be used to manage the worker in the case that the relayer opts to connect to an external price reporting service.
This mostly consists of moving the existing `PriceReporterExecutor` into the `native_executor` module, while keeping some utilities which will be shared in the `manager` module.
The next PR will have the implementation of the `ExternalPriceReporterExecutor`.
> workers: price-reporter: reorganize price reporter modules for external executor

- Cargo.lock
- Cargo.toml
We observed that `ahash`, a transitive dependency through `metrics` had bumped its MSRV to 1.72.0. This broke proof submission though the cause is unknown. For now, we will pin metrics to a known working version.
- Tested submitting a match against the deployed sequencer. Was able to reproduce the problem before this fix, and was able to submit a match afterward.
> meta: Pin metrics to `0.22.1`

- Cargo.lock
- circuit-types/src/order.rs
- external-api/src/http/network.rs
- external-api/src/http/order_book.rs
- external-api/src/http/price_report.rs
- external-api/src/http/task.rs
- external-api/src/http/wallet.rs
- external-api/src/lib.rs
- workers/api-server/src/auth.rs
- workers/api-server/src/http.rs
- workers/api-server/src/http/network.rs
- workers/api-server/src/http/order_book.rs
- workers/api-server/src/http/price_report.rs
- workers/api-server/src/http/task.rs
- workers/api-server/src/http/wallet.rs
This PR publishes the HTTP routes offered by the relayer in the `external-api` crate. This is nice for building rust-based clients that may inherit these types directly.
- Tested a few endpoints on the relayer
> external-api: Publish HTTP routes on crate interface

- common/src/types/wallet/mod.rs
- common/src/types/wallet/orders.rs
- workers/api-server/src/http/wallet.rs
This PR updates the way in which we remove orders from a wallet. Specifically, we no longer replace the order with a default but have the order list behave more like an append-centric vector. This makes for a more sensible API client-side.
This comes as a result of circuit changes that allow for more flexibility in updating orders.
- Used the changes to create and cancel orders in the `renegade-cli` and verified its functionality
> common: wallet: orders: Remove orders entirely from `KeyedList`

- common/src/types/tasks.rs
- external-api/src/bus_message.rs
- external-api/src/http/task.rs
- state/src/applicator/task_queue.rs
- workers/api-server/src/http/task.rs
- workers/api-server/src/http/wallet.rs
- workers/task-driver/integration/tests/update_wallet.rs
- workers/task-driver/src/driver.rs
- workers/task-driver/src/running_task.rs
- workers/task-driver/src/tasks/create_new_wallet.rs
- workers/task-driver/src/tasks/lookup_wallet.rs
- workers/task-driver/src/tasks/pay_offline_fee.rs
- workers/task-driver/src/tasks/pay_relayer_fee.rs
- workers/task-driver/src/tasks/redeem_relayer_fee.rs
- workers/task-driver/src/tasks/settle_match.rs
- workers/task-driver/src/tasks/settle_match_internal.rs
- workers/task-driver/src/tasks/update_merkle_proof.rs
- workers/task-driver/src/tasks/update_wallet.rs
This PR changes the API format of the task status to give a cleaner interface to the client. As well, for update wallet tasks we name the tasks by the update they perform.
- Tested the create + cancel order flows
- Opened a websocket on one of the tasks, verified the shape of the JSON
> external-api: task: Add descriptor to `TaskStateResponse`

- circuit-types/src/fixed_point.rs
- common/src/types/wallet/balances.rs
- common/src/types/wallet/orders.rs
- external-api/src/types.rs
- workers/api-server/src/http/wallet.rs
This PR makes a few changes to the API and the serialization we impose on it:
- We do not remove default elements from the wallet when delivering a wallet to the API. These, importantly, should remain in place when a wallet is updated (unless they are overridden) so removing them from the API response makes it difficult or impossible for a client to correctly construct a wallet update.
- We serialize and deserialize fixed point values by the decimal string of their `repr` field.
- I also simplified some of the withdrawal logic in the balance API
- Tested the API through our CLI
> common, external-api: wallet: Do not filter default elements

- Cargo.lock
- config/Cargo.toml
- config/src/lib.rs
- workers/price-reporter/src/manager.rs
- workers/price-reporter/src/manager/external_executor.rs
- workers/price-reporter/src/reporter.rs
- workers/price-reporter/src/worker.rs
This PR implements a secondary executor for the price reporter worker which connects to an external price reporter service, subscribing to all price updates over a single websocket connection. It spawns a separate task which manages the websocket connection and forwards incoming/outgoing messages between it and the executor over a pair of channels.
I have tested running the relayer ad-hoc with both the native and external executor, ensuring that it starts smoothly and that websocket subscriptions are established.
> workers: price-reporter: add external price reporter executor

- Cargo.lock
- common/src/types/token.rs
- config/Cargo.toml
- config/src/token_remaps.rs
- workers/api-server/src/http.rs
- workers/handshake-manager/src/manager/price_agreement.rs
- workers/price-reporter/src/mock.rs
This PR accomplishes the following:
1. Pares down any token metadata hardcoded in the relayer to contain only those tokens which are supported by Binance, and are currently on the hosted token remap in Github. This latter condition is temporary, I'll hammer out canonical token list w/ @ChrisBender tomorrow & update hosted token remap accordingly.
2. Simplifies the `ERC20_DATA` static to only contain ticker renaming information across exchanges, deferring the token address & decimals to the remap used by the relayer as the source of truth.
Also, this PR temporarily switches the quote asset for the default pairs from USDC to USDT. This is because many assets do not have a USDC pair on Binance. When stablecoin price conversion is implemented, we can go back to default USDC quotes w/ price …
> common: types: token: clean up token statics

- common/src/types/token.rs
- config/src/token_remaps.rs
- workers/handshake-manager/src/manager/price_agreement.rs
- workers/price-reporter/src/manager.rs
- workers/price-reporter/src/manager/external_executor.rs
- workers/price-reporter/src/reporter.rs
This PR is introduces some preliminary changes to facilitate the implementation of stablecoin-quote price conversion. Primarily:
1. Adds a static set of stablecoin tokens, which are candidates for price conversion when they are a quote asset
2. Adds a static mapping from exchange -> most liquid stable quote asset for that exchange, this will be the pair through which price is converted when the pair in the order is quoted with a different stablecoin
3. Lifts the mapping from exchange -> atomic (price, timestamp) out of the `AtomicPriceStreamState`. This makes the subsequent implementation of kicking off price streams for potentially different pairs than what was requested, as well as computing the price via conversion through the most liquid stable quote asset, much smoother. For example, …
> workers: price-reporter: per-exchange stream states

- common/src/types/token.rs
- workers/price-reporter/src/manager/external_executor.rs
This PR implements price conversion for stable-quoted assets in the external executor of the price reporter. This includes the following logic when a BASE<>NON-DEFAULT STABLE pair's price is requested:
1. Subscribe to price streams for BASE<>DEFAULT STABLE and NON-DEFAULT STABLE<>DEFAULT STABLE
2. Compute the converted price as (BASE/DEFAULT STABLE) / (NON-DEFAULT STABLE / DEFAULT STABLE)
I have asserted that this works ad-hoc, by running the relayer against the deployed price reporter and logging when price conversion occurs.
In the next PR, I will implement this for the native executor.
> workers: price-reporter: stable quote price conversion in external executor

- common/src/types/tasks.rs
- common/src/types/wallet/balances.rs
- common/src/types/wallet/orders.rs
- workers/handshake-manager/src/manager/internal_engine.rs
- workers/task-driver/src/helpers.rs
- workers/task-driver/src/tasks/settle_match_internal.rs
This PR modifies the logic for balance and order updates to make them mutually consistent:
- Orders are now overwritten if they are zero'd (amount is zero)
- Balances are now overwritten if they are zero'd (amount and fees are zero)
- Balances are added to the wallet in the same fashion orders are, i.e:
- Overwriting the first zero'd balance if it exists
- Appending if possible
- Erroring otherwise
> common: wallet: balances, orders: Make order/balance append consistent

- workers/api-server/src/websocket.rs
- workers/price-reporter/src/exchange/connection.rs
- workers/price-reporter/src/manager.rs
- workers/price-reporter/src/manager/external_executor.rs
- workers/price-reporter/src/manager/native_executor.rs
This PR ensures that we compute and publish price reports for the correct pairs when price updates come in. Previously, we would report prices for the exact pair for which an update was received, however it is possible that was a conversion pair (e.g. (requested quote, default stable)), for which we don't actually care about the price. More importantly, for any converted pairs, we would never report the price for the actual requested (base, quote), since we never get price updates directly for that pair.
We now track the top-level `requested_pairs`, and a mapping from a conversion pair to the requested pairs that depend on it, in the `PriceStreamStatesManager`, so that when a price update comes in, we can report prices for all of the requested pairs that depend on that update.
I have …
> workers: price-reporter: manager: properly compute price reports upon price update

- Cargo.lock
- Cargo.toml
This PR declaratively pins `metrics = 0.22.3` and patches `ahash = 0.8.11` to avoid inconsistency with the contracts code.
> deps: pin metrics=0.22.3, patch ahash=0.8.11

- docker/sequencer/Dockerfile
This PR tweaks the sequencer Dockerfile to use the exact Rust toolchain used in the contracts repo, as opposed to installing the latest nightly. This ensures that the contracts are compiled with the correct toolchain.
The sequencer image now builds & deploys the contracts successfully.
> docker: sequencer: install rust toolchain used in contracts

- Cargo.lock
- arbitrum-client/src/client/contract_interaction.rs
- state/src/applicator/task_queue.rs
- state/src/interface/task_queue.rs
- util/src/telemetry/helpers.rs
- util/src/telemetry/mod.rs
- workers/task-driver/src/driver.rs
- workers/task-driver/src/tasks/create_new_wallet.rs
- workers/task-driver/src/tasks/pay_offline_fee.rs
- workers/task-driver/src/tasks/pay_relayer_fee.rs
- workers/task-driver/src/tasks/redeem_relayer_fee.rs
- workers/task-driver/src/tasks/settle_match_internal.rs
- workers/task-driver/src/tasks/update_wallet.rs
This PR changes the applicator logic for the task queue such that preemption is not supported when a queue that a task attempts to preempt is already paused. This way, only one preemptive task for a queue can be running at a given time. This should mitigate the observed error w/ conflicting preemptive tasks causing double-resumes, spawning duplicates of the task at the top of the queue. This requires modification of the logic in the task driver to await the successful pausing of queues for a preemptive task.
This PR also includes some added telemetry which aided in the debugging of the issue described above, it generally seemed good to keep around.
These changes are running in staging, I will keep an eye on whether this issue gets observed again.
> workers: task-driver: driver, state: applicator: task_queue: await queue pausing & reject double-pauses

- Cargo.lock
- renegade-metrics/Cargo.toml
- renegade-metrics/src/helpers.rs
- workers/gossip-server/src/peer_discovery/heartbeat.rs
- workers/gossip-server/src/peer_discovery/peers.rs
This PR ensures that we `.set` gauge metrics directly, as the [`metrics_exporter_statsd`](https://docs.rs/metrics-exporter-statsd/latest/metrics_exporter_statsd/) crate [doesn't support incrementing/decrementing gauges](https://arc.net/l/quote/ucictrkr)
> renegade-metrics, workers: gossip-server: set gauge metrics directly

- workers/task-driver/src/driver.rs
- workers/task-driver/src/running_task.rs
This PR updates the running task `transition_state` method to await the application of the transition to a completed state. This prevents the issue of the subsequent `pop_task` state transition being applied before the `transition_state` transition, despite being proposed after.
I've tested this locally with a two-node cluster and am no longer seeing the ordering issue.
> workers: task-driver: running_task: await task completion before popping

- Cargo.lock
- circuits/src/mpc_gadgets/bits.rs
- circuits/src/mpc_gadgets/comparators.rs
- circuits/src/mpc_gadgets/modulo.rs
- test-helpers/src/mpc_network/mocks.rs
This PR adjusts the interfaces used in `circuits` and `test-helpers` to match changes in `ark-mpc`. Specifically these changes force the `OfflinePhase` (formerly `BeaverSource`) to return MACs with the shared values.
These changes also get all tests passing in the workspace.
Finally, the changes ingest a few optimizations that were made while integrating the offline phase, resulting in a significant speedup in match-settle latency.
- Unit tests pass workspace wide
> circuits, test-helpers: Ingest interface changes from `ark-mpc`

- Cargo.lock
- circuit-types/src/traits.rs
- circuits/benches/full_match.rs
- constants/src/lib.rs
- test-helpers/src/mpc_network/mocks.rs
This PR updates the circuit and mock beaver source interfaces that use `ark-mpc` to ingest changes made to the interface.
> test-helpers, circuit-types: Ingest ark-mpc changes

- Cargo.lock
- common/Cargo.toml
- common/src/types.rs
- common/src/types/offline_phase.rs
This PR introduces the basic types for pairwise offline phase storage. We will allocate one of these `PairwiseOfflineSetup` types per pair of clusters in the network. Each cluster will store their setup values and update them through the raft. Popping, appending, etc are all supported.
- Unit tests pass crate wide
> common: types: offline-phase: Add offline phase type definitions

- core/src/main.rs
- core/src/setup.rs
- state/src/interface/mod.rs
This PR increases the Raft heartbeat interval to 1s and the election timeout to be bounded between 10-15s. This ensures that Raft elections are not instigated unnecessarily when the network manager is handling bursts of load, in which case Raft heartbeats take longer to dequeue and execute.
We also move the node setup to after the gossip server is spun up, so that nodes are able to gossip raft messages, receive heartbeats, and establish leadership accordingly before the node setup delay kicks in - otherwise this gives nodes enough time to self-elect before heartbeating and thus never have a consistent view of leadership (as they would self-elect as leaders w/ the same term and # of log entries before ever heartbeating, leading to a stalemate)
I tested this by running a 2-node cluster …
> core: setup, state: interface: increase election & heartbeat intervals

- .github/workflows/test.yml
- state/src/applicator/mod.rs
- state/src/applicator/return_type.rs
- state/src/interface/mod.rs
- state/src/interface/node_metadata.rs
- state/src/interface/notifications.rs
- state/src/lib.rs
- state/src/replication/raft_node.rs
- workers/task-driver/src/tasks/create_new_wallet.rs
This PR adds return types to the state applicator. These return types allow the applicator to return a value to the waiters of a proposal. This will be used for allocating preprocessing values to a given node in the MPC prep.
I also changed the semantics of the `ProposalWaiter` so that they can no longer be joined. This simplifies the implementation of the return value semantics as we avoid buffering results of partially ready joins. This functionality was not used anywhere -- just vestigial complexity.
- Unit tests pass crate-wide
> state: applicator: Add return types to applicator

- .github/workflows/test.yml
- common/src/types/offline_phase.rs
- state/src/applicator/mod.rs
- state/src/applicator/return_type.rs
- state/src/interface/mod.rs
- state/src/interface/node_metadata.rs
- state/src/interface/notifications.rs
- state/src/lib.rs
- state/src/replication/raft_node.rs
- state/src/storage/db.rs
- state/src/storage/tx/mod.rs
- state/src/storage/tx/mpc_preprocessing.rs
- workers/task-driver/src/tasks/create_new_wallet.rs
This PR defines storage primitives for access to the MPC preprocessing phase. Currently we only have a method for appending in setters, the pop case is more complicated as this requires the applicator to _return_ values from the preprocessing functionality.
- Tested a set, append, get sequence
> state: storage: mpc-preprocessing: Define storage primitives

- common/src/types/mpc_preprocessing.rs
- state/src/applicator/mod.rs
- state/src/applicator/mpc_preprocessing.rs
- state/src/interface/mpc_preprocessing.rs
- state/src/storage/tx/mpc_preprocessing.rs
This PR implements the state transition logic for consuming and appending MPC preprocessing values to the preprocessing store for a given cluster pair. 
- Tested the applicator methods as well as through raft consensus
> state: applicator: mpc-preprocessing: Implement state transitions

- common/src/types/wallet/mod.rs
- common/src/types/wallet/order_metadata.rs
- state/src/lib.rs
- state/src/storage/tx/mod.rs
- state/src/storage/tx/order_metadata.rs
This PR sets up storage primitives for order metadata and order history. For each wallet, we store a list of historical orders with states. This store is denormalized from the wallet store.
> state: storage: order-metadata: Setup order metadata storage primitive

- external-api/src/bus_message.rs
- state/src/applicator/error.rs
- state/src/applicator/mod.rs
- state/src/applicator/order_book.rs
- state/src/applicator/order_metadata.rs
- state/src/applicator/task_queue.rs
- state/src/applicator/wallet_index.rs
- state/src/interface/mod.rs
- state/src/interface/order_metadata.rs
- state/src/lib.rs
- state/src/storage/db.rs
- state/src/storage/tx/node_metadata.rs
- state/src/storage/tx/order_metadata.rs
- workers/api-server/src/websocket/price_report.rs
- workers/api-server/src/websocket/task.rs
- workers/api-server/src/websocket/wallet.rs
- workers/price-reporter/src/manager.rs
- workers/task-driver/src/tasks/update_wallet.rs
This PR adds order metadata update methods to the `state` module. These allow orders in a wallet's order history to have their state updated.
- When a wallet is updated, modify its order history. We isolate these changes to the `state` module to avoid floating the wallet / wallet history denormalization up to the interface
> state: applicator, interface: Add order history state transitions

- common/src/types/wallet/order_metadata.rs
- common/src/types/wallet/orders.rs
- state/src/applicator/order_metadata.rs
- state/src/applicator/wallet_index.rs
- state/src/interface/order_metadata.rs
- state/src/interface/wallet_index.rs
This PR updates order history for new and cancelled orders in the wallet update handlers. We modify order history here to hide the wallet index / order history denormalization from the interface. That is, when a wallet is updated, the order history is brought to a consistent state without the caller having to separately update order history.
- Tested order history via wallet update interface
> state: applicator: wallet-index: Update order history on wallet update

- common/src/types/tasks.rs
- state/src/applicator/order_book.rs
- state/src/applicator/order_metadata.rs
- state/src/applicator/wallet_index.rs
- workers/handshake-manager/src/manager/internal_engine.rs
- workers/task-driver/integration/tests/settle_match.rs
- workers/task-driver/src/helpers.rs
- workers/task-driver/src/tasks/settle_match.rs
- workers/task-driver/src/tasks/settle_match_internal.rs
This PR adds miscellaneous order state transition logic for transitioning into `SubmittingMatch` and `Filled` states in particular. As well, when a validity proof for an order comes in, we transition to `Matching`.
- Will test state transitions ad hoc when the API is in place (next pr)
> state, task-driver: Add misc order state transitions

- external-api/src/http/wallet.rs
- state/src/interface/order_metadata.rs
- workers/api-server/src/error.rs
- workers/api-server/src/http.rs
- workers/api-server/src/http/network.rs
- workers/api-server/src/http/order_book.rs
- workers/api-server/src/http/price_report.rs
- workers/api-server/src/http/task.rs
- workers/api-server/src/http/wallet.rs
- workers/api-server/src/router.rs
This PR adds an HTTP route for querying order history on a wallet. I also added URL query parameters to the handler signature to allow for urls like `/wallet/:id/order-history?order_history_len=10` rather than forcing a client to send a body in a `GET`.
- Tested locally
> workers: api-server: wallet: Add order history route + handler

- workers/api-server/src/websocket.rs
- workers/api-server/src/websocket/order_status.rs
This PR adds an order status websocket handler. This handler listens to updates on the order history topic for a wallet and forwards them to the client.
- Unit tests pass crate wide
- Tested the websocket topic with a local relayer running on my machine
> workers: api-server: websocket: Add order status websocket handler

- .github/workflows/upgrade.yml
- bin/release.zsh
- docker/sequencer/deploy_contracts.sh
This PR ensures that the `upgrade` Github Action supports the new `dev` environment appropriately, and has the sequencer deploy the full suite of testing ERC20s first, so that their addresses are consistent regardless of changes in the Renegade contracts.
> github, docker: sequencer: support dev env & deploy erc20s first

- Cargo.lock
- arbitrum-client/Cargo.toml
- arbitrum-client/src/abi.rs
- arbitrum-client/src/client/event_indexing.rs
- workers/chain-events/src/listener.rs
This PR uses the new event paradigm from the contracts, querying a single transaction to reconstruct a commitment's Merkle opening. This gives a constant time `FindingOpening` step for tasks.
I also removed the Merkle update listener from the `chain-events` worker instead of fixing the downstream errors -- it's not very useful at the moment.
- Test on staging cluster
> arbitrum-client: event-indexing: Query single tx for Merkle path

- workers/api-server/src/http/wallet.rs
- workers/task-driver/src/helpers.rs
- workers/task-driver/src/tasks/settle_match.rs
- workers/task-driver/src/tasks/settle_match_internal.rs
This PR moves fee payment out of the match-settle flow. Instead, fee payment is done when a user withdraws. This removes the period after a match in which a wallet is ineligible for another match.
- Tested against a local relayer
> workers: task-driver, api-server: Settle fees only on withdrawal

- state/src/applicator/task_queue.rs
- workers/task-driver/src/driver.rs
This PR adjusts the conditions under which we execute the internal matching engine after popping a task, adding the clause that the engine should only be run by the executor of the last task. This is currently the most straightforward way to ensure that the engine is only run on one node.
Additionally, this PR removes the `expect`ation of successful task queue pausing when running a preemptive task, as this can error healthily in cases such as attempting to preempt a committed task, or pause an already-paused queue.
The combination of these two changes should remediate the issue we were seeing in `dev` where nodes would panic after a match was found.
> state: applicator: only run matching engine on executor of last task

- Cargo.lock
- workers/api-server/Cargo.toml
- workers/task-driver/src/lib.rs
- workers/task-driver/src/simulation/error.rs
- workers/task-driver/src/simulation/mod.rs
- workers/task-driver/src/simulation/wallet_tasks.rs
This PR implements logic to simulate wallet updates by tasks enqueued on a wallet. This will be used for two purposes:
1. To expose an api endpoint that (at a high level) gets the "back of queue" wallet. I.e. the wallet after all currently queued tasks complete. This will allow clients to correctly sign wallet updates when multiple updates are enqueued
2. To allow the API layer to validate task definitions when enqueuing them behind existing tasks
Testing is deferred to live testing once the API for this feature is in place.
- Unit tests pass crate wide
> workers: task-driver: Implement task simulation

- Cargo.lock
- common/src/types/tasks.rs
- state/src/applicator/mod.rs
- state/src/applicator/task_queue.rs
- state/src/interface/task_queue.rs
- state/src/lib.rs
- state/src/storage/tx/mod.rs
- state/src/storage/tx/task_queue.rs
- workers/api-server/Cargo.toml
- workers/task-driver/src/driver.rs
- workers/task-driver/src/lib.rs
- workers/task-driver/src/simulation/error.rs
- workers/task-driver/src/simulation/mod.rs
- workers/task-driver/src/simulation/wallet_tasks.rs
This PR adds preemptive tasks to the queue and pops them when the queue is resumed. This will allow:
1. Task history to be made aware of matches on the wallet
2. Task simulation at the API layer to be aware of match updates to a wallet
- Updated task queue unit tests to check for the preemptive task when paused
> state: applicator: task-queue: Add preemptive tasks to queue

- common/src/types/tasks.rs
- external-api/src/http/wallet.rs
- state/src/interface/wallet_index.rs
- workers/api-server/src/http.rs
- workers/api-server/src/http/wallet.rs
- workers/task-driver/src/tasks/update_wallet.rs
This PR adds an endpoint to query the "back of queue" wallet: that is, the wallet after all queued tasks have been speculatively applied to it. This allows clients to sign multiple queued state transitions by having the relayer simulate their in-flight state transitions.
We use this functionality to construct `UpdateWalletTaskDescriptor` types so that the API layer correctly constructs the  updated wallet from the back of queue.
I also fixed a bug that results from being able to enqueue multiple tasks: the `UpdateWalletTask` needs to fetch the most recent version of the `old_wallet` in its constructor to -- in particular -- update to the most recent Merkle path.
- Implemented the client logic in the CLI and tested there. Queued up multiple tasks of all kinds and verified …
> workers: api-server: Add `/v0/wallet/:id/back_of_queue` endpoint

- workers/gossip-server/src/peer_discovery/heartbeat.rs
- workers/job-types/src/network_manager.rs
- workers/network-manager/src/manager/control_directives.rs
This PR creates a new control signal for the network manager responsible for signaling the removal of a peer from the Kademlia DHT, and issues this control signal whenever a peer is expired.
Without this, a cluster will continue trying to dial expired peers (e.g. after a cluster upgrade), which is a safe failure but still wastes bandwidth.
> workers: network-manager: remove expired peers from KDHT

- common/src/types/wallet/balances.rs
- external-api/src/http/wallet.rs
- workers/api-server/src/http.rs
- workers/api-server/src/http/wallet.rs
This PR separates out fee payment from the withdrawal API. Given the new `/wallet/:id/back-of-queue` endpoint; clients can hit `/wallet/:id/pay-fees` then `/wallet/:id/balances/:mint/withdraw` to withdraw a balance. This avoids the need for a client to compute the withdrawal wallet state _after_ fee payment happens.
- Tested locally
> api-server: http: wallet: Add fee payment API

- workers/price-reporter/src/exchange/coinbase.rs
This PR tweaks the CB connection to not report prices when it is missing a bid / offer, e.g. if we stream a price right after the connection is established. This is likely the reason why we saw half-prices on the FE.
> workers: price-reporter: coinbase: omit unready prices

- common/src/types/tasks.rs
- common/src/types/wallet/order_metadata.rs
- state/src/applicator/mod.rs
- state/src/applicator/order_history.rs
- state/src/applicator/wallet_index.rs
- state/src/interface/mod.rs
- state/src/interface/order_history.rs
- state/src/interface/wallet_index.rs
- state/src/storage/tx/mod.rs
- state/src/storage/tx/order_history.rs
- workers/handshake-manager/src/manager.rs
- workers/task-driver/integration/tests/settle_match.rs
- workers/task-driver/src/helpers.rs
- workers/task-driver/src/tasks/settle_match.rs
- workers/task-driver/src/tasks/settle_match_internal.rs
This PR updates the order history to store the order itself under the `data` field. As well, this PR fixes a bug wherein the settlement logic failed to update the `filled` field on the order metadata.
- @sehyunc will test frontend integration
> state: order-history: Add all order fields to stored history

- common/src/types/tasks/descriptors.rs
- common/src/types/tasks/history.rs
- common/src/types/tasks/mod.rs
- common/src/types/wallet/order_metadata.rs
- state/src/interface/task_queue.rs
- util/src/lib.rs
- workers/api-server/src/auth.rs
- workers/api-server/src/http/wallet.rs
- workers/task-driver/integration/tests/update_wallet.rs
This PR defines new types and type description representations that will enable storing semantically meaningful descriptions of tasks. These types will be stored in a per-wallet task history and querying by the API layer to implement a task history API.
> common: types: task: history: Define task history storage types

- common/src/types/tasks/descriptors.rs
- common/src/types/tasks/history.rs
- state/src/lib.rs
- state/src/storage/db.rs
- state/src/storage/tx/mod.rs
- state/src/storage/tx/task_history.rs
This PR adds db access methods for task history. This closely models the order history with the exception that we need not lookup individual task states or modify them. So the interface is simpler.
I had to remove serde tagging configs from the task history enums, bincode does not implement this type of enum deserialization. We will define separate types at the API layer that re-introduce proper enum serialization. 
> state: storage: task-history: Define storage access methods

- Cargo.lock
- Cargo.toml
- circuit-types/Cargo.toml
- circuits/Cargo.toml
- renegade-crypto/Cargo.toml
- rustc-ice-2024-04-27T23_52_08-98557.txt
- rustc-ice-2024-04-27T23_52_08-98561.txt
This PR pins the version of `serde` used throughout the relayer to `1.0.197`, to ensure it is the same version used by all of the deployed contracts. This doesn't limit current usage of serde functionality and seems to be causing invalid signature errors in the contracts.
> chore: pin serde to 1.0.197 for contracts compatibility

- common/src/types/tasks/history.rs
- state/src/applicator/mod.rs
- state/src/applicator/task_queue.rs
- state/src/interface/task_queue.rs
- state/src/lib.rs
- workers/task-driver/src/driver.rs
- workers/task-driver/src/running_task.rs
This PR handles the state transition logic to update task history; specifically by placing the popped task in the history when the queue is popped. This PR also passes success/failure information into the pop state transition so that the task history may store which tasks were successful vs not.
> state: applicator: task-queue: Append to task history on queue pop

- external-api/Cargo.toml
- external-api/src/types/api_network_info.rs
- external-api/src/types/api_order_book.rs
- external-api/src/types/api_task_history.rs
- external-api/src/types/api_wallet.rs
- external-api/src/types/mod.rs
This PR adds API types for the task history API and destructures the existing types into multiple files. We need to replicate these types at the API layer to give proper enum tagging. We cannot used internally tagged enums at the storage layer as `bincode` doesn't support them.
> external-api: types: api-task-history: Add task history API types

- external-api/src/bus_message.rs
- external-api/src/types/api_task_history.rs
- state/src/applicator/mod.rs
- state/src/applicator/task_queue.rs
- state/src/interface/wallet_index.rs
- workers/api-server/src/websocket.rs
- workers/api-server/src/websocket/task.rs
This PR adds a websocket handler for the task history endpoint. This pushes updates about historical tasks as well as active tasks and their state. In this way, this endpoint is a superset of the current task status websocket.
- Tested websockets locally
> api-server: websocket: task: Add task history websocket handler

- arbitrum-client/src/client/mod.rs
- arbitrum-client/src/helpers.rs
- external-api/src/types/api_task_history.rs
- state/src/applicator/task_queue.rs
- workers/task-driver/integration/helpers.rs
This PR updates the `arbitrum-client` to use the `ethers` `NonceManager` middleware. This allows the client to submit multiple concurrent transactions in a nonce-consistent way, rather than relying on a nonce-fetch which may be out of date with respect to a transaction yet to be executed.
- Replicated the out of date nonce bug on a local relayer targeting the staging sequencer. Verified that the bug was fixed after this change
> arbitrum-client: Use `NonceManager` ethers middleware

- workers/price-reporter/src/errors.rs
- workers/price-reporter/src/exchange.rs
- workers/price-reporter/src/exchange/binance.rs
- workers/price-reporter/src/exchange/coinbase.rs
- workers/price-reporter/src/exchange/connection.rs
- workers/price-reporter/src/exchange/kraken.rs
- workers/price-reporter/src/exchange/okx.rs
- workers/price-reporter/src/exchange/uni_v3.rs
- workers/price-reporter/src/manager.rs
This PR adds a new method, `supports_pair`, to the `ExchangeConnection` trait, which we use to check if a given exchange supports a given pair by making the requisite API call for that exchange.
We use this in the `connect` methods of the `ExchangeConnection` implementors to error on connecting to a price stream for a pair that an exchange doesn't support. This change is absorbed by the price reporter, as well, since it invokes the same method.
We also expose a helper method for the external price reporter to use in its own validation logic before trying to `connect`.
We don't use this method for any pre-connection checks in the relayer, since the implementation of price conversion through "default" stables for each exchange (paired with the assumption that quote tokens are stables) lets …
> workers: price-reporter: exchange: per-exchange pair support API calls

- arbitrum-client/src/abi.rs
- arbitrum-client/src/constants.rs
- state/src/storage/tx/order_book.rs
- workers/chain-events/src/listener.rs
This PR explicitly deletes orders after their wallets have been nullified. Keeping these orders around after they've been nullified only results in state bloat. Orders that are still valid will be re-gossiped by their managing cluster anyways.
- Tested submitting and cancelling orders in a wallet. Verified that the `/v0/order_book/orders` route reflected these changes
> state: storage: order-book: Delete orders when nullified

- config/src/lib.rs
- core/src/main.rs
- mock-node/src/lib.rs
- workers/handshake-manager/src/manager.rs
- workers/handshake-manager/src/manager/internal_engine.rs
- workers/handshake-manager/src/worker.rs
This PR adds a configurable `match-mutual-exclusion-list` to the config. This set is passed to the handshake manager which checks whether two wallets are in this list before matching. If they are, the match is skipped. 
We will use this config as a means to various ends: whitelisting, liquidity provisioning, etc.
- Tested the config value on live wallets
> handshake-manager: internal-engine: Add mutual exclusion list

- .github/workflows/upgrade.yml
This PR targets only the `us-east-2` cluster on upgrades seeing as we now run relayers in only `us-east-2`.
> github: workflows: Change relayer cluster to use us-east-2

- workers/price-reporter/src/exchange/coinbase.rs
This PR sets the `Content-Type: application/json` header in the API request to Coinbase when checking for the existence of a pair. Without this Coinbase will consider the request malformed.
> workers: price-reporter: exchange: coinbase: use json content type header

- external-api/src/types/api_task_history.rs
- state/src/applicator/task_queue.rs
- workers/api-server/src/websocket.rs
This PR removes the `handle_connection` traces in the relayer's websocket server and downgrades connection errors to `info`. The `handle_connection` ends up creating many long running traces that have no detailed information. As well, if a client hangs up, we report an error logs which distracts from actual errors in traces.
> api-server: websocket: Do not trace websocket `handle_connection`

- Cargo.lock
- common/src/worker.rs
- core/src/main.rs
- mock-node/src/lib.rs
- state/Cargo.toml
- state/src/applicator/mod.rs
- state/src/applicator/task_queue.rs
- state/src/interface/mod.rs
- state/src/interface/node_metadata.rs
- state/src/interface/order_book.rs
- state/src/lib.rs
- state/src/replication/error.rs
- state/src/replication/mod.rs
- state/src/replication/raft_node.rs
- state/src/replication/worker.rs
- test-helpers/src/lib.rs
- test-helpers/src/mocks.rs
- workers/task-driver/integration/main.rs
This PR implements the `Worker` trait for the `ReplicationNode` so that it can gracefully handle failures on the Raft thread. We already find ourselves needing to implement this and the most sensible approach is to hook into the worker management patterns that are already present.
All the unit tests pass, and I also tested locally that the node appropriately shuts down when the Raft thread panics (which we see occasionally in `dev`).
> state: replication: create `Worker` for Raft replication node

- Cargo.lock
- workers/price-reporter/src/exchange/coinbase.rs
This PR adds the `User-Agent` header to Coinbase requests. Despite testing the changes in the last relevant PR locally and seeing the pair validation request succeed, it was once again failing in the deployed environments, and failed locally when I tested again (status 400). Although not explicitly documented anywhere in the Coinbase API docs, setting the `User-Agent` header has the price reporter working for me locally.
> workers: price-reporter: add user-agent header to cb reqs

- docker/release/Dockerfile
- docker/release/bootloader.sh
This PR adds a basic "bootloader" script to the Docker image which fetches the node's config file from S3, and fills it in with values set via environment variables.
> docker: release: add bootloader script

- state/src/applicator/task_queue.rs
This PR fixes a bug wherein the matching engine is not run after a wallet's task queue is unpaused; i.e. after a match settles. This prevents recursive matches from being settled even when available. 
- Tested a recursive match with two wallets created on a local relayer
> state: applicator: task-queue: Run matching engine after resuming queue

- workers/task-driver/src/simulation/wallet_tasks.rs
This PR adds a wallet reblind step to the offline fee task simulation, this ensures that any back-of-queue fetches when these tasks are in the queue serve properly reblinded public shares.
> workers: task-driver: simulation: reblind wallet in offline fee sim

- Cargo.lock
- state/Cargo.toml
- state/src/lib.rs
- state/src/replication/log_store.rs
- state/src/replicationv2/error.rs
- state/src/replicationv2/log_store.rs
- state/src/replicationv2/mod.rs
- state/src/storage/tx/raft_log.rs
This PR initializes the `replicationv2` module and implements the shim interface between the consensus engine and the log store (mdbx). Testing is deferred until the `openraft::StateMachine` implementation is in place; at which point we can use the `openraft` test suite.
Other CI may fail in the meantime, will clean this up at the end.
Some code is marked as to be deleted, after the consensus engine swap is complete.
> state: replicationv2: Initialize module

- state/src/applicator/mod.rs
- state/src/replicationv2/error.rs
- state/src/replicationv2/log_store.rs
- state/src/replicationv2/mod.rs
- state/src/replicationv2/state_machine.rs
- state/src/storage/cursor.rs
- state/src/storage/error.rs
- state/src/storage/tx/mod.rs
- state/src/storage/tx/raft_log.rs
This PR implements the `RaftStateMachine` trait for the new consensus engine. Additionally this PR fixes a few bugs with storage that were discovered while integrating.
Not all tests pass, snapshotting needs to be implemented before the `openraft` suite passes
- Non-state tests pass
> state: replicationv2: state-machine: Implement state machine

- docker/release/bootloader.sh
This PR adds an optional `PUBLIC_IP` env var that can be used by the bootloader script to fill in a public IP to the config file. This is currently used only by the bootstrap nodes.
> docker: release: add optional public IP to bootloader script

- Cargo.lock
- state/Cargo.toml
- state/src/applicator/mod.rs
- state/src/replicationv2/error.rs
- state/src/replicationv2/mod.rs
- state/src/replicationv2/snapshot.rs
- state/src/replicationv2/state_machine.rs
- state/src/storage/db.rs
This PR implements the procedure for snapshotting relayer state. This proceeds as follows:
1. A read tx is initiated to read-lock the DB
2. The DB's data file is copied to the snapshot location
3. gzip the data file 
- Support excluding tables from the snapshot
- Tested snapshot and recovery
> state: replicationv2: snapshot: Implement snapshot procedure

- state/src/replicationv2/snapshot.rs
- state/src/storage/db.rs
- state/src/storage/tx/mod.rs
This PR adds support for excluding tables from the snapshot. We will use this to exclude raft logs, peer index, local node metadata, and any other tables that don't need to be snapshotted as we decide.
- Tested snapshotting with excluded tables
- Tested snapshot overwriting
> state: replicationv2: snapshot: Implement table exclusion for snapshots

- common/src/types/tasks/descriptors.rs
- workers/task-driver/src/driver.rs
- workers/task-driver/src/tasks/update_wallet.rs
This PR adds a check in the creation of an `UpdateWalletTask` which ensures that the new wallet is "one reblind on top of" the old wallet. It also tweaks the error handling of spawning tasks to notify listeners if creating a task fails (not just running it).
I tested this by running a local relayer and asserting that a valid deposit passes this check, and that a doubly-reblinded deposit does not.
> workers: task-driver: tasks: update_wallet: check reblind progression

- state/src/interface/mod.rs
- state/src/lib.rs
- state/src/replication/log_store.rs
- state/src/replicationv2/error.rs
- state/src/replicationv2/snapshot.rs
- state/src/replicationv2/state_machine.rs
- state/src/storage/db.rs
- state/src/storage/tx/mod.rs
- state/src/storage/tx/raft_log.rs
This PR implements the logic to update a `StateMachine` from a snapshot that has finished being received. We do so by opening a cursor on each table and copying out of the cursor exhaustively.
I also restructured some of how DB tables are allocated to make the table index more explicit and centrally defined. 
- Tested DB copy operation and snapshot application
- Unit tests pass generally
- Deferring passing the `openraft` suite to a follow-up
> state: replicationv2: snapshot: Apply snapshot to state machine

- common/src/types/token.rs
This PR renames USDC -> USD for Coinbase. This is not necessary for streaming prices, as the markets are directly aliased in the Advanced Trade API, but this is necessary for validating pairs, which uses a different Coinbase API. This API will, for example, 404 for the LDO-USDC market, but will have a success response for the LDO-USD market. So it's simpler to just always use USD.
Importantly, we don't set this as the default stable for Coinbase, since that incurs logic that assumes there is a USD-USDC market for price conversion, which there is not. A renaming is more apt.
This is working as expected in dev
> common: types: token: rename USDC->USD for coinbase

- state/src/replicationv2/log_store.rs
- state/src/replicationv2/mod.rs
- state/src/replicationv2/network/mock.rs
- state/src/replicationv2/network/mod.rs
This PR adds an implementation of a mock local network and defines the initial tests for the new consensus engine.
- Connect network to gossip layer
> state: replicationv2: Implement mock network and initial raft tests

- state/src/replicationv2/error.rs
- state/src/replicationv2/mod.rs
- state/src/replicationv2/network/mock.rs
- state/src/replicationv2/network/mod.rs
- state/src/replicationv2/raft.rs
This PR sets up the raft client interface that the high level state will interact with. This interface will handle a number of tasks beyond what the raft exposes directly, namely:
- Forwarding proposals to the leader
- Returning handles so that clients can fire and forget, then later await a proposal
- Learner promotion
- Updated the mock network to use the `RaftClient` and the tests to go through the client
> state: replicationv2: raft: Add `RaftClient` initial interface

- Cargo.lock
- Cargo.toml
- arbitrum-client/Cargo.toml
- circuit-types/Cargo.toml
- circuits/Cargo.toml
- common/Cargo.toml
- core/Cargo.toml
- renegade-crypto/Cargo.toml
- state/Cargo.toml
- util/Cargo.toml
- workers/chain-events/Cargo.toml
- workers/handshake-manager-tests/Cargo.toml
- workers/handshake-manager/Cargo.toml
- workers/job-types/Cargo.toml
- workers/price-reporter/Cargo.toml
- workers/proof-manager/Cargo.toml
- workers/proof-manager/src/proof_manager.rs
- workers/proof-manager/src/worker.rs
- workers/task-driver/Cargo.toml
This PR makes the following changes to the proof manager:
1. Name all threads (why not)
2. Increase the thread stack size to 10MB (default is 2MB)
3. Preprocess all the circuit keys & layouts when the proof manager starts up
Empirically (when testing on an EC2 instance w/ a dev build) this no longer triggers the stack overflows we were seeing in the dev environment, which seemed to be coming from the proof manager, typically when generating the preprocessed circuit keys.
The way the orderbots/quoters all hit the relayer at ~the same time, it's possible there was redundant work being done in generating the keys - this wouldn't directly explain the stack overflow, but regardless it is helpful to have this be done at startup.
We are no longer seeing stack overflows in dev.
> workers: proof-manager: worker: increase stack size & frontload circuit preprocessing

- state/src/replicationv2/error.rs
- state/src/replicationv2/mod.rs
- state/src/replicationv2/network/mock.rs
- state/src/replicationv2/raft.rs
This PR supports node membership updates in the raft client interface and adds tests for joining and leaving clusters, scaling up and down.
- Proposal waiters
- Connection to gossip network
- Connect raft client to state interface
> state: replicationv2: raft: Node join and leave

- state/src/applicator/task_queue.rs
- state/src/storage/tx/mod.rs
- state/src/storage/tx/task_queue.rs
This PR has the task queue get cleared whenever a task fails. This is because it's likely that any subsequent tasks will fail, too. Concretely, only wallet update tasks are certain to fail, but the simplest approach is to clear the entire queue. We ensure that cleared tasks are still recorded in the task history in a "failed" state.
All unit tests pass, and I tested this locally by modifying wallet update tasks to fail trivially, enqueuing a number of them, and ensuring that none others executed after the first failed.
Empirically, order bots & quoters in dev do not seem to be struggling with queue lengths.
> state: storage, applicator: implement task queue clearing

- config/src/lib.rs
- state/src/applicator/mod.rs
- state/src/applicator/order_history.rs
- state/src/interface/mod.rs
- state/src/interface/node_metadata.rs
- state/src/lib.rs
- state/src/notifications.rs
- state/src/replicationv2/mod.rs
- state/src/replicationv2/network/mod.rs
- state/src/replicationv2/raft.rs
This PR sets up the connection between the state interface and the raft client. This involves spawning a raft inside the state constructor and tying together the notifications queue, dbs, state machine, etc.
We no longer run the raft as a separate worker, this is handled by `openraft`
- Tested some basic state transitions through the interface
> state: interface: Connect state interface to raft client

- state/src/interface/error.rs
- state/src/interface/mod.rs
- state/src/interface/mpc_preprocessing.rs
- state/src/interface/node_metadata.rs
- state/src/interface/order_book.rs
- state/src/interface/order_history.rs
- state/src/interface/peer_index.rs
- state/src/interface/task_queue.rs
- state/src/interface/wallet_index.rs
- state/src/lib.rs
This PR changes the interface of the state to use async methods all around. Callers of the state interface are all async, so we wish to avoid blocking their worker threads unnecessarily -- as mdbx may do.
Instead, we spawn all state access methods on blocking tasks that manage a read or write transaction, and await this blocking task's completion. 
- All unit tests pass for the state library
> state: interface: Use async state interface

- workers/network-manager/src/error.rs
- workers/network-manager/src/executor.rs
- workers/network-manager/src/executor/behavior.rs
- workers/network-manager/src/executor/control_directives.rs
- workers/network-manager/src/executor/identify.rs
- workers/network-manager/src/executor/pubsub.rs
- workers/network-manager/src/executor/request_response.rs
- workers/network-manager/src/lib.rs
- workers/network-manager/src/worker.rs
We spawn network manager tasks on a tokio runtime instead of using a single thread. This is complicated by `Swarm` not implementing `Sync`, so we broker access to the `Swarm` via a `behavior_rx` queue. This queue is drained and its events handled on the main thread to obviate synchronization on the `Swarm`.
This is done ahead of the raft request/response integration to avoid processing raft messages (or otherwise awaiting their processing) on the main thread.
- Deferred until the relayer builds
> workers: network-manager: Multithread task handlers

- state/src/interface/error.rs
- state/src/interface/mod.rs
- state/src/interface/raft.rs
- state/src/replicationv2/error.rs
- state/src/replicationv2/network/gossip.rs
- state/src/replicationv2/network/mod.rs
- state/src/replicationv2/raft.rs
- workers/network-manager/src/executor.rs
- workers/network-manager/src/executor/behavior.rs
- workers/network-manager/src/executor/control_directives.rs
- workers/network-manager/src/executor/request_response.rs
- workers/network-manager/src/lib.rs
- workers/network-manager/src/waiters.rs
This PR adds the notion of waiters to the network manager; allowing requesting workers to await gossip responses from peers. We use this in the raft networking implementation to directly await an asynchronous response from a peer. 
- Deferred until workspace builds
> workers: network-manager: Respond to waiting workers on gossip response

- Cargo.lock
- common/Cargo.toml
- common/src/types/tasks/descriptors.rs
This PR fixes the `verify_wallet_update_signature` method to use the same exact serialization of the wallet commitment as the contracts do. While the previous `BigUint::to_bytes_be` _seemed_ correct, it would exclude leading zero bytes from the serialization, whereas in the contracts, we serialize to exactly 32 bytes, including leading zeros.
Since the JS SDK also generates signatures with the faulty serialization, the relayer would verify those signatures, while the contracts would not.
> common: types: descriptors: proper commitment serialization in signature check

- workers/proof-manager/src/proof_manager.rs
- workers/proof-manager/src/worker.rs
This PR tunes the proof manager worker to:
1. Infer the number of threads to spawn automatically, which [defaults to the number of logical CPUs](https://docs.rs/rayon/latest/rayon/struct.ThreadPoolBuilder.html#method.num_threads)
2. Spawn tasks in FIFO order - by default, tasks are [generally executed in LIFO order](https://docs.rs/rayon/latest/rayon/fn.spawn.html) to optimize for cache locality on the executing thread, but in our case it's a much fairer queueing mechanism to process proof tasks in the order they were enqueued
This is running smoothly in dev
> workers: proof-manager: infer num threads & spawn fifo

- state/src/interface/mod.rs
- state/src/interface/mpc_preprocessing.rs
- state/src/interface/node_metadata.rs
- state/src/interface/order_book.rs
- state/src/interface/order_history.rs
- state/src/interface/peer_index.rs
- state/src/interface/raft.rs
- state/src/interface/task_queue.rs
- state/src/interface/wallet_index.rs
- state/src/lib.rs
- state/src/replicationv2/mod.rs
- state/src/replicationv2/network/gossip.rs
- state/src/replicationv2/network/mock.rs
- state/src/replicationv2/network/mod.rs
- state/src/replicationv2/raft.rs
This PR changes the raft networking implementations to use trait objects internally. This is key to avoiding generics that color all encapsulating interfaces, including those beyond the `state` crate. This change also vastly simplifies the mocking and testing approach in the integration tests of other crates.
The performance implications should be minimal -- certainly dwarfed by the I/O bound nature of these traits' implementation. 
> state: replicationv2: network: Dynamically dispatch all network impls

- workers/gossip-server/src/peer_discovery/heartbeat.rs
This PR bumps the intra-cluster heartbeat timeout to 10s. This is because there's little benefit to having the intra-cluster timeout be shorter than the raft election timeout, we will always expire a leader before the election timeout runs down. Making it 10s lines these two timeouts up, and also gives us a tolerance of 3 missed heartbeats (at an interval of 3s) before a peer is expired.
> workers: gossip-server: heartbeat: bump intra-cluster heartbeat timeout

- common/src/types/tasks/descriptors/node_startup.rs
- config/src/lib.rs
- core/src/main.rs
- core/src/setup.rs
- state/src/interface/mod.rs
- state/src/interface/peer_index.rs
- state/src/interface/raft.rs
- state/src/replicationv2/mod.rs
- state/src/replicationv2/raft.rs
- workers/gossip-server/src/server.rs
- workers/task-driver/src/running_task.rs
- workers/task-driver/src/tasks/node_startup.rs
- workers/task-driver/src/traits.rs
This PR implements the process by which a new raft is initialized if none is detected during gossip warmup. The node startup task waits for a configurable timeout to elapse before checking whether it has been added to an initialized (non-empty voters) raft cluster. If not, it will initialize a new raft cluster with the peer ids it knows to be in its cluster.
- When joining an existing cluster, a node must:
- Request a snapshot and begin catchup
- Request promotion to a voter when it has replicated all logs
- Unit tests pass crate wide
- Tested consistency after wallet updates between raft nodes given the following conditions:
- Node 1 starts up, completes gossip warmup and initializes a new cluster. Node 2 starts up and learns about this raft after it is intialized.
- Node 1 starts up; …
> task-driver: node-startup: Create new raft cluster after gossip warmup

- common/src/types/tasks/descriptors/node_startup.rs
- config/src/lib.rs
- core/src/main.rs
- core/src/setup.rs
- mock-node/src/lib.rs
- state/src/interface/mod.rs
- state/src/interface/node_metadata.rs
- workers/task-driver/Cargo.toml
- workers/task-driver/integration/helpers.rs
- workers/task-driver/integration/main.rs
- workers/task-driver/src/driver.rs
- workers/task-driver/src/tasks/node_startup.rs
- workers/task-driver/src/traits.rs
- workers/task-driver/src/worker.rs
This PR adds protocol fee & relayer wallet lookup to the node startup task. If, after gossip warmup, a node has discovered no existing raft, it will create a new raft and lookup/create a relayer wallet. If instead the node has found an existing raft, it will do no lookup and instead learn about the relayer wallet through the replication subsystem.
- Test snapshotting
- Await promotion when joining a new cluster
- Unit test pass
- Tested a two node cluster; both cases in which the first node online can find a wallet on-chain and when a new wallet must be created. Verified that both nodes had the wallet after the setup was finished
> task-driver: node-startup: Lookup relayer wallet if first node online

- common/src/types/tasks/descriptors/mod.rs
- state/src/replicationv2/raft.rs
- workers/task-driver/src/driver.rs
This PR removes the call to `queue_key` in the `start_task` trace - for matches, this would cause the task driver to panic as `queue_key` is unimplemented for `SettleMatchInternal` and `SettleMatch`. Instead, we define a new method on the `TaskDescriptor`, `affected_wallets`, which returns the IDs of the wallets implicated in the given task. This is used to set the `wallet_ids` field on the trace.
Additionally, this PR tweaks the `try_promote_learners` method to not `unwrap` the call to `promote_learner`. In dev, we've seen this cause panics due to `the cluster is already undergoing a configuration change` errors
> workers: task-driver: replace queue_key() in trace field

- state/src/applicator/mod.rs
- state/src/applicator/mpc_preprocessing.rs
- state/src/applicator/order_book.rs
- state/src/applicator/order_history.rs
- state/src/applicator/return_type.rs
- state/src/applicator/task_queue.rs
- state/src/applicator/wallet_index.rs
- state/src/replicationv2/state_machine.rs
This PR enables the state machine to gracefully handle expected failures, dubbed "rejections", of proposal applications. This is achieved by adding the `ApplicationRejected` variant to the `ApplicatorReturnType`, which is returned by the applicator in a few choice scenarios.
Currently, we only return a rejection in the following cases:
1. Attempting to pop a task when the queue is paused
2. Attempting to transition a task when the queue is paused
3. Attempting to preempt a task queue when some task on it has already committed
4. Attempting to preempt a task queue when it is already paused
I have tested this locally by running a relayer in which the `append_task` state transition returns an `Ok(ApplicatorReturnType::ApplicationRejected(..))`, and one in which it returns an `Err(..)`, and …
> state: applicator: handle expected application failures

- config/src/lib.rs
- state/src/replicationv2/snapshot.rs
- state/src/replicationv2/state_machine.rs
- state/src/storage/cursor.rs
- state/src/storage/tx/mod.rs
This PR fixes a few bugs with snapshotting, namely:
1. Snapshot directory is not created by 
2. Early close on the snapshot file by the underlying `openraft` implementation. We just re-open the file in out `install_snapshot` implementation.
3. Improper double deserialization of CoW buffers
- Tested a raft wherein the first node comes online and processes state transitions long enough to snapshot. Brought up a second node and verified through the API that the state was the same
> state: replicationv2: snapshot: Fix misc bugs with snapshots

- arbitrum-client/src/client/mod.rs
- arbitrum-client/src/constants.rs
- core/src/main.rs
This PR reduces the polling interval of the ethers provider used in the `arbitrum-client`. The default value is 7s, probably set for use on Ethereum where block times are ~12s (Arbitrum block time is ~260ms). This value is also used as the initial delay to wait before querying the chain for updates.
Tested in the fronted on local relayer, SubmittingTx now takes ~1s compared to ~4-5s before.
> arbitrum-client: Decrease ethers polling interval for quicker tx updates

- .github/workflows/upgrade.yml
- Cargo.lock
- core/Cargo.toml
- docker/release/Dockerfile
- state/src/applicator/task_queue.rs
- util/Cargo.toml
- util/src/lib.rs
- util/src/metered_channels.rs
- workers/job-types/Cargo.toml
- workers/job-types/src/gossip_server.rs
- workers/job-types/src/handshake_manager.rs
- workers/job-types/src/network_manager.rs
- workers/job-types/src/price_reporter.rs
- workers/job-types/src/proof_manager.rs
- workers/job-types/src/task_driver.rs
- workers/task-driver/integration/main.rs
This PR introduces the `MeteredTokioReceiver` and `MeteredCrossbeamReceiver` wrapper types, which augment the underlying channel primitives by recording message queue lengths every time a message is pulled from the queue. This is guarded behind a compiler flag to remove the queueing overhead when necessary.
I tested this by running a relayer locally w/ a local Datadog agent and ensuring that metrics show up in Datadog.
> util: metered_channels: create metered receivers for worker queues

- common/src/worker.rs
- core/src/main.rs
- mock-node/src/lib.rs
- state/src/interface/mod.rs
- state/src/lib.rs
- state/src/replicationv2/raft.rs
This PR adds a timer event to the `SystemClock` to periodically check for raft core panicks. The core does not expose a direct way of measuring or awaiting this, so we attempt to read the server state of the raft. If it has panicked, this will return with a `Fatal` error.
- Simulated a panic in the state machine as we've seen in `dev`, node shut down
> state: replicationv2: raft: Periodically check raft core for panicks

- config/src/lib.rs
This PR changes the default relayer fee from 20 bps to 8 bps
> config: Change relayer fee to default 8 bps

- arbitrum-client/integration/main.rs
- state/src/applicator/wallet_index.rs
- state/src/interface/order_book.rs
- state/src/storage/tx/order_book.rs
- workers/job-types/src/price_reporter.rs
- workers/task-driver/integration/main.rs
This PR fixes a bug with order indexing wherein the nullifier set is incorrectly updated. Previously we were updating order info before removing an order from its old nullifier set. This causes the nullifier update to instead remove the order from the _current_ set, then immediately add it back. Further, this prevents the order from being removed from its _old_ nullifier set. This caused spurious nullification of valid orders in `dev`
I moved the calls to update the nullifier set to the `write_order` method to avoid leaking these ordering details across the storage interface.
- Replicated the spurious nullification "Order not found" bug locally
- Verified that the fix does prevent this case
> state: storage: order-book: Update nullifier set before order info

- workers/task-driver/src/helpers.rs
This PR changes the criterion for a balance being overwritten from `mint == 0` to `balance.is_zerod()`. The `Balance::is_zerod` method is explicitly: `balance.amount == 0 && balance.protocol_fee_balance == 0 && balance.relayer_fee_balance == 0`. Effectively, this PR allows balances to be overwritten by augmentations if only the mint is non-zero. This is already explicitly allowed in the circuits.
- @sehyunc will test integration with a bug he's seeing
> workers: task-driver: helpers: Allow zero'd balances to be overwritten

- core/src/setup.rs
- state/src/applicator/error.rs
- state/src/applicator/mod.rs
- state/src/applicator/return_type.rs
- state/src/applicator/task_queue.rs
- state/src/interface/error.rs
- state/src/interface/task_queue.rs
- state/src/lib.rs
- state/src/replication/state_machine.rs
- workers/task-driver/src/driver.rs
This task fixes a bug in which concurrent matches were allowed to process. This ends up panicking the state machine and thereby the raft as we try to pop a preemptive task twice. The root cause is that two match tasks _both_ attempt to pause the task queue. Only one succeeds, but neither waits for the pause state transition to finish before starting the task.
I changed the driver's implementation to await the preemption proposal before continuing.
While fixing this codepath, I also fixed a few other bugs that have not yet come up but will:
- We now pause/resume task queues in an "all-or-none" fashion. This mitigates a bug in which we succeed to pause one task queue and not another. We will fail the driver's loop and never resume the first wallet's task queue.
- To more easily support the …
> workers: task-driver: driver: Await task queue pause + resume

- workers/gossip-server/src/peer_discovery/heartbeat.rs
- workers/network-manager/src/worker.rs
This PR fixes a bug wherein a peer reports its own multiaddr incorrectly. Specifically, peers must end the multiaddr with their p2p protocol, i.e. `/p2p/{peer_id}`. 
Instead, peers reordered the `QuicV1` and `P2p` protocols, appending `quic-v1`. This causes the DHT layer to incorrect address the nodes by adding an extra `p2p` entry, e.g: `p2p/{peer_id}/quic-v1/p2p/{peer_id}`. This prevented the transport from dialing properly, and ultimately led to spurious peer expiry.
- Ran a multi-node cluster with a few tasks, verified that the peers stopped expiring each other after the fix. Was able to run tasks on the cluster.
> network-manager: properly configure local addr

- state/src/interface/peer_index.rs
- state/src/replication/raft.rs
- workers/gossip-server/src/peer_discovery/heartbeat_timer.rs
- workers/network-manager/src/executor.rs
This PR fixes a few peer remove bugs:
1. A deadlock bug wherein we block on the raft removal within a write tx.
2. A bug wherein concurrent removal proposals result in errors that prevent the raft from making progress.
- Tested removing a peer from a cluster. More edge cases that need to be covered in follow ups
> state: raft: Fix peer removal bugs

- circuits/Cargo.toml
- circuits/benches/internal_match_settlement.rs
- circuits/src/zk_circuits/valid_match_settle/mod.rs
This PR adds a benchmark for singleprover match settlement; this operation is done by the internal engine.
- Ran the benchmark
> circuits: benches: internal-match-settlement: Add benchmark

- circuits/Cargo.toml
- circuits/benches/internal_match_settlement.rs
- circuits/src/zk_circuits/valid_match_settle/mod.rs
- common/src/types/gossip.rs
- gossip-api/src/pubsub/cluster.rs
- gossip-api/src/pubsub/mod.rs
- gossip-api/src/request_response/heartbeat.rs
- gossip-api/src/request_response/mod.rs
- workers/gossip-server/src/peer_discovery/heartbeat.rs
- workers/gossip-server/src/peer_discovery/peers.rs
- workers/gossip-server/src/server.rs
- workers/job-types/src/gossip_server.rs
- workers/network-manager/src/executor/pubsub.rs
This PR is the first of two that improves the way in which we expire peers. Specifically, we implement a [SWIM](https://www.cs.cornell.edu/projects/Quicksilver/public_pdfs/SWIM.pdf) inspired propose/reject protocol wherein:
1. A node believes another to have failed, by timing out on heartbeats. This node sends a pubsub message to the cluster proposing that the cluster expire the candidate peer.
2. Each recipient of the pubsub message checks their own last known heartbeat, if it is within some tolerance they reject the proposal
3. If no rejections are sent within some time window, the cluster expires the peer
This PR implements the messaging half of that, but not the timeout, rejection, expiry logic.
- Ran a cluster and killed a node, verified that the messages were sent correctly
> workers: gossip-server: Notify cluster peers before expiring

- .github/workflows/upgrade.yml
- Cargo.lock
- core/Cargo.toml
- state/Cargo.toml
- state/src/applicator/task_queue.rs
This PR adds metrics gauging the lengths of tasks queues in the relayer. We do this in the applicator, despite the fact that metrics will be emitted from all nodes in the cluster - this can be easily deduplicated in DataDog. We don't record these metrics in the interface layer (i.e. when proposing state transitions) because we would be unable to accurately capture queue lengths when preemptive tasks are added / queues are cleared due to task failure.
> state: applicator: task_queue: record task queue lengths

- arbitrum-client/Cargo.toml
- arbitrum-client/integration/helpers.rs
- arbitrum-client/integration/main.rs
- arbitrum-client/src/client/contract_interaction.rs
- arbitrum-client/src/client/event_indexing.rs
- arbitrum-client/src/client/mod.rs
- config/src/lib.rs
- core/Cargo.toml
- core/src/main.rs
- core/src/setup.rs
- mock-node/src/lib.rs
- state/src/interface/node_metadata.rs
- workers/chain-events/src/listener.rs
- workers/handshake-manager-tests/src/main.rs
- workers/task-driver/integration/helpers.rs
- workers/task-driver/integration/main.rs
- workers/task-driver/integration/tests/update_wallet.rs
This PR tweaks the `arbitrum_client` to be configured with a list of Arbitrum keypairs, from which it will randomly select one every time a darkpool contract client is needed. This required an extra compiler flag to gate usage of the `rand` crate so that the contracts repo, which import that `arbitrum_client` crate just to make use of their conversion utilities, can still be built to WASM.
The relayer wallet is derived from the first supplied keypair.
I tested this by running a local relayer w/ 2 keys, executing a few `new-wallet` tasks, and asserting that there were transactions submitted from both associated addresses.
> arbitrum-client: use multiple arbitrum keypairs

- gossip-api/src/pubsub/cluster.rs
- gossip-api/src/pubsub/mod.rs
- gossip-api/src/request_response/heartbeat.rs
- gossip-api/src/request_response/mod.rs
- workers/gossip-server/src/peer_discovery/peers.rs
- workers/gossip-server/src/server.rs
This PR sends all expiry rejections through pubsub to ensure that all cluster peers hear about a rejection. This allows us to also safely place a proposed expiry candidate in the candidate state on all nodes that _do not_ reject.
- Tested expiry on a small cluster, including forcing a rejection
> gossip-server: peer-discovery: Send expiry updates through pubsub

- gossip-api/src/pubsub/cluster.rs
- gossip-api/src/pubsub/mod.rs
- gossip-api/src/request_response/heartbeat.rs
- gossip-api/src/request_response/mod.rs
- state/src/interface/peer_index.rs
- workers/gossip-server/src/orderbook.rs
- workers/gossip-server/src/peer_discovery/expiry_window.rs
- workers/gossip-server/src/peer_discovery/heartbeat.rs
- workers/gossip-server/src/peer_discovery/mod.rs
- workers/gossip-server/src/peer_discovery/peers.rs
- workers/gossip-server/src/server.rs
This PR adds a `PeerExpiryWindows` struct that tracks both the expiry candidacy and invisibility windows. These windows are updated through the expiry gossip protocol.
- Move expiry rejection to pubsub and transition peers to expiry candidates locally when not rejecting an expiry proposal
- Tested expiry of a node; verified that it went into the candidate state and waited the appropriate time before expiry.
> workers: gossip-server: Track expiry candidates and invisibility window

- arbitrum-client/integration/helpers.rs
- arbitrum-client/src/client/contract_interaction.rs
- state/src/replication/raft.rs
- workers/task-driver/integration/main.rs
This PR changes the proposal logic for removing a raft leader from the cluster. When doing so the proposing node first campaigns for election, then proposes the removal. This prevents a bug wherein the proposal is forwarded to a raft leader that no longer exists and is lost.
- Expired the leader on a local cluster, verified that the cluster recovered quickly
> state: replication: raft: Campaign before expiring leader

- external-api/src/http/admin.rs
- external-api/src/http/mod.rs
- state/src/interface/raft.rs
- workers/api-server/src/http.rs
- workers/api-server/src/http/admin.rs
This PR initializes the `/admin` api with an `is-leader` endpoint that returns true iff the node is a raft leader. This will be used by the snapshot sidecar to determine if a new snapshot should be written to s3.
> api-server: Add `/v0/admin/is-leader` endpoint

- Cargo.lock
- Cargo.toml
- snapshot-sidecar/Cargo.toml
- snapshot-sidecar/src/main.rs
- workers/proof-manager/Cargo.toml
This PR adds a `snapshot-sidecar` binary to the repo. This util will watch a configured file location and do the following:
1. When a file changes, check the if the local relayer is a raft leader via `/v0/admin/is-leader`
2. If so, upload the file to s3
We will configure this sidecar to run alongside the relayer in our environments and watch the snapshot file.
- Tested locally with both leader and non-leader sidecars
> snapshot-sidecar: Implement sidecar snapshot manager

- config/src/cli.rs
- config/src/parsing.rs
- docker/release/Dockerfile
- docker/release/bootloader.sh
This PR adds the `snapshot-sidecar` to the release build and runs it in the container with the relayer. 
- Ran the relayer dockerfile locally using a dummy config I placed on s3. Turned the snapshot frequency up to once every five logs, then created a new wallet and added an order. Verified that the relayer's snapshot was sent to s3
> docker: release: Run snapshot sidecar in relayer container

- docker/sequencer/deploy_contracts.sh
This PR sets the default fee used in our deploy script to 2 bps for consistency across the codebase
> docker: sequencer: deploy-contracts: Use 2bps fee for consistency

- arbitrum-client/src/helpers.rs
- state/src/interface/mod.rs
- state/src/lib.rs
- state/src/replication/mod.rs
- state/src/replication/raft.rs
- state/src/replication/state_machine/mod.rs
- state/src/replication/state_machine/recovery.rs
- state/src/replication/state_machine/snapshot.rs
- state/src/storage/cursor.rs
- state/src/storage/tx/mod.rs
This PR changes the state machine to check for a snapshot at startup and recover from the snapshot if it is present. This also involves cleanup logic -- which for now is just clearing all task queues so that wallets are not stuck. 
- In the node startup task, check all wallets on-chain for updates since the snapshot was taken
- Tested recovering a node from a snapshot with a wallet in the state, verified that the state held the wallet without any lookup task
> state: replication: state-machine: Recover from snapshot at startup

- common/src/types/wallet/shares.rs
- state/src/interface/mod.rs
- state/src/interface/raft.rs
- state/src/lib.rs
- state/src/replication/state_machine/mod.rs
- state/src/replication/state_machine/recovery.rs
- workers/task-driver/src/tasks/node_startup.rs
This PR refreshes all recovered wallets when recovering from a snapshot. That is, for each wallet found in the snapshot, the relayer will check if the wallet's nullifier has been used. If so, the relayer will run a lookup wallet task to refresh the wallet state from on-chain.
- Setup a wallet in a snapshot. Used another relayer to update the wallet. Ran the original relayer with its snapshot in place and verified that the relayer looked up the most recent version.
> task-driver: node-startup: Refresh wallets if recovering from snap

- state/src/interface/peer_index.rs
- state/src/interface/raft.rs
- state/src/replication/raft.rs
- workers/task-driver/src/tasks/node_startup.rs
This PR aims to stabilize the onboarding of a new Raft node that needs to install a snapshot from the leader. In the case of a large snapshot, it takes significantly longer than the gossip warmup period to download it. As such our current initialization check fails, and we attempt to initialize a new Raft. As such, this PR:
1. Defers the initialization check to `openraft`'s `is_initialized()` method for consistency
2. Increases the snapshot chunk size from a default of `3MiB` -> `10MiB` to speed up snapshot download
3. Increases the learner promotion timeout to 5 minutes to allow more time for snapshot download
This is currently being tested in dev
> state: replication: raft: tweak initialization check & snapshot installation

- state/src/replication/state_machine/mod.rs
- state/src/replication/state_machine/recovery.rs
This PR makes two changes to the recovery logic:
1. Do not fail the node if snapshot recovery fails. This is more generally the desired behavior in the case of an invalid snapshot
2. Do not attempt recovery if the snapshot file length is zero. This may happen if a dummy snapshot was created ahead of time; e.g. in the snapshot sidecar
- Tested creating a dummy snap with the sidecar, verified that the snapshot was skipped
> state: state-machine: recovery: Do not error on empty snapshot

- state/src/replication/raft.rs
This PR increases the timeout that the leader uses when sending snapshot chunks to peers from the default of 200ms to 1s. Previously, the leader would time out every time it tried to send a chunk, so it would get stuck in an endless loop of trying to send the same (first) chunk of the snapshot to a learner.
This can be seen in the chunked snapshot implementation [here](https://github.com/datafuselabs/openraft/blob/v0.9.11/openraft/src/network/snapshot_transport.rs#L201-L204): upon timeout, the implementation continues to the next iteration of the loop [without incrementing the chunk offset](https://github.com/datafuselabs/openraft/blob/v0.9.11/openraft/src/network/snapshot_transport.rs#L217), never to complete.
I tested this by bringing up a relayer node, letting it build up a ~50MB …
> state: replication: raft: increase snapshot rpc timeout

- core/src/main.rs
- mock-node/src/lib.rs
- state/src/interface/task_queue.rs
- workers/handshake-manager/src/manager.rs
- workers/handshake-manager/src/manager/handshake.rs
- workers/handshake-manager/src/manager/internal_engine.rs
- workers/handshake-manager/src/manager/match.rs
- workers/handshake-manager/src/manager/scheduler.rs
- workers/handshake-manager/src/state.rs
- workers/handshake-manager/src/worker.rs
This PR changes the implementation of the internal matching engine to run on the non-blocking Tokio pool. We observed a deadlock in the matching engine when running a relayer under intense load. This deadlock occurs on the blocking Tokio pool when spawning too many internal engine tasks at one; which themselves spawn blocking tasks for DB access. Eventually we exhaust the blocking pool's ability to spawn new tasks or await blocking tasks as these two granularities of blocking tasks get interleaved and exhaust the pool, preventing one another from making progress.
The internal engine is now implemented `async` anyways with the blocking components themselves spawned onto the blocking pool, so it is fine to run the engine `async`. 
I additionally added early exit conditions to the matching …
> workers: handshake-manager: Do not use blocking pool for internal engine

- core/src/setup.rs
- workers/handshake-manager/src/manager.rs
- workers/handshake-manager/src/manager/internal_engine.rs
- workers/job-types/src/task_driver.rs
- workers/task-driver/integration/helpers.rs
- workers/task-driver/src/driver.rs
This PR changes the way in which we notify waiters about the result of a preemptive task. Instead of going through the open notifications set, we directly send a response channel alongside the `RunImmediate` job. The driver responds directly on this channel rather than looking up channels in the open notifications map.
This fixes an issue we have seen wherein the handshake manager registers a notification with the driver for an immediate task, but beats the task's registration, causing an erroneous `"task not found"` error. The handshake manager will then retry matches unnecessarily and possibly create a duplicate match which will need to be cancelled. The net effect of this is wasted work.
- Tested a case in which two matches occur at the same time on the same wallet. Verified that it …
> task-driver: driver: Notify preemptive task senders directly

- Cargo.lock
- state/src/interface/mod.rs
- state/src/replication/raft.rs
- workers/gossip-server/src/peer_discovery/heartbeat.rs
This PR makes some miscellaneous tweaks to the Raft module to aid in stability, particularly around downloading snapshots when joining a cluster. Namely:
1. We increase the snapshot installation RPC timeout to 1 minute, as this must include the time it takes for a node to install/apply a fully downloaded snapshot as its storage layer
2. We increase the Raft heartbeat interval to 3s, as this is also the timeout for any `AppendEntries` RPCs, which can include thousands of entries for a follower to apply
3. We increase the inter-cluster heartbeat timeout to 30s, as empirically we oftentimes see expiries between cluster peers and the bootstrap nodes
4. We include learners when checking if we've already expired a node. Previously, we would always assume we've already expired a learner, …
> state: replication: misc tweaks

- Cargo.lock
- gossip-api/Cargo.toml
- gossip-api/src/request_response/mod.rs
- state/src/interface/raft.rs
- state/src/replication/network/gossip.rs
- state/src/replication/network/mod.rs
- state/src/replication/raft.rs
- util/src/telemetry/mod.rs
- util/src/telemetry/propagation.rs
- workers/gossip-server/src/orderbook.rs
- workers/gossip-server/src/peer_discovery/heartbeat.rs
- workers/gossip-server/src/peer_discovery/peers.rs
- workers/gossip-server/src/server.rs
- workers/handshake-manager/src/manager.rs
- workers/job-types/src/network_manager.rs
- workers/network-manager/src/executor/request_response.rs
This PR adds basic tracing to the network manager and propagates the traces across nodes sending/receiving a message. I added a layer of encapsulation to the `GossipRequest` and `GossipResponse` to permit adding tracing headers to these types. 
- Deployed to dev, verified that I was able to see request/response handlers together in a trace
> gossip-api: trace gossip requests across network

- Cargo.lock
- gossip-api/src/lib.rs
- gossip-api/src/request_response/mod.rs
- state/src/replication/network/gossip.rs
- state/src/replication/network/mod.rs
- workers/network-manager/Cargo.toml
- workers/network-manager/src/executor.rs
- workers/network-manager/src/executor/behavior.rs
- workers/network-manager/src/executor/pubsub.rs
- workers/network-manager/src/executor/request_response.rs
This PR changes the `network-manager` to spawn all authentication tasks on the blocking pool rather than directly calling them. This prevents the async pool from being drained under heavy load with large payloads. 
A follow-up will change the cluster auth mechanism to use a symmetric scheme to further speed up these blocking operations.
- Reproduced a bug wherein `AppendEntries` messages continuously timeout and nodes begin expiring one another. Verified that the node was much more stable after this change. Symmetric auth will further reduce this issue.
> network-manager: Spawn request authentication on blocking thread

- Cargo.lock
- gossip-api/Cargo.toml
- gossip-api/src/lib.rs
This PR changes the serialization backend in gossip HMACs to `bincode` from `serde_json`. This results in approximately a 2x speedup.
- Tested a cluster with this change
> gossip-api: Use `bincode` to serialize requests for hmac

- bin/build_and_push.sh
- bin/deploy.sh
This PR adds two scripts: `build_and_push.sh` and `deploy.sh` to build and push the relayer image and deploy the relayer ECS service on the latest image respectively. These allow us to deploy without going through CI, which can be costly.
- Tested both scripts in `dev`
> bin: Add scripts for manual relayer deployments

- common/src/types/wallet/keychain.rs
- workers/handshake-manager/src/error.rs
- workers/handshake-manager/src/manager/internal_engine.rs
- workers/handshake-manager/src/manager/price_agreement.rs
This PR tweaks the `get_execution_price` method of the internal matching engine to request the order pair's price directly from the price reporter, as opposed to fetching the price vector of default pairs and looking within it for the necessary pair.
This fixes a bug wherein we could not settle matches on orders for pairs outside of the default pair list.
I tested this by running a relayer locally and successfully settling a match on the MKR-USDC pair.
Additionally, I noticed the `sign_commitments` method on the `Wallet` type was still using the wrong serialization of the commitment, so I updated that to serialize in the same way as the contracts. This was covered by my above test, as I used the CLI, which invokes this method to generate a wallet update signature. A commitment whose …
> workers: handshake-manager: internal_engine: use direct pair price

- state/src/applicator/task_queue.rs
- workers/task-driver/src/driver.rs
This PR makes two changes:
1. Do not error on missing tasks. Tasks may end up missing if their queue was cleared by a preemptive task. If this is the case, we should not error as this shuts down the raft, but instead reject the transition as the task is already completed. We saw this happen in a load test
2. Check if a queue is paused before attempting to pause it. This avoids an unnecessary rejection through raft which can be costly.
- Tested conflicting matches, verified that the second change took effect.
> state: applicator: task-queue: Do not error on missing task

- common/src/types/tasks/descriptors/mod.rs
- state/src/applicator/mod.rs
- state/src/applicator/task_queue.rs
- state/src/interface/task_queue.rs
- state/src/lib.rs
- state/src/storage/tx/mod.rs
- state/src/storage/tx/task_assignments.rs
This PR removes the `executor` field on each task in favor of tracking this information in a `task-assignments` table. Doing so will allow us to re-assign tasks when a node goes down in a simpler manner. I.e. by updating this index.
- Unit tests pass; more will come in reassignment PR
- Tested the basic task flows
> state: applicator, storage: Track task executor via `task-assignments` table

- common/src/types/tasks/descriptors/mod.rs
- state/src/applicator/mod.rs
- state/src/applicator/task_queue.rs
- state/src/interface/peer_index.rs
- state/src/interface/task_queue.rs
- state/src/lib.rs
- state/src/storage/tx/mod.rs
- state/src/storage/tx/task_assignments.rs
This PR adds a `ReassignTasks` state transition that is appended to the log when a peer is removed from the cluster. This task reassigns all tasks on a failed node to the log proposer.
- Killed a node while it was executing a task; verified that its task was reassigned and executed.
- Killed a node with a queued (not yet executing task). Verified that the task was dequeued and executed on one of the remaining nodes
> state: applicator: Reassign tasks when cluster peer removed

- state/src/applicator/order_book.rs
This PR changes the `add_order_validity_proof` transition handler to emit a warning and return cleanly in the case that an order is not found. This can happen on a node catching up to the raft that sees a nullifier on-chain and removes the order.
> state: applicator: order-book: Do not error on order not found

- config/src/cli.rs
- state/src/replication/raft.rs
This PR sets the default gossip warmup period to 30s, and sets the max `AppendEntries` payload size to 100.
This will be tested in dev shortly to see if it makes autoscaling more stable
> config: cli, state: replication: raft: tweak payload size & gossip warmup

- common/src/types/gossip.rs
- state/src/interface/peer_index.rs
- state/src/replication/mod.rs
- state/src/replication/state_machine/mod.rs
- state/src/replication/state_machine/snapshot.rs
This PR fixes a few flakey and incorrect unit tests in the `state` crate. Some tests are still somewhat flakey, but they now are all passable.
> state: Fix flakey unit tests

- common/src/types/wallet/balances.rs
- common/src/types/wallet/orders.rs
This PR fixes a bug wherein new wallets or wallets with unused balances would fail to attempt validity proofs on new orders. This was because of an overly-restrictive condition in `get_matchable_orders`
- Tested new wallet flows locally
> common: wallet: balances: Allow empty balances in validity proofs

- arbitrum-client/src/client/contract_interaction.rs
- common/src/types/tasks/descriptors/mod.rs
- common/src/types/tasks/descriptors/refresh_wallet.rs
- common/src/types/wallet/types.rs
- state/src/applicator/task_queue.rs
- workers/api-server/src/http/wallet.rs
- workers/task-driver/src/driver.rs
- workers/task-driver/src/helpers.rs
- workers/task-driver/src/tasks/lookup_wallet.rs
- workers/task-driver/src/tasks/mod.rs
- workers/task-driver/src/tasks/node_startup.rs
- workers/task-driver/src/tasks/redeem_relayer_fee.rs
- workers/task-driver/src/tasks/refresh_wallet.rs
This PR moves the wallet refresh logic to a separate task that better handles edge cases like an already up-to-date wallet. This task will lookup the wallet on-chain much like the `LookupWalletTask` but more directly uses the wallet information already in state.
Clearing the queue via the API causes running tasks to fail. For this reason, I transitioned some errors in the task queue applicator to be warnings or log rejections so as not to panic the raft.
- Tested refreshing a wallet in a variety of cases, and verified that errors were appropriately handled:
- While an `UpdateWallet` is running
- While a `SettleInternalMatch` is running
- While no tasks are running
> task-driver: tasks: refresh-wallet: Implement wallet refresh task

- arbitrum-client/src/client/contract_interaction.rs
- common/src/types/tasks/descriptors/mod.rs
- common/src/types/tasks/descriptors/refresh_wallet.rs
- common/src/types/wallet/types.rs
- external-api/src/http/wallet.rs
- state/src/applicator/mod.rs
- state/src/applicator/task_queue.rs
- state/src/interface/task_queue.rs
- state/src/lib.rs
- workers/api-server/src/http.rs
- workers/api-server/src/http/wallet.rs
- workers/task-driver/src/driver.rs
- workers/task-driver/src/helpers.rs
- workers/task-driver/src/tasks/lookup_wallet.rs
- workers/task-driver/src/tasks/mod.rs
- workers/task-driver/src/tasks/node_startup.rs
- workers/task-driver/src/tasks/redeem_relayer_fee.rs
- workers/task-driver/src/tasks/refresh_wallet.rs
This PR adds an endpoint for refreshing a wallet from on-chain state. This will clear the wallet's task queue and lookup the wallet from chain-state.
In a follow up, I'm going to move this to its own task to cover a few cases that a simple lookup wallet cannot cover alone. More testing to come then
- Tested the basic flow using the endpoint
> state, api-server: add `refresh-wallet` endpoint and initial implementation

- Cargo.lock
- circuit-types/Cargo.toml
- circuit-types/src/fixed_point.rs
- util/src/matching_engine.rs
This PR changes the implementation of `compute_max_amount` in the matching engine to use `FixedPoint` floor division rather than `f64` floor division. This fixes a bug we saw in a deployment wherein the matching engine generates invalid witnesses, which then fail to prove.
- I added a test using an order and balance I saw fail in a load test, verified that `compute_max_amount` returns a valid value now.
> util: matching-engine: Use fixed point floor div when generating amounts

- state/src/lib.rs
- state/src/replication/raft.rs
- workers/task-driver/src/tasks/node_startup.rs
This PR makes a couple tweaks to how we set up & maintain a Raft cluster, namely:
1. In the node startup task, we only transition to setting up a relayer wallet if the local nodes is the elected leader. It is possible for a node to attempt to initialize a Raft if the true leader takes too long to begin sending it logs, but when it succeeds in doing so, the new node should await voter promotion
2. We correctly remove expired learners via the `sync_membership` loop, and we add batched semantics to the `RemovePeers` state transition. We previously would never correctly remove learners.
All state unit tests pass, and I am testing the effect on thrash in dev.
> state: replication, workers: task-driver: node-startup: remove learners separately, only setup wallet if leader

- state/src/lib.rs
- state/src/storage/tx/mod.rs
- state/src/storage/tx/relayer_fees.rs
This PR adds storage helpers for relayer fees. This allows us to set the `match-fee` field (representing the relayer's take rate) on a per-wallet basis. We will use this to implement a `fee-whitelist.json` file in the config, which allows us to set per-wallet fees.
> state: storage: tx: relayer-fees: Add storage methods for relayer fees

- config/src/cli.rs
- config/src/parsing.rs
- state/src/interface/node_metadata.rs
- state/src/replication/state_machine/snapshot.rs
- workers/api-server/src/http/wallet.rs
This PR adds a `--relayer-fee-whitelist` config option which allows the parent process to specify a `.json` file containing whitelist entries like the following:
```json
{
"wallet_id": "id",
"fee": 0.0005,
...
}
```
These values are parsed and stored in state. Upon wallet creation, a fee is looked up (defaulting to the relayer's base fee) and the wallet's `match_fee` field is set using this value.
- Added a wallet to the whitelist and created a new wallet under that ID, verified that it was given the whitelisted fee
- Added a new wallet not in the whitelist, verified that it was given the base fee
> config: Add `relayer-fee-whitelist` option and use whitelisted fees in `new-wallet` creation

- docker/release/Dockerfile
- node-support/bootloader/src/main.rs
This PR adds an additional path to the bootloader wherein we download the fee whitelist file from s3 on startup if it exists and configure the relayer to use this whitelist file.
- Tested with a whitelist file present in the s3 bucket, created a wallet using a whitelisted wallet ID, and verified that it received the whitelisted fee
> node-support: bootloader: Download whitelist from s3 on startup

- common/src/types/tasks/descriptors/pay_fees.rs
- common/src/types/tasks/history.rs
- external-api/src/types/api_task_history.rs
- workers/api-server/src/http/wallet.rs
- workers/task-driver/integration/tests/pay_offline_fee.rs
- workers/task-driver/integration/tests/redeem_relayer_fee.rs
- workers/task-driver/src/simulation/wallet_tasks.rs
- workers/task-driver/src/tasks/pay_offline_fee.rs
This PR adds the `amount`, `mint`, and `is_protocol` fields to the historical fee payment task description. This will allow for these fields to be consumed via the API and displayed on the FE.
- Tested via the API locally
> external-api, common: tasks: Record fee payment mint + amount in history

- workers/api-server/src/router.rs
This PR adds CORS headers to non-200 responses so that the client can read the error message on failed requests.
Tested with local relayer and frontend.
> workers: api-server: Add CORS header on non-200 responses

- common/src/types/wallet/order_metadata.rs
- state/src/applicator/order_history.rs
- state/src/interface/order_history.rs
- state/src/interface/wallet_index.rs
- state/src/storage/tx/order_history.rs
- workers/task-driver/src/tasks/settle_match.rs
- workers/task-driver/src/tasks/settle_match_internal.rs
- workers/task-driver/src/utils/order_states.rs
This PR adds partial fill information to historical orders. Each partial fill contains the amount, price, and timestamp of the partial fill.
- Tested via the CLI with unmatched, incrementally matched, and fully matched orders
> state: storage: order-history: Record partial fills in order history

- common/src/types/wallet/order_metadata.rs
This PR changes the type used to store prices at which partial fills executed from `FixedPoint` to `f64`. This makes for a more interpretable, readable API response; and the partial fills are only used for historical reference.
- Tested the endpoint locally
> common: wallet: order-metadata: Report partial fill price as f64

- Cargo.lock
- arbitrum-client/Cargo.toml
- arbitrum-client/src/constants.rs
- arbitrum-client/src/helpers.rs
- core/Cargo.toml
- renegade-metrics/Cargo.toml
- renegade-metrics/src/gauge.rs
- renegade-metrics/src/global_metrics.rs
- renegade-metrics/src/helpers.rs
- renegade-metrics/src/labels.rs
- renegade-metrics/src/lib.rs
- state/src/applicator/task_queue.rs
- util/src/telemetry/metrics.rs
- workers/gossip-server/src/peer_discovery/heartbeat.rs
- workers/gossip-server/src/peer_discovery/mod.rs
- workers/gossip-server/src/peer_discovery/peer_metrics.rs
- workers/gossip-server/src/peer_discovery/peers.rs
- workers/proof-manager/src/proof_manager.rs
- workers/task-driver/integration/helpers.rs
- workers/task-driver/src/driver.rs
This PR introduces the `Gauge` struct, which manages an atomic, incrementable/decrementable gauge value from which metrics are reported. This is necessary as StatsD does not recognize the `gauge.increment()` / `gauge.decrement()` events, only `gauge.set()` - so we expose them through this wrapper.
The metrics from which in-flight tasks, proofs, and transactions were calculated were replaced with static gauges of this type.
> renegade-metrics: gauge: add atomic gauge metric primitive

- state/src/interface/peer_index.rs
This PR reinstates the marking of fresh heartbeats for added peers. Primarily this aids in initial communication with the bootstrap nodes, wherein they will self-report very stale heartbeats, leading to new nodes expiring one bootstrap very quickly. The previous issue with fresh heartbeats extending the lifetime of an expired peer in nodes' peer indices is alleviated by filtering out expiry candidates from heartbeats.
This was tested in dev by triggering an upgrade - bootstraps were not expired, and there was no thrash (i.e., nodes getting expired and re-added repeatedly)
> state: interface: peer_index: mark fresh heartbeats for added peers

- Cargo.lock
- arbitrum-client/src/abi.rs
- arbitrum-client/src/helpers.rs
- circuit-types/src/elgamal.rs
- circuit-types/src/lib.rs
This PR adds helpers for parsing and decrypting notes emitted by fees paid in `settleOfflineFee` transactions. These helpers are used by the `fee-sweeper` to sweep transaction history and redeem fees.
- Tested via the `fee-sweeper`
> arbitrum-client, circuit-types: Add helpers for accessing fee notes

- constants/src/lib.rs
This PR updates the `TESTNET_DEPLOY_BLOCK` constant to match the block at which we deployed the Darkpool proxy contract to Arbitrum Sepolia
> constants: update testnet deploy block to match Sepolia deployment

- common/src/types/token.rs
- docker/sequencer/deploy_contracts.sh
This PR replaces the `REN` token with the `ARB` token in the global ticker names list
> common: token: s/ren/arb

- Cargo.lock
- circuit-types/Cargo.toml
- circuit-types/src/balance.rs
- circuit-types/src/lib.rs
- circuit-types/src/order.rs
- common/src/lib.rs
- common/src/types/token.rs
- common/src/types/wallet/mocks.rs
- constants/src/lib.rs
- docker/sequencer/deploy_contracts.sh
- external-api/src/http/wallet.rs
- external-api/src/lib.rs
- external-api/src/types/api_task_history.rs
- external-api/src/types/api_wallet.rs
- renegade-metrics/src/helpers.rs
- util/src/hex.rs
This PR replaces the `biguint_to_hex_str` conversion method w/ a specialized `biguint_to_hex_addr` one that preserves padding to 20 bytes for addresses where appropriate. The native `BigUint::to_str_radix` would trim leading zeroes, leading to issues across the stack when token addresses had leading zeroes, e.g. inability to find tokens by address in the token mapping, and returning trimmed addresses via the API which the frontend would fail to match to its own token mapping.
All unit tests pass, and this is being tested in the mini-env.
> util: hex, circuit-types: ensure biguint -> address conversion has proper padding

- circuits/src/lib.rs
- config/src/cli.rs
- config/src/parsing.rs
- core/src/main.rs
- mock-node/src/lib.rs
- util/src/matching_engine.rs
- workers/handshake-manager/src/manager.rs
- workers/handshake-manager/src/manager/internal_engine.rs
- workers/handshake-manager/src/worker.rs
- workers/task-driver/integration/tests/settle_match.rs
This PR adds a `min_fill_size` config option to the relayer and uses this value as a threshold which matches must exceed to be settled. Specifically, we threshold the quote asset swap implied by a match. Using the quote instead of the base is preferred as Renegade currently quotes all swaps in USDC -- so the logic is simpler.
- Unit tests pass; added a matching engine test for a `min_fill_size` violation
- Tested on a locally run relayer with a WETH trade
> handshake-manager: internal-engine: Check matches above `min_fill_size`

- config/src/cli.rs
- config/src/parsing.rs
- state/src/interface/node_metadata.rs
- state/src/storage/tx/node_metadata.rs
- workers/task-driver/src/tasks/pay_offline_fee.rs
This PR adds an `--auto-redeem-fees` flag that is set to false by default. On the Renegade internal relayer cluster, we will _not_ enable this flag, and will instead use separate fee redemption infra.
- Submitted fee payments for a wallet, verified that the relayer did not redeem
> config: Add `--auto-redeem-fees` flag set to false by default

- state/src/replication/state_machine/mod.rs
- state/src/replication/state_machine/recovery.rs
- state/src/replication/state_machine/snapshot.rs
- state/src/storage/tx/mod.rs
This PR makes the following 2 changes to how snapshots are handled:
1. When applying an installed snapshot, we use MDBX's `clear_table` method instead of dropping & re-adding a table. We are seeing `BadDbi` errors occasionally after installing snapshots that are generally linked to accessing tables that are deleted ([ex](https://github.com/erthink/libmdbx/issues/146))
2. When updating from a snapshot, either when recovering from one on startup or after installing one, we delete the snapshot data afterwards to save on disk space in the relayer
Things are working smoothly in dev, though it has proven difficult to reproduce the issue that prompted these changes even before deploying them to dev.
> state: replication: clear tables instead of dropping & remove db when applying snapshots

- node-support/snapshot-sidecar/src/main.rs
This PR tweaks the snapshot sidecar daemon to watch the snapshot directory, as opposed to the lockfile directly. This is because on Linux, the re-created lockfile is not re-watched by the underlying filesystem monitoring tool (`inotify`). [Here](https://github.com/notify-rs/notify/issues/165) is a thread digging into a similar issue w/ moving directories back and forth.
I tested this change against the previous implementation on a Debian image and confirmed that where the other implementation only registered one deletion event (on the first deletion), this implementation caught all the deletion events post re-creation.
Note that this issue does not occur on MacOS, which could have previously confounded local testing.
> node-support: snapshot-sidecar: watch snapshot directory

- core/src/setup.rs
- workers/handshake-manager/src/manager.rs
- workers/handshake-manager/src/manager/internal_engine.rs
- workers/job-types/src/task_driver.rs
- workers/task-driver/integration/helpers.rs
- workers/task-driver/integration/tests/settle_match.rs
- workers/task-driver/src/driver.rs
- workers/task-driver/src/running_task.rs
This PR has the task driver enqueue a refresh task for wallets affected by tasks which failed after the task's commit point. This ensures that there is no discrepancy between onchain and relayer wallet state, in the case that the relayer failed to update wallet state after new state has been committed onchain.
All unit tests pass, and this is currently being tested in dev, as integration tests currently do not work (and assume that verification is disabled, so they can't be run against the devnet sequencer).
Confirmed that refresh tasks are enqueued when failing in e.g. the `SubmittingTx` step of tasks, and that orderbot load is handled as expected (e.g. matches being processed, queues pausing/resuming expectedly)
> workers: task-driver: refresh wallets for post-commit task failures

- state/src/lib.rs
- state/src/storage/tx/matching_pools.rs
- state/src/storage/tx/mod.rs
This PR initializes the storage layer for the matching pools feature, establishing the DB layout for the `POOL_TABLE` and the minimum necessary access methods for the expected usage.
This includes some basic unit tests, all of which pass.
Next up is the interface layer for interacting with matching pools state.
> state: storage: matching_pools: create pool table & barebones access methods

- Cargo.lock
- config/src/cli.rs
- config/src/parsing.rs
- core/src/main.rs
- mock-node/src/lib.rs
- workers/api-server/Cargo.toml
- workers/api-server/src/compliance/client.rs
- workers/api-server/src/compliance/mod.rs
- workers/api-server/src/error.rs
- workers/api-server/src/http.rs
- workers/api-server/src/http/wallet.rs
- workers/api-server/src/lib.rs
- workers/api-server/src/worker.rs
This PR adds a `--compliance-service-url` config option to the the relayer which, when set, enables compliance checks on deposits. The only requirement on the config is that the server on the other end must implement the [compliance-server-api](https://github.com/renegade-fi/relayer-extensions/tree/master/compliance/compliance-api).
If not set, compliance screens are not enabled.
- Tested a deposit with no `--compliance-service-url` specified
- Tested a deposit on a low risk wallet with `--compliance-service-url` pointing to a locally running compliance service
- Tested a deposit on a high risk wallet with `--compliance-service-url` pointing to a locally running service. Received http 400
> api-server: compliance: Check wallet screening compliance if configured

- state/src/interface/matching_pools.rs
- state/src/interface/mod.rs
- state/src/storage/tx/matching_pools.rs
This PR establishes the state interface for matching pools. This is basically a thin wrapper around some of the storage layer access methods, along with some helpers dedicated to the global matching pool. The setters are stubbed out in anticipation of the associated state transitions.
This includes a small test suite for the global matching pool helpers, which is also stubbed out (and thus currently fails). I also filled out the storage layer test suite with cases ensuring the consistency checks work as expected, these new tests all pass.
> state: interface: matching_pools: create state interface for matching pools

- state/src/applicator/matching_pools.rs
- state/src/applicator/mod.rs
- state/src/interface/matching_pools.rs
- state/src/lib.rs
This PR introduces the state transitions & handlers for matching pools, & fills out the interface stubs for sending the associated proposals for these state transitions.
Because the applicator handlers for these transitions are so thin (they directly call the underlying storage methods and do nothing else), I don't believe this merits any tests in the applicator.
All matching pool unit tests now pass.
> state: applicator: matching_pools: state transitions & handlers

- common/src/types.rs
- common/src/types/tasks/descriptors/mod.rs
- common/src/types/tasks/descriptors/update_wallet.rs
- common/src/types/tasks/history.rs
- constants/src/lib.rs
- external-api/src/types/api_task_history.rs
- state/src/applicator/order_book.rs
- state/src/applicator/wallet_index.rs
- state/src/interface/matching_pools.rs
- state/src/interface/node_metadata.rs
- state/src/lib.rs
- state/src/storage/tx/matching_pools.rs
- state/src/storage/tx/order_book.rs
- workers/api-server/src/http/wallet.rs
- workers/task-driver/integration/tests/update_wallet.rs
- workers/task-driver/src/tasks/update_wallet.rs
This PR implements the logic for assigning orders to the appropriate matching pool. The logic is as follows: by default, indexed new orders are added to the global matching pool. However, we add the desired matching pool for an order to be added to the `UpdateWalletTaskDescriptor`, and in the `UpdateWalletTask` we subsequently assign a new order to the desired matching pool after it is indexed.
This gets us 2 things:
1. In the "happy path," orders that are created in the global matching pool do not need to invoke another state transition for being assigned to the global matching pool.
2. Orders that are intended for non-global matching pools are assigned to those pools during the `UpdateWalletTask`, i.e. there is no danger of a race in which we begin matching those orders across the …
> workers: task-driver: update_wallet: order matching pool assignment

- state/src/interface/order_book.rs
- workers/handshake-manager/src/manager/internal_engine.rs
This PR updates the internal matching engine to check that local orders which are candidates for a match are in the same matching pool. For now, we only add this check the internal matching engine.
I tested this ad-hoc by running a local relayer, putting up 2 crossing orders via the CLI, and ensuring that they matched & settled successfully.
Testing that orders _not_ in the same matching pool do _not_ match is deferred for when the admin API endpoint for creating orders in different matching pools is implemented.
> workers: handshake-manager: internal_engine: check that orders are in the same matching pool

- common/src/types/tasks/descriptors/update_wallet.rs
- common/src/types/tasks/history.rs
- constants/src/lib.rs
- state/src/applicator/order_book.rs
- state/src/applicator/wallet_index.rs
- state/src/interface/matching_pools.rs
- state/src/interface/mod.rs
- state/src/interface/node_metadata.rs
- state/src/interface/order_book.rs
- state/src/lib.rs
- state/src/storage/tx/matching_pools.rs
- state/src/storage/tx/order_book.rs
- workers/handshake-manager/src/manager/internal_engine.rs
- workers/task-driver/integration/tests/update_wallet.rs
- workers/task-driver/src/tasks/update_wallet.rs
This PR lowers the assumption of the default global matching pool into the storage layer. We now no longer need to explicitly create the global pool or assign orders into it. The global pool is not tracked as a separate matching pool in the `POOL_TABLE`, and as such any orders w/o an explicit pool assignment are considered to be in the global pool.
Additionally, we now only remove orders from their matching pool when they are cancelled (this implicitly moves them back to the global pool, but they are not matchable regardless). This is the only situation in which we want to remove orders from their matching pools.
All unit tests pass.
> state: storage: matching_pools: default global pool at storage layer

- core/src/main.rs
- external-api/src/http/admin.rs
- mock-node/src/lib.rs
- state/src/storage/tx/matching_pools.rs
- workers/api-server/src/http.rs
- workers/api-server/src/http/admin.rs
- workers/api-server/src/http/wallet.rs
- workers/api-server/src/worker.rs
This PR adds an admin API endpoint for assigning an existing order to an existing matching pool. This will also trigger a matching engine run on the assigned order
This was tested on a local relayer via the CLI, where I confirmed that an order moved into a matching pool containing a crossing order proceeded to match successfully.
> workers: api-server: admin: order assignment endpoint

- external-api/src/http/admin.rs
- workers/api-server/src/http.rs
- workers/api-server/src/http/admin.rs
This PR introduces a convenience endpoint for getting an order's metadata via the admin API. This will be used by the quoters to poll for the successful fill of an order that has been targeted for matching. The information returned here is already available vis the open orders API endpoint, but this makes it simpler to search for a specific order.
This has been tested locally via the CLI.
> workers: api-server: admin: order metadata endpoint

- common/src/types/network_order.rs
- state/src/applicator/order_history.rs
- state/src/applicator/wallet_index.rs
- state/src/storage/tx/order_book.rs
- workers/gossip-server/src/orderbook.rs
This PR smooths out some bugs / inconsistencies in order cancellation. In doing so, we slightly change the semantics of the local order set from "any orders managed by the local cluster" to "any _open_ orders managed by the local cluster," where "open" signifies that they are not cancelled and not completely filled.
Namely, the following changes are made:
1. When an order is cancelled, remove it from the local orders set, and mark the underlying `NetworkOrder` as cancelled
- This also drops the validity proofs/witnesses from the order, which previously was not happening, resulting in the order still being considered `ready_for_match`
2. When recording an order fill, if the order is completely filled, remove it from the local orders set
All unit tests pass.
> state: applicator: wallet_index: update local orders set & network order state when cancelling

- config/src/cli.rs
- config/src/parsing.rs
- state/src/interface/node_metadata.rs
- state/src/storage/tx/node_metadata.rs
- workers/api-server/src/http/wallet.rs
- workers/task-driver/integration/tests/pay_relayer_fee.rs
- workers/task-driver/integration/tests/redeem_relayer_fee.rs
- workers/task-driver/integration/tests/settle_match.rs
- workers/task-driver/src/tasks/pay_offline_fee.rs
- workers/task-driver/src/tasks/pay_relayer_fee.rs
- workers/task-driver/src/utils/validity_proofs.rs
This PR adds a `fee-encryption-key` config option and makes this option mutually exclusive with `fee-decryption-key`. For relayers that run fee decryption and settlement externally, the decryption key need not be placed in the relayer config; only the encryption key.
- Ran a relayer with only an encryption key, went through common flows of creating a new wallet, depositing, placing an order, matching, then paying fees. Verified that all flows, including fee payment, worked as expected
> config: cli: Allow public-key-only configuration for fee key

- renegade-crypto/src/hash.rs
- state/src/applicator/wallet_index.rs
This PR fixes a bug wherein we may attempt to transition an order to the cancelled state when it does not exist. This may happen if the chain events listener removes the order before it can be cancelled.
This happened in testnet and caused the cluster to degrade.
- Tested the cancellation flows, this fix will be tested live
> state: applicator: wallet-index: Check order info exists when cancelling

- external-api/src/http/admin.rs
- workers/api-server/src/http.rs
- workers/api-server/src/http/admin.rs
- workers/handshake-manager/src/manager/internal_engine.rs
This PR tweaks the admin `/open-orders` endpoint to support a `matching_pool` query param to filter open orders by, and also to calculate the fillable amount of each order & include that in the response. This may require using the current price of the order's base asset, which is naturally liable to drift by the time the client receives this API response. This is assumed to be understood by the client.
I tested this by running a local relayer & probing the `/open-orders` API while I moved an order between matching pools, including the global pool. I asserted that the responses were properly filtered and included the expected fillable amount
> workers: api-server: admin: open-orders: matching pool filter + fillable amt

- node-support/bootloader/src/main.rs
This PR configures the bootloader script to read in the admin API key from an environment variable and insert it into the relayer's config file.
This has been tested in dev, where the admin API is confirmed to work as expected.
> node-support: bootloader: read admin api key from env var

- workers/api-server/src/http/admin.rs
This PR updates the admin order assignment endpoint to check for an order's existence via it's metadata as opposed to the network order book - this is because filled orders are removed from the network order book, and there is also a critical section in the `Updating State` step of the `SettleMatchInternalTask` wherein a partially filled order is removed but not yet reindexed to the network order book.
As such it is less error-prone and more semantically correct to check for an order's existence via it's presence in the metadata table.
> workers: api-server: http: admin: check order existence by metadata

- circuits/src/lib.rs
- circuits/src/zk_circuits/valid_commitments.rs
- circuits/src/zk_circuits/valid_fee_redemption.rs
- circuits/src/zk_circuits/valid_match_settle/mod.rs
- circuits/src/zk_circuits/valid_reblind.rs
- circuits/src/zk_circuits/valid_relayer_fee_settlement.rs
- circuits/src/zk_circuits/valid_wallet_update.rs
- circuits/src/zk_gadgets/elgamal.rs
- common/src/keyed_list.rs
- common/src/types/gossip.rs
- common/src/types/handshake.rs
- common/src/types/network_order.rs
- common/src/types/proof_bundles.rs
- common/src/types/tasks/descriptors/mod.rs
- common/src/types/tasks/history.rs
- config/src/cli.rs
- external-api/src/http/network.rs
- state/src/applicator/mod.rs
- state/src/interface/peer_index.rs
- state/src/lib.rs
- state/src/replication/mod.rs
- workers/api-server/src/http/network.rs
This PR adds the local peer's cluster ID to the network topology response in `GET /v0/network`. This will be used by clients to filter the network response by exactly the cluster responding to the request.
I also cleaned up a bunch of clippy lints that were left over from upgrading the rust toolchain.
- Tested the endpoint
> external-api: network: Add `local_cluster_id` to network topology resp

- Cargo.lock
- node-support/bootloader/Cargo.toml
- node-support/bootloader/src/main.rs
This PR updates the bootloader to:
1. Generate the peer id for the local node
2. Register a gas wallet with the funds manager under that peer id on startup
- Tested against a locally deployed funds manager
> node-support: bootloader: Register gas wallet on startup

- Cargo.lock
- state/Cargo.toml
- state/benches/storage.rs
This PR adds storage throughput benchmarks for the `state` crate. These take two form:
- Raw key-value read/write benchmarks
- Read/write benchmarks of the wallet type to get an idea of throughput with serialization
> state: benches: storage: Add storage benchmarks

- common/src/types.rs
- common/src/types/handshake.rs
- common/src/types/tasks/descriptors/settle_match.rs
- common/src/types/wallet/order_metadata.rs
- gossip-api/src/request_response/handshake.rs
- state/src/applicator/order_history.rs
- state/src/interface/order_history.rs
- state/src/interface/wallet_index.rs
- state/src/storage/tx/order_history.rs
- workers/handshake-manager/src/manager/handshake.rs
- workers/handshake-manager/src/manager/internal_engine.rs
- workers/handshake-manager/src/manager/match.rs
- workers/handshake-manager/src/manager/price_agreement.rs
- workers/handshake-manager/src/state.rs
- workers/task-driver/integration/tests/settle_match.rs
- workers/task-driver/src/tasks/settle_match_internal.rs
- workers/task-driver/src/utils/order_states.rs
This PR introduces the `TimestampedPrice` struct and uses it in the `SettleMatch` and `SettleMatchInternal` tasks with the purpose of it being used in the `PartialOrderFill` struct.
The goal here is to communicate to the frontend the time at which the price used in each of an order's partial fills was sampled. This allows us to more accurately estimate the savings relative to hypothetically executing the fill on Binance.
We use the timestamp of the price sampling, as opposed to the timestamp of the fill execution, as we deem that to be the point at which the execution process for a fill begins. In calculating the savings, we want to communicate to the user: "if you began the execution process at this time in Renegade, you'd get this price, if you began it at this time in Binance, you'd …
> common: types, workers: handshake-manager: use timestamped price in order metadata

- Cargo.lock
- Cargo.toml
- arbitrum-client/Cargo.toml
- test-helpers/Cargo.toml
- workers/task-driver/Cargo.toml
This PR pins the `alloy-sol-types` and `alloy-primitives` dependency versions to those used in the `stylus-sdk` and thereby the contracts.
> workspace: Pin `alloy` libraries to version used in contracts

- workers/price-reporter/src/manager.rs
This PR fixes the price staleness check to be in terms of milliseconds, following https://github.com/renegade-fi/renegade/pull/722
This is deployed in dev (branched off of `HEAD~1`, as `HEAD` currently doesn't build) and has been tested to work
> workers: price-reporter: manager: fix staleness threshold to be in ms

- Cargo.lock
- arbitrum-client/src/helpers.rs
This PR ingests the interface changes in `alloy` after upgrading to `0.7.7`.
> arbitrum-client: Fix alloy interface incompatibilities

- state/src/interface/order_history.rs
- state/src/interface/wallet_index.rs
- state/src/replication/mod.rs
- state/src/replication/raft.rs
- state/src/storage/tx/order_history.rs
This PR fixes a number of timing and concurrency bugs in unit tests that largely amount to shrinking the test size. As well, I fixed a bug that occurs when expiring the leader in which we campaign and then attempt to forward the expiry proposal to the leader.
> state: Fix timing bugs in unit tests

- state/Cargo.toml
- state/benches/applicator.rs
- state/src/applicator/mod.rs
This PR adds benchmarks for the state applicator for a few important state transitions. Importantly a few of these are on different wallets each iteration to prevent queue buildup affecting the results.
> state: benches: applicator: Add state transition benchmarks

- config/Cargo.toml
- config/src/parsing.rs
- state/Cargo.toml
- state/benches/interface.rs
- state/src/interface/order_history.rs
- state/src/interface/wallet_index.rs
- state/src/lib.rs
- state/src/replication/mod.rs
- state/src/replication/network/mock.rs
- state/src/replication/raft.rs
- state/src/storage/tx/order_history.rs
- workers/task-driver/integration/main.rs
This PR adds consensus benchmarks to the `state` module. These benchmarks measure the full round trip latency of proposing a state update simulated under various network delays.
- Ran the benchmarks
> state: benches: interface: Add consensus benchmarks

- common/src/types/tasks/history.rs
- external-api/src/types/api_task_history.rs
- workers/price-reporter/src/manager.rs
This PR adds the `LookupWallet` & `RefreshWallet` tasks to to task history, i.e. creates `HistoricalTaskDescription` and `ApiHistoricalTaskDescription` variants for them. They are written to task history via existing code paths.
I tested this by running a local relayer, triggering a wallet lookup & refresh, and ensuring that the lookup & refresh tasks were returned in the task history API endpoint by using the CLI
> common: types: tasks: history: add wallet lookups & refreshes to task history

- external-api/src/http/admin.rs
- workers/api-server/src/http/admin.rs
This PR adds the containing wallet's ID to the `OpenOrder` struct - this is to enable per-wallet rate limiting by the quoters.
**TODO:**
- Update the `OpenOrder` type in the JS SDK
- Testing (pretty straightforward change so prefer to do this once quoter changes are made)
> external-api: http: admin: add wallet_id to OpenOrder

- circuits/src/zk_circuits/valid_wallet_update.rs
- constants/src/lib.rs
This PR increases `MAX_BALANCES` from 5 to 10 and decreases `MAX_ORDERS` from 5 to 4.
- Tested against deployed test contracts (using new vkeys) with a local relayer
> constants: Set `MAX_BALANCES=10`, `MAX_ORDERS=4`

- common/src/types/tasks/descriptors/node_startup.rs
- config/src/cli.rs
- core/src/setup.rs
- state/src/interface/node_metadata.rs
- state/src/storage/tx/node_metadata.rs
- workers/task-driver/integration/tests/redeem_relayer_fee.rs
- workers/task-driver/src/tasks/node_startup.rs
- workers/task-driver/src/utils/validity_proofs.rs
This PR skips the relayer wallet creation step if the relayer is not configured to redeem fees into its own wallet. In this case, the relayer does not need a wallet for any other purpose.
- Started up a node that does not need a relayer wallet, verified that it did not create one
> task-driver: node-startup: Do not create wallet if not needed

- Cargo.lock
- circuit-types/src/keychain.rs
- circuits/Cargo.toml
- circuits/src/zk_circuits/mod.rs
- circuits/src/zk_circuits/valid_commitments.rs
- circuits/src/zk_circuits/valid_fee_redemption.rs
- circuits/src/zk_circuits/valid_match_settle/mod.rs
- circuits/src/zk_circuits/valid_offline_fee_settlement.rs
- circuits/src/zk_circuits/valid_reblind.rs
- circuits/src/zk_circuits/valid_relayer_fee_settlement.rs
- circuits/src/zk_circuits/valid_wallet_create.rs
- circuits/src/zk_circuits/valid_wallet_update.rs
- common/src/types/wallet/derivation.rs
- common/src/types/wallet/mocks.rs
- external-api/src/types/api_wallet.rs
This PR adds a `nonce` field to the `PublicKeychain` type and constrains its use in the circuits. The nonce is allowed to change exactly when the keychain rotates, and in no other location. 
I added constraints where necessary, but most circuits already captured this constraint in a more general keychain equality check. For those circuits, I made sure to test the fallibility of our nonce tests when these constraints were not present.
- For each circuit, I added a unit test for the nonce behavior. Then I commented out constraints to make the test fail, and then added them back to ensure the test passes.
- All other tests pass
> circuits, circuit-types: Add keychain nonce and constrain increments

- common/src/types/tasks/descriptors/lookup_wallet.rs
- common/src/types/tasks/descriptors/mod.rs
- common/src/types/tasks/descriptors/update_wallet.rs
- common/src/types/wallet/derivation.rs
- common/src/types/wallet/keychain.rs
- common/src/types/wallet/mocks.rs
- common/src/types/wallet/mod.rs
- common/src/types/wallet/types.rs
- external-api/src/http/admin.rs
- external-api/src/http/wallet.rs
- external-api/src/types/api_wallet.rs
- workers/api-server/src/http/admin.rs
- workers/api-server/src/http/wallet.rs
- workers/handshake-manager-tests/src/helpers.rs
- workers/task-driver/integration/helpers.rs
- workers/task-driver/integration/tests/lookup_wallet.rs
- workers/task-driver/src/tasks/lookup_wallet.rs
- workers/task-driver/src/tasks/node_startup.rs
- workers/task-driver/src/tasks/refresh_wallet.rs
This PR adds API support for key rotation by making two key changes:
1. Only accept `sk_match` when looking up or creating a wallet. This is necessary as a client may not know their `sk_root` value if it has rotated an unknown number of times. They will find out their `sk_root` value via the `nonce` field in the looked up wallet.
2. Accept a new public root key in each wallet update request. We validate that if the root key is rotated, the nonce must be incremented.
- Deferred until a follow up with further API changes
> external-api: Make API changes for key rotation

- common/src/types/wallet/derivation.rs
- common/src/types/wallet/keychain.rs
- common/src/types/wallet/mocks.rs
- external-api/src/http/wallet.rs
- external-api/src/types/api_wallet.rs
- util/src/hex.rs
- workers/api-server/src/http/wallet.rs
This PR adds a symmetric hmac key to the wallet keychain types in `common` and `external-api`. This key is not used on-chain, so it is not added to the circuit types.
This key will replace the `sk_root` signature for relayer API auth. Allowing for a stable auth key while `sk_root` rotates.
- API testing deferred until authentication steps are complete
> external-api, common: Add symmetric key to wallet keychain types

- state/src/applicator/matching_pools.rs
- state/src/storage/tx/matching_pools.rs
This PR ensures that we do not try to double-create or double-delete a matching pool in the state applicator, as the only other place where this check is enforced is at the API layer, in a manner that is ignorant of concurrent requests.
> state: applicator: reject concurrent matching pool create / delete

- circuit-types/src/elgamal.rs
This PR adds a `point_on_curve` method to the `BabyJubJubPoint` type that we use for in circuit curve operations. This allows, among other things, consumers of this interface to check the validity of a point before attempting a cast to an arkworks `Projective` point, which will panic for invalid points.
I use this in the funds manager to check that a ciphertext is valid.
- Tested in the `funds-manager`
> circuit-types: elgamal: Add `point_on_curve` method to jubjub point

- Cargo.lock
This PR updates the dependencies for the relayer, including `ark-mpc` changes to `Scalar` serialization that were not committed.
- Tested relayer flows
> Cargo.lock: Update deps including `ark-mpc` for serialization changes

- Cargo.lock
- state/Cargo.toml
This PR pins `openraft=0.9.13` to avoid a log spam issue introduced in `0.9.14`. See [here](https://github.com/datafuselabs/openraft/issues/1236) for more details.
> state: Pin `openraft` to `0.9.13` to avoid log spam

- arbitrum-client/src/client/mod.rs
- constants/src/lib.rs
This PR adds a temporary `MAINNET_DEPLOY_BLOCK` to `constants` set to zero to avoid panics in the `arbitrum-client`.
> constants: Add temporary mainnet deploy block to remove panic

- config/Cargo.toml
- config/src/cli.rs
- core/src/main.rs
This PR makes certain relayer configs available via environment variables. This allows us to specify them as container environment variables in a more configurable way.
- Tested each environment variable
> config: cli: Allow some config entries to come from env vars

- Cargo.lock
- config/src/cli.rs
- config/src/parsing.rs
- core/src/main.rs
- mock-node/src/lib.rs
- workers/api-server/Cargo.toml
- workers/api-server/src/error.rs
- workers/api-server/src/http.rs
- workers/api-server/src/http/rate_limit.rs
- workers/api-server/src/http/wallet.rs
- workers/api-server/src/router.rs
- workers/api-server/src/worker.rs
This PR adds per-wallet task rate limiting in the API server. Note that we intentionally do not form consensus over rate limits. In a multi-node cluster, one can simply set the rate limit to `desired_rate_limit / num_nodes` and approximate an exact rate limit. 
Admin tasks are exempt from rate limiting, and paying fees is also not rate limiting.
- Set the rate limit to 3 then tested repeatedly refreshing a wallet through the CLI
> api-server: http: rate-limit: Add wallet task rate limiting

- config/src/cli.rs
- config/src/parsing.rs
- core/src/main.rs
- mock-node/src/lib.rs
- workers/api-server/src/http.rs
- workers/api-server/src/http/wallet.rs
- workers/api-server/src/worker.rs
- workers/job-types/src/price_reporter.rs
This PR enables a configurable deposit/withdrawal limit on the relayer, denominated in $USDC and defaulting to $1.
Note that on withdrawal, a user is allowed to withdraw their full balance, even if it does not exceed the withdrawal minimum.
- Tested depositing and withdrawing with small amounts and amounts barely above the threshold
> api-server: http: wallet: Enforce minimum deposit/withdrawal amounts

- Cargo.lock
- config/Cargo.toml
- config/src/cli.rs
- config/src/parsing.rs
- constants/src/lib.rs
- core/src/main.rs
- util/src/runtime.rs
- workers/api-server/src/websocket.rs
- workers/chain-events/Cargo.toml
- workers/chain-events/src/listener.rs
- workers/gossip-server/Cargo.toml
- workers/gossip-server/src/server.rs
- workers/handshake-manager/src/manager.rs
- workers/handshake-manager/src/manager/scheduler.rs
- workers/price-reporter/Cargo.toml
- workers/price-reporter/src/manager/external_executor.rs
- workers/price-reporter/src/manager/native_executor.rs
- workers/proof-manager/src/proof_manager.rs
- workers/task-driver/src/tasks/node_startup.rs
This PR adds a bootstrap mode to the relayer. This is set via a `OnceLock` and checked in various locations throughout the relayer to avoid work that isn't relevant to a bootstrap node.
- Ran a relayer in bootstrap mode, bootstrapped two nodes off of it and made sure they discovered one another
> constants: Add `in_bootstrap_mode` and gate functionality behind it

- workers/handshake-manager/src/manager.rs
- workers/handshake-manager/src/manager/price_agreement.rs
This PR removes the `DEFAULT_PAIRS` static and instead replaces it with the token mapped tickers for all named tokens we support. This more directly represents the prices we want in an environment and works better across environments with different token lists.
- Ran a relayer after this change without panicking on the mainnet token list
> handshake-manager: price-agreement: Initialize streams from token map

- config/src/cli.rs
- node-support/bootloader/src/main.rs
This PR makes three fixes:
- Add a bootstrap mode environment variable
- Add a default value for the `--contract-address` field. This is a meaningless default but is important for testing methods that require a mock config
- Fix hmac key parsing in the bootloader script to properly handle a `0x` prefixed hex string
- Ran in bootloader mode via env var
> config: cli: Add environment variable for bootstrap mode

- workers/task-driver/src/tasks/refresh_wallet.rs
This PR changes the logic of the refresh task to _always_ lookup a wallet, even if the nullifier is fresh. This prevents any bugs that may come downstream of nullifier and public blinder stores on-chain getting out of sync.
- Looked up a wallet a few times and then refreshed it
> task-driver: refresh-wallet: Don't check nullifier before lookup

- config/src/cli.rs
This PR sets the default relayer fee to 2bps
> config: cli: Set default relayer fee to 2bps

- common/src/types/token.rs
This PR adds exchange support entries for XAI, RDNT, ETHFI.
- Ran the relayer on the mainnet token map
> common: token: Add exchange support entries for new tokens

- circuit-types/src/fixed_point.rs
This PR sets the fixed point precision to 63 bits
> circuit-types: fixed-point: Set precision to 63 bits

- docker/sequencer/deploy_contracts.sh
- util/src/matching_engine.rs
- workers/price-reporter/src/manager.rs
This PR makes a few miscellaneous changes including that we now add Binance to the `non_zero_prices` list so that the min connections constraint does not fail.
- Fetched prices for all pairs from the relayer directly, all were nominal
> price-reporter: manager: Do not block binance price on min connections

- workers/api-server/src/websocket.rs
This PR removes a spammy log that occurs when a client resets a websocket connection. It doesn't inform anything useful
> workers: api-server: websocket: Remove spammy websocket connection log

- bin/build_and_push.sh
- bin/deploy.sh
- workers/price-reporter/src/manager/external_executor.rs
This PR makes two changes:
- Downgrades an error log for `ConnectionHangup` in the price reporter to a warn
- Fixes the `bin/deploy.sh` and `bin/build_and_push.sh` scripts to use explicit flags rather than indexed arguments. Among other things this fixes an issue we've seen before in parsing the tag `latest` for an ECS revision rather than the SHA itself
- Deployed to testnet
> workers: price-reporter: external-executor: Downgrade error logs to warn

- Cargo.lock
- Cargo.toml
- bin/build_and_push.sh
- core/Cargo.toml
- core/src/error.rs
- core/src/main.rs
- metrics-sampler/Cargo.toml
- metrics-sampler/src/lib.rs
- metrics-sampler/src/raft_metrics_sampler.rs
- metrics-sampler/src/sampler.rs
- mock-node/src/lib.rs
- renegade-metrics/src/labels.rs
- state/src/interface/mod.rs
- state/src/interface/raft.rs
- state/src/lib.rs
This PR introduces the `metrics-sampler` module, which defines a framework for sampling various system metrics on fixed intervals using the `system-clock`.
As an example, we port over the raft metrics to `metrics-sampler` in the form of the `RaftMetricsSampler`.
This pattern will subsequently be used to sample product insight metrics.
I tested this with a local relayer & on testnet, where the raft metrics are being recorded as expected.
> metrics-sampler: create metrics-sampler module & port raft metrics 

- Cargo.lock
- core/src/main.rs
- metrics-sampler/Cargo.toml
- metrics-sampler/src/lib.rs
- metrics-sampler/src/onboarding_metrics_sampler.rs
- metrics-sampler/src/raft_metrics_sampler.rs
- metrics-sampler/src/sampler.rs
This PR utilizes the new `AsyncMetricsSampler` primitive to sample metrics regarding aggregate user onboarding progress states.
This has been tested in testnet by creating a new user, executing the full suite of onboarding tasks, and confirming that the sampled metrics reflected this progress.
> metrics-sampler: add aggregate onboarding metrics samples

- Cargo.lock
- core/src/main.rs
- metrics-sampler/Cargo.toml
- metrics-sampler/src/churn_metrics_sampler.rs
- metrics-sampler/src/lib.rs
- metrics-sampler/src/onboarding_metrics_sampler.rs
This PR creates a metrics sampler for churn metrics. Two notable omissions from this sampler are metrics for the time since order creation and the time since last fill. These are non-trivial to compute using a sample-based approach, we'd need to scan through task history and even then we wouldn't be able to match on the correct cancellation event since order cancellation historical task types have the entire cancelled order struct in them, which likely has a different `amount` than the order metadata.
This is running in testnet & is reporting metrics accurately.
> metrics-sampler: churn_metrics_sampler: create churn metrics sampler

- Cargo.lock
- external-api/Cargo.toml
- external-api/src/http/wallet.rs
- external-api/src/lib.rs
This PR allows wallet update signatures to be base64 serialized by introducing a custom visitor that deserializes bytes from _either_ a json array or a base64 string encoding of the bytes.
- Tested wallet updates through the CLI to ensure current clients will still work
> external-api: Allow base64 serialization of wallet update signatures

- Cargo.lock
- external-api/Cargo.toml
- external-api/src/http/wallet.rs
- external-api/src/lib.rs
This PR allows certain bigints int the external API to be serialized as a `u64` or a number string, e.g. `"10"`. This makes the API simpler on clients that do not naturally serialize bigints as limbs
- Tested against the golang and rust clients
> external-api: Allow bigints to serialize as number strings

- Cargo.lock
- circuit-types/src/balance.rs
- circuit-types/src/lib.rs
- circuit-types/src/order.rs
- common/src/types/wallet/balances.rs
- common/src/types/wallet/mod.rs
- common/src/types/wallet/orders.rs
- external-api/src/types/api_wallet.rs
- workers/api-server/src/http/admin.rs
- workers/api-server/src/http/wallet.rs
This PR validates the amounts and prices in type constructors so that API requests with invalid amounts and prices fail immediately rather than in proving.
This resolves a failure we saw the other day with a task that failed to prove:
- [Proof Manager Trace](https://us5.datadoghq.com/apm/trace/7336502415864029284?env=mainnet&graphType=flamegraph&shouldShowLegend=true&sort=time&spanID=9997409649345608247&timeHint=1726577099553.513)
- [Task Trace](https://us5.datadoghq.com/apm/trace/7867002605463599268?env=mainnet&graphType=flamegraph&shouldShowLegend=true&sort=time&spanID=12153791715795463094&timeHint=1726577094800.8882)
- Added validation tests
- Tested a huge order at the API layer
> circuit-types, common: Validate amounts and prices in constructors

- external-api/src/http/admin.rs
- state/src/interface/raft.rs
- state/src/replication/raft.rs
- workers/api-server/src/http.rs
- workers/api-server/src/http/admin.rs
This PR adds the `/v0/admin/trigger-snapshot` route that allows us to trigger an immediate snapshot of the raft state.
- Tested the endpoint on a locally running node
> api-server: http: admin: Add `trigger-snapshot` route

- Cargo.lock
- state/Cargo.toml
- state/benches/storage.rs
- state/src/interface/order_book.rs
- state/src/interface/peer_index.rs
- state/src/interface/raft.rs
- state/src/lib.rs
- state/src/replication/network/gossip.rs
- state/src/replication/network/mod.rs
- state/src/replication/state_machine/snapshot.rs
- state/src/storage/db.rs
- state/src/storage/error.rs
- state/src/storage/tx/order_book.rs
- workers/gossip-server/src/peer_discovery/heartbeat.rs
- workers/gossip-server/src/peer_discovery/peers.rs
- workers/gossip-server/src/server.rs
- workers/handshake-manager/src/manager/scheduler.rs
- workers/network-manager/src/executor/request_response.rs
This PR migrates the underlying `state` serialization from `bincode` to `cbor` to support schema evolution in our `state` modules. This was deployed to mainnet in three phases:
- Deploy receiver code that allows all nodes to receive snapshots & raft messages in either `cbor` or `bincode` serialization. All snapshots were converted on-the-fly to `cbor` serialization and all new raft messages were serialized with `cbor`
- Deploy code that migrates raft messages from `bincode` -> `cbor`
- Deploy the code in this PR, which removes all shim logic.
Additionally, while deploying, I found and optimized a number of bottlenecks. Namely:
- Do not fetch all orders from state using `get_all_orders`, as our state has grown this has become a serious deserialization burden
- Do not send order IDs in …
> state: Switch serialization to cbor to allow type evolution

- Cargo.lock
- circuit-types/src/order.rs
- circuits/src/lib.rs
- common/src/keyed_list.rs
- common/src/types/tasks/descriptors/update_wallet.rs
- common/src/types/wallet/balances.rs
- common/src/types/wallet/mocks.rs
- common/src/types/wallet/mod.rs
- common/src/types/wallet/order_metadata.rs
- common/src/types/wallet/orders.rs
- common/src/types/wallet/shares.rs
- common/src/types/wallet/types.rs
- external-api/src/types/api_task_history.rs
- external-api/src/types/api_wallet.rs
- state/Cargo.toml
- state/src/interface/wallet_index.rs
- util/src/matching_engine.rs
- workers/api-server/src/http/admin.rs
- workers/api-server/src/http/wallet.rs
- workers/handshake-manager-tests/src/mpc_match.rs
- workers/handshake-manager/src/manager/internal_engine.rs
- workers/task-driver/integration/tests/settle_match.rs
- workers/task-driver/integration/tests/update_wallet.rs
- workers/task-driver/src/tasks/refresh_wallet.rs
- workers/task-driver/src/utils/validity_proofs.rs
This PR adds the `min_fill_size` field to the `Order` type. This involves breaking out the `common::wallet::Order` into a new type -- distinct from `circuit_types::Order` -- to include fields that don't go into the circuits.
- Deployed to testnet
- Tested min fills
> common: wallet: orders: Add `min_fill_size` field to `Order`

- common/src/types/token.rs
This PR remaps the BTC token to wBTC for prices. Renegade trades wBTC, so we use the wrapped price directly.
- Tested a local price reporter with these changes
> common: token: Remap BTC to wBTC

- gossip-api/src/request_response/mod.rs
This PR removes span tags for the arguments to `AuthenticatedGossipResponse::verify_cluster_auth`. This includes the hmac key and the gossip response body.
> gossip-api: request-response: Remove trace fields

- arbitrum-client/src/abi.rs
- arbitrum-client/src/client/contract_interaction.rs
- common/src/types/wallet/shares.rs
- workers/gossip-server/src/peer_discovery/heartbeat.rs
- workers/gossip-server/src/peer_discovery/peers.rs
- workers/gossip-server/src/server.rs
- workers/task-driver/src/tasks/refresh_wallet.rs
This PR adds logic to the `refresh-wallet` task which checks whether the wallet's public blinder has been seen on-chain. If it has _not_, the refresh task can assume that the shares held locally by the relayer are up-to-date.
- Tested with a locally running relayer for both cases:
- Tested the case in which a wallet was up to date
- Tested the case in which a wallet was out of date (updated it on a different relayer)
> task-driver: refresh-wallet: Check for public blinder on-chain

- external-api/src/http/admin.rs
- workers/api-server/src/http.rs
- workers/api-server/src/http/admin.rs
This PR introduces a new admin API endpoint for fetching the matching pool to which a given order pertains.
This was tested against a local relayer.
> workers: api-server: http: admin: add get matching pool for order route

- circuit-types/src/match.rs
- circuit-types/src/transfers.rs
- circuits/src/zk_circuits/valid_match_settle_atomic.rs
This PR adds the initial set of constraints for `VALID MATCH SETTLE ATOMIC`. This is focused on the constraints in the matching engine, ensuring that the internal party's order parameters are not violated by the match.
- Settlement constraints
- Proof Linking
- Tests
> circuits: valid-match-settle-atomic: Matching engine constraints

- circuit-types/src/balance.rs
- circuit-types/src/lib.rs
- circuit-types/src/match.rs
- circuit-types/src/note.rs
- circuit-types/src/order.rs
- circuit-types/src/transfers.rs
- circuits/benches/valid_fee_redemption.rs
- circuits/src/zk_circuits/valid_commitments.rs
- circuits/src/zk_circuits/valid_match_settle_atomic.rs
- circuits/src/zk_circuits/valid_relayer_fee_settlement.rs
- circuits/src/zk_circuits/valid_wallet_update.rs
- circuits/src/zk_gadgets/arithmetic.rs
This PR adds constraints for the external party's settlement; which is effectively just their fees. Specifically:
- Constrain both of the protocol fee and relayer fee to be valid amounts
- Constrain the protocol fee to be computed correctly
We do not validate the relayer fee _value_; instead allowing the relayer to set its fee on a per-trade basis. The actor submitting the tx should validate this fee.
- Proof linking
- Testing
> circuits: valid-match-settle-atomic: Add external party fees

- circuits/Cargo.toml
- circuits/benches/valid_match_settle_atomic.rs
This PR adds benchmarks for the `VALID MATCH SETTLE ATOMIC` circuit. This includes benchmarks for constraint generation, prover latency, and verifier latency.
- Proof linking
- Ran the benchmark
> circuits: benches: valid-match-settle-atomic: Add benchmarks

- Cargo.lock
- arbitrum-client/src/conversion.rs
This PR updates the conversion helpers in the `arbitrum-cilent` to add a new conversion helper for the match settle atomic types.
> arbitrum-client: conversion: Add conversion helpers for new types

- circuit-types/src/fixed_point.rs
- external-api/src/http/external_match.rs
- external-api/src/http/mod.rs
- workers/api-server/src/http.rs
- workers/api-server/src/http/external_match.rs
- workers/task-driver/src/driver.rs
This PR defines initial request/response types for the external (atomic) matching engine. The request type specifies an external order which will match against our consenting internal orders. The response type is to be defined.
The endpoint will send a job to the handshake manager for matching. If a match is found, the task driver will drive the proof and bundling of a response before sending the full payload back to the api layer.
- Hit the endpoint
> api-server: external-match: Define initial endpoint

- config/src/cli.rs
- config/src/parsing.rs
- core/src/main.rs
- state/src/applicator/task_queue.rs
- state/src/interface/wallet_index.rs
- workers/handshake-manager/src/error.rs
- workers/handshake-manager/src/manager.rs
- workers/handshake-manager/src/manager/matching/external_engine.rs
- workers/handshake-manager/src/manager/matching/internal_engine.rs
- workers/handshake-manager/src/manager/matching/match_helpers.rs
- workers/handshake-manager/src/manager/matching/mod.rs
- workers/handshake-manager/src/manager/matching/mpc_engine.rs
- workers/handshake-manager/src/manager/scheduler.rs
- workers/handshake-manager/src/worker.rs
- workers/job-types/src/handshake_manager.rs
- workers/job-types/src/lib.rs
- workers/job-types/src/network_manager.rs
This PR generalizes the matching engine logic for locally inferred matches. Specifically, we break out much of the core matching logic into a set of helpers in the `HandshakeExecutor` that will allow for easy re-use between the internal engine and external (atomic) engine.
This has the benefit of also simplifying and optimizing the match critical path.
I also removed the match mutual exclusion list as this argument is no longer needed.
- Live testing deferred until the feature branch is ready for merge
> handshake-manager: matching: Generalize local matching engine logic

- common/src/types/wallet/balances.rs
- mock-node/src/lib.rs
- state/src/interface/wallet_index.rs
- workers/api-server/src/http.rs
- workers/api-server/src/http/admin.rs
- workers/api-server/src/http/external_match.rs
- workers/chain-events/src/listener.rs
- workers/handshake-manager-tests/src/mpc_match.rs
- workers/handshake-manager/src/manager.rs
- workers/handshake-manager/src/manager/matching/external_engine.rs
- workers/handshake-manager/src/manager/matching/internal_engine.rs
- workers/handshake-manager/src/manager/matching/match_helpers.rs
- workers/network-manager/src/executor/control_directives.rs
- workers/network-manager/src/executor/pubsub.rs
This PR sets up the initial logic for the external matching engine and connects it via the `HandshakeManager`'s job queue to the api server's endpoint.
- External match settlement; i.e. return the bundle to the caller and await on-chain settlement
- Tested the endpoint, verified that it correctly called the external engine
> handshake-manager: matching: external-engine: Add external engine logic

- Cargo.lock
- circuit-types/src/fixed_point.rs
- circuit-types/src/lib.rs
- circuit-types/src/match.rs
- circuit-types/src/order.rs
- common/src/types/proof_bundles.rs
- common/src/types/tasks/descriptors/settle_match.rs
- external-api/src/bus_message.rs
- external-api/src/http/external_match.rs
- workers/api-server/src/error.rs
- workers/api-server/src/http.rs
- workers/api-server/src/http/external_match.rs
- workers/handshake-manager/src/manager.rs
- workers/handshake-manager/src/manager/matching/external_engine.rs
- workers/handshake-manager/src/manager/matching/internal_engine.rs
- workers/job-types/Cargo.toml
- workers/job-types/src/handshake_manager.rs
- workers/job-types/src/proof_manager.rs
- workers/proof-manager/src/mock.rs
- workers/proof-manager/src/proof_manager.rs
- workers/task-driver/src/tasks/mod.rs
- workers/task-driver/src/tasks/settle_match_external.rs
- workers/task-driver/src/tasks/settle_match_internal.rs
This PR implements the proof generation and client response steps of the settle external match task. This involves creating the witness and statement for the proof of `VALID MATCH SETTLE ATOMIC`, proving the circuit w/ proof-links, and responding via the system bus to the client.
- Hit the API endpoint and got back a settlement bundle
> task-driver: tasks: settle-match-external: Create atomic settlement bundles

- Cargo.lock
- arbitrum-client/src/abi.rs
- arbitrum-client/src/client/contract_interaction.rs
- arbitrum-client/src/conversion.rs
- external-api/Cargo.toml
- external-api/src/bus_message.rs
- external-api/src/http/external_match.rs
- workers/api-server/src/http/external_match.rs
- workers/task-driver/src/tasks/settle_match_external.rs
This PR changes the return type for atomic match settlement to include:
- The match result directly
- The exact transaction payload needed to submit the match on-chain
- Hit the API endpoint, verified the response
> task-driver: settle-match-external: Send full tx payload to client

- config/src/cli.rs
- config/src/parsing.rs
- state/src/interface/node_metadata.rs
- state/src/storage/tx/node_metadata.rs
- workers/api-server/src/http.rs
- workers/api-server/src/http/external_match.rs
- workers/task-driver/src/tasks/settle_match_external.rs
This PR adds a parameter `external-fee-addr` to the relayer config; specifying the address at which the relayer will collect externally paid fees (those paid by an external party in an atomic match settlement).
If this address is not specified we disable atomic matches
- Tested the API with the addr specified and without, verified functionality in both cases.
> config: cli: Add `external-fee-addr` config parameter

- arbitrum-client/src/abi.rs
- arbitrum-client/src/client/event_indexing.rs
- arbitrum-client/src/helpers.rs
This PR adds a helper to recover wallet shares from an atomic match settlement transaction, e.g. by refreshing a wallet after one has succeeded.
- Built a client to query and submit atomic matches, used it to submit an atomic match, then refreshed the internal wallet to get the up-to-date shares.
> arbitrum-client: event-indexing: Recover shares from atomic match settle

- arbitrum-client/Cargo.toml
- arbitrum-client/src/client/event_indexing.rs
- workers/task-driver/src/tasks/settle_match_external.rs
This PR implements the last step of the `settle-external-match` task; waiting for the atomic settlement to land on-chain. We do so by listening for a nullifier spent event with a timeout. 
If the timeout is exceeded, the task completes immediately under assumption that the bundle was not sent to the contract. If the nullifier is seen within the timeout, we refresh the wallet to pick up the newly modified shares.
- Add refresh logic in the `chain-events` worker to pick up any missed settlements
- Tested both cases:
- Had the solver client drop the match (no submission on-chain). I verified that the task timed out and did not refresh the wallet
- Had the solver client submit the match, I verified that the nullifier was seen by the relayer and the wallet correctly …
> task-driver: settle-match-external: Await atomic match settlement

- external-api/src/http/admin.rs
- workers/api-server/src/http.rs
- workers/api-server/src/http/admin.rs
This PR tweaks the existing admin open orders & order metadata endpoints, shifting the responsibility of potentially calculating an order's fillable amount from the former to the latter.
As a result, the open orders endpoint now simply returns the IDs of open orders, and the order metadata endpoint (now the "augmented order" endpoint) returns an "augmented order" (fka `OpenOrder`) that contains the order metadata, managing wallet ID, and optionally the fillable amount at the current price.
This makes the open orders endpoint significantly lighter, and shifts the expectation of relayer admins to "follow up" with augmented order requests for open orders.
This was tested on a local relayer using the CLI
> external-api, workers: api-server: http: admin: add augmented order endpoint

- external-api/src/bus_message.rs
- external-api/src/http/admin.rs
- external-api/src/types/admin.rs
- external-api/src/types/mod.rs
- state/src/applicator/wallet_index.rs
- workers/api-server/src/http/admin.rs
- workers/api-server/src/websocket.rs
- workers/api-server/src/websocket/handler.rs
- workers/api-server/src/websocket/order_status.rs
- workers/api-server/src/websocket/price_report.rs
- workers/api-server/src/websocket/task.rs
- workers/api-server/src/websocket/wallet.rs
This PR introduces an admin websocket endpoint for subscribing to wallet updates without filtering by wallet ID. This endpoint doesn't stream out any substantive information about the updates themselves, rather just the wallet / order IDs.
This required adding an admin authentication method for the websocket server, as well as a new system bus topic / message for these opaque updates.
This will be tested downstream of implementing the consumption of this API in the JS SDK
> external-api, workers: api-server: websocket: add admin websocket endpoint for all wallet updates

- common/src/types/wallet/mocks.rs
- common/src/types/wallet/mod.rs
- common/src/types/wallet/orders.rs
- external-api/src/http/external_match.rs
- external-api/src/types/api_wallet.rs
- state/src/interface/order_book.rs
- workers/handshake-manager-tests/src/mpc_match.rs
- workers/handshake-manager/src/manager.rs
- workers/handshake-manager/src/manager/matching/external_engine.rs
- workers/handshake-manager/src/manager/matching/internal_engine.rs
- workers/task-driver/integration/tests/settle_match.rs
- workers/task-driver/integration/tests/update_wallet.rs
This PR adds an `allow_external_matches` field to the `Order` struct and filters external match candidates by this value. I also made the following changes with this:
- Added an `OrderBuilder` struct now that there are a number of optionally configurable fields
- Added tracing to a few of the matching engine methods so that we can watch their latency as the order state grows
- Created an order with `allow_external_matches = false` and verified that the external match client got no match
- Created an order with `allow_external_matches = true` and verified that the client received an external match
> common: wallet: orders: Add `allow_external_matches` flag

- Cargo.lock
- common/src/types/wallet/mocks.rs
- common/src/types/wallet/mod.rs
- common/src/types/wallet/orders.rs
- external-api/src/http/external_match.rs
- external-api/src/types/api_wallet.rs
- state/src/interface/order_book.rs
- state/src/interface/task_queue.rs
- state/src/interface/wallet_index.rs
- state/src/lib.rs
- state/src/storage/tx/wallet_index.rs
- workers/api-server/src/http.rs
- workers/api-server/src/http/wallet.rs
- workers/chain-events/Cargo.toml
- workers/chain-events/src/listener.rs
- workers/handshake-manager-tests/src/mpc_match.rs
- workers/handshake-manager/src/manager.rs
- workers/handshake-manager/src/manager/matching/external_engine.rs
- workers/handshake-manager/src/manager/matching/internal_engine.rs
- workers/task-driver/integration/tests/settle_match.rs
- workers/task-driver/integration/tests/update_wallet.rs
- workers/task-driver/src/running_task.rs
- workers/task-driver/src/tasks/settle_match_external.rs
This PR adds a `wallet_id` <-> `nullifier` double sided mapping. This mapping is updated when a wallet is written. It will allow us to determine which wallets need refreshing when a nullifier is seen on-chain.
We will allow this mapping to backfill naturally through wallet writes in deployment; its use in the events listener will require no backfill.
- Added a test for the new mapping
> state: storage: wallet-index: Track nullifier <-> wallet mapping

- state/src/replication/state_machine/snapshot.rs
- state/src/storage/tx/mod.rs
This PR checks if a table exists before attempting to read it from the snapshot. This is necessary when creating a new table.
- Currently testing an upgrade with a new table in testnet
> state: replication: snapshot: Check if table exists before reading

- common/src/types.rs
- common/src/types/tasks/descriptors/settle_match.rs
- renegade-metrics/src/lib.rs
- workers/handshake-manager/src/manager/matching/external_engine.rs
- workers/task-driver/src/tasks/settle_match_external.rs
- workers/task-driver/src/tasks/settle_match_internal.rs
This PR updates the `settle-external-match` task to record order fill metrics when an atomic match is witnessed on-chain. Note that if a client fails to submit the atomic match bundle on-chain the fill will be missed. For now, we choose not to solve this problem under the assumption that this is a sufficiently unlikely edge case. We can reevaluate if this makes sense once the atomic match system is deployed.
- Submitted an atomic match and printed the fill history after the match
> task-driver: settle-match-external: Record historical fill and metrics

- Cargo.lock
- external-api/Cargo.toml
- external-api/src/auth/auth_helpers.rs
- external-api/src/auth/error.rs
- external-api/src/auth/mod.rs
- external-api/src/lib.rs
- workers/api-server/Cargo.toml
- workers/api-server/src/auth/admin_auth.rs
- workers/api-server/src/auth/helpers.rs
- workers/api-server/src/auth/mod.rs
- workers/api-server/src/auth/wallet_auth.rs
- workers/api-server/src/error.rs
This PR adds auth v2 helpers to the `external-api` crate available behind the `auth` feature flag. These headers change the MAC payload to be `[path_bytes, header_bytes, body_bytes]` rather than just the body, and prefix renegade headers with `x-renegade`.
I'll upgrade the relayer to check first for a v2 auth then for a v1 auth in the next pr. We will leave the relayer backwards compatible until clients can upgrade.
- Tested both the wallet and admin APIs
> external-api: auth: Add auth v2 helpers

- Cargo.lock
- common/Cargo.toml
- common/src/types/wallet/keychain.rs
- external-api/src/auth/auth_helpers.rs
- external-api/src/lib.rs
- workers/api-server/src/auth/mod.rs
- workers/api-server/src/router.rs
- workers/api-server/src/websocket.rs
This PR migrates the relayer authentication to use v2 authentication. Specifically, I introduce shim code to first try v2 auth then fall back to v1 if v2 is not available. This preserves backwards compatibility while the clients are being updated.
- Tested with an old client using v1 auth
- Tested with a new client using v2 auth
> api-server: auth: Add authv2 shims while clients migrate

- common/src/types/gossip.rs
- workers/handshake-manager/src/manager/matching/external_engine.rs
This PR adds a wrapper function around `run_external_matching_engine` that catches any errors and unblocks the client with a `NoMatch` message. Before this change, the external engine might fail and never respond to the API server, leaving the API server to timeout.
- Tested with a client and hardcoded an error, verified that the client received back a no match immediately
> handshake-manager: external-engine: Respond to client if match fails

- external-api/src/http/admin.rs
- workers/api-server/src/http.rs
- workers/api-server/src/http/admin.rs
This PR tweaks the `/admin/wallet/:id/order-ids` endpoint to only return the IDs of _matchable_ orders in the wallet. This is preferable to returning all order IDs, including those of default / empty orders.
This has been tested in testnet.
> workers: api-server: http: admin: return matchable order IDs for wallet

- common/src/types.rs
- workers/api-server/src/http/admin.rs
- workers/handshake-manager/src/manager/matching/match_helpers.rs
- workers/handshake-manager/src/manager/price_agreement.rs
This PR fixes the calculation of the fillable amount in the admin order metadata endpoint. We need to decimal-correct the price when computing the fillable amount, but we return the "original" price (which effectively assumes the base/quote tokens use the same number of decimals) to the client, as this is easier to interpret. This basically defers the responsibility of decimal-adjusting the fillable amount to the client if it wishes to compute the value by multiplying it with the price.
> wokers: api-server: admin: decimal-adjust fillable price

- circuits/src/zk_circuits/valid_match_settle/multi_prover.rs
- circuits/src/zk_circuits/valid_match_settle/single_prover.rs
- circuits/src/zk_circuits/valid_match_settle_atomic.rs
This PR replaces the use of `FixedPointGadget::constrain_equal_integer_ignore_fraction` with `FixedPointGadget::constrain_equal_floor` in all matching engine locations. The former allows integral values that are _either_ the floor or the ceiling of the fixed point value. The ladder restricts this to the floor, which is simpler.
> circuit: zk-circuits: Use `constrain_equal_floor` in matching engine

- circuits/benches/valid_wallet_create.rs
- circuits/src/zk_circuits/mod.rs
- circuits/src/zk_circuits/valid_wallet_create.rs
- circuits/src/zk_gadgets/wallet_operations.rs
- common/src/types/tasks/descriptors/mod.rs
- common/src/types/tasks/descriptors/new_wallet.rs
- external-api/src/http/wallet.rs
- workers/api-server/src/http/wallet.rs
- workers/task-driver/integration/tests/create_new_wallet.rs
- workers/task-driver/src/tasks/create_new_wallet.rs
- workers/task-driver/src/tasks/node_startup.rs
This PR enforces that a new wallet's public blinder is correctly constructed from a blinder seed. This prevents malicious darkpool users from "frontrunning a blinder" and thereby temporarily blocking an _existing_ user's wallet update.
> circuits: zk-circuits: valid-wallet-create: Add public blinder check

- common/src/types/tasks/descriptors/new_wallet.rs
This PR adds a default deserialization for the blinder seed on a new wallet task
> common: descriptors: new-wallet: Add serde default for blinder seed

- external-api/src/http/external_match.rs
- workers/task-driver/src/tasks/settle_match_external.rs
This PR changes the external match result type to use API friendly and consistent types.
> external-api: external-match: Use API friendly types in external match

- common/src/types/wallet/orders.rs
- workers/task-driver/src/tasks/refresh_wallet.rs
This PR updates the order ID matching logic to consider orders equivalent if they are on the same pair and side; rather than direct equality. This allows us to match order IDs after a partial fill, e.g. by an atomic settlement.
> task-driver: refresh-wallet: Match order ids on same pair and side

- docker/sequencer/deploy_contracts.sh
- util/src/arbitrum.rs
- workers/task-driver/integration/main.rs
This PR updates the `deploy_contracts.sh` script in the testing sequencer image to use the new ERC20 deployment command as per https://github.com/renegade-fi/renegade-contracts/pull/269.
Our integration testing stack is outdated at the moment, so I'm deferring running the integration tests with these changes until it is fixed.
> docker: sequencer: deploy_contracts: use new erc20 deploy script

- workers/api-server/src/auth/mod.rs
This PR logs a warning when a deprecated auth method is used. We will look for these warnings to ensure no client is using deprecated auth before removing those auth handlers
- Tested the warning log
> api-server: auth: Log warning when deprecated auth is used

- renegade-metrics/src/helpers.rs
- renegade-metrics/src/labels.rs
- workers/handshake-manager/src/manager.rs
- workers/task-driver/src/tasks/settle_match_external.rs
- workers/task-driver/src/tasks/settle_match_internal.rs
This PR labels external matches with a tag `is_external_match = true` for external matches. This will help us disambiguate on the metrics dashboard side.
> renegade-metrics: helpers: Label external matches in volume metrics

- state/src/applicator/wallet_index.rs
- state/src/storage/tx/order_book.rs
This PR deletes orders when they are cancelled. We have the order history now so keeping around cancelled orders merely pollutes the table.
- Prune phantom orders from state with migration
- Tested the case in which an order is deleted
> state: storage: order-book: Delete orders when cancelled

- state/src/storage/tx/order_book.rs
- workers/task-driver/src/lib.rs
- workers/task-driver/src/state_migration/mod.rs
- workers/task-driver/src/state_migration/remove_phantom_orders.rs
- workers/task-driver/src/tasks/node_startup.rs
This PR introduces the notion of a state migration to the relayer's startup task, and defines an initial one to remove phantom orders from the order book. These migrations are run in the last step of the node startup task and can be used to define arbitrary cleanup, backfill, etc logic. 
The migration defined here removes all orders which are not contained within a wallet.
- Relayer starts up correctly
- Tested against the mainnet snapshot, order book phantom orders went from 918 -> 0 and local order phantom orders went from 409 -> 0
> task-driver: state-migration: remove-phantom-orders: Define migration

- state/src/caching/mod.rs
- state/src/caching/order_cache.rs
- state/src/interface/mod.rs
- state/src/interface/peer_index.rs
- state/src/interface/raft.rs
- state/src/lib.rs
This PR adds an order book cache that will initial support two queries:
- Fetching the locally matchable orders
- Fetching the externally matchable local orders
This cache will evolve into a more complex caching layer in which we can query for orders e.g. by pair and side.
- Will test the match cache once it's integrated in a follow-up
> state: caching: order-cache: Add order book cache

- state/src/applicator/mod.rs
- state/src/applicator/order_book.rs
- state/src/applicator/wallet_index.rs
- state/src/caching/order_cache.rs
- state/src/interface/mod.rs
- state/src/replication/error.rs
- state/src/replication/state_machine/mod.rs
This PR adds logic in the state transition handlers to keep the order book cache up to date. Specifically:
- When a new order is added to a wallet, we add it to the `externally_enabled` cache if it has `allow_external_matches=true`
- When an order is cancelled, we remove it from the cache entirely
- When an order's validity proof is added to the state, we add it to the `matchable_orders` cache
- Added unit tests
- Will test full functionality when I integrate into the matching engine queries
> state: applicator: Update order book cache on state updates

- state/src/applicator/mod.rs
- state/src/applicator/order_book.rs
- state/src/applicator/order_history.rs
- state/src/caching/order_cache.rs
- state/src/interface/order_book.rs
- state/src/interface/order_history.rs
- state/src/interface/wallet_index.rs
- state/src/replication/state_machine/snapshot.rs
- state/src/storage/tx/wallet_index.rs
- workers/api-server/src/http/admin.rs
- workers/handshake-manager/src/manager.rs
- workers/handshake-manager/src/manager/matching/external_engine.rs
- workers/handshake-manager/src/manager/matching/internal_engine.rs
- workers/task-driver/src/state_migration/remove_phantom_orders.rs
This PR adds logic to backfill an orderbook cache from a received snapshot. This will bring cache consistency between nodes when a new node comes online.
- Test extensively in testnet
- Added a test applying a snapshot to the cache
> state: replication: snapshot: Backfill order book cache from snapshot

- arbitrum-client/src/client/event_indexing.rs
- arbitrum-client/src/helpers.rs
This PR adds logic to the `arbitrum-client` to parse shares from an unknown selector as a fallback. This may occur if, for example, the darkpool is called as part of a nested transaction.
- Upgrade RPC provider and use a tracing API for a more robust solution
- Looked up quoters that are stuck in mainnet successfully
> arbitrum-client: event-indexing: Parse shares from nested transactions

- config/src/cli.rs
- core/src/main.rs
- mock-node/src/lib.rs
- workers/api-server/src/http.rs
- workers/api-server/src/http/external_match.rs
- workers/api-server/src/http/wallet.rs
- workers/api-server/src/worker.rs
This PR returns 400 in the external match endpoint if an `ExternalOrder` is sent with an order size below the minimum fill size. This is as opposed to soft blocking these requests by failing to match them.
- Tested the endpoint with a small order
> api-server: external-match: Return 400 if order size too small

- common/src/types/exchange.rs
- external-api/src/http/external_match.rs
- workers/api-server/src/http/admin.rs
- workers/api-server/src/http/external_match.rs
- workers/api-server/src/http/price_report.rs
- workers/handshake-manager/src/manager/price_agreement.rs
- workers/job-types/src/price_reporter.rs
- workers/price-reporter/src/mock.rs
This PR allows for quote-denominated external orders at the api layer. We do this by sampling a price and converting a quote-denominated order to a base-denominated one before passing the order to the matching engine.
I also refactored some logic in the price reporter's queue to give a cleaner interface.
- Tested with both quote denominated and base denominated orders
> external-api: external-match: Allow quote denominated external orders

- arbitrum-client/src/client/event_indexing.rs
- arbitrum-client/src/errors.rs
- arbitrum-client/src/helpers.rs
This PR changes the unknown selector wallet share parsing logic to use the `debug_traceTransaction` RPC method. Previously we were scanning the calldata for a known selector, which is not robust.
The new approach walks the call tree, finding all transactions to the darkpool, then attempts to parse wallet shares from each one. We also check that the parsed wallet shares' public blinder matches the expected blinder, in case multiple darkpool transactions were submitted in one parent frame.
> arbitrum-client: event-indexing: Use debug traces for unknown selectors

- Cargo.lock
- core/src/main.rs
- external-api/src/http/external_match.rs
- mock-node/src/lib.rs
- workers/api-server/Cargo.toml
- workers/api-server/src/http.rs
- workers/api-server/src/http/external_match.rs
- workers/api-server/src/worker.rs
This PR does gas estimation on an external match transaction if requested by the client.
> api-server: external-match: Do gas estimation if requested

- workers/task-driver/src/tasks/settle_match_external.rs
This PR updates the external party's relayer fee to be zero for external matches
> task-driver: settle-match-external: Set external relayer fee to zero

- external-api/src/bus_message.rs
- external-api/src/http/external_match.rs
- workers/api-server/src/http.rs
- workers/api-server/src/http/external_match.rs
- workers/handshake-manager/src/manager.rs
- workers/handshake-manager/src/manager/matching/external_engine.rs
- workers/job-types/src/handshake_manager.rs
- workers/price-reporter/src/manager/native_executor.rs
This PR adds an endpoint to generate a quote for an external match. This does not require proving a valid atomic match settlement, nor locking up an order for an atomic match. It is intended to allow clients to quickly gauge a price for an intended external match.
> api-server: external-match: Add endpoint to generate an external quote

- common/src/types/exchange.rs
- common/src/types/token.rs
- config/src/token_remaps.rs
- workers/price-reporter/src/exchange.rs
- workers/price-reporter/src/exchange/binance.rs
- workers/price-reporter/src/exchange/coinbase.rs
- workers/price-reporter/src/exchange/kraken.rs
- workers/price-reporter/src/exchange/okx.rs
- workers/price-reporter/src/mock.rs
This PR removes the relayer's mapping of supported exchanges for each token ticker in favor of parsing this information from the new token mapping format.
This was tested w/ a couple quick unit tests where we fetch the testnet token mapping, and try instantiating token objects / reading their supported exchanges & tickers, and by running a price reporter that ingested these changes and asserting that all price streams were initialized correctly.
I also tested a number of trades in testnet using this version of the relayer & the associated price reporter version, both buys & sells, high-cap & low-cap tokens. Everything worked smoothly.
> common: token: get supported exchanges from token mapping

- external-api/src/http/external_match.rs
- workers/api-server/src/http.rs
- workers/api-server/src/http/external_match.rs
This PR signs the external quote handed back to the external party. This allows the external party to submit the quote to be assembled with the signature as proof that the quote is valid. This allows the relayer to keep the quote's price firm between quote and assembly.
> api-server: external-match: Sign external match quotes

- workers/api-server/src/http.rs
- workers/api-server/src/http/external_match.rs
- workers/api-server/src/http/wallet.rs
- workers/job-types/src/handshake_manager.rs
This PR defines the `ExternalMatchProcessor` type, which papers over the shared logic of requesting, processing, and estimating gas for external quotes. This is ahead of the implementation of an external quote assemble endpoint, which will run the external engine using a previously quoted price.
> api-server: external-match: Refactor helpers -> `ExternalMatchProcessor`

- Cargo.toml
- circuit-types/src/match.rs
- external-api/src/http/external_match.rs
- workers/api-server/src/http/external_match.rs
This PR adds the fee take and two fields indicating the external party's net transfers to the atomic match bundle response. This allows the external party to know exactly the amount they will receive after executing the transaction, without any extra computation on their end.
> api-server: external-match: Add extra detail for external match fees

- Cargo.lock
- common/src/types/token.rs
- config/src/token_remaps.rs
- core/src/main.rs
- external-api/src/http/admin.rs
- mock-node/src/lib.rs
- renegade-metrics/src/helpers.rs
- workers/api-server/Cargo.toml
- workers/api-server/src/http.rs
- workers/api-server/src/http/admin.rs
- workers/api-server/src/worker.rs
- workers/handshake-manager/src/manager/price_agreement.rs
- workers/price-reporter/src/mock.rs
- workers/task-driver/integration/main.rs
This PR adds a new admin endpoint that refreshes the token mapping from the remote source (Github repo). Implementing this required changing the way in which we store the static token mapping objects (address -> ticker mapping, address -> decimals mapping, ticker -> supported exchanges mapping). Namely, instead of using a `OnceLock` that is initialized at startup, we wrap a `RwLock` with a `LazyLock` so we can have a mutable statics that can be overwritten by the refresh endpoint.
Mutable static structures may raise eyebrows, but this approach felt simpler than lifting the mappings into heap-allocated objects that we pass around references to, particularly when one considers that consumers of the relayer library crates (i.e., the price reporter) also rely on these statics being set.
This …
> external-api: admin: add token mapping refresh endpoint

- external-api/src/http/external_match.rs
- workers/api-server/src/http.rs
- workers/api-server/src/http/external_match.rs
- workers/handshake-manager/src/manager.rs
- workers/handshake-manager/src/manager/matching/external_engine.rs
- workers/job-types/src/handshake_manager.rs
This PR adds an endpoint for external match clients to assemble quotes that they receive from the relayer.
> api-server: external-match: Add endpoint to assemble quotes to bundles

- external-api/src/http/external_match.rs
- workers/api-server/src/http/external_match.rs
This PR allows the `min_fill_size` to be specified in quote units in the external matching engine. Specifically, if the size of the order is specified by `quote_amount`, we expect `min_fill_size` in units of the quote asset. Whereas if the order size is specified by `base_amount`, we expect it in units of base.
> api-server: external-match: Allow `min_fill` in quote units

- external-api/src/http/order_book.rs
- external-api/src/types/api_order_book.rs
- workers/api-server/src/http.rs
- workers/api-server/src/http/order_book.rs
This PR adds a `/v0/supported-tokens` endpoint to the relayer, returning a list of tokens by address and ticker.
> api-server: Add `/v0/supported-tokens` route

- external-api/src/http/order_book.rs
- external-api/src/types/api_order_book.rs
- workers/api-server/src/http.rs
- workers/api-server/src/http/order_book.rs
- workers/api-server/src/router.rs
This PR sets the `Content-Type` header to "application/json" on all HTTP `GET` or `POST` responses.
> api-server: router: Add `Content-Type` header to http responses

- arbitrum-client/src/abi.rs
- arbitrum-client/src/client/contract_interaction.rs
- arbitrum-client/src/client/event_indexing.rs
- arbitrum-client/src/helpers.rs
- external-api/src/http/external_match.rs
- workers/api-server/src/http/external_match.rs
This PR adds support for a non-sender receiver address in the tx calldata generated for an external match. If one is specified the calldata generated targets the `processAtomicMatchSettleWithReceiver` selector, otherwise the calldata targets the `processAtomicMatchSettle` selector as before.
> arbitrum-client: Add `receiver_address` to external match settlement calldata

- Cargo.lock
- config/src/cli.rs
- config/src/parsing.rs
- core/Cargo.toml
- core/src/main.rs
- metrics-sampler/src/lib.rs
- state/src/applicator/order_book.rs
- state/src/applicator/task_queue.rs
- state/src/interface/node_metadata.rs
- state/src/lib.rs
- state/src/storage/error.rs
- state/src/storage/tx/node_metadata.rs
- state/src/storage/tx/order_history.rs
- state/src/storage/tx/task_history.rs
- workers/api-server/src/http/admin.rs
- workers/api-server/src/http/task.rs
- workers/event-manager/Cargo.toml
- workers/event-manager/src/error.rs
- workers/event-manager/src/lib.rs
- workers/event-manager/src/worker.rs
- workers/job-types/Cargo.toml
- workers/job-types/src/event_manager.rs
- workers/job-types/src/lib.rs
- workers/task-driver/src/utils/order_states.rs
This PR adds the necessary config options for the event manager worker and massages them into the relayer. This includes scaffolding the event manager worker itself, and optionally disabling access to the historical state tables if the associated config option is unset.
Even when historical state is disabled, we intend to maintain an updated view of order metadata for actively-managed (not filled nor cancelled) orders. The logic for disabling historical state does not currently capture this nuance, as the implementation is deferred for later.
All unit tests pass assuming local historical state is enabled, the config option for which has been defaulted to true for now. End-to-end testing w/ historical state disabled will be done when event exporting is implemented.
> config, workers: event-manager: event manager worker config

- Cargo.lock
- core/src/main.rs
- workers/event-manager/Cargo.toml
- workers/event-manager/src/error.rs
- workers/event-manager/src/lib.rs
- workers/event-manager/src/manager.rs
- workers/event-manager/src/worker.rs
This PR introduces the `EventManagerExecutor`, responsible for the core logic of exporting ingested events to the configured address. Currently, we only support Unix socket addresses.
I tested that the worker runs without issue when the event manager is disabled (i.e., no socket address provided), and will test proper event export once the sidecar responsible for this is implemented in the next PR.
> workers: event-manager: manager: create event manager executor

- Cargo.lock
- core/src/main.rs
- mock-node/src/lib.rs
- workers/event-manager/Cargo.toml
- workers/event-manager/src/error.rs
- workers/event-manager/src/lib.rs
- workers/event-manager/src/manager.rs
- workers/event-manager/src/worker.rs
- workers/job-types/src/event_manager.rs
- workers/task-driver/integration/helpers.rs
- workers/task-driver/integration/main.rs
- workers/task-driver/src/driver.rs
- workers/task-driver/src/tasks/create_new_wallet.rs
- workers/task-driver/src/tasks/settle_match_external.rs
- workers/task-driver/src/tasks/settle_match_internal.rs
- workers/task-driver/src/tasks/update_wallet.rs
- workers/task-driver/src/traits.rs
- workers/task-driver/src/worker.rs
This PR implements the construction & emitting of events from across the relayer to the new event manager worker.
One thing to note: we emit events right before tasks complete, to obviate any possibility of task retries causing duplicate event emission. I chose this approach for simplicity, and because empirically we have very few failure beyond a task's commit point. With that said, of course we can consider some deduplication scheme / deterministic event IDs, and then emit events right after a task's commit point.
All unit tests pass, and e2e testing is deferred until the receiving side of these events is implemented in the event manager worker
> workers: task-driver: emit events from tasks

- Cargo.lock
- Cargo.toml
- config/src/cli.rs
- config/src/parsing.rs
- core/src/main.rs
- docker/release/Dockerfile
- node-support/bootloader/src/main.rs
- node-support/event-export-sidecar/Cargo.toml
- node-support/event-export-sidecar/src/event_socket.rs
- node-support/event-export-sidecar/src/hse_client.rs
- node-support/event-export-sidecar/src/main.rs
- workers/event-manager/Cargo.toml
- workers/event-manager/src/error.rs
- workers/event-manager/src/manager.rs
- workers/event-manager/src/worker.rs
- workers/job-types/src/event_manager.rs
This PR adds a new `node-support` daemon responsible for re-exporting events from the relayer to the historical state engine. It establishes the Unix socket the relayer exports events to, listens for events on this socket, and submits them to the HSE.
As a part of these changes, I swapped the `Multiaddr` `event_export_addr` config option for a `Url`-based one. This was due to parsing issues with Unix multiaddrs - it interprets `/` as a protocol delimiter so only sibling paths could be used for a socket. URLs capture the same flexibility that we need between HTTP and Unix addresses with better parsing.
**Testing:**
I tested this with a local relayer / sidecar / HSE / DB with the following flow: create wallet, deposit, place order, match, withdraw (and on one of the wallets, cancel order).
> node-support: event-export-sidecar: create event export sidecar

- external-api/src/http/external_match.rs
This PR adds a `get_quote_amount` helper to precisely calculate the implied quote amount given a decimal corrected price.
> external-api: external_match: add `get_quote_amount` helper

- external-api/src/types/api_network_info.rs
- workers/api-server/src/http/network.rs
This PR add an `is_leader` field to the network topology API response. This allows consumers to direct requests to the leader. Internally, we will use this functionality to request a snapshot from the leader when a cluster upgrade begins.
> external-api: network-info: Mark raft leader as such

- external-api/src/http/external_match.rs
- workers/api-server/src/http/external_match.rs
This PR allows an external order to update in between quote and assembly. Updates are allowed on the following fields:
- `base_amount`: To facilitate base denominated updates
- `quote_amount`: To facilitate quote denominated updates
- `min_fill_size`: To adjust the minimum fill in accordance with the base/quote update
This allows e.g. solvers to tweak a quote after assembling a route while being guaranteed a firm price.
> api-server: external-match: Allow order amounts to change in assemble

- external-api/src/http/external_match.rs
This PR replaces `biguint_to_hex_string` with `biguint_to_hex_addr` so that hex strings are padded to the Ethereum address length. This addresses an issue where match bundles were returning mints with invalid Etheruem addresses due to lack of padding.
> external-api: external_match: fix mint serialization in match_bundle

- util/src/telemetry/datadog/formatter.rs
- workers/job-types/src/event_manager.rs
This PR adds descriptor methods to the top-level `RelayerEvent` enum and the individual event variants. This is useful for any consuming crates that want to do logging around events. 
Additionally, we upgrade the datadog log formatter to include the fields of the current span in the JSON log. In the event of any failure to parse these fields, we silently omit them. This allows us to capture useful contextual information directly on logs, even if their surrounding spans are sampled out.
> workers: job-types: event_manager: add descriptor methods to relayer events

- state/src/replication/raft.rs
Currently, when syncing with the leader, followers receive `AppendEntries` requests that are too large to deserialize and store within the timeout.
So, this PR tweaks the append entries timeout to be higher and makes the leader's log purge strategy more aggressive.
> state: replication: raft: Tweak params to allow nodes to sync

- circuit-types/src/order.rs
- common/src/types/wallet/mod.rs
- common/src/types/wallet/orders.rs
- state/src/caching/mod.rs
- state/src/caching/order_cache.rs
- state/src/caching/order_metadata_index.rs
This PR builds an `OrderMetadataIndex` that will operate as part of the order book cache. The metadata index allows us to query open orders by pair and side, sorted by matchable amount. This will allow for more efficient access in the matching engine and prevent small fills when a larger fill is possible.
- Will test in a follow-up when the cache is integrated with the state and matching engine
> state: caching: order-metadata-index: Build order metadata index

- state/src/caching/order_metadata_index.rs
This PR adds support for updating the matchable amount of an order and deleting an order from the cache.
- Will test end-to-end when integrated into the matching engine
> state: caching: order-metadata-cache: Support order amount updates and deletion

- state/src/applicator/order_book.rs
- state/src/applicator/wallet_index.rs
- state/src/caching/order_cache.rs
- state/src/interface/order_book.rs
- state/src/replication/state_machine/snapshot.rs
This PR modifies the read path of the order cache to use the new order metadata based access methods
> state: caching: order-cache: Build new filter-based cache interface

- core/src/main.rs
- mock-node/src/lib.rs
- state/src/applicator/mod.rs
- state/src/applicator/task_queue.rs
- state/src/interface/mod.rs
- state/src/lib.rs
- workers/job-types/src/event_manager.rs
This PR introduces a `TaskCompletion` event type, representing the completion of a task (successful or not). This will be used to index task history, and as such it is basically a wrapper around the `HistoricalTask` type. This event gets emitted in the state applicator in the same code path where we record historical tasks. As such, we check that the local peer is the executor of the task before emitting the event, to prevent duplicate event emission across the cluster.
> workers: job-types, state: applicator: emit task completion events

- common/src/types/wallet/balances.rs
- state/src/applicator/error.rs
- state/src/applicator/matching_pools.rs
- state/src/applicator/order_book.rs
- state/src/applicator/task_queue.rs
- state/src/caching/order_cache.rs
- state/src/caching/order_metadata_index.rs
- state/src/interface/order_book.rs
- state/src/replication/error.rs
- state/src/replication/state_machine/snapshot.rs
- workers/api-server/src/http/admin.rs
- workers/handshake-manager/src/manager.rs
- workers/handshake-manager/src/manager/matching/external_engine.rs
- workers/handshake-manager/src/manager/matching/internal_engine.rs
- workers/handshake-manager/src/manager/matching/mod.rs
This PR adds back in write paths for the order book cache and uses the new order book cache in the state interface. This involves two caller locations:
- The admin API, which roughly just uses renamed methods
- The matching engine, which now constructs an order book filter based on the order it is trying to match
> state: interface: Use new order book cache in interface methods

- external-api/src/http/task_history.rs
- external-api/src/http/wallet.rs
- workers/api-server/src/http/task.rs
- workers/api-server/src/http/wallet.rs
This PR adds a `pagination_token` field to the `GetOrderHistoryResponse` and `GetTaskHistoryResponse` structs. This allows for these APIs to support pagination, though we leave it safely unimplemented for now.
> external-api: wallet, task_history: add pagination token to historical APIs

- config/src/cli.rs
- config/src/parsing.rs
- state/src/applicator/order_book.rs
- state/src/applicator/order_history.rs
- state/src/interface/node_metadata.rs
- state/src/storage/tx/order_history.rs
- workers/api-server/src/http/admin.rs
- workers/api-server/src/http/wallet.rs
- workers/api-server/src/websocket/task.rs
- workers/task-driver/src/tasks/update_wallet.rs
- workers/task-driver/src/utils/order_states.rs
This PR tweaks the state & API code paths dependent on historical state being enabled. We allow for tracking "actively-managed historical state," i.e. historical state pertaining to objects (order metadata, tasks) which may still be updated by the relayer. Concretely, this means:
- Tasks
- We continue streaming task status updates over websocket via _both_ the task status and task history topics. We continue to enable the task history topic since it is a reliable source of all task status updates for a given wallet.
- We do not write tasks to the task history table if historical state is disabled.
- Orders
- We now allow writing to / reading from the order history table even if historical state is disabled. However, if historical state is disabled we remove orders from the table once they …
> state, workers: allow for actively-managed historical state

- state/src/lib.rs
This PR fixes red CI tests in `main`. The state unit tests need to set `record_historical_state=true` after this CLI flag was added to the config.
> state: Fix unit tests after historical state CLI flag added

- arbitrum-client/src/abi.rs
- external-api/src/http/admin.rs
- workers/api-server/src/error.rs
- workers/api-server/src/http.rs
- workers/api-server/src/http/admin.rs
This PR adds an endpoint to refresh external match fees with admin authentication
> api-server: admin: Add endpoint to refresh external match fees

- util/src/telemetry/metrics.rs
- util/src/telemetry/mod.rs
This PR adds ability to configure metrics parameters (prefix, buffer size, queue size) while maintaining backwards compatibility. The existing `configure_telemetry` function remains unchanged, while a new `configure_telemetry_with_metrics_config` function allows optional configuration of these parameters.
> util: add metrics config

- workers/api-server/src/http/external_match.rs
This PR switches the fee estimation in the quote endpoint to use `get_external_match_fee` as opposed to `get_protocol_fee`. This correctly accounts for overridden fees in quotes.
> api-sever: http: external-match: Use override fees in quote amounts

- .github/workflows/test.yml
- Cargo.lock
- circuits/Cargo.toml
- circuits/src/lib.rs
- circuits/src/zk_circuits/proof_linking.rs
- circuits/src/zk_circuits/valid_match_settle/mod.rs
- state/Cargo.toml
- state/src/applicator/order_book.rs
- state/src/applicator/wallet_index.rs
- state/src/replication/mod.rs
This PR gates long-running unit tests behind a `ci` feature flag, and enables that flag (disabling the tests) in github workflows. This allows us to run tests in debug mode, so that the total time taken to run all tests does not exceed what the test runners allow
> workspace: Gate long tests behind `ci` feature flag

- workers/api-server/src/auth/mod.rs
- workers/api-server/src/router.rs
This PR tweaks the wallet & admin auth handlers to expect the query string to be included in the path when validating an authenticated request's HMAC.
However, since there are clients that are currently implemented with the assumption that query strings should be excluded from the HMAC signature, we introduce some shim code here that first attempts to validate auth with the expectation that query strings are included in the path, then falls back to to validating auth while excluding query strings from the path. This is a temporary provision to ensure that deploying this change in the relayer does not require coupled client-side upgrades.
I tested this by running a local relayer & local frontend, and attempted to invoke the task history endpoint for a wallet with the `task_history_len` …
> workers: api-server: auth, router: include query string in path for auth

- external-api/src/types/api_task_history.rs
This PR derives `PartialEq, Eq` for the `ApiHistoricalTask` type. This makes testing the historical state engine significantly easier.
Tested by testing the historical state engine, which uses this type.
> external-api: types: api_task_history: derive eq impls

- common/src/types/tasks/descriptors/settle_match.rs
- workers/api-server/src/http/external_match.rs
- workers/handshake-manager/src/manager.rs
- workers/handshake-manager/src/manager/matching/external_engine.rs
- workers/job-types/src/handshake_manager.rs
- workers/task-driver/src/tasks/settle_match_external.rs
This PR makes the bundle timeout configurable as input to the matching engine. The API server uses this option to configure the timeout different based on whether the bundle is produced from the direct match flow versus the assemble flow.
> handshake-manager: external-engine: Use configurable bundle timeout

- Cargo.lock
- workers/task-driver/src/tasks/settle_match_external.rs
This PR changes the way that metrics are reported in the `settle-external-match` task to watch for settlement and report on a separate thread. This allows the main thread to wait for a configurable timeout without early-exiting the metrics report.
> task-driver: settle-match-external: Report metrics regardless of timeout

- external-api/src/http/task.rs
- workers/api-server/src/http.rs
- workers/api-server/src/http/task.rs
This PR adds an API endpoint for checking if a wallet's queue is paused.
> external-api; workers: api-server: add task queue paused route

- arbitrum-client/src/client/event_indexing.rs
- arbitrum-client/src/constants.rs
- arbitrum-client/src/errors.rs
- workers/task-driver/src/tasks/settle_match_external.rs
This PR filters the settlement waiter in `settle-match-external` by the selectors used for atomic matches.
> task-driver: settle-match-external: Filter settlement by selector

- state/src/storage/tx/order_history.rs
- state/src/storage/tx/task_history.rs
- workers/task-driver/src/state_migration/mod.rs
- workers/task-driver/src/state_migration/purge_historical_state.rs
- workers/task-driver/src/state_migration/remove_phantom_orders.rs
- workers/task-driver/src/tasks/node_startup.rs
This PR adds a new state migration for purging historical state. Namely, this means removing terminal orders from order history and all task history, for all wallets. We no longer need to track this in the relayer since the historical state engine is active.
> workers: task-driver: state_migration: purge historical state startup task

- external-api/src/http/mod.rs
- external-api/src/http/order_book.rs
- external-api/src/types/api_order_book.rs
- external-api/src/types/mod.rs
- workers/api-server/src/http.rs
- workers/api-server/src/http/order_book.rs
This PR publishes the types, route definition, and response structure for the supported tokens route out from behind the `order-book-api` feature flag, so that it is available always.
> external-api: types: Move supported tokens from behind feature flag

- circuit-types/src/fixed_point.rs
- config/src/cli.rs
- external-api/Cargo.toml
- external-api/src/http/external_match.rs
- test-helpers/src/mpc_network/mock_with_delay.rs
- workers/api-server/src/http/external_match.rs
- workers/handshake-manager/src/manager/matching/external_engine.rs
- workers/job-types/src/handshake_manager.rs
This PR allows for two new ways to specify the size of an external match:
- `exact_base_output`: Enforces that _exactly_ `exact_base_output` of the base token is received by the API user, net of fees.
- `exact_quote_output`: Enforces that _exactly_ `exact_quote_output` of the quote token is received by the API user, net of fees.
> api-server: external-match: Allow `exact_base_output` and `exact_quote_output` order size specifiers

- constants/src/lib.rs
- external-api/src/http/order_book.rs
- workers/api-server/src/http.rs
- workers/api-server/src/http/external_match.rs
- workers/api-server/src/http/order_book.rs
- workers/task-driver/src/tasks/settle_match_external.rs
This PR adds the an endpoint for fetching external match fees on an asset: `/v0/order_book/external-match-fee?mint=0xdeadbeef`. This returns both the relayer and protocol fee.
> api-sever: order-book: Add external match fee endpoint

- .gitignore
- workers/proof-manager/src/proof_manager.rs
- workers/task-driver/src/tasks/settle_match_external.rs
This PR fixes a small bug wherein the relayer fee used in the `VALID MATCH SETTLE ATOMIC` witness is overridden with the external party's fee. This was introduced in #902.
> task-driver: settle-match-external: Use correct relayer fee for witness

- circuits/src/zk_gadgets/poseidon.rs
- circuits/src/zk_gadgets/poseidon/gates.rs
- circuits/src/zk_gadgets/poseidon/hash.rs
- circuits/src/zk_gadgets/poseidon/mod.rs
This PR makes a series of optimizations to the Poseidon2 gadgets that fuse multiple permutation rounds across gates, to minimize the gate footprint.
The result is a significant decrease in the gates used for the following circuits. This results in decrease in the power of two rounding used for most circuits, halving their prover time.
- **Single Poseidon Hash**: 359 -> 199 gates
- `VALID WALLET CREATE`: 13575 -> 7655 gates
- `VALID WALLET UPDATE`: 54715 -> 32155 gates
- `VALID REBLIND`: 75857 -> 42097 gates
- `VALID OFFLINE FEE SETTLEMENT`: 80145 -> 46065 gates
- `VALID RELAYER FEE SETTLEMENT`: 128289 -> 72449 gates
- `VALID FEE REDEMPTION`: 65792 -> 37792 gates
> circuits: zk-gadgets: poseidion: Fuse Poseidon rounds across gates

- circuits/src/lib.rs
- circuits/src/zk_circuits/mod.rs
- circuits/src/zk_circuits/valid_malleable_match_settle_atomic.rs
- circuits/src/zk_circuits/valid_match_settle_atomic.rs
This PR adds an initial set of tests for the constraints in `VALID MALLEABLE MATCH SETTLE ATOMIC`.
- Test price protection, shares, and misc
- Benchmarks
> circuits: zk-circuits: valid-malleable-match: Add constraint tests

- circuits/Cargo.toml
- circuits/benches/valid_malleable_match_settle_atomic.rs
This PR adds a benchmark for the `VALID MALLEABLE ATOMIC MATCH SETTLE` circuit. The current benchmark results are the following:
- **Constraint Generation**: 223.22us
- **Prover**: 101.45ms
- **Verifier**: 1.07ms
> circuits: benches: valid-malleable-match: Add benchmark

- workers/api-server/src/http/external_match.rs
- workers/api-server/src/http/wallet.rs
This PR improves the error message emitted when the relayer is unable to fetch a price reporter at the API layer. Rather than `{ "code": 500, "error": "NotEnoughDataReported(0)" }` we respond with `{ "code": 500, "error": "price too stale for matching, try again shortly" }`.
> api-server: http: external-match: Improve price reporter error message

- workers/api-server/src/http/external_match.rs
This PR sets the assemble match timeout to zero to temporarily reduce quoter contention
> api-server: external-match: Set assembly timeout to zero temporarily

- circuits/src/zk_circuits/proof_linking.rs
- workers/task-driver/src/tasks/settle_match_external.rs
This PR adds helpers for proving the proof-link relation between an atomic match circuit and `VALID COMMITMENTS`. Because the match circuits use the same link group layouts, I generalized the helper to cover all atomic match proof links -- malleable or not.
This PR also adds a test suite for the linking relation between `VALID MALLEABLE MATCH SETTLE ATOMIC` and `VALID COMMITMENTS`, with valid and invalid test cases.
> circuit: zk-circuits: proof-linking: Add malleable match proof links

- workers/api-server/src/http/admin.rs
- workers/task-driver/src/tasks/node_startup.rs
In this PR, we set the relayer's local view of the native ETH external match fee on node startup and in the external match fees refresh endpoint. This ensures that, for example, we return the correct expected receive & fee amounts when returning an external match quote.
> workers: api-server, task-driver: set native asset external match fee

- Cargo.lock
- Cargo.toml
This PR patches `parity-scale-codec-derive` to `v3.6.12` to fix an incompatibility with `parity-scale-codec@3.6.12` generated by `ethers`. 
See [this issue](https://github.com/paritytech/parity-scale-codec/issues/702) for more info.
- Built the `test-helpers` crate with features `contracts`, previously failed
> Cargo.toml, Cargo.lock: Patch `parity-scale-codec-derive` to `v3.6.12`

- Cargo.lock
- arbitrum-client/Cargo.toml
- arbitrum-client/src/client/contract_interaction.rs
- arbitrum-client/src/contract_types/mod.rs
- arbitrum-client/src/contract_types/serde_def_types.rs
- arbitrum-client/src/contract_types/types.rs
- arbitrum-client/src/conversion.rs
- arbitrum-client/src/helpers.rs
- arbitrum-client/src/lib.rs
- common/Cargo.toml
- common/src/types/tasks/descriptors/mod.rs
- common/src/types/tasks/descriptors/update_wallet.rs
- common/src/types/wallet/keychain.rs
This PR removes the dependency on `contracts-common` from the relayer repo, which previously caused a cyclic dependency. To do so, we directly replicate the functionality from the contracts into the relayer.
> arbitrum-client, common: Remove dependency on `contracts-common`

- common/src/types/token.rs
- workers/api-server/src/http/external_match.rs
- workers/handshake-manager/src/manager/price_agreement.rs
This PR explicitly validates the token pair in an external match. Currently, invalid pairs fail when fetching a price, with an unhelpful error message.
> api-server: external-match: Validate token pair explicitly

- circuits/src/zk_circuits/valid_malleable_match_settle_atomic.rs
This PR adds sized witness and statement types for the `VALID MALLEABLE MATCH SETTLE ATOMIC` circuit.
> circuits: zk-circuits: malleable-match: Add sized witness/statement types

- arbitrum-client/src/client/event_indexing.rs
This PR removes the error log emitted by awaiting nullifier spent. This would log an error even in the case that a nullifier cannot be found. We defer to higher level callers to determine if this is an error, and log as appropriate.
> arbitrum-client: event-indexing: Do not log error waiting for nullifier

- Cargo.toml
This PR disables default features for the `constants` crate at the workspace level. Without this, workspace crates referring to `constants` via the workspace will turn on default features. The default `constants` features are not wasm compatible, so external crates that need wasm builds were failing.
> Cargo.toml: Disable `constants` default features at workspace level

- Cargo.lock
- Cargo.toml
This PR downgrades our Alloy dependencies to match the versions used in the latest Stylus SDK.
All unit tests pass.
> meta: downgrade alloy to match Stylus SDK deps

- common/Cargo.toml
- common/src/types/token.rs
- util/Cargo.toml
- util/src/lib.rs
- util/src/serde.rs
This PR changes the (de)serialization of the `Token` type to always lowercase strings. This provides a more sensible API for, among other things, fetching prices -- in which the request should not be case sensitive.
> common: types: token: (De)serialize token addresses as lowercase str

- core/Cargo.toml
- state/Cargo.toml
- state/src/applicator/task_queue.rs
- state/src/storage/tx/task_queuev2.rs
This PR changes the applicator logic for the task queue to double write between the v1 and v2 implementations of the task queue. This will be deployed independently and subsequently migrated into a version that _reads from_ the v2 task queues and implements their locking semantics. 
I also made a few cleanups for unused helpers in the applicator, and removed the task queue length metrics (also unused).
> storage: applicator: task-queue: Double write task updates

- workers/api-server/src/http/external_match.rs
This PR updates the token validation logic in the external match API to allow either named tokens or the native token address. Previously we were only checking for named tokens, thereby disallowing native asset requests erroneously.
> api-server: external-match: Allow native asset in token validation

- state/src/applicator/mod.rs
- state/src/applicator/task_queue.rs
- state/src/interface/task_queue.rs
- state/src/lib.rs
- state/src/storage/tx/task_queuev2.rs
This PR updates the `TaskQueue` to track its preemption state, and enforces valid transitions in the `TaskQueue` update helpers. These transitions enforce the write-preferenced access class logic that the new task queue implements. 
We add the access logic to the `TaskQueue` type so that it remains internally consistent through mutations, rather than encoding the access logic at higher layers (the applicator) which may be prone to bad writes.
> state: storage: task-queuev2: Add write-preference access class logic

- state/src/applicator/task_queue.rs
- state/src/storage/tx/task_queuev2.rs
This PR removes the `running_tasks` field from the `TaskQueue`. This won't be used for any task queue logic, so it's unnecessary to track.
> state: storage: task-queuev2: Remove running tasks from `TaskQueue`

- state/src/applicator/task_queue.rs
- state/src/lib.rs
- state/src/storage/tx/task_queuev2.rs
This PR allows a task to preempt multiple queues by changing the task to queue key mapping from `id -> id` to `id -> vec<id>`.
> state: storage: task-queuev2: Allow task to preempt multiple queues

- Cargo.lock
- state/Cargo.toml
- state/src/applicator/task_queue.rs
This PR adds the implementation of `EnqueuePreemptiveTask`. This state transition merely calls out to the preemption helpers in the storage layer and handles task assignment. For the migration, we also double write to the old task queue implementation.
The version in this PR will be deployed ahead of a version which switches over to using the new task queue for all preemptive tasks.
In a follow up, deployed separately:
- Change the pop and transition task helpers to use the new task queue
- Further tests with these new implementations
> state: applicator: task-queue: Implement `EnqueuePreemptiveTask`

- state/src/applicator/task_queue.rs
- state/src/storage/error.rs
- state/src/storage/tx/task_queuev2.rs
This PR changes the `pop_task` method to use the new queue primarily and only double write to the old queue.
I also moved the logic to enforce that a running task has not committed, and to requeue that task into the storage layer.
> state: applicator: task-queue: Use new task queue in pop method

- state/src/applicator/task_queue.rs
- state/src/storage/tx/task_queuev2.rs
This PR updates the remaining task queue applicator methods to use the new task queue implementation. 
I also added a few tests for the new task queue impl.
- Refactor the task driver to use the new preemptive tasks
> state: applicator: task-queue: Use new task queue for all methods

- state/src/lib.rs
- state/src/storage/db.rs
- state/src/storage/tx/mod.rs
- workers/task-driver/src/state_migration/mod.rs
- workers/task-driver/src/state_migration/remove_old_task_queues.rs
- workers/task-driver/src/tasks/node_startup.rs
This PR removes all keys for the old task queue implementation from the state using a state migration run during `NodeStartup` task execution.
This will be deleted after it is deployed.
> task-driver: state-migration: remove-old-task-queues: Add state migration

- core/src/setup.rs
- external-api/src/http/external_match.rs
- state/src/interface/order_book.rs
- workers/api-server/src/http/external_match.rs
- workers/handshake-manager/src/manager/matching/external_engine.rs
- workers/job-types/src/handshake_manager.rs
This PR adds an API option to allow a bundle to be shared with other clients. This will be exposed behind a higher rate limit on the auth server that sits in front of the relayer.
> api-server: external-match: Allow shared bundles on API

- common/src/types/exchange.rs
- common/src/types/token.rs
- workers/price-reporter/src/exchange.rs
This PR adds a `Renegade` variant to the `Exchange` enum. This will be used by the price reporter to support "renegade midpoint" and automatic quote translation.
> common: types: exchange, token: Add helpers for `Renegade` exchange

- external-api/src/http/external_match.rs
This PR fixes a bug where `requested_quote_amount` was incorrectly calculated as 0 for orders with `exact_base_output` set but `base_amount` unset.
The issue occurred because `get_quote_amount()` was directly using `self.base_amount` (which was 0) rather than the effective base amount calculated by `get_base_amount()`. This resulted in `get_quote_amount()` incorrectly returning 0. This only affected logging / metrics.
The fix modifies `get_quote_amount()` to use the effective base amount from `get_base_amount()` when neither `quote_amount` nor `exact_quote_output` is set. Circular dependencies should be impossible since `validate()` ensures exactly one of the sizing constraints is set, preventing recursive calls between the two methods.
- retrieved quotes using each type of amount …
> external-api: external_match: fix bug in get_quote_amount

- Cargo.lock
- arbitrum-client/src/client/event_indexing.rs
- arbitrum-client/src/contract_types/types.rs
- arbitrum-client/src/conversion.rs
- arbitrum-client/src/errors.rs
- workers/chain-events/Cargo.toml
- workers/chain-events/src/error.rs
- workers/chain-events/src/listener.rs
- workers/task-driver/src/tasks/settle_match_external.rs
This PR removes the nullifier watch loop from the settlement task. This is necessary as we now emit the same bundle to multiple clients who mark their requests with `allow_shared`. The existing logic in the settlement task would then double count each settlement for which it emits multiple bundles.
Instead, we move the metrics and wallet refresh logic to the `chain-events` worker, which will see each nullifier exactly once.
> chain-events: listener: Record external match metrics from spent nullifier

- Cargo.lock
- config/src/cli.rs
- core/src/main.rs
- mock-node/src/lib.rs
- workers/chain-events/Cargo.toml
- workers/chain-events/src/error.rs
- workers/chain-events/src/listener.rs
This PR allows the chain events listener to use a websocket connection rather than polling via the HTTP-based arbitrum client. This will allow us to receive nullifier events as fast as possible without spending API compute units polling in a short interval.
- Configure the relayer in testnet and mainnet to use a websocket connection
> chain-events: listener: Allow `chain-events` worker to use ws connection

- workers/api-server/src/http/external_match.rs
This PR marks all direct external match requests as shared. This parameter will not be configurable for the direct match path.
> api-server: http: external-match: Mark direct external matches as shared

- Cargo.lock
- arbitrum-client/src/abi.rs
- arbitrum-client/src/client/mod.rs
- arbitrum-client/src/conversion.rs
- core/Cargo.toml
- core/src/main.rs
- workers/chain-events/Cargo.toml
- workers/chain-events/src/error.rs
- workers/chain-events/src/listener.rs
This PR fixes the chain events listener's websocket implementation by using the `subscribe_logs` method directly rather than sending `eth_getFilterChanges` through the websocket as ethers will do by default. In the process, I also migrated this crate to use alloy.
> chain-events: listener: Use `subscribe_logs` for websocket client

- external-api/src/http/mod.rs
- external-api/src/http/price_report.rs
- external-api/src/lib.rs
- workers/api-server/src/http.rs
- workers/api-server/src/http/order_book.rs
- workers/api-server/src/http/price_report.rs
- workers/job-types/src/price_reporter.rs
This PR adds the `v0/token-prices` endpoint, which fetches all token prices for all pairs supported by the relayer.
> external-api: price-report: Add `/v0/token-prices` endpoint

- arbitrum-client/integration/helpers.rs
- arbitrum-client/src/contract_types/types.rs
- arbitrum-client/src/conversion.rs
- circuits/Cargo.toml
- circuits/benches/valid_wallet_create.rs
- circuits/src/zk_circuits/valid_wallet_create.rs
- test-helpers/src/contract_interaction.rs
- workers/task-driver/src/tasks/create_new_wallet.rs
This PR changes the `VALID WALLET CREATE` circuit to compute the full wallet commitment in-circuit, as opposed to by the contract. 
For `VALID WALLET CREATE` this increases the circuit size to the next power of two, but only implies a minimal impact on prover latency, from ~150ms -> ~324ms
> circuits: zk-circuits: wallet-create: Compute full wallet share comm

- arbitrum-client/src/contract_types/types.rs
- arbitrum-client/src/conversion.rs
- circuits/src/zk_circuits/valid_wallet_update.rs
- workers/task-driver/integration/helpers.rs
- workers/task-driver/src/tasks/update_wallet.rs
This PR changes the `VALID WALLET UPDATE` circuit to compute the wallet's full share commitment in circuit, as opposed to just the private share commitment.
This PR takes the circuit size to the next power of two which increases prover time from 634ms to 1.24s. This is the same prover time as before the Poseidon arithmetization optimizations in #904, though note that we have a considerably larger margin before the next power of two in gate count.
> circuits: zk-circuits: wallet-update: Compute full commitment in circuit

- circuits/Cargo.toml
- circuits/benches/valid_match_settle_with_commitments.rs
- circuits/src/zk_circuits/valid_match_settle/mod.rs
This PR adds a benchmark suite for the new `VALID MATCH SETTLE WITH COMMITMENTS` circuit.
- Benchmarks run
> circuits: benches: match-settle-commitments: Add benchmarks

- circuits/src/zk_circuits/valid_match_settle_atomic.rs
This PR adds a variant of `VALID MATCH SETTLE ATOMIC` which computes the full wallet commitment in-circuit. This is done to remove the need to compute this value in the contracts.
- Add a benchmark for the new circuit
> circuits: zk-circuits: match-settle-atomic: Compute full commitment

- circuits/Cargo.toml
- circuits/benches/valid_match_settle_atomic_with_commitments.rs
This PR adds a benchmark suite for `VALID MATCH SETTLE ATOMIC WITH COMMITMENTS`.
> circuits: benches: match-settle-atomic-commitments: Add benchmark

- arbitrum-client/src/contract_types/types.rs
- arbitrum-client/src/conversion.rs
- circuits/src/zk_circuits/valid_offline_fee_settlement.rs
- workers/task-driver/src/tasks/pay_offline_fee.rs
This PR computes the full wallet commitment in the `VALID OFFLINE FEE SETTLEMENT` circuit, rather than computing only the private share commitment. This removes the need to do so in the contract handler.
> circuits: zk-circuits: valid-offline-fee: Compute full wallet commitment

- arbitrum-client/src/contract_types/types.rs
- arbitrum-client/src/conversion.rs
- circuits/src/zk_circuits/valid_fee_redemption.rs
- workers/task-driver/src/tasks/redeem_fee.rs
This PR computes the full wallet commitment in the `VALID FEE REDEMPTION` circuit, rather than only computing the private commitment and deferring the full commitment to the contracts.
> circuits: zk-circuit: valid-fee-redemption: Compute full wallet comm

- state/src/applicator/order_book.rs
- state/src/caching/order_cache.rs
- state/src/caching/order_metadata_index.rs
This PR ensure the `OrderMetadatIndex` stays up to date with the global state by accounting for partial fills.
When partial fills occur, validity proofs must be generated so we hook into the `add_order_validity_proof` to update matchable amounts given that the order was pre-existing.
> state: order cache: ensure order metadata cache is synced with state

- arbitrum-client/src/client/contract_interaction.rs
This PR sets the number of retries on the `PendingTransaction` to 20 (default is 3). This will allow the client to poll for longer and avoid unnecessary `TxDropped` errors. 
The `PendingTransaction` is polled on the same interval passed into the `ArbitrumClientConfig` -- currently 100ms. So this change will take the total poll length from 300ms -> 2s
> arbitrum-cilent: contract-interaction: Set `PendingTransaction` retries

- state/src/caching/matchable_amount.rs
- state/src/caching/order_cache.rs
- state/src/interface/order_book.rs
- workers/api-server/src/http/order_book.rs
This PR ensures `GetDepthByMintResponse` returns raw token values denominated in the base token. Previously, we were not considering the fact that `wallet.get_matchable_amount_for_order()` returns the matchable amount for a given order in terms of the order's sell asset.
> state, workers: fix depth units

- common/src/types/tasks/descriptors/mod.rs
- common/src/types/tasks/descriptors/settle_match.rs
- workers/handshake-manager/src/manager/matching/external_engine.rs
- workers/job-types/src/handshake_manager.rs
- workers/task-driver/src/driver.rs
- workers/task-driver/src/task_state.rs
- workers/task-driver/src/tasks/settle_malleable_external_match.rs
This PR updates the external matching engine to create malleable matches when requested. This is specified by the `bounded_match` flag on the `ExternalEngineOptions` type. When set, the matching engine proceeds with the normal match flow, until the point at which a match is found and needs to be settled. The engine will then derive _bounds_ on the match and forward a `SettleMalleableExternalMatchTask` to the driver.
- Full testing deferred until this engine config is accessible from the API
> handshake-manager: external-engine: Create malleable matches when requested

- external-api/src/http/external_match.rs
- workers/api-server/src/http.rs
- workers/api-server/src/http/external_match.rs
- workers/job-types/src/handshake_manager.rs
This PR adds an endpoint for assembling a quote into a malleable match bundle. This largely mimics the regular assemble flow, but creates a `BoundedMatchResult` rather than an `ExternalMatchResult`.
- Build malleable match calldata, left for a follow up.
> api-server: http: external-match: Add malleable match endpoint

- arbitrum-client/src/abi.rs
- arbitrum-client/src/client/contract_interaction.rs
- arbitrum-client/src/contract_types/types.rs
- arbitrum-client/src/conversion.rs
- circuit-types/src/match.rs
- external-api/src/http/external_match.rs
- workers/api-server/src/http.rs
- workers/api-server/src/http/external_match.rs
- workers/task-driver/src/tasks/settle_malleable_external_match.rs
This PR builds the calldata for a `processMalleableAtomicMatchSettle` call in assembling a malleable bundle.
> api-server: http: external-match: Build malleable match calldata for bundle

- arbitrum-client/integration/event_indexing.rs
- arbitrum-client/src/abi.rs
- arbitrum-client/src/client/event_indexing.rs
- arbitrum-client/src/constants.rs
- arbitrum-client/src/conversion.rs
This PR adds handlers for `processMalleableAtomicMatchSettle` and `processMalleableAtomicMatchSettleWithReceiver` in the logic used to parse `ExternalMatchResults` from a nullifier transaction.
> arbitrum-client: event-indexing: Parse external match from malleable

- Cargo.lock
- arbitrum-client/Cargo.toml
- arbitrum-client/src/client/event_indexing.rs
- arbitrum-client/src/conversion.rs
- arbitrum-client/src/helpers.rs
- circuit-types/src/fees.rs
- circuit-types/src/match.rs
This PR adds share recovery helpers to the arbitrum client that recover a wallet's shares from a malleable match transaction. We reconstruct the wallet share updates locally, as opposed to emitting an event on-chain, for simplicity.
> arbitrum-client: event-indexing: Recover shares from malleable matches

- external-api/src/http/external_match.rs
This PR changes the price in malleable match responses to be a `FixedPoint` type. This will allow clients to compute exactly the amount received when a base amount is specified. We will add client side helpers to convert `FixedPoint` to `f64` for a human readable price.
> external-api: external-match: Send price as `FixedPoint`

- Cargo.lock
- arbitrum-client/Cargo.toml
- arbitrum-client/integration/helpers.rs
- arbitrum-client/integration/main.rs
- arbitrum-client/src/abi.rs
- arbitrum-client/src/client/contract_interaction.rs
- arbitrum-client/src/client/event_indexing.rs
- arbitrum-client/src/client/mod.rs
- arbitrum-client/src/constants.rs
- arbitrum-client/src/conversion.rs
- arbitrum-client/src/errors.rs
- arbitrum-client/src/helpers.rs
- arbitrum-client/src/lib.rs
- core/Cargo.toml
- renegade-metrics/Cargo.toml
- renegade-metrics/src/helpers.rs
This PR transitions the `arbitrum-client` from using `ethers` to `alloy` and makes the appropriate simplifications. This will be followed up with a PR that removes `ethers` entirely from the relayer. 
- Generalize the `arbitrum-client` to support multiple chains (Base)
- Other testing deferred until repo builds, i.e. after `ethers` is removed entirely
> arbitrum-client: Transition from `ethers` to `alloy`

- Cargo.lock
- darkpool-client/Cargo.toml
- darkpool-client/src/arbitrum/mod.rs
- darkpool-client/src/base/conversion.rs
- darkpool-client/src/base/mod.rs
- darkpool-client/src/client/event_indexing.rs
- darkpool-client/src/conversion.rs
- darkpool-client/src/lib.rs
- darkpool-client/src/traits.rs
- gossip-api/Cargo.toml
- workers/proof-manager/Cargo.toml
This PR begins the Base implementation of the darkpool client, implementing the first few setter methods.
- Implement the rest of the client
> darkpool-client: base: Add base implementation

- Cargo.lock
- darkpool-client/src/base/conversion.rs
- darkpool-client/src/base/mod.rs
This PR implements the remaining setter method in the `BaseDarkpool` implementation of `DarkpoolImpl`
- Share recovery methods
> darkpool-client: base: Implement remaining setter methods

- darkpool-client/src/base/conversion.rs
- darkpool-client/src/base/mod.rs
This PR implements the helper to parse external matches from a transaction, completing the Base implementation of the `DarkpoolImpl` trait.
- Further testing against real contracts
> darkpool-client: base: Implement external match parse method

- core/src/main.rs
- darkpool-client/integration/main.rs
- darkpool-client/src/client/mod.rs
- darkpool-client/src/constants.rs
- mock-node/src/lib.rs
- workers/task-driver/integration/main.rs
This PR makes two changes to the `DarkpoolClient`:
- Use the `SimpleNonceManager` which re-fetches the current nonce on every call. We do this to prevent the nonce getting out of sync. I will follow up with a PR that uses a custom cached nonce manager, the alloy `CachedNonceManager` does not have an invalidation mechanism.
- Set the client's polling interval to the configured value.
> darkpool-client: client: Respect `polling_interval` config param

- bin/build_and_push.sh
- bin/deploy.sh
This PR updates the `build_and_push` & `deploy` scripts to expect chain-aware environment names, i.e. `arbitrum-sepolia` and `arbitrum-one` instead of `testnet` and `mainnet`, respectively.
Both of these newly-named ECR repos have already been created, so the scripts should be ready for immediate use.
> bin: use chain-aware env in build & deploy scripts

- Cargo.lock
- circuits/src/zk_gadgets/arithmetic.rs
- circuits/src/zk_gadgets/comparators.rs
This PR fixed the `greater_than_eq_zero` gadget in the `comparators` to fix a soundness issue when the gadget returns false. The updated implementation follows the [circomlib implementation](https://github.com/iden3/circomlib/blob/35e54ea21da3e8762557234298dbb553c175ea8d/circuits/comparators.circom#L89-L99) as suggested in the audit.
> circuits: zk-gadgets: comparators: Fix `greater_than_eq_zero`

- common/src/types/token.rs
- workers/api-server/src/http/external_match.rs
This PR adds the `is_native_asset` method to the `Token` struct to encapsulate comparison to the hardcoded "native asset" address representation. This needs to be lower cased, so using this method in the api server fixes a bug validating native asset pairs.
> common: token: Add `is_native_asset` method

- common/src/types/chain.rs
- config/src/cli.rs
- constants/src/lib.rs
- darkpool-client/Cargo.toml
- darkpool-client/src/client/mod.rs
- darkpool-client/src/lib.rs
- workers/price-reporter/src/mock.rs
This PR updates the `Chain` enum to cover our chain options more granularly, and includes a new `all-chains` Cargo feature to the `darkpool-client` crate. Together, these changes allow external crates to construct either `DarkpoolClient` based on the `Chain`.
> common, darkpool-client: granular chain enum & all-chains feature

- bin/build_and_push.sh
- common/src/types/chain.rs
This PR tweaks the `build_and_push` script to set the `CARGO_FEATURES` build arg appropriately based on the passed-in `--chain` flag.
This was used to build the `arbitrum-sepolia` relayer
> bin: set cargo features in build script

- common/src/types/token.rs
This PR changes the behavior of `default_chain` to return the only configured chain in the case that only one chain is configured an `DEFAULT_CHAIN` is not set. This obviates the need to set the static `DEFAULT_CHAIN` in a single-chain implementation.
> common: token: Fall back to singleton map if default not configured

- common/src/types/token.rs
This PR ensures the default chain is set in an idempotent way, allowing multiple token remaps to be configured without panicking.
> common: token: idempotent set default chain

- Cargo.lock
- darkpool-client/src/base/mod.rs
- node-support/bootloader/Cargo.toml
- node-support/bootloader/src/config.rs
- node-support/bootloader/src/gas_wallet.rs
- node-support/bootloader/src/helpers.rs
- node-support/bootloader/src/main.rs
- node-support/bootloader/src/snapshot.rs
This PR makes a number of changes to the relayer's bootloader:
1. Use the chain-dependent funds manager URL for registering a gas wallet
2. Internalize the funds manager API types, to prevent a cyclic dependency with `funds-manager-api`
3. Remove fee whitelisting -- not currently used
4. Refactor individual components of the bootloader into their own files
> node-support: bootloader: Use chain-dependent gas wallet URL

- common/src/types/token.rs
This PR defaults the `chain` field on the `Token` struct when not present during deserialization. This allows for API backwards compatibility for endpoints expecting a token.
> common: token: Default `chain` in deserialization

- config/src/token_remaps.rs
This PR allows the supported exchanges global static map to merge values across token remaps. If we're only loading one token remap: no need to clear the exchange support map. If we're loading multiple: we assume supported exchanges are chain-agnostic and we want to merge across remaps.
> config: token-remaps: allow merging supported exchanges

- darkpool-client/Cargo.toml
- darkpool-client/src/errors.rs
- darkpool-client/src/lib.rs
- darkpool-client/src/transfer_auth/arbitrum.rs
- darkpool-client/src/transfer_auth/mod.rs
- darkpool-client/src/transfer_auth/permit2_abi.rs
- test-helpers/src/contract_interaction.rs
This PR moves the transfer auth helpers from the `test-helpers` crate to the `darkpool-client` crate. 
A follow-up will add helpers for Base transfer auth.
> darkpool-client: Move arbitrum transfer auth to `DarkpoolClient`

- config/src/lib.rs
- config/src/token_remaps.rs
This PR adds the canonical exchange field to the TokenRemap struct along with a getter method to retrieve the map of Ticker -> Canonical Exchange.
> config: token-remaps: add canonical exchange field

- darkpool-client/src/arbitrum/abi.rs
- darkpool-client/src/arbitrum/mod.rs
This PR adds the `quote_amount` field to malleable match calldata generated by the relayer in the external match API. This value defaults to the maximum tradable quote amount, in line with the base amount default.
> darkpool-client: arbitrum: Add `quote_amount` to malleable match calls

- darkpool-client/src/base/mod.rs
- darkpool-client/src/conversion.rs
- darkpool-client/src/transfer_auth/arbitrum.rs
- darkpool-client/src/transfer_auth/base.rs
- darkpool-client/src/transfer_auth/common.rs
- darkpool-client/src/transfer_auth/mod.rs
This PR adds the Base transfer auth helpers to the darkpool client in the same pattern as is done for the Arbitrum transfer auth helpers. These two implementations differ only in how they serialize withdrawal structs. The Stylus VM uses `postcard` serialization across the board, whereas we use the Solidity ABI encoding to serialize transfer structs in the solidity contracts.
The deposit (permit2) digest is the same on both chains, so I moved that to a common helper.
> darkpool-client: transfer-auth: base: Implement Base transfer auth

- common/src/types/token.rs
- workers/price-reporter/src/manager.rs
This PR ensures prices are fetched from the canonical exchange by adding `Exchange::Renegade` to the list of supported exchanges so that it is subscribed to on `StreamPrice`, and read from the Renegade topic on `PeekPrice`. 
`NativeExecutor` does not require changes since it is not used to establish connections, we would see a `todo!("implement renegade connection")` if this code path was used.
> price-reporter: use Renegade exchange when peeking price

- Cargo.lock
- darkpool-client/src/base/mod.rs
This PR ingests the Base ABI changes made in [this PR](https://github.com/renegade-fi/renegade-solidity-contracts/pull/120) into the relayer implementation. Specifically, we set the `quoteAmount` field in the `processMalleableAtomicMatchSettle` calldata.
- Further testing deferred until auth server works
> darkpool-client: base: Ingest Base ABI changes

- config/src/cli.rs
- darkpool-client/src/client/event_indexing.rs
This method publishes the `fetch_tx_darkpool_calls` method. This method is useful to consumers outside the crate, e.g. in the auth server.
> darkpool-client: event-indexing: Publish `fetch_tx_darkpool_calls`

- state/src/applicator/wallet_index.rs
- workers/chain-events/src/listener.rs
This PR handles two panics in the same way; by logging an error or rejecting and continuing normal operation. These panics are:
- In the state applicator, we no longer panic when order metadata cannot be found during a wallet update.
- In the chain events listener, we no longer panic if handling a nullifier fails. If it does fail, we clear the queue of the wallet to sync its state with the state stored on-chain.
> chain-events, state: applicator: Handle panics

- workers/chain-events/src/listener.rs
This PR adds error logging to the websocket chain events listener as is done in the HTTP listener.
> chain-events: listener: Do not panic websocket listener

- external-api/src/http/external_match.rs
- state/src/replication/mod.rs
- workers/api-server/src/http/external_match.rs
- workers/handshake-manager/src/manager/matching/external_engine.rs
- workers/handshake-manager/src/manager/matching/internal_engine.rs
- workers/handshake-manager/src/manager/matching/match_helpers.rs
- workers/job-types/src/handshake_manager.rs
This PR:
1. Adds a `min_quote_amount` field to the `ExternalMatchingEngineOptions` struct, which will control the minimum matchable quote amount using existing paths.
2. When an external user passes a quote-denominated order to the API server, the API server will respect `min_fill_size` by forwarding this value to the external matching engine.
3. This PR also cleans up some of the logic for setting the `ExternalMatchingEngineOptions` in the api server, specifically I factored out the large conversion method into smaller helpers.
4. Removed an extra clone in the matching engine, by allowing callers to pass iterators of orders rather than objects which implement `IntoIterator<Item = OrderIdentifier>`.
> workers: handshake-manager: Add min_quote_amount to external engine

- config/src/cli.rs
- workers/api-server/integration/ctx/external_match.rs
- workers/api-server/integration/ctx/mod.rs
- workers/api-server/integration/ctx/wallet_setup.rs
- workers/api-server/integration/external_match/basic_match.rs
- workers/api-server/integration/main.rs
This PR finishes the setup for the basic "no quote" external match test. 
- Valid external match tests
- Exact amount and min fill tests
> api-server: integration: external-match: Fix basic external match test

- test-helpers/src/macros.rs
- workers/api-server/integration/ctx/external_match.rs
- workers/api-server/integration/ctx/mod.rs
- workers/api-server/integration/ctx/wallet_setup.rs
- workers/api-server/integration/external_match/basic_match.rs
- workers/api-server/integration/helpers.rs
- workers/api-server/integration/main.rs
This PR adds a full test suite for the basic parameterization of external matches by using only `quote_amount` and `base_amount` to specify size.
> api-server: integration: external-match: Add full basic match tests

- mock-node/src/lib.rs
- workers/api-server/integration/ctx/wallet_setup.rs
- workers/api-server/integration/external_match/min_fill_size.rs
This PR adds a full test suite for the `min_fill_size` setting. All tests pass except for one which has an issue with representable amounts. I'll fix this with changes to the way we setup external orders in the next PR.
> api-server: integration: Add full `min_fill_size` test suite

- workers/api-server/src/http.rs
This PR removes a spammy error log that originates when a client hangs up a connection unexpectedly. We don't need to monitor the stream for errors as the internal errors are already captured elsewhere.
> api-server: http: Remove spammy error logs

- renegade-metrics/src/helpers.rs
- renegade-metrics/src/labels.rs
- workers/chain-events/src/listener.rs
- workers/handshake-manager/src/manager.rs
- workers/task-driver/src/tasks/settle_match_internal.rs
This PR ensures the `match_quote_volume` metric is tagged with associated wallet ids. This enables us to accurately track natural crosses by filtering out matches associated with any of the quoters' wallet ids.
> workers: settlement: record wallet_ids of match

- common/src/types/tasks/descriptors/mod.rs
- core/src/setup.rs
- gossip-api/src/request_response/mod.rs
- state/src/applicator/task_queue.rs
- state/src/interface/task_queue.rs
- state/src/lib.rs
- util/src/channels/traced_channel.rs
- util/src/telemetry/propagation.rs
- workers/network-manager/src/executor/behavior.rs
- workers/network-manager/src/executor/request_response.rs
- workers/task-driver/src/driver.rs
This PR adds tracing context to all tasks so that the task driver handlers may open spans in the parent span that created the task; i.e. we retain the OTel context across consensus boundaries. 
This will give a much clearer picture of the e2e latency for API requests which involve a task (e.g. external matches).
> common: tasks: descriptors: Add tracing context to all tasks

- renegade-metrics/src/helpers.rs
- renegade-metrics/src/labels.rs
This PR tags match quote volume metric with the `base_asset` so that we can group by base asset in DD.
For example, to add a pie chart widget that displays internally settled quote volume by asset, we need to be able to group `match_quoter_volume` metric by `base_asset`.
> metrics: tag volume metric with base asset for group by

- external-api/src/http/external_match.rs
- workers/api-server/integration/ctx/external_match.rs
- workers/api-server/integration/ctx/node_state.rs
- workers/api-server/integration/external_match/matching_pool.rs
- workers/api-server/integration/external_match/mod.rs
- workers/api-server/src/http/external_match/handlers.rs
- workers/api-server/src/http/external_match/processor.rs
- workers/handshake-manager/src/manager/matching/external_engine.rs
- workers/job-types/src/handshake_manager.rs
This PR adds a param for the matching pool in all external match requests. If no pool is specified we match against all pools, including the global pool. If a pool is specified we match only against orders in that pool.
I added two integrations tests for:
- No pool specified -> should match against an order allocated in a non-global pool
- Pool specified -> should only match against orders in the given pool
> external-api, handshake-manager: Add matching pool param to external match API

- external-api/src/types/api_network_info.rs
- workers/api-server/src/http.rs
- workers/api-server/src/http/network.rs
This PR correctly reports the network ID as the stringified chain in the `/v0/network` handler.
> api-server: network: Report chain correctly in `/v0/network`

- state/src/applicator/error.rs
- state/src/applicator/matching_pools.rs
- state/src/applicator/task_queue.rs
- state/src/storage/error.rs
- state/src/storage/tx/matching_pools.rs
- state/src/storage/tx/order_history.rs
- state/src/storage/tx/task_queue.rs
This PR replaces `StorageError::InvalidWrite` with `StorageError::Reject` and converts a storage level rejection into a state applicator rejection. This allows the storage layer to reject a state applicator's state transition directly rather than signalling through a subset of its error types.
> state: storage: error: Allow storage layer to reject state transitions

- workers/chain-events/src/lib.rs
- workers/chain-events/src/listener.rs
- workers/chain-events/src/post_settlement.rs
This PR ensures the applicator is made aware of fills on external orders using the same code paths for handling fills on internal orders. Currently, we do not record historical state in the relayer, but we do emit `SystemBusMessage::OrderMetadataUpdated` messages that are propagated to clients listening to the order history topic over socket connections.
> workers: chain-events: update order metadata on settlement

- state/src/interface/order_book.rs
- state/src/storage/tx/order_book.rs
- workers/task-driver/src/tasks/refresh_wallet.rs
This PR makes a couple tweaks to smooth out a potential race condition between wallet refreshes and external matches. Concretely, the race occurs when a refresh task is enqueued and begins executing in the time between an external match request finding a matchable order on the wallet being refreshed, and when the external match task actually preempts the queue.
We make the following changes:
1. We move the commit point of the `RefreshWallet` task to `FindingWallet`, effectively making it non-preemptable. This ensures that even in this race condition, we can't preempt a `RefreshWallet` task during the `FindingWallet` step, before it gets the chance to update validity proofs for the wallet orders. In other tasks which update the wallet & proofs, these actions occur after the commit point, …
> state, task-driver: use FindingWallet as refresh commit point, remove nullified orders from cache

- common/src/types/wallet/order_metadata.rs
- workers/chain-events/src/post_settlement.rs
This PR adds a roll-up helper on OrderMetadata that collapses all but the most recent fill into a single aggregate entry, ensuring that fill arrays are bounded while
- `total_filled()` callsites receive correct data
- newest fill is still delivered to subscribers (frontends and other clients).
This is currently invoked in the external match flow iff historical state is disabled.
> state, common: bound fills array growth if historical state disabled

- workers/api-server/integration/ctx/external_match.rs
- workers/api-server/integration/external_match/matching_pool.rs
- workers/api-server/integration/external_match/mod.rs
- workers/api-server/integration/external_match/relayer_fee.rs
- workers/api-server/src/http/external_match/handlers.rs
- workers/api-server/src/http/external_match/processor.rs
This PR adds two tests for setting the `relayer_fee_rate` value in the external match API:
1. A test which sets the relayer fee rate to a random value between 0% and 1%.
2. A test which sets the relayer fee rate to an invalid value (> 1%) which the API rejects.
> api-server: integration: relayer-fee: Add tests for non-zero relayer fee

- common/src/types/token.rs
This PR adds a `maybe_from_ticker` method which allows the caller to handle the case in which a token's ticker is unsupported.
> common: types: token: Add `maybe_from_ticker` method

- mock-node/src/lib.rs
- workers/api-server/Cargo.toml
- workers/api-server/benches/quote_endpoint.rs
This PR adds a benchmark for the quote endpoint which we will use to measure execution latency and bottlenecks.
> api-server: benches: Add quote endpoint benchmark

- common/src/types/token.rs
- external-api/src/http/price_report.rs
- workers/api-server/src/http.rs
- workers/api-server/src/http/price_report.rs
This PR adds $USDT to the `get_all_base_tokens` return value by filtering on a new `is_tradable` method which returns true for USDT. 
I also reformatted the request format for the `/v0/price_report` endpoint. This endpoint is only used internally, so changing its interface is fine.
> price-reporter: Support USDT price streaming

- workers/api-server/src/http/external_match/processor.rs
This PR allows USDT in external match requests. This represents the changes needed to allow relayer trading on the USDT/USDC pair; internal trading included.
> api-server: external-match: processor: Allow USDT in token validation

- common/src/types/proof_bundles.rs
- darkpool-client/src/arbitrum/mod.rs
- darkpool-client/src/base/mod.rs
- darkpool-client/src/client/contract_interaction.rs
- darkpool-client/src/traits.rs
- external-api/src/bus_message.rs
- external-api/src/http/external_match.rs
- workers/api-server/src/http/external_match/processor.rs
- workers/job-types/src/proof_manager.rs
- workers/proof-manager/src/implementations/external_proof_manager/mod.rs
- workers/proof-manager/src/implementations/external_proof_manager/prover_service_client.rs
- workers/proof-manager/src/implementations/native_proof_manager.rs
- workers/proof-manager/src/mock.rs
- workers/task-driver/src/tasks/settle_malleable_external_match.rs
This PR refactors the malleable atomic match settle job of the proof manager to also prove the `VALID MALLEABLE MATCH SETTLE ATOMIC` <-> `VALID COMMITMENTS` proof link. This is an analogous change to that in #1088.
> proof-manager: Prove malleable match settle + commitments link together

- common/src/types/proof_bundles.rs
- darkpool-client/src/arbitrum/mod.rs
- workers/job-types/src/proof_manager.rs
- workers/proof-manager/src/implementations/external_proof_manager/mod.rs
- workers/proof-manager/src/implementations/external_proof_manager/prover_service_client.rs
- workers/proof-manager/src/implementations/native_proof_manager.rs
- workers/proof-manager/src/mock.rs
- workers/task-driver/src/tasks/create_new_wallet.rs
- workers/task-driver/src/tasks/pay_offline_fee.rs
- workers/task-driver/src/tasks/pay_relayer_fee.rs
- workers/task-driver/src/tasks/redeem_fee.rs
- workers/task-driver/src/tasks/settle_malleable_external_match.rs
- workers/task-driver/src/tasks/settle_match_external.rs
- workers/task-driver/src/tasks/settle_match_internal.rs
- workers/task-driver/src/tasks/update_wallet.rs
- workers/task-driver/src/utils/validity_proofs.rs
This PR adds a proof manager job to link a proof of `VALID REBLIND` and a proof of `VALID COMMITMENTS` and uses this job in the task driver when we need to re-prove validity proofs. 
I also implemented the external prover client handler for this job.
> task-driver: validity-proofs: Link reblind-commitments through proof manager

- workers/api-server/src/compliance/client.rs
This PR fixes a double slash `/` issue in the compliance URL that was introduced in #1085 by passing the compliance url as type `Url`, which automatically suffixes a `/`.
> api-server: compliance: Fix URL + path join

- config/src/token_remaps.rs
This PR ensures the dummy USD token expresses support on the OKX exchange. This is required to subscribe to the OKX USDT/USD stream. I confirmed OKX supports this market by manually hitting their API.
> config: token-remaps: add usd support for okx

- workers/task-driver/src/driver.rs
- workers/task-driver/src/tasks/create_new_wallet.rs
- workers/task-driver/src/tasks/lookup_wallet.rs
- workers/task-driver/src/tasks/node_startup.rs
- workers/task-driver/src/tasks/pay_offline_fee.rs
- workers/task-driver/src/tasks/pay_relayer_fee.rs
- workers/task-driver/src/tasks/redeem_fee.rs
- workers/task-driver/src/tasks/refresh_wallet.rs
- workers/task-driver/src/tasks/settle_malleable_external_match.rs
- workers/task-driver/src/tasks/settle_match.rs
- workers/task-driver/src/tasks/settle_match_external.rs
- workers/task-driver/src/tasks/settle_match_internal.rs
- workers/task-driver/src/tasks/update_merkle_proof.rs
- workers/task-driver/src/tasks/update_wallet.rs
- workers/task-driver/src/traits.rs
This PR adds the `Descriptor` trait which all task descriptors must implement. This trait then exposes a `bypass_task_queue` method, analogous to the method defined on the `Task` trait. We use this method to skip calling `pop_task` on tasks which bypass the queue.
This was the cause of the "key not found for task" errors that we've been seeing in production.
> task-driver: tasks: Add `bypass_task_queue` method to task descriptors

- workers/task-driver/src/tasks/create_new_wallet.rs
- workers/task-driver/src/tasks/lookup_wallet.rs
- workers/task-driver/src/tasks/pay_offline_fee.rs
- workers/task-driver/src/tasks/pay_relayer_fee.rs
- workers/task-driver/src/tasks/redeem_fee.rs
- workers/task-driver/src/tasks/refresh_wallet.rs
- workers/task-driver/src/tasks/settle_malleable_external_match.rs
- workers/task-driver/src/tasks/settle_match.rs
- workers/task-driver/src/tasks/settle_match_external.rs
- workers/task-driver/src/tasks/settle_match_internal.rs
- workers/task-driver/src/tasks/update_merkle_proof.rs
- workers/task-driver/src/tasks/update_wallet.rs
- workers/task-driver/src/utils/merkle_path.rs
- workers/task-driver/src/utils/mod.rs
- workers/task-driver/src/utils/validity_proofs.rs
This PR exposes a second method for re-proving validity proofs for a wallet; `update_validity_proofs__skip_queue_check`. This method removes the check that the wallet's task queue is empty. In the case of a wallet refresh, we want to always prove validity for orders, so we use this method.
I also made a new cleanups to the task driver utils.
> task-driver: tasks: refresh-wallet: Always reprove validity in `VALID REBLIND`

- darkpool-client/src/traits.rs
- docker/release/Dockerfile
This PR makes a couple changes to TX submission in the darkpool client(s):
1. We add a 1-minute timeout to the awaiting of tx mining
2. We use `eth_gasPrice` as an estimate of gas price, rather than the latest block's basefee
We do this because we have seen a number of tasks get stuck indefinitely in the "submitting tx" phase, presumably because the pending txs are stuck in the mempool. As such, we use `eth_gasPrice` because it is an all-in estimate (basefee + priority fee) of the gas price to set, and it's a cheaper RPC call. We add the timeout to ensure that tasks don't hang indefinitely, but rather error out.
> darkpool-client: add timeout to tx submission

- state/src/storage/tx/task_queue.rs
This PR changes the error returned if a task is not found in the task queue table. We specifically want to `reject` here so the state machine does not propagate the error to the OpenRaft worker, causing a complete Raft shutdown.
> state: storage: reject transition if task not found

- common/src/types/token.rs
This PR makes the `is_tradable` method chain agnostic by comparing tickers rather than addresses.
> common: token: Make `is_tradable` chain-agnostic

- common/src/types/network_order.rs
- state/src/applicator/mod.rs
- state/src/applicator/order_book.rs
- state/src/interface/order_book.rs
- state/src/storage/tx/order_book.rs
- workers/task-driver/src/state_migration/double_write_validity_proofs.rs
This PR removes the `validity_proofs` field from the `NetworkOrder` type and replaces all use of the field with the appropriate lookups to the new `proofs` table.
- Remove the `validity_proof_witnesses` field
> common: types: network-order: Remove validity proofs from network order

- workers/task-driver/src/tasks/update_wallet/helpers/events.rs
- workers/task-driver/src/tasks/update_wallet/helpers/mod.rs
- workers/task-driver/src/tasks/update_wallet/helpers/witness_generation.rs
- workers/task-driver/src/tasks/update_wallet/mod.rs
- workers/task-driver/src/tasks/update_wallet/task.rs
This PR modularizes the `update_wallet` task's implementation.
This comes ahead of additional logic to precompute cancellation proofs.
Breaking the helpers into a module will help segment components of the
update wallet task into more discoverable locations.
> task-driver: tasks: update-wallet: Modularize update wallet impl

- state/src/applicator/mod.rs
- state/src/applicator/order_book.rs
- state/src/interface/order_book.rs
- state/src/lib.rs
- state/src/storage/tx/proofs.rs
This PR adds state methods for precomputed cancellation proofs. Specifically this PR introduces a new state transition for appending cancellation proofs which will be done by the task driver on order placement.
- Use this state transition in the task driver
- Recompute cancellation proofs for orders on wallet update
> state: storage: proof: Add storage methods for cancellation proofs

- common/src/types/tasks/descriptors/mod.rs
- common/src/types/tasks/descriptors/update_wallet.rs
- common/src/types/tasks/history.rs
- common/src/types/wallet/orders.rs
- external-api/src/http/external_match.rs
- workers/api-server/benches/api-server-bench-util/src/lib.rs
- workers/api-server/src/http/admin.rs
- workers/api-server/src/http/wallet.rs
- workers/task-driver/src/tasks/lookup_wallet.rs
- workers/task-driver/src/tasks/pay_offline_fee.rs
- workers/task-driver/src/tasks/pay_relayer_fee.rs
- workers/task-driver/src/tasks/refresh_wallet.rs
- workers/task-driver/src/tasks/settle_match.rs
- workers/task-driver/src/tasks/settle_match_internal.rs
- workers/task-driver/src/tasks/update_merkle_proof.rs
- workers/task-driver/src/tasks/update_wallet/helpers/mod.rs
- workers/task-driver/src/tasks/update_wallet/helpers/proofs.rs
- workers/task-driver/src/tasks/update_wallet/task.rs
- workers/task-driver/src/utils/mod.rs
- workers/task-driver/src/utils/proofs/cancellation_proofs.rs
- workers/task-driver/src/utils/proofs/mod.rs
- workers/task-driver/src/utils/proofs/validity_proofs.rs
This PR makes two changes:
- Moves the `precompute_cancellation_proofs` flag to the `Order` type.
- Creates logic to recompute cancellation proofs for all orders in the same path as the validity proofs, so that pre-computed cancellation proofs will always stay up to date.
- Delete cancellation proofs from state when an order is cancelled.
> common: types: order: Move precompute cancellation flag to `Order`
