renegade-fi/renegade

.github/workflows/clippy.yml
.github/workflows/rustfmt.yml
.github/workflows/test.yml

This PR refactors the CI workflows to give them better naming and use more common actions.

ci: workflows: Refactor workflows to make them more understandable

---

core/src/system_bus.rs

This PR fixes a bug with the system bus in which stream readers poll the bus once and never again. The underlying issue is that we never stored the waker nor called `Waker::wake()` on it, so the executor parked the task permanently.
Fixing this involves two changes:
1. The `TopicFabric` stores an `wakers: Arc<RwLock<Vec<Waker>>>`  field representing the tasks actively waiting on the bus. On `publish` the fabric calls `Waker::wake` on each of these. The shared reference is also passed to the readers.
2. The `TopicReader`s register themselves in the fabric's `wakers` struct when they are polled and return `Poll::Pending`, this allows them to be woken up next time a message is pushed onto the bus.
- Previously the events were somewhat unreliably being delivered …

core: system-bus: Track `Waker`s and awake readers on `publish`

---

circuits/src/zk_circuits/valid_wallet_update.rs

This PR tests a handful of circuit constraints and edge cases that are needed for security. 
Some tests left to write:
- Testing that internal and external transfers are not made for mints the prover has no balance for.
- Bounds checks
- Invalid nullifier, commitment, opening, etc.
- Fixed constraint bugs that came up from testing

circuits: zk-circuits: valid-wallet-update: Improve test coverage for circuit

---

circuits/src/lib.rs
circuits/src/types/balance.rs
circuits/src/types/keychain.rs
circuits/src/zk_circuits/mod.rs
circuits/src/zk_circuits/valid_commitments.rs
circuits/src/zk_circuits/valid_match_encryption.rs
circuits/src/zk_circuits/valid_settle.rs
circuits/src/zk_circuits/valid_wallet_create.rs
circuits/src/zk_circuits/valid_wallet_update.rs
core/Cargo.toml
core/src/api/http.rs
core/src/api_server/error.rs
core/src/api_server/http_handlers.rs
core/src/api_server/mod.rs
core/src/api_server/routes.rs
core/src/api_server/server.rs
core/src/api_server/worker.rs
core/src/handshake/jobs.rs
core/src/handshake/worker.rs
core/src/main.rs
core/src/proof_generation/error.rs
core/src/proof_generation/jobs.rs
core/src/proof_generation/mod.rs
core/src/proof_generation/proof_manager.rs
core/src/proof_generation/worker.rs
core/src/state.rs

This PR adds the initial code structure, job types, error definitions, and worker behavior for the proof generation module. This worker will handle the logic of generating bulletproofs when requested by other workers. Eventually this worker will also target a hardware accelerator (likely a GPU to begin) for accelerated proving.
As a proof-of-concept, this PR also adds the `/wallet/create` endpoint to the relayer, which forwards a job to the proof generation module to generate a proof of `VALID NEW WALLET` given the initializing fees and wallet keychain.
- Tested the `/wallet/create` endpoint and worker flow with a locally running relayer, verified that it correctly generated a proof.

core: proof-generation: Bootstrap proof generation module

---

core/src/api_server/http.rs
core/src/api_server/websocket.rs
core/src/api_server/websocket/handler.rs
core/src/api_server/websocket/price_report.rs
core/src/api_server/websocket/task.rs
core/src/api_server/websocket/wallet.rs
core/src/external_api/types.rs
core/src/handshake/manager.rs
core/src/main.rs
core/src/state/orderbook.rs
core/src/state/state.rs
core/src/state/wallet.rs
core/src/tasks/driver.rs
core/src/types.rs

This PR adds the bulk of the websocket API implementation, this includes:
- Wallet updates
- Order book updates
- Network topology updates
- Handshake events
- Task state updates
Events are produced by various `Worker`s in the node and broadcast via the `SystemBus`. The websocket handler listens on all relevant bus topics and forwards them onto the websocket connection.
- Websocket authentication for routes that mutate or view wallet state. We will take a similar auth approach to the HTTP api.
- Unit tests
- Tested each websocket route locally

core: api-server: websocket: Implement websocket APIs and system bus events

---

core/src/chain_events/listener.rs
core/src/starknet_client/client.rs
core/src/starknet_client/mod.rs

Add support for a `starknet-devnet` sequencer node located at `localhost:5050`. Includes some modifications to event streaming logic to support sync from genesis.

core: starknet-client, chain-events: Add devnet sequencer support

---

circuits/integration/zk_circuits/valid_match_mpc.rs
circuits/src/zk_circuits/valid_match_mpc.rs
circuits/src/zk_gadgets/fixed_point.rs

Previously in `VALID MATCH MPC`, the computed quote amount was constrained to equal the expected quote amount by directly shifting the expected quote amount into a `FixedPoint` representation. This is not valid for non-integral prices as the quote amount has its fractional component truncated during the MPC.
This PR changes the constraint to be such that the difference between the computed quote amount and the expected quote amount (shifted into a `FixedPoint` representation) is less than `DEFAULT_PRECISION` bits in width. This is equivalent to the constraint that the difference is purely fractional; i.e. that the expected amount is the correct integral truncation of the computed amount.
- Added an integration test for random non-integral prices in the price protection range
- Unit and …

circuits: zk-circuits: valid-match-mpc: Floor div quote amount 

---

core/src/api_server/router.rs

Previously we were not handling preflight requests properly, leading to issues browser side while testing.
A note on the settings:
- `Access-Control-Allow-Origin`: We are client-p2p not client-server, so all origins is the best CORS policy.
- `Access-Control-Allow-Headers`: An open policy is fine for now, unused headers are ignored and we don't have a caching layer in between that might be affected.
- `Access-Control-Allow-Methods`: We set this to the set of HTTP methods registered on a route
- `Access-Control-Allow-Credentials`: Seeing as all our requests are cross-origin, we need to allow cross origin credential sharing. As well, we aren't doing any sort of server-side credential creation, so cookie security is managed client side.
- `Access-Control-Max-Age`: I set this to the maximum …

core: api-server: router: Add preflight request support

---

core/src/price_reporter/reporter.rs

This PR changes the way we handle exchange failures. Specifically, we previously only allowed `MAX_CONN_RETRIES` over the course of a connection's lifetime; now we allow `MAX_CONN_RETRIES` every `MAX_CONN_RETRY_WINDOW_MS` milliseconds. This detects consecutive failures only, not simple recoverable failures that accrue over time.
- Tested a few quick failures with Binance

core: pricer-reporter: reporter: Use token bucket for exchange failures

---

core/src/network_manager/manager.rs

Previously, we were operating over TCP transport; so peers would replace their local port with a TCP port discovered by the `Identity` protocol. Now that we are gossiping over UDP (QUIC), replacing with a TCP port gives an undialable address. This 
PR replaces the updated address with a UDP port.
- Verified that after the `Identity` subprotocol returns a dialable address, peers can indeed dial a given node.

core: network-manager: Switch transport on discovered public IP addr

---

core/src/handshake/manager/internal_engine.rs
core/src/tasks/helpers.rs
core/src/tasks/settle_match.rs
core/src/tasks/settle_match_internal.rs

This PR completes the task implementation of `settle-match-internal`; including:
- Prove `VALID SETTLE` after the match proof is complete
- Submit the proof on-chain
- Update the state and Merkle proofs for the new wallet
- Update the proofs of `VALID COMMITMENTS` and `VALID REBLIND` for both wallets and their orders
- Implement recursive fills after a settlement is complete
- Test the implementation on both recursive and non-recursive matches

core: tasks: settle-match-internal: Finish task implementation

---

circuits/Cargo.toml
circuits/Dockerfile
circuits/benches/valid_wallet_create.rs
circuits/src/lib.rs
circuits/src/zk_circuits/mod.rs
circuits/src/zk_circuits/valid_wallet_create.rs

This PR refactors the `VALID WALLET CREATE` circuit over the Stark curve. As well, the PR adds benchmarks for:
- constraint generation
- proof generation
- proof verification
- CI will remain red until refactor is complete

circuits: zk-circuits: `VALID WALLET CREATE`: Refactor over Stark curve

---

circuits/Cargo.toml
circuits/benches/valid_commitments.rs
circuits/src/zk_circuits/mod.rs
circuits/src/zk_circuits/valid_commitments.rs

This PR refactors the `VALID COMMITMENTS` circuit over the Stark curve. As well, this PR adds benchmarks for:
- Constraint generation latency
- Prover latency
- Verifier latency
- CI will remain red until the refactor is complete

circuits: zk-circuits: `VALID COMMITMENTS`: Refactor over stark curve

---

circuits/benches/match.rs
test-helpers/src/mpc_network.rs

This PR adds benchmarks for the raw match MPC (generates the shared witness), constraint generation latency, and shared prover latency with a non-zero connection latency. The connection latencies tested are:
- `1ms`: A healthy overestimate of the point-to-point latency within an AWS AZ
- `10ms`: A healthy overestimate of the point-to-point latency within an AWS region but not in the same AZ
- `100ms`: A somewhat realistic estimate on point-to-point latency from a network outside of the AWS backbone, perhaps in a different region on the same continent.

circuits: benches: `match`: Add benchmarks with connection delay

---

.dockerignore
starknet-client/Dockerfile
starknet-client/integration/contract_interaction.rs
starknet-client/integration/helpers.rs
starknet-client/integration/main.rs
starknet-client/src/client/contract_interaction.rs
starknet-client/src/helpers.rs
starknet-client/src/lib.rs
starknet-client/src/types.rs

This PR adds integration test cases for:
- Checking Merkle root validity
- Checking nullifier use
- Submitting a `new_wallet` tx
- Submitting an `update_wallet` tx
- Submitting a `process_match` tx
As well, this PR makes the following changes to fix bugs caught by the tests:
- Fix calldata parsing bugs for secret share recovery
- Add a `CalldataDeserializable` trait and implement it on basic calldata types

starknet-client: integration: Add contract interaction integration tests

---

statev2/src/replication/log_store.rs
statev2/src/storage/cursor.rs

This PR adds unit tests to the `LogStore` implementation testing a variety of functionality, including:
- Metadata access at initialized and non-initialized states
- Full logs access
- Partial log access
- Log access with a size bound in place
As well, this PR chances the semantics of the `seek` interfaces on the `DbCursor` type. Previously, the `seek_<x>` methods would return the kv pair under the cursor after seeking, thereby moving the cursor to the next element. It is more convenient to higher level modules if the `seek` interfaces simply reposition the cursor, and the next access to `get_current` or `Iterator::next` on the `DbCursor` will return the value. This PR achieves this by buffering a result after a `seek`.

statev2: replication: log-store: Add `LogStore` unit tests

---

circuits/src/zk_circuits/valid_wallet_update.rs

This PR makes the changes necessary to `VALID WALLET UPDATE` to incorporate the fee implementation. This involves checking:
- All fees are paid upon withdrawal
- Fees do not change during the update
- To change the managing cluster the node must have paid all relayer balances
- Unit tests pass, tested positive and negative cases of the above
- CI will fail until the fee implementation is further along

circuits: zk-circuits: `VALID WALLET UPDATE`: Implement fee specific constraints

---

workers/handshake-manager/src/manager/internal_engine.rs

Previously, the handshake manager would allow matches of zero volume as part of the logic that allows for undercapitalized orders. This leads to infinite recursive loops in internal matches, and makes no sense, so we explicitly disallow it.
- Tested the zero volume case before the fix, verified that the test passed afterwards

handshake-manager: internal-engine: Reutrn no match with zero volume

---

statev2/state/src/replication/network.rs
statev2/state/src/replication/raft_node.rs

This PR adds additional tests for raft cluster join/leave semantics. Specifically for conducting leader election and forming consensus over larger peer-sets, and in the event of node failure.

statev2: state: replication: Add tests for large cluster join/leave semantics

---

workers/price-reporter/src/reporter.rs

This PR adds additional logs to indicate the state of the connection retry loop in the price reporter.
Additionally, we change the logic to drop an exchange if a connection cannot be established, instead of forcing all price streams to terminate.

workers: price-reporter: Add logging to connection retry loop

---

task-driver/integration/tests/settle_match.rs

This PR adds an integration test for the `settle-match` task. This task settles a match that originated from an MPC. The test verifies that the wallets of both parties are updated properly on-chain.
- Tested the `settle-match` flow

task-driver: integration: settle-match: Add `settle-match` integration test

---

task-driver/src/settle_match_internal.rs

This PR addresses the bug in which if the SettleMatchInternal task errors during instantiation, the cleanup function is not called, resulting in deadlock.

task-driver: Cleanup if SettleMatchInternal task errors outside of task-driver

---

workers/api-server/src/router.rs

This PR enables CORS on error responses, fixing the issue of API responses not containing error data in the response when received by the client.

workers: Enable CORS on error responses

---

renegade-crypto/benches/poseidon.rs

This PR adds a simple criterion benchmark for the Poseidon 2 implementation

benches: poseidon: Add poseidon 2 benchmark

---

Cargo.lock
circuit-macros/src/circuit_type/singleprover_circuit_types.rs
circuit-types/Cargo.toml
circuit-types/src/balance.rs
circuit-types/src/fee.rs
circuit-types/src/fixed_point.rs
circuit-types/src/keychain.rs
circuit-types/src/lib.rs
circuit-types/src/match.rs
circuit-types/src/merkle.rs
circuit-types/src/order.rs
circuit-types/src/traits.rs
circuit-types/src/transfers.rs
circuit-types/src/wallet.rs

This PR finishes refactoring all types in the `circuit-types` crate over the new proof system. This largely involves deleting code and fixing imports where traits have changed.

circuit-types: Refactor application level types over new proof system

---

circuits/src/lib.rs
circuits/src/zk_circuits/mod.rs
circuits/src/zk_circuits/valid_wallet_update.rs

This PR refactors the `VALID WALLET UPDATE` circuit to work over the `mpc-plonk` system. This circuit handles the changes made to a wallet when an order is placed, balance deposited, etc.

circuits: zk-circuits: valid-wallet-update: Refactor over `mpc-plonk`

---

Cargo.lock
circuits/src/zk_circuits/valid_match_settle/mod.rs
config/src/lib.rs
core/src/main.rs
statev2/proto/Cargo.toml
statev2/proto/src/lib.rs
workers/job-types/Cargo.toml
workers/job-types/src/handshake_manager.rs
workers/job-types/src/proof_manager.rs

This PR refactors the `job-types`, `config`, and `core` crates after the `mpc-plonk` refactor.

job-types, config, core: Refactor over new circuit definition

---

arbitrum-client/src/client/event_indexing.rs
circuit-types/src/wallet.rs
task-driver/src/driver.rs
task-driver/src/helpers.rs
task-driver/src/lib.rs
task-driver/src/lookup_wallet.rs

This PR refactors the `lookup-wallet` task over the `mpc-plonk` system.

task-driver: lookup-wallet: Refactor task over `mpc-plonk`

---

circuit-types/src/fixed_point.rs

This PR fixes a flakey test in the fixed point implementation by specifying a correctness tolerance as a ratio of the difference to expected -- rather than an absolute difference. This is used in multiplication tests where the difference between floating point expected values and our fixed point implementation may be larger due to the different approximations the two representations make.
- Ran the unit tests many times to verify the flaky behavior was fixed

circuit-types: fixed-point: Fix flakey test with percentage tolerance

---

Cargo.lock
arbitrum-client/src/conversion.rs
circuit-types/src/lib.rs
circuit-types/src/match.rs
circuit-types/src/traits.rs
circuits/integration/mpc_circuits/match_settle.rs
circuits/src/lib.rs
circuits/src/mpc_circuits/settle.rs
circuits/src/zk_circuits/mod.rs
circuits/src/zk_circuits/proof_linking.rs
circuits/src/zk_circuits/valid_commitments.rs
circuits/src/zk_circuits/valid_match_settle/mod.rs
circuits/src/zk_circuits/valid_reblind.rs
circuits/src/zk_circuits/valid_wallet_create.rs
circuits/src/zk_circuits/valid_wallet_update.rs
task-driver/src/helpers.rs
util/src/matching_engine.rs

This PR adds linking helpers for computing proof links between our application level circuits. Testing is deferred to a follow up PR
- Add unit tests

circuits: zk-circuits: proof-linking: Implement linking helpers

---

circuits/Cargo.toml
circuits/src/lib.rs
circuits/src/zk_circuits/proof_linking.rs
circuits/src/zk_circuits/valid_match_settle/mod.rs

This PR adds testing for the proof linking helpers defined in #322. These test a variety of correct and incorrect linking cases.

circuits: zk-circuit: proof-linking: Test linking helpers

---

Cargo.lock
arbitrum-client/src/conversion.rs
circuit-macros/src/circuit_type.rs
circuit-macros/src/circuit_type/mpc_types.rs
circuit-macros/src/circuit_type/multiprover_circuit_types.rs
circuit-macros/src/circuit_type/proof_linking.rs
circuit-macros/src/circuit_type/singleprover_circuit_types.rs
circuit-types/src/lib.rs
circuit-types/src/macro_tests.rs
circuit-types/src/match.rs
circuit-types/src/traits.rs
circuits/Cargo.toml
circuits/integration/mpc_circuits/match_settle.rs
circuits/src/lib.rs
circuits/src/mpc_circuits/settle.rs
circuits/src/zk_circuits/mod.rs
circuits/src/zk_circuits/proof_linking.rs
circuits/src/zk_circuits/valid_commitments.rs
circuits/src/zk_circuits/valid_match_settle/mod.rs
circuits/src/zk_circuits/valid_reblind.rs
circuits/src/zk_circuits/valid_wallet_create.rs
circuits/src/zk_circuits/valid_wallet_update.rs
task-driver/src/helpers.rs
util/src/matching_engine.rs

This PR merges the proof linking feature branch into mainline.

feature-branch: Merge `proof-linking` into `main`

---

Cargo.lock
common/Cargo.toml
common/src/types/proof_bundles.rs
workers/proof-manager/src/mock.rs
workers/proof-manager/src/proof_manager.rs

This PR changes the proof manager interface to return link hints with the proofs
- Some crates have yet to be updated, testing deferred until then

workers: proof-manager: Return link hints with proofs

---

task-driver/src/settle_match_internal.rs

This PR proves commitment links between `VALID COMMITMENTS` <-> `VALID MATCH SETTLE` in the internal matching engine's task `SettleMatchInternal`. This is effectively the single-prover analog of #334 
- Refactor Arbitrum client to accept proof links
- Test these changes with the new integration testing stack
- Further testing deferred to integration tests

task-driver: settle-match-internal: Prove links in task impl

---

workers/api-server/src/http/wallet.rs

This PR changes the API server to use the timestamp specified by the client if it is valid (not stale) in the `ValidWalletUpdateStatement`. This keeps the shares of the new wallet consistent with what the client has signed.

workers: api-server: wallet: Validate and use timestamp from request

---

config/src/lib.rs
statev2/src/interface/error.rs
statev2/src/interface/mod.rs
statev2/src/interface/wallet_index.rs
statev2/src/lib.rs
statev2/src/replication/raft_node.rs

This PR adds a new `State` type that will be passed around to workers for state access and modification. As a PoC, I added a `new_wallet` method and associated getter and a test for it.

statev2: interface: Define state handle

---

Cargo.lock
common/src/worker.rs
statev2/src/interface/mod.rs
statev2/src/interface/order_book.rs
statev2/src/interface/peer_index.rs
statev2/src/storage/tx/order_book.rs
statev2/src/storage/tx/peer_index.rs
workers/api-server/Cargo.toml
workers/api-server/src/error.rs
workers/api-server/src/http.rs
workers/api-server/src/http/network.rs
workers/api-server/src/http/order_book.rs
workers/api-server/src/http/wallet.rs
workers/api-server/src/router.rs
workers/api-server/src/websocket.rs
workers/api-server/src/websocket/wallet.rs
workers/api-server/src/worker.rs

This PR refactors the API server implementation over the new raft-based `statev2` implementation. All unit tests pass, the API itself will be tested when the refactor is complete (and the node builds).

workers: api-server: Refactor over statev2 implementation

---

workers/chain-events/src/listener.rs

This PR refactors the `chain-events` worker to enqueue `UpdateMerkleProof` tasks through the state's raft-backed task queue.
- Deferred until relayer task queue integration complete

workers: chain-events: listener: Update to use task-queue

---

state/src/interface/order_book.rs

This PR adds an additional check to the state interface method to fetch locally schedulable orders. That is, we check that the containing wallet's task queue is both empty and unpaused. If either is false a task is (or soon will be) in progress and matches will have to contend for preemption.

state: order-book: Do not schedule matches with non-empty wallet queue

---

state/src/storage/db.rs

This PR sets the max size of the db to 64GB (up from the 32KB default). This stops a known issue wherein the map sometimes fills up throughout the course of integration tests.

state: storage: db: Open db with max size 64 GB

---

circuits/Dockerfile
circuits/benches/full_match.rs
circuits/docker-compose.yml
circuits/integration/main.rs
circuits/integration/mpc_circuits/match_settle.rs

This PR updates `circuits` integration tests to include fee changes

circuits: integration: Update integration tests with fee changes

---

.gitattributes
.gitignore
Cargo.lock
arbitrum-client/src/abi.rs
circuits/Cargo.toml
circuits/benches/full_match.rs
circuits/benches/match.rs
circuits/benches/valid_relayer_fee_settlement.rs
circuits/benches/valid_wallet_create.rs

This PR adds benchmarks for the `VALID RELAYER FEE SETTLEMENT` circuit.
I also had to increase the size of the SRS now that we are proving larger circuits (fee settlement). This includes using git LFS to track the `srs.ptau` file as it is now too large to be tracked normally.
- Benchmarks run

circuits: benches: `VALID RELAYER FEE SETTLEMENT`: Add benchmarks

---

Cargo.lock
circuit-types/src/srs.rs
circuits/Cargo.toml
circuits/benches/valid_offline_fee_settlement.rs
circuits/src/lib.rs

This PR adds benchmarks for the `VALID OFFLINE FEE SETTLEMENT` circuits.
- Benchmarks run correctly

circuits: benches: valid-offline-fee-settlement: Add benchmarks

---

circuits/Cargo.toml
circuits/benches/valid_fee_redemption.rs

This PR adds benchmarks for the `VALID FEE REDEMPTION` circuit
- Benchmarks run

circuits: benches: valid-fee-redemption: Add benchmarks

---

external-api/src/http/wallet.rs
external-api/src/types.rs
util/Cargo.toml
util/src/hex.rs
workers/api-server/src/http.rs
workers/api-server/src/http/wallet.rs

This PR updates the `external-api` and `workers/api-server` crates to ingest the fee design changes
- Unit tests pass for both affected crates

external-api, workers: api-server: Update with fee changes

---

external-api/src/http/wallet.rs
external-api/src/types.rs
util/Cargo.toml
util/src/hex.rs
workers/api-server/src/http.rs
workers/api-server/src/http/wallet.rs
workers/job-types/src/proof_manager.rs
workers/proof-manager/src/mock.rs
workers/proof-manager/src/proof_manager.rs

This PR adds the fee circuits as jobs for the `proof-manager`, the handler logic for them is straightforward.
- All unit tests pass for `workers/proof-manager`

workers: proof-manager: Add fee proof jobs

---

circuits/benches/valid_relayer_fee_settlement.rs
common/src/types/tasks.rs
common/src/types/wallet/balances.rs
workers/task-driver/src/helpers.rs
workers/task-driver/src/tasks/lookup_wallet.rs
workers/task-driver/src/tasks/settle_match_internal.rs
workers/task-driver/src/tasks/update_wallet.rs

This PR updates the task implementations to correctly include the new changes from the circuits; fees, fixups, etc. 
- Deferred until the follow up
- The `workers/task-driver` crate builds

workers: task-driver: Fixup task implementations with new fees circuits

---

workers/handshake-manager-tests/src/mpc_match.rs
workers/handshake-manager/src/manager/match.rs

This PR fixes up the `handshake-manager` implementation to incorporate the fees changes.

workers: handshake-manager: Integrate fees changes

---

workers/api-server/src/http/wallet.rs

This PR overwrites the `managing_cluster` field of a new wallet with the default `BabyJubJubPoint`. This will eventually be overwritten with the relayer's cluster key, but we do this for now to avoid forcing API clients to specify a valid key.
- Hit the `POST /v0/wallet` endpoint, verified that the deserialization error we saw before was not present

workers: api-server: wallet: Overwrite managing cluster with default

---

workers/api-server/src/http/wallet.rs

This PR fixes up the public shares of the wallet after overwriting the `managing_cluster` and `match_fee` with locally configured values in `POST /v0/wallet`.
- I am able to create a new wallet through the API

api-server: http: wallet: Fixup shares after overwriting wallet fields

---

circuit-types/src/fixed_point.rs

This PR changes the `FixedPoint` type to use `f64` for serialization to give a more human-readable value
- Added a `test_serde` method, it passes
- Unit tests broadly pass

circuit-types: fixed-point: (De)serialize as f64

---

arbitrum-client/src/client/event_indexing.rs

This PR sets the `to_block` field on the event filter for Merkle tree `NodeChanged` events consistently to preclude the possibility of fetching incorrect Merkle paths in the case that `NodeChanged` events are being posted while the `find_merkle_authentication_path` is querying events.
All `arbitrum-client` integration tests pass.

arbitrum-client: event_indexing: get coord change events for consistent block

---

workers/network-manager/src/manager/pubsub.rs

This PR implements the routing of inbound pubsub messages to their intended workers (gossip server, handshake manager), mirroring the appropriate logic [before the statev2 changes](https://github.com/renegade-fi/renegade/pull/407/commits/7d521fc8abe2bf984c2fecffec4827db613900fb#diff-5bcfd28af7d991b53b56872ddc2c11d423653054e8cad69ee4c582f04fba99a3) as a point of reference.

workers: network-manager: pubsub: implement inbound pubsub handling

---

external-api/src/types/api_task_history.rs

This PR changes the response type serialization for task history in two ways:
1. We serialize mints as hex strings rather than bigints
2. We flatten the task's state into a single display description, rather than a nested structure
- Tested locally, validated the JSON shape
- @sehyunc will test with the JS client

external-api: api-task-history: Improve mint & state serialization

---

state/src/replicationv2/log_store.rs
state/src/replicationv2/snapshot.rs
state/src/replicationv2/state_machine.rs
state/src/storage/tx/raft_log.rs

This PR implements various bug fixes to get the `openraft` test suite passing on our implementation of the log store and state machine.
- `openraft` suite passes

state: replicationv2: Fix misc bugs to pass `openraft` test suite

---

workers/task-driver/src/tasks/update_wallet.rs

This PR changes the `get_transfer_idx` method of the `UpdateWalletTask` not to `expect` a transfer's mint to be present in the wallet. We don't validate elsewhere that there is a balance with the given mint before reaching this point in the task, so it should be handled gracefully as opposed to panicking the task driver.

workers: task-driver: update_wallet: do not panic on invalid transfer mint

---

state/src/replicationv2/mod.rs
state/src/replicationv2/network/mock.rs
state/src/replicationv2/network/mod.rs
state/src/replicationv2/raft.rs

This PR changes the behavior of state transitions to forward the request to the leader. That is, if a follower receives a state transition proposal, it will forward the request to the leader it knows about. If that node knows of a more updated leader the behavior will continue recursively.
- Tested submitting a proposal to a random node, not necessarily the leader

state: replicationv2: raft: Forward state transitions to leader

---

state/src/replicationv2/state_machine.rs

This PR properly notifies proposal waiters when a proposal is successfully applied. State unit tests pass now, but some intermittently fail with:
```
thread 'interface::task_queue::test::test_task_history' panicked at state/src/interface/task_queue.rs:361:61:
called `Result::unwrap()` on an `Err` value: Replication(Proposal("no leader"))
```
This is because we are attempting to apply state transitions before the local peer assumes a leader position, we should probably bump the timeout there.

state: replicationv2: state_machine: notify for successful results

---

state/src/interface/raft.rs
state/src/replicationv2/raft.rs
workers/task-driver/src/tasks/node_startup.rs

This PR adds two wait conditions to each of the raft setup paths:
1. If starting a new raft, the task will wait for leader election before continuing. This is especially important when a raft is initialized with a number of other peers together.
2. If joining an existing raft, the task will await its sync with the leader and subsequent promotion from learner to follower (voter)
- Unit tests pass crate-wide
- Tested both cases, joining an existing raft and creating one anew

task-driver: node-startup: Await leader election and voter promotion

---

state/src/interface/mod.rs
state/src/replication/raft.rs

This PR adds a timer event loop to periodically check for expirations that were successful at the gossip layer but not at the raft layer; i.e. the peer is no longer dialable but has not been removed from the raft. This may happen, for example, if a peer expires at the same time as the leader. 
- Reproduced a case in which the leader gets stuck with a missed expiry, verified that these changes fixed it

state: replication: raft: Periodically check for missed expirations

---

node-support/snapshot-sidecar/src/main.rs
state/src/replication/state_machine/mod.rs
state/src/replication/state_machine/snapshot.rs

This PR changes the snapshot implementation to create and remove a `.lock` file in between snapshot start and end. This allows the `snapshot-sidecar` to watch for a file deletion event. These events are much more reliable in that they only occur once. Write events occur many times when writing a large snapshot, causing the sidecar to save a snapshot too early, when it is incomplete.
- Tested the sidecar with the lock file, verified that I could recover a relayer from the snapshot it produced in s3

replication: snapshot: Use lock file to signal snapshot completion

---

state/src/replication/state_machine/snapshot.rs

This PR adjusts the way in which we build snapshots by compressing to a tmp file, & renaming the tmp file to the expected snapshot archive path when the compression is complete. This is because otherwise, we would be overwriting a snapshot file that may be currently in use by the node to stream the snapshot to a peer. We have seen this result in 0-length snapshot chunks being sent to peers that are streaming snapshots when another snapshot build is underway.
I ran the state crate unit tests. All of the snapshot-related ones passed, and while there were some failures, those failures are also present before this PR. Namely, the failures are:
- Some tests fail due to `Replication("no leader")`, i.e. we are not awaiting an election appropriately
- The `add_peer` / `remove_peer` tests fail due …

state: replication: state_machine: snapshot: compress snapshot to tmp file until done

---

external-api/src/http/admin.rs
workers/api-server/src/auth/mod.rs
workers/api-server/src/http.rs
workers/api-server/src/http/admin.rs
workers/api-server/src/router.rs

This PR adds a `v0/admin/open-orders` endpoint to fetch open orders managed by the node.
- Tested the endpoint locally

api-server: http: admin: Add `/v0/admin/open-orders` endpoint

---

state/src/applicator/task_queue.rs

This PR removes two sources of potential raft panics when looking up a key for a task. This was observed to crash the raft on the `testnet` cluster.

state: applicator: task-queue: Do not panic on "key not found for task"

---

state/src/applicator/task_queue.rs
workers/task-driver/src/driver.rs

This PR ensures that we clean up tasks that failed to be constructed from their descriptors. Concretely we propose a `PopTask` state transition for them, which handles removing them from the queue, cleaning up their assignment, clearing the queue if they failed (in this case, they did), etc.
We only do this for non-preemptive tasks, as this logic is executed in task queue resumption for preemptive tasks. On that note, we do this unilaterally for tasks that do and do not bypass the task queue. We ensure that this is safe by having the applicator gracefully reject the state transition if the task to be popped cannot be found at the top of its queue (e.g. if it is a task that bypasses the queue).
All unit tests pass (except for `test_raft_scale_down`, though that should be unaffected by …

state: applicator, workers: task-driver: pop tasks that cannot be constructed

---

workers/network-manager/src/composed_protocol.rs

This PR bumps the request/response timeout on the libp2p behavior to 1 minute from the default of 10s. In the testnet cluster, we see failures to send `InstallSnapshot` RPC responses when the application of the snapshot takes over 10s - this is intended to alleviate that.
This has been tested in dev w/ orderbot load and we saw no service degradation.

workers: network-manager: composed_protocol: bump request-response timeout

---

workers/api-server/src/http/admin.rs
workers/api-server/src/http/network.rs
workers/api-server/src/http/price_report.rs
workers/api-server/src/http/wallet.rs

This PR fixes a few IDOR vulnerabilities discovered in the process of auditing the api server. These are largely around creating orders or wallets -- objects that are indexed globally and may overwrite the orders/wallets of other users.
- Tested the IDOR vulnerabilities after after update

workers: api-server: Fix IDOR vulnerabilities

---

workers/task-driver/src/utils/validity_proofs.rs

This PR makes a small change to avoid proving validity for orders in a wallet if further tasks are in the queue. These tasks will immediately invalidate any validity proofs, so it's wasteful to prove them.
- Tested both scenarios locally: a task queue empty behind the current task and a task queue full behind the current task

task-driver: utils: Don't prove validity if task queue non-empty

---

workers/task-driver/src/tasks/refresh_wallet.rs

This PR adds a helper to overwrite order ids on a wallet refresh with those on the existing wallet where possible. This is not perfect, but a best effort attempt to avoid duplicate orders in order history. A complete solution is left out of scope to tame the complexity of the solution.
- Replicated the duplicate order issue, verified that it was mitigated with this approach

task-driver: refresh-wallet: Maintain consistent order ids on refresh

---

common/src/types/token.rs
workers/price-reporter/Cargo.toml

This PR adds new tokens as per the new token map as well as their support entries for the exchanges we pull prices from.
- Tested these tokens with a price reporter running locally

common: token: Add new tokens and exchange support entries

---

arbitrum-client/src/client/contract_interaction.rs

We occasionally see a tx failing but still being included in the block (e.g. [1](https://arbiscan.io/tx/0xfa5311f672685961cc8c6cca018c80be998806169ca1ff3584c03e4fad53f6aa) [2](https://arbiscan.io/tx/0x82123c07d7660a9bbad63d7d0943d8afab5d6d4448b9656830a57f9161b864f4)). The current logic in the `arbitrum-client` sees this as a success and continues on with the task, attempting to find the wallet's Merkle path. This results in `CommitmentNotFound` errors.
Adding this early failure will help us detect this case and root cause it more accurately.
- Tested with a local relayer that all methods still work

arbitrum-client: contract-interaction: Fail task if tx status is zero

---

config/src/cli.rs
core/src/error.rs
core/src/main.rs
node-support/snapshot-sidecar/src/main.rs

This PR properly formats logs for the snapshot sidecar worker to make them well behaved in datadog.
- Deployed to testnet

node-support: snapshot-sidecar: Properly format logs

---

state/src/replication/log_store.rs

This PR changes all logstore operations to use `with_read_tx` and `with_write_tx` that spawn the transaction on the tokio blocking pool. This prevents us from blocking the async thread when the DB is busy.

state: replication: log_store: Do not block async pool on log operations

---

circuits/src/zk_circuits/valid_match_settle/single_prover.rs
circuits/src/zk_circuits/valid_match_settle_atomic.rs

This PR adds settlement constraints to the `VALID MATCH SETTLE ATOMIC` circuit for the internal party. We directly use the settlement constraints from the `VALID MATCH SETTLE` circuit.
- External party fees
- Tests
- Proof linking

circuits: valid-match-settle-atomic: Add settlement constraints

---

circuits/src/zk_circuits/proof_linking.rs
circuits/src/zk_circuits/valid_match_settle_atomic.rs

This PR adds defines the proof linking groups between `VALID COMMITMENTS` and `VALID MATCH SETTLE ATOMIC`. We directly use the party 0 group from the `VALID COMMITMENTS` <-> `VALID MATCH SETTLE` link, as they contain the same values and represent the "same" link.
- Tested proof linking and link malleability

circuits: proof-linking: Add valid commitments <-> match atomic link

---

circuits/benches/valid_match_settle_atomic.rs

This PR fixes a bug in the `VALID MATCH SETTLE ATOMIC` benchmark, wherein we do not allocate proof-linking groups in the constraint application benchmark. This caused the benchmark to fail.
- Ran the benchmark after the fix

circuits: benches: valid-match-settle-atomic: Fix benchmark bug

---

common/src/types/wallet/mocks.rs
common/src/types/wallet/mod.rs
common/src/types/wallet/orders.rs
external-api/src/http/external_match.rs
external-api/src/types/api_wallet.rs
state/src/interface/order_book.rs
workers/api-server/src/http.rs
workers/handshake-manager-tests/src/mpc_match.rs
workers/handshake-manager/src/manager.rs
workers/handshake-manager/src/manager/matching/external_engine.rs
workers/handshake-manager/src/manager/matching/internal_engine.rs
workers/task-driver/integration/tests/settle_match.rs
workers/task-driver/integration/tests/update_wallet.rs

This PR adds admin authentication to the external match route. We will issue API keys and authenticate this endpoint externally through an auth extension; which itself will hold the admin key.
- Tested the endpoint with admin authentication

api-server: http: Admin authenticate external match route

---

external-api/src/bus_message.rs
external-api/src/http/admin.rs
external-api/src/types/admin.rs
external-api/src/types/mod.rs
state/src/applicator/wallet_index.rs
workers/api-server/src/http.rs
workers/api-server/src/http/admin.rs
workers/api-server/src/websocket.rs
workers/api-server/src/websocket/handler.rs
workers/api-server/src/websocket/order_status.rs
workers/api-server/src/websocket/price_report.rs
workers/api-server/src/websocket/task.rs
workers/api-server/src/websocket/wallet.rs

This PR is the culmination of all the other feature work done on the `andrew/new-admin-order-endpoints` branch, which has all been reviewed.

external-api, workers: api-server: new admin endpoints

---

circuits/src/zk_gadgets/fixed_point.rs

This PR adds a `constrain_equal_floor` method to the `FixedPointGadget` that constrains a given fixed point to equal a given integral value when floored. This will replace the `constrain_equal_integer_ignore_fraction` that is used throughout the matching engine.
- Tested all edge cases for the floor gadget

circuits: zk-gadgets: fixed-point: Add floor constraint gadget

---

circuits/src/zk_circuits/valid_wallet_update.rs

This PR constrains the wallet blinder update in the `VALID WALLET UPDATE` circuit. Specifically, this constraint requires the prover to know the preimage of the new blinder shares. This prevents a malicious party from using a public blinder that is not their own and thereby blocking an honest party from reblinding.
- Tested updating a wallet with deployed contracts

circuits: zk-circuits: valid-wallet-update: Constrain blinder update

---

state/src/interface/order_book.rs

This PR updates the order book methods in the `state` to use the order book cache for expensive match queries. Specifically for fetching the matchable and _externally_ matchable orders.
- Cache backfill logic from snapshots
- Rigorous testing in testnet
- Full testing deferred until feature complete

state: interface: order-book: Use order book cache

---

state/src/applicator/wallet_index.rs

This PR updates the external order cache for _all_ orders in a wallet update, rather than new and cancelled orders. This captures wallet updates which may change the `allow_external_matches` flag.
- Will test in testnet ahead of deploy

state: applicator: wallet-index: Update external cache for all orders

---

workers/api-server/src/http/external_match.rs

Currently when estimating gas for a transaction, the estimation reverts because ERC20 transfers have not been pre-approved. To sidestep this limitation, we mark the transaction sender as the _darkpool itself_ when estimating gas: the darkpool will have an automatic "approval" for itself as the spender and will fail less often.
This can still fail if the transferred amount exceeds the darkpool's balance. In that case we fall back to a default gas estimation, which I determined as an overestimate of a few external match transactions I submitted manually.

api-server: external-match: Use darkpool address for gas estimation

---

workers/handshake-manager/src/manager/matching/external_engine.rs
workers/price-reporter/src/manager/native_executor.rs

This PR adds additional logging to the external match engine.

workers: handshake-manager: Add further external match logging

---

state/src/interface/mod.rs

This PR opens two new spans for DB operations:
- One encompassing the entire blocking operation: building a tx, executing the DB ops, and committing the tx.
- One capturing _just_ the DB ops

state: interface: Trace DB operations

---

Cargo.lock
Cargo.toml
state/Cargo.toml
state/src/interface/mod.rs
state/src/storage/db.rs
state/src/storage/tx/mod.rs
util/Cargo.toml
workers/network-manager/Cargo.toml

This PR fixes the span nesting in the DB transaction traces.

state: storage: tx: Fix trace nesting in db transactions

---

state/src/interface/order_book.rs
workers/handshake-manager/src/manager/matching/external_engine.rs

This PR adds trace metrics to determine how many orders are being filtered from each step of the order book query. This will help us determine why API users sometimes see no quote when they expect one.

state: interface: Add order book filter trace metrics

---

state/src/applicator/task_queue.rs

This PR tweaks the way in which we determine the executor in `maybe_append_historical_task`, namely we pass it in from `pop_and_record_task`. The reason for this, is that for preemptive tasks which are placed on multiple queues (i.e., `SettleMatchInternal`), we call `pop_and_record_task` on each of these queues. However, we use the same task ID, so when the first `pop_and_record_task` is called, it removes the executor assignment for that task ID before the other queue's `pop_and_record_task` is called. As a result, in `maybe_append_historical_task`, when we try to find the task's executor to determine if we should emit an event for it, we come up short.

state: applicator: task_queue: pass executor to pop_and_record_task

---

circuits/src/zk_circuits/valid_malleable_match_settle_atomic.rs
circuits/src/zk_circuits/valid_match_settle/multi_prover.rs
circuits/src/zk_circuits/valid_match_settle/single_prover.rs
circuits/src/zk_circuits/valid_match_settle_atomic.rs
circuits/src/zk_gadgets/wallet_operations.rs

This PR defines the circuit constraints for the `VALID MALLEABLE MATCH SETTLE ATOMIC` circuit. See the [spec](https://renegade-fi.notion.site/Renegade-Circuit-Spec-24cf2047fdee4fac9212a9b5f1a8f3de?pvs=74) for more info.

circuits: zk-circuits: valid-malleable-match: Define circuit constraints

---

circuits/src/zk_circuits/valid_malleable_match_settle_atomic.rs
circuits/src/zk_gadgets/wallet_operations.rs

This PR adds further testing to the `VALID MALLEABLE MATCH SETTLE ATOMIC` constraints that ccompletely cover the constraints defined in the [spec](https://renegade-fi.notion.site/Renegade-Circuit-Spec-24cf2047fdee4fac9212a9b5f1a8f3de)
- Benchmarks

circuits: zk-circuits: valid-malleable-match: Add complete testing suite

---

Cargo.lock
Cargo.toml

This PR bumps the alloy versions used in the relayer.
- Relayer does not build yet, an analogous change is needed in the contracts.

workspace: Upgrade `alloy` versions

---

common/src/types/wallet/keychain.rs

This PR breaks out the wallet commitment signature helper into a separate helper that signs arbitrary bytes. This is useful for generating withdrawal authorization, which comprises an `sk_root` signature of the ABI-encoded transfer.

common: wallet: keychain: Add generic payload signing method

---

arbitrum-client/src/client/event_indexing.rs

This PR fixes the logic for awaiting a nullifier spend event to also pre-fetch events matching the filter before polling the stream. This is because the event stream only includes events that are emitted after the initial poll of the stream, so if a transaction spending the given nullifier is settled before the filter is created, we will miss the associated nullifier spent event.

arbitrum-client: event_indexing: prefetch nullifier spent events

---

Cargo.lock
state/Cargo.toml
state/src/storage/error.rs
state/src/storage/tx/mod.rs
state/src/storage/tx/task_queuev2.rs
workers/job-types/Cargo.toml

This PR implements the storage primitives for the new version of the task queue that segments out tasks as either concurrent or serial.

state: storage: task_queuev2: Implement storage primitives

---

state/src/storage/tx/task_queuev2.rs

This PR implements a `can_run` method on the new task queue that determines whether a task can run based on its presence in the access class lists of the `TaskQueue`. The rules here are:
- A serial task may run iff it is the first task on the serial queue and the concurrent queue is empty. Note that we disallow concurrent preemptive tasks to be enqueued if the serial queue is non-empty, so this requirement does not starve serial tasks.
- A concurrent task may run iff it is included in the concurrent queue.

state: storage: task-queuev2: Implement `can_run` helper method

---

Cargo.lock
Cargo.toml
arbitrum-client/src/client/event_indexing.rs
arbitrum-client/src/helpers.rs

This PR bumps the alloy version of the relayer to the latest.

Cargo.toml: bump alloy version

---

state/src/caching/matchable_amount.rs
state/src/caching/mod.rs
state/src/caching/order_cache.rs
state/src/caching/order_metadata_index.rs

This PR adds the matchable amount cache along with associated getters and setters.

state: matchable amt cache

---

state/src/caching/order_cache.rs

This PR ensures only externally matchable liquidity is cached. Previously, we were caching matchable liquidity of all orders.

state: order cache: only cache external match liquidity

---

state/src/caching/order_cache.rs
state/src/caching/order_metadata_index.rs

This PR returns the pair, side, and matchable amount when removing an order form the order metadata index. This prevents a panic if an order is not found in the index. This ensures all tests pass once again.

state: caching: avoid panic if order not found in cache

---

external-api/src/http/external_match.rs

This PR swaps the `data` and `input` fields on the `TransactionRequest` returned to external match clients. Clients are expecting to deserialize the calldata on a `data` field. It is simpler to modify the `TransactionRequest` server side, rather than expect all clients to update.

external-api: external-match: Use `data` field on `TransactionRequest`

---

darkpool-client/src/base/conversion.rs
darkpool-client/src/base/mod.rs
darkpool-client/src/lib.rs

This PR defines the `ToContractType` and `ToCircuitType` traits, which encapsulate conversion logic between circuit and contract types.
- Share recovery

dakrpool-client: base: conversion: Make all conversions trait based

---

node-support/bootloader/src/main.rs

This PR tweaks the bootloader script to check if there is already a `p2p-key` set in the config file before generating a random one.

node-support: bootloader: check for p2p key in config

---

node-support/bootloader/src/main.rs

This PR skips the step in the bootloader in which the node downloads the latest cluster snapshot if the `--bootstrap-mode` config is set.

node-support: bootloader: Skip snapshot in bootstrap mode

---

Cargo.lock
Cargo.toml
darkpool-client/src/client/mod.rs
workers/chain-events/src/listener.rs

This PR bumps `alloy` to `v1.0.1` in the relayer

chore: Bump alloy to `v1.0.1`

---

darkpool-client/src/client/event_indexing.rs
workers/task-driver/src/utils/find_wallet.rs

This PR changes the `DarkpoolClient` to use a more efficient block scan range when querying events by topic. Specifically, we have an exponentially widening window on block range until an event is found. This allows for recent events to be found quickly while still covering all events since the deploy block.
This is done to mitigate the timeout issues with large block range queries from Alchemy.

darkpool-client: event-indexing: Use more efficient block scan

---

state/src/applicator/task_queue.rs
util/src/channels/traced_channel.rs
workers/event-manager/src/manager.rs
workers/gossip-server/src/server.rs
workers/handshake-manager/src/manager.rs
workers/job-types/src/event_manager.rs
workers/job-types/src/gossip_server.rs
workers/job-types/src/handshake_manager.rs
workers/job-types/src/network_manager.rs
workers/job-types/src/price_reporter.rs
workers/job-types/src/proof_manager.rs
workers/job-types/src/task_driver.rs
workers/network-manager/src/executor.rs
workers/price-reporter/src/manager/external_executor.rs
workers/price-reporter/src/manager/native_executor.rs
workers/price-reporter/src/mock.rs
workers/proof-manager/src/mock.rs
workers/proof-manager/src/proof_manager.rs
workers/task-driver/src/driver.rs
workers/task-driver/src/tasks/settle_match_internal.rs
workers/task-driver/src/utils/validity_proofs.rs

This PR uses traced channels for all workers in the relayer.

workers: Use traced channels in all workers

---

.cursor/Dockerfile
.cursor/environment.json
.gitignore

This PR sets up the background agent configuration for use in Cursor.

.cursor: Setup cursor background agent config

---

state/Cargo.toml
state/benches/caching.rs

This PR adds a benchmark for the open matchable amount cache in the state.

state: benches: caching: Add matchable amount caching benchmark

---

external-api/src/http/order_book.rs
state/benches/caching.rs
workers/api-server/src/http.rs
workers/api-server/src/http/order_book.rs
workers/api-server/src/http/price_report.rs

This PR adds an endpoint to fetch the price and book depth for all supported pairs.

api-server: http: order-book: Add depth for all pairs endpoint

---

workers/task-driver/src/tasks/update_wallet.rs

This PR skips a wallet update txn when none of the on-chain state has changed; e.g. when changing the external match status of an order.

task-driver: tasks: update-wallet: Skip tx when no circuit update

---

external-api/src/http/admin.rs
external-api/src/http/order_book.rs
external-api/src/http/price_report.rs
external-api/src/lib.rs
util/src/on_chain/config_utils.rs
workers/api-server/benches/api-server-bench-util/src/lib.rs
workers/api-server/integration/main.rs
workers/api-server/src/http.rs
workers/api-server/src/http/admin.rs
workers/api-server/src/http/network.rs
workers/api-server/src/http/order_book.rs
workers/api-server/src/http/price_report.rs
workers/api-server/src/http/task.rs
workers/api-server/src/http/wallet.rs
workers/api-server/src/lib.rs
workers/api-server/src/param_parsing.rs
workers/api-server/src/router.rs
workers/api-server/src/websocket.rs
workers/api-server/src/websocket/order_status.rs
workers/api-server/src/websocket/task.rs
workers/api-server/src/websocket/wallet.rs
workers/task-driver/src/tasks/node_startup.rs

This PR adds a method to fetch the relayer fee for a given set of assets via: `/v0/order_book/relayer-fees?tickers=WETH,WBTC,...`.

api-server: http: order-book: Add relayer fees handler

---

workers/chain-events/src/listener.rs

This PR adds a bit of extra logging to the handler logic for nullifier spend events. This is useful in debugging whether or not a nullifier spend event failed to be reported by the RPC

workers: chain-events: listener: extra logging around nullifier spends

---

workers/task-driver/src/running_task.rs

This PR removes the error propagation from `pop` errors in the task cleanup phase. If an error occurs with popping the task from all queues; we should refresh the wallets, which the next lines do anyways.
Propagating this error will skip the wallet refresh task; which may be necessary in cases where the task has failed. Further, the wallet refresh task will cleanup the task queues of all affected wallets.

task-driver: running-task: Do not skip wallet refresh if `pop` fails
